### ISSUE TITLE
Lobby - Matchmaking Funnel A/B Test Ideas

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#100]
## Description

Optimize number of players entering ranked queue (existing and new user)

- Player entered site
- Player clicked Play button
- Player entered Ranked queue
- Player found ranked game
- Player completed ranked game
.

Optimize ranked game “sticky-ness”

- Player finished placement games
- Player playing daily limit per day
- Player converted to customer (subscribe) 

Ideas from Feature Suggestion: https://colonist.featureupvote.com/ 

## Idea 2 - Better CTA

```
border-bottom: solid 5px #904b17;
border-top: solid 1px #fa8933;
text-shadow: 0px 1px 1px #6d380f;
```

<img width="396" alt="image" src="https://user-images.githubusercontent.com/6215305/176430126-f8835646-05b0-4581-ba0d-c5d746f93ba3.png">

**Comment by omarhurani** [comment]
@samgawaran we briefly discussed ideas on how we could change the **Play** button and matchmaking screens to incentivise players to use them instead of the lobby, and I suggested taking some elements from games like Fortnite and Apex Legends. This video is a quick overview on what we talked about

https://user-images.githubusercontent.com/26940488/173595880-cf48b8c4-e70e-484f-8474-f15c6837ebdf.mp4

**Comment by goktugyil** [comment]
These are separate issues,

> Optimize number of players entering ranked queue

1. https://github.com/colonistio/design/issues/99
2. Make Play button more interesting, good examples from Apex/Valorant https://ptb.discord.com/channels/605233308577562643/729052204404572320/986244074883407892
3. Stop non subscribers from opening public rooms
4. Stop non users from opening public rooms
5. Require 1 matchmade unranked game before using public rooms

**Comment by goktugyil** [comment]
> Optimize ranked game “sticky-ness”

1. End game screen shows reque
2. Implement leagues
3. Lower placement game amount
4. Show placement game amount in lobby
5. Show placement game amount in MM screen
6. Show placement game amount in profile
7. Show placement game amount in leaderboard
8. Lower daily free limit and shove it into player face
9. End game has a link directly into regional leaderboard
10. Add coin rewards for end of league

**Comment by demiculus** [comment]
Aggregated the useful looking & nonimplemented ideas here: https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=304465379
