### ISSUE TITLE
Membership Announcement Banners Submission #2 - Social Media and Banner Ads

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#102]
## Summary

Created several studies that we could apply for both social media and banner ads. Explored a little more here since we could be a little more flexible in the design for both social media and banner ads since its not seen everytime the player visits our website.

### Social Media Ads

![Social Media Ads-min](https://user-images.githubusercontent.com/90673012/174584663-cce48649-235f-4d6f-94b4-0b4b5ee9f046.png)

Implemented a lot of designs/borders to choose from, we could mod it in the next iterations but I recommend doing something like in `6B` since I based that on some AAA games ranking/divisions postings

### Banner Ads 1 & 2
![image](https://user-images.githubusercontent.com/90673012/174584967-64e90d7f-5795-49bd-8682-a6048b783927.png)

Applied some of the studies I made in social media ads via a banner ad format. Overlayed it in our popup patch notes and page

### Banner Ads 3 & 4
![image](https://user-images.githubusercontent.com/90673012/174585016-16972163-ffee-4de7-8465-b0da88f88756.png)

Tried out some new variations here using the membership icons. 

## Related Submission

- https://github.com/colonistio/design/issues/101

## Related links

- https://github.com/colonistio/design/issues/7

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @goktugyil

**Comment by samgawaran** [comment]
> Crop the bg images 

it was part of the design on that study but I get what you mean 😅

**Comment by demiculus** [comment]
@samgawaran you can open a new issue with the selected assets loom vid here https://github.com/colonistio/katan/pull/7516
