### ISSUE TITLE
Profile Page Submission #39 - Scenarios: Friends Tab

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#104]
## Summary
Scenarios involving the friends tab. There are some deviations when you're looking at your own friends tab vs someone else. since in your own profile, you can manage friend requests and blocked players.

### Own Friend's Tab vs Guest Friend's Tab

![Own Friend's Tab vs Guest Friend's Tab](https://user-images.githubusercontent.com/90673012/174824998-d988180f-8a82-4bbc-80f1-1bab52a3aa98.png)

as discussed on #103 players will have more options on what they can do inside their friends tab. this shows the difference for guest-view and owner-view

### Friends Tab Scenarios
![Friends Tab Scenarios](https://user-images.githubusercontent.com/90673012/174825364-7681aa9b-c927-4029-8113-78105fead468.png)

These are the scenarios that covers the `Friends` tab inside the player-view friends tab

### Friend Request and Blocked Players Scenarios
![Friend Request and Blocked Players Scenarios](https://user-images.githubusercontent.com/90673012/174825522-f35f2bd6-3709-4439-a927-244cbbc52ac0.png)

Scenarios covering Friend Requests and Blocked Players Tab for player-view

## Related Submission

- https://github.com/colonistio/design/issues/103

## Related links

- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by demiculus** [comment]
rejecting should also show top banner, rest is okay
