### ISSUE TITLE
Membership Announcement Banners Submission #3 - Adblock and Lobby Ads Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#105]
## Summary
Adjusted the designs from #101 to reflect the finalized icons and membership tier names. Added some new studies and changed the copy as well.

> https://github.com/colonistio/katan/pull/7516

@JuanRoman77 already added the revamped images but here's a quick look at what changed:
https://prnt.sc/088mvPG3SE2B

### Membership Icons
![image](https://user-images.githubusercontent.com/90673012/175007138-f8027b7c-8943-4c2a-a543-d842a723cb75.png)

Added the revised symbol icons here

### Membership Icons + Hex BG
![image](https://user-images.githubusercontent.com/90673012/175006958-9093e5e9-8120-4601-9336-51b071be3176.png)

Removed `right banner ads` as Juan suggested. 

### Membership Icons + Faded
![image](https://user-images.githubusercontent.com/90673012/175007769-2787c5a8-3bc8-4113-8f9e-9b51151144cb.png)

Added the fades here and removed the design where it shows the three icons since it doesn't look good.

### Sample Overlay in Lobby

![image](https://user-images.githubusercontent.com/90673012/175008580-6f69d45f-48a5-48ee-bb76-d73fdf3e408c.png)

## Related Submission

- https://github.com/colonistio/design/issues/101

## Related links

- https://github.com/colonistio/design/issues/7

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @goktugyil @JuanRoman77

I'd recommend using the fades. I already made the BGs lighter for those

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/175109272-f3704ae1-1ff5-4bb4-a008-f82ca0d14dfc.png)
😭

**Comment by JuanRoman77** [comment]
Designs look good. I'll change the titles and texts.

**Comment by goktugyil** [comment]
Q: Why did we choose to go with these complex line images. Instead of these simple images? https://github.com/colonistio/design/issues/101

**Comment by demiculus** [comment]
1. Create a standardization document here: https://github.com/colonistio/design https://www.loom.com/share/f7c5cf95ca7a40ef9a550b046e6da34b  (do this after all of these are approved and the new version is released
2. @samgawaran the faded bg isn't centered with the foreground icon, make sure they're centered

> Q: Why did we choose to go with these complex line images. Instead of these simple images? https://github.com/colonistio/design/issues/101

Our game is not about gems, its about hexes, this fits our style better. I would say to iterate on them to make the tier1 have less lines, tier 2 more lines and tier 3 very complicated but then again we can do those changes later on. @samgawaran note this down and do an iteration next week.
