### ISSUE TITLE
Membership Announcement Banners Submission #4 - Social Media and Banner Ads Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#106]
## Summary
Additional announcement ads based on #105 and implemented the new designs here

### Social Media Ads
![Social Media Ads-min](https://user-images.githubusercontent.com/90673012/175029473-74fc1785-cd0d-4b6a-b919-b4486943fca2.png)

### Banners 1 & 2
![image](https://user-images.githubusercontent.com/90673012/175030252-29b97dd5-12f4-4c2a-8797-ff9ed3c6ccbc.png)

### Banners 3 & 4 
![image](https://user-images.githubusercontent.com/90673012/175029721-ae5445e7-173c-4504-9c41-966b1f34f484.png)

I'd recommend using either the banners 1 &  3, No. 1 is safe since we have that layout while No. 3 shows the name of the tiers. 

## Related Submissions

- https://github.com/colonistio/design/issues/102

## Related Link

- https://github.com/colonistio/design/issues/7

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @goktugyil @JuanRoman77

I'd recommend `6A` on social media and either `1` and `3` for the banner ads

**Comment by JuanRoman77** [comment]
Social Media ads: use #1, discard the rest. Swap these icons, put the Premium one bigger in the middle. I'll edit the title and texts below.
![image](https://user-images.githubusercontent.com/73320460/175109939-d96e9c94-66f7-441e-b02f-248c978db2d9.png)

**Comment by goktugyil** [comment]
Can we have a video for this afterwards? Will Mayla make that? 
I'm bored from that calm sebastian music, pick another music

**Comment by samgawaran** [comment]
> Can we have a video for this afterwards? Will Mayla make that? 

I'll work with Mayla about it and give her the assets needed
