### ISSUE TITLE
Membership Announcement Banners Submission #5 - Banner Ads Iteration #3

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#107]
## Summary

Social Media Post Template has already been decided and will be added along with the other approved files in this [GDrive Link](https://drive.google.com/drive/folders/1MEpdd5AwH7NBTnUqZtDecFR-ZTxLjYoG?usp=sharing)

This issue focuses on the banner ads along with @JuanRoman77 suggested copy.

## Details

![image](https://user-images.githubusercontent.com/90673012/175285519-e6a088e8-8713-4b40-a688-78a7b7fb018a.png)

added `2A` and `2B` which uses the same design variation on this [social media template](https://prnt.sc/uWmauu30mwMg) for membership which Juan prefers.

Added a couple of new colored layouts since Demi mentioned via discord that we could use `3A` if ever we need something up immediately.

## Related Submission

- https://github.com/colonistio/design/issues/106
- https://github.com/colonistio/design/issues/102

## Related links

- https://github.com/colonistio/design/issues/7

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @goktugyil @JuanRoman77 

added all of the approved assets here btw: https://drive.google.com/drive/folders/1MEpdd5AwH7NBTnUqZtDecFR-ZTxLjYoG?usp=sharing

I'll add what would be approved here in the gdrive too.

**Comment by JuanRoman77** [comment]
Gotta add Colonist logo
And phrase be Unlimited Ranked Games, No ads, and more!

**Comment by samgawaran** [comment]
> Gotta add Colonist logo

I see no strong reason to add the logo here tbh. the banners are only shown inside the website itself which has a logo in the header already which makes it seem redundant

**Comment by JuanRoman77** [comment]
I think I'll add 2A 👍

**Comment by samgawaran** [comment]
> I think I'll add 2A 👍

here you go! I updated the copy here to: `And phrase be Unlimited Ranked Games, No ads, and more!`
https://drive.google.com/drive/u/0/folders/1-ZkPXr342L5G_s6G0JPx5zhj4YYdDdWP

**Comment by JuanRoman77** [comment]
You missed a comma 😄

**Comment by demiculus** [comment]
> you didn't decide what to include on the assets folder before you closed the issue lol.

https://www.loom.com/share/4c750038463a456f8328db0874edb62f

lol not sure it didn't send.. you can go with juans one, but then make sure to do the things I wrote there, also edit the checklist so we don't have this problem again.
