### ISSUE TITLE
Store Page Fix #5 - Disclaimers: Billed Monthly/Annually & Button Variations

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#108]
## Summary

@JuanRoman77 and I talked about improving the info presented inside the membership card. We decided the remove the `*When billed annually` and just put it plainly as `billed monthly` or `billed annually` to be more straightforward.

Also added the button variations talked about [here](https://github.com/colonistio/katan/pull/7519#issuecomment-1164158770)

## Details
![image](https://user-images.githubusercontent.com/90673012/175342231-bd093e3a-6989-494d-869a-1f72aed9f7f6.png)

## Related links

- https://github.com/colonistio/design/issues/6

## Submission Checklist

- [x] I did not leave out anything that has already been implemented
- [x] I considered mobile (table & phone) devices
- [x] I considered horizontal & vertical mobile devices
- [x] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [x] I looked at examples of other products
- [x] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
Looks good. Although we could make it font-size-default (1 rem) so there aren't that many different font sizes in the UI. But that's an easy fix, we can decide later.
