### ISSUE TITLE
Membership Buttons Research #1 - Player Already has a membership

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#109]
## Summary
Question came from @demiculus 

> if the player owns monthly elite we know what to show in the monthly tab. But what do we show in the yearly tab? Can you check out some examples of other sites and see what they've done? We can either put a "manage" or an "upgrade" button under it

I was able to check a few sites that allow free trial for a subscription, besides my ongoing subscription in chess.com and Loom, and see what they show when a player/use opts to change from monthly to annual and vice versa. 

### Current look
![image](https://user-images.githubusercontent.com/90673012/175460708-ea29ca3e-f961-4b23-b951-05c2c1d6911b.png)

talked about the current look [here](https://github.com/colonistio/katan/pull/7519#issuecomment-1164084009)

Scenarios covered:
- When the player subscribed to the `Premium` tier. `Plus` will show **Downgrade** and `Elite` will show **Upgrade**
- When the player subscribed to the `Plus` tier. both `Premium` and `Elite` will show upgrade
- When the player subscribed to the `Elite` tier. both `Premium` and `Elite` will show downgrade
- Membership Card that's been subscribed by the player will show **Manage** 

_____________________________________________________________________

What's left:
- When a player is subscribed to an annual plan, what will the monthly plan show? and vice versa.

###
![image](https://user-images.githubusercontent.com/90673012/175460510-5547a876-4370-4849-bee5-963f1cfc8721.png)

> When a player is subscribed to an annual plan and wants to go monthly:

- Loom shows that when a user paid a one-time annual fee. When they go monthly, it will show them the credits left on their annual plan. **No refunds for the player, instead they will be charged after the credits left from their annual plan dries up**

Recommended:
Show `Manage` and redirect them to their profile/membership tab. Add a section there that shows `Bill monthly`

_____________________________________________________________________

> When a player is subscribed to a monthly plan and wants to go annual:

- When a player wants to subscribe annually after they go monthly. The renewal date they will get is the exact date they go for annual. ex. Paid annual on 24/6/2022 - renewal date is: 24/6/2023

Recommended:
Show `Upgrade` on the button. Also, have a section in the profile/membership tab that shows `Upgrade to Annual`

## Related links

- https://github.com/colonistio/katan/pull/7519#issuecomment-1164084009
- https://github.com/colonistio/design/issues/89

## Submission Checklist

- [x] I did not leave out anything that has already been implemented
- [x] I considered mobile (table & phone) devices
- [x] I considered horizontal & vertical mobile devices
- [x] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [x] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @goktugyil 

added Goku here as he was in the chat when this task came up.

**Comment by demiculus** [comment]
@samgawaran solutions sound good, can you make the designs?
