### ISSUE TITLE
Membership Buttons Update #2 - Design: Player Already has a membership

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#111]
## Summary
Created the designs based on the research from https://github.com/colonistio/design/issues/109. 

_Edit:_ checked hexs.io/store to the stripe billing portal and figured that we should use the billing portal screens when changing plans. Also, Stripe automatically transfers a credit when changing from Annual to Monthly.

Also updated all store screens to the latest designs.

## Details
![image](https://user-images.githubusercontent.com/90673012/176126100-243998e4-7eae-49bb-86b4-c5f92a0734df.png)
![image](https://user-images.githubusercontent.com/90673012/176126869-34744aec-7d5f-4392-9983-de2abefbf731.png)

## Related links
- https://github.com/colonistio/design/issues/109.

### Store Prototypes (Main Flow)
[Desktop](https://www.figma.com/proto/Ele0FIHqdAM10wXXPQi0gT/Colonist-%2F-Store-Tab?page-id=0%3A1&node-id=2%3A1675&viewport=554%2C258%2C0.06&scaling=scale-down-width&starting-point-node-id=2%3A1675&show-proto-sidebar=1)
[Mobile Landscape](https://www.figma.com/proto/Ele0FIHqdAM10wXXPQi0gT/Colonist-%2F-Store-Tab?page-id=0%3A1&node-id=2%3A26366&viewport=554%2C258%2C0.06&scaling=scale-down-width&starting-point-node-id=2%3A26366&show-proto-sidebar=1)
[Mobile Portrait](https://www.figma.com/proto/Ele0FIHqdAM10wXXPQi0gT/Colonist-%2F-Store-Tab?page-id=0%3A1&node-id=2%3A28796&viewport=554%2C258%2C0.06&scaling=scale-down-width&starting-point-node-id=2%3A28796&show-proto-sidebar=1)

## Submission Checklist

- [ ] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
For Review
@demiculus @JuanRoman77

**Comment by demiculus** [comment]
White is not the ideal color to use here https://i.imgur.com/5I7waEG.png

**Comment by demiculus** [comment]
So you're saying any button should take the player to their own profile and then send them to the stripe interface?

I think its good to do that when they want to downgrade, its not good when they want to upgrade. Upgrade should be made easier. I'll create the issue like that.

**Comment by demiculus** [comment]
@JuanRoman77 who for what reason changed the `Downgrade` name to `Subscribe` ?

**Comment by JuanRoman77** [comment]
It was never Downgrade, Sam changed it in Figma. Let's ask him.

**Comment by samgawaran** [comment]
sorry for the confusion, but to answer the question: 

the research indicates that a lot of membership services with tiered plans shows `Downgrade` for their lower tiers and `Upgrade` for higher tiers if you're subscribed already. Otherwise, it will show `Subscribe` if you're not a member yet.

**Comment by JuanRoman77** [comment]
> sorry for the confusion, but to answer the question:
> 
> the research indicates that a lot of membership services with tiered plans shows `Downgrade` for their lower tiers and `Upgrade` for higher tiers if you're subscribed already. Otherwise, it will show `Subscribe` if you're not a member yet.

Where can we see this research? How many games/gaming platforms appear in it?

**Comment by samgawaran** [comment]
> Where can we see this research? How many games/gaming platforms appear in it?

it's in #109 but here is the compiled images:

![image](https://user-images.githubusercontent.com/90673012/176355520-9da22f4e-35d9-4b63-ba7b-41275d596c65.png)

It's not games though... only game I can check without being locked in a payment wall is chess.com. But a majority of service software shows `Downgrade` on their lower tiers like in Loom

**Comment by JuanRoman77** [comment]
This is inconclusive. It's better to a/b test it. I added it to [insert ab test list link]
