### ISSUE TITLE
Friends Tab Improvement #1 - Follow/Following Design + Scenarios

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#112]
## Summary

Reworked almost all of the screens I presented in #104.

I based the decisions behind the design in this list of feedback https://github.com/colonistio/design/issues/104#issuecomment-1164498586 

Suggestion:
Instead of calling it as `Friends` tab, I think it's better to just call it as `Followers` tab like what Twitter and Instagram do. Those websites also allow users to follow anyone they want.

I did some variations for the buttons [here](https://user-images.githubusercontent.com/90673012/176644714-505f4a62-584a-4aae-a5a4-5fc4b77016a4.png) and decided that using buttons is still the best way to show the follow/unfollow.

## Changes
![image](https://user-images.githubusercontent.com/90673012/176639297-7f485835-6cb9-4fe2-9571-1b52c92834cf.png)

1, 2) - Change the copy from Friends to Followers
3) - Made the buttons smaller from `40px` to `32px` Follow & Following has different color schemes
4) - Replaced `Friends` and `Friend Requests` into Follow & Following also added the current number of players inside a category

### Guest Tab / Owner Tab
![image](https://user-images.githubusercontent.com/90673012/176636474-0e444ad9-442a-494b-82df-82b94ade9f06.png)

### Follower Tab States
![Follower's Tab States](https://user-images.githubusercontent.com/90673012/176637771-27b9e048-3717-43b8-ab11-15841322ffdc.png)

### Unfollow/Unblock via the Follower's tab
![Unblocking someone via Follower's Tab](https://user-images.githubusercontent.com/90673012/176637619-b86d9b25-d684-47b4-abb8-47199943130d.png)

### Following / Unfollowing via the Profile Sticky
![Unfollowing someone via their Profile Sticky](https://user-images.githubusercontent.com/90673012/176638435-5b503fd9-5acb-411e-9783-1fd02d4264df.png)

## Related links

- https://github.com/colonistio/design/issues/104
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by JuanRoman77** [comment]
You don't follow people in games, you have friends. That's for social media.
I'll check the rest later.
