### ISSUE TITLE
Remove Ads CTAs Submission #1 - Web Sizes and Mobile Ads Idea

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#113]
## Summary
I was [asked](https://prnt.sc/w5VzCNohw0_a) by Demi to create `remove ads` buttons for our advertisements including the adblocks. I checked how other games besides chess.com do this and I saw a large number of mobile games have this so I tried to think of a way that we could also do ads for our mobile browsers. Here are some samples

### Requirements
![image](https://user-images.githubusercontent.com/90673012/177031287-e4bb1a1c-af7e-4142-ae54-68439170e289.png)

- We only have 2 ad sizes at the moment: Store Ads (300px) and Adblocks (160px)
- both use `.875rem` and uses hex `#1E90FF`
- We also don't show any ads for our mobile browsers currently.

### Web Browser Samples
![image](https://user-images.githubusercontent.com/90673012/177031543-f9db30ba-0889-48ef-aa8d-2536c283379a.png)

- Inspected colonist.io and saw that the 1700px and below browser sizes doesn't show ad blocks: https://prnt.sc/wq6g9PuyUgqK

### Mobile Browser Ads Proposal
![image](https://user-images.githubusercontent.com/90673012/177031687-909cb27a-1f2b-4c53-8212-7d638a40890a.png)

- the majority of free-to-play mobile games show ads, we can probably show some mobile ads here to boost ad revenue.
- Good example to advertise memberships and new features: https://prnt.sc/iYmEA4BibTYS

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
The samples have different colors 🤔
I like the lighter one, better contrast.

**Comment by demiculus** [comment]
created an implementation issue
