### ISSUE TITLE
Design: Find game flow

### ISSUE THREAD

**Issue by JeffdEon** [colonistio/design#115]
## Description

Omar, now that the matchmaking system is more "mature" we feel like it's a good time to actually promote the feature and encourage people using it. That is, we want to improve the find game flow and start funnelling people into the `play` button so they start using the matchmaker/ranked.

User Benefits (if everyone on the site used the `play` button to find games instead of lobby):
- Low wait times
- We can automatically find good matches and in the future match grievers together
- Actually find games for people of similar skill so they have a better experience on the site
- Expose more people to ranked

So there are 2 parts to this issue:

1. Increase amount of matchmaking games
- Currently our ranked game count sits around 7.5-5.5 % of site games, unranked around 0.5-2% of site games: https://metabase.colonist.io/dashboard/18-game-summary?date_filter=past30days

2. If for some reason ranked games are low, increase conversion from unranked to ranked (ranked is going to make more $$$)

----------------------------------------

You came forward with some great `find game` flows from Apex. Feel free to redesign anything in the find game flow in order to increase our numbers (ex: `play` button, when the lobby is shown, what is shown after clicking the `play` button, etc). For now come up with a few designs and flows and work with Sam on making mock ups. Have an implementation plan ready but don't start coding anything until everything is done, iterated on and finalized.

Reference: When we were working on the leaderboards this is the `find game` design we came up with: https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=1381%3A57955&node-id=5541%3A335895&viewport=1797%2C-376%2C0.06&scaling=scale-down&starting-point-node-id=5541%3A335895

No need to use anything from this design, just sharing. Ideally you optimize the other parts, except what the button does after clicking, but if that is required to increase our matchmaking games, do that as well.

----------------------------------------

We'll see if your changes are successful or not from here: https://metabase.colonist.io/dashboard/18-game-summary?date_filter=past30days

Our ideal outcome is, in 2 months is 35% of players use matchmaking. This will be 5x our current matchmade games and will solve all the issues the system has at the moment. It might possibly allow us enough playerbase to add expansions to matchmaking also.

**Comment by demiculus** [comment]
@omarhurani this has a lot of moving parts. Some of them are more important than others. 

Can you create a roadmap for this? When executed there should be no way we're doing backward improvement. The roadmap should be divided into phases that we will develop, push and test. Should include analytics and what to track for each phase. Should include possibility of reverting as well as trying out multiple versions for a phase.

Some stuff I notice:
- The play button and the button above it look isolated, it should be clear they are the same (similarity principle might be used here: https://youtu.be/FryaH599ec0?t=495 )
- Lets not forget Bot games
- Talk w jeff to see if/when it makes sense to remove non-ranked game queues
- The goal should be clear. What are we aiming to achieve with this. Whats the success & fail metrics?

**Comment by samgawaran** [comment]
These design ideas are a huge shift on our current signed landing page (currently Lobby) This is a good basis to move forward if we want the site to be primarily a _matchmake-first_ before _custom lobby_

I can improve the UI but I agree with Demi that the goal should be clear first before I could do some iterations for the design.

Also:
- Current plan is to allow multiple game modes to be selected
- What does the gear icon mean? I think it should also show an info icon for each game mode settings
- Fun Maps aren't that clear, if I clicked on it would it be unranked or ranked?

I like the design ideas, we could definitely improve the UI for it. The current design does not provide space for SF and C&K game modes

**Comment by goktugyil** [comment]
Overall I like it, details need to be flushed out of course

1. I'm guessing the middle content part will have links to profile, leaderboard, etc.. So person can look at their summary and jump in for details while waiting for a match
2. Should Create Room be, Create Private Room or Play with Friends?
3. How is the newly suggested "Select Game Type" screen different from the latest one we've designed? It would be beneficial to see them side by side
4. Also it's better to reduce texts if we can from "Select Game Type" screen
5. @JeffdEon will this kind of change cause any structural unsolvable bugs?

**Comment by JeffdEon** [comment]
> The goal should be clear. What are we aiming to achieve with this. Whats the success & fail metrics?

We can add to this list but in general after pulling retention data ranked is higher. So converting people to ranked might increase site retention.

> This is a good basis to move forward if we want the site to be primarily a matchmake-first before custom lobby

The theory is that matchmaking is the better system after everyone uses it. But we can't know that until it happens. In theory, more people in queue == less waiting, higher quality matches, filter out grievers, possibly higher retention.

**Comment by JeffdEon** [comment]
Sorry I'm a bit late to the show but this is my feedback. Likely some of it is repeated. 

1. These buttons don't look "joined". They don't seem like they act together. It think this is what Demi was pointing out.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/58959537/180650646-c1955bb9-03ae-46af-b037-e7aa071f5e1f.png">

> How is the newly suggested "Select Game Type" screen different from the latest one we've designed? It would be beneficial to see them side by side

2. Agree with this comment. What makes the new design "better" and what made you go with something like this?
3. You say it would be a lot of work to let the people interact with the site while waiting. What is "a lot of work?" what would need to be changed.

**Comment by JeffdEon** [comment]
Other misc comments.

> Talk w jeff to see if/when it makes sense to remove non-ranked game queues

It seems like unranked isn't necessary at this stage. I'm assuming the people that would use unranked are just using lobby now. I'd say keep unranked in until changes are done and numbers stabilize. Then we evaluate whether it should just be removed.

**Comment by JeffdEon** [comment]
> If for some reason ranked games are low, increase conversion from unranked to ranked (ranked is going to make more $$$)

Don't need to have designs now. But assuming funnelling people from unranked into ranked makes the most sense (higher retention, etc) what ideas do you have for achieving this?

**Comment by omarhurani** [comment]
> 1. These buttons don't look "joined". They don't seem like they act together. It think this is what Demi was pointing out.
> 
> <img alt="image" width="182" src="https://user-images.githubusercontent.com/58959537/180650646-c1955bb9-03ae-46af-b037-e7aa071f5e1f.png">

Yes, this is just a demonstration.

> > How is the newly suggested "Select Game Type" screen different from the latest one we've designed? It would be beneficial to see them side by side
> 
> 2. Agree with this comment. What makes the new design "better" and what made you go with something like this?

In my opinion, this design groups related categories into one area from which the player can select the specific variant to play (if you're in this area, you're just playing causal. If you're in that area, it is ranked). Also, in a lot of the games that I've seen, there is no mention of "unranked". If it doesn't have "ranked" specifically mentioned on it, it is not.

> 3. You say it would be a lot of work to let the people interact with the site while waiting. What is "a lot of work?" what would need to be changed.

The current dialog blocks the site. If we use a different approach, any link the user clicks will change the site and they will be disconnected. This needs to be handled in a way to not let players accidentally close off the site (e.g. warning message before switching).

> 4. I'd need to also see the design with CK and SF added. It doesn't seem like it would take it in well.

They can be in the place of the "Fun Maps". Also, if a couple more game modes are needed to be added, we can replace the rows with a grid that has more compressed information, as long as the icons and text are clear.

> Other misc comments.
> 
> > Talk w jeff to see if/when it makes sense to remove non-ranked game queues
> 
> It seems like unranked isn't necessary at this stage. I'm assuming the people that would use unranked are just using lobby now. I'd say keep unranked in until changes are done and numbers stabilize. Then we evaluate whether it should just be removed.

I don't think having a big "Play" button with no casual play potential is a good step, especially if we're making the lobby less easy to access.

> > Current plan is to allow multiple game modes to be selected
> 
> At the beginning when I was designing backend architecture I wanted to maintain flexibility so I left in the idea of selecting multiple queues as a way to reduce wait time. If you don't care what you play you'll be thrown into the first thing that matches.
> 
> The backend is about 70% done. So not ready to implement but knowing what we know now I think this feature isn't necessary. It doesn't seem like other games do this and most people just stick to a single game mode. So this added unnecessary complexity to some UI designs in the past and made a bit of a mess in the backend code. At this point I don't see a reason to remove the code from the backend but unless we really think there's a benefit we can probably ignore multi-select for now. When designing UI maybe keep it in the back of your mind but that's about it.

I'm not sure on how useful multiple queuing is. I'd assume that most people would like to play a specific game mode and not anything, especially that the play experience is significantly different between variants.

> > The "Fun Maps" section can be replaced with any other content we want to promote, or remove it completely.
> 
> Just as an FYI. We added a fun map queue a long time ago and it was a pretty big failure. Not sure if you were around for that. I don't think we can do small custom things like this until our numbers are higher. But I agree a spot for fun "seasonal" or other temporary modes in the future mades sense. For now we don't need it.

I added it as a filler that can be replaced with anything we find suitable, or removed completely.


> > If for some reason ranked games are low, increase conversion from unranked to ranked (ranked is going to make more $$$)
> 
> Don't need to have designs now. But assuming funnelling people from unranked into ranked makes the most sense (higher retention, etc) what ideas do you have for achieving this?

If we make more people click the "Play" button, more people will be exposed to ranked. I'm not fully aware of what is planned for ranked (other than leagues), but I remember something around seasonal awards. These should allow players to discover ranked and incentivize them to play it.

**Comment by samgawaran** [comment]
@demiculus should we close this?

**Comment by demiculus** [comment]
Yes. 
@omarhurani do you see anything here that we can abtest for a significant result so I can add to the abtest list?

**Comment by omarhurani** [comment]
Do we want to test out a different flow for selecting the game mode?

Now it is: Click button
Downside: Need a button for each mode

Idea: Button to select gamemode (into a popup) > button to play. Play button remembers gamemode
Downside: More steps

Test here would be if the extra steps will negatively affect numbers. If not, we can have a more flexible design that's not limited by the main page size. @samgawaran what do you think?

---

Testing widget-based matchmaking indicator, current is popup.

Downside: rest of website will be interactive, need to open all links in new tabs to avoid people leaving queue accidentally 

---

Testing matchmaking indicator feedback, showing different steps or tips, just having something change on the screen to indicate something is happening.

**Comment by samgawaran** [comment]
> Idea: Button to select gamemode (into a popup) > button to play. Play button remembers gamemode

I think this wouldn't be efficient in the current number of game modes we offer. I think games like CS:GO is doing this because they have 50+ combination of game modes/maps that it would be hard to show on a single screen without using tabs or scrolling.

We can do research on a more flexible system once we release more game modes on matchmaking.

> widget-based matchmaking indicator, current is popup.

This would actually be helpful, something like Tetr.io and Overwatch matchmaking widget where they could still browse other pages of the site while matchmaking, but I think this could be better discussed in a new design issue for matchmaking widgets

**Comment by JeffdEon** [comment]
I'd say all of these sounds great but fall under "future optimization". What do you guys think?
