### ISSUE TITLE
Reclaming Adblock Strategy (RAS) Design Submission #1 - Research and Design

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#118]
## Summary
I was tasked to do some designs on the popups. I did some research on how other games/sites show their adblock popups and based some of the ideas on them.

### Research

![Adblock Popups](https://user-images.githubusercontent.com/90673012/179925411-5a1a326e-68a8-44ca-8be2-4eb6353dc4c9.png)
- Websites use either `Whitelist Us` or `Disable Adblocker` in their CTA 
- Uses `Adblocker Detected` as the shortest title in the popup. Longer titles also shows Adblocker on their wording

### Wording
![image](https://user-images.githubusercontent.com/90673012/179925969-4877f881-e9cf-4b32-bce3-e7297647ea91.png)

- I followed the wordings I saw on the websites I researched

### Popup Design
![Popup Design](https://user-images.githubusercontent.com/90673012/179934514-fd58182c-f1da-49c1-b689-0abd605a8033.png)

- I based 3 and 4 on Mobile games. with 3 using the ribbon designs on our in-game banners.
- Followed the number 1 (current) as the design used for the flow

### Scenarios
**Softblock**
![image](https://user-images.githubusercontent.com/90673012/179935029-418421aa-d058-45a7-b4b8-aba3af83c17d.png)

**Hardblock**
![image](https://user-images.githubusercontent.com/90673012/179935233-a708e71d-86b5-4ea6-a3e1-61893535d8fe.png)

## Related links

- https://github.com/colonistio/katan/issues/7730
- https://github.com/colonistio/katan/issues/7717

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by demiculus** [comment]
@samgawaran the designs in the popup are different than the ones on the site. @jashinjashua has stuff to ask you as well.

@samgawaran if you're changing the popup styles make sure to propose them separately from the content you're proposing.

**Comment by demiculus** [comment]
1. Revert to whatever popup style we're using.
2. Create more of the soft & hardblock wordings, copy the successful websites popups. We will do a/b tests on different popup wordings to see which ones are most effective.

**Comment by jashinjashua** [comment]
> @samgawaran the designs in the popup are different than the ones on the site. @jashinjashua has stuff to ask you as well.

 hello @samgawaran. So I'm stuck with the generic site popup design. I didn't color the buttons, I didn't make them close together and didnt average the body text. because that's not how the general site popup design is. I did the requested solutions but the design is up to date.  https://prnt.sc/BBQSjcDsqmpd.
