### ISSUE TITLE
Reclaming Adblock Strategy (RAS) Design Submission #2 - Adblock Popup Wording A/B Test Ideas

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#119]
## Summary

I checked how popular websites/platforms show their adblock popups and adapted the wording to make it work in the Colonist brand. research can be found [here](https://github.com/colonistio/design/issues/118)

### Language Styles
I checked some articles on what advertising language is best to use on gaming platforms and found these document: http://repositori.uin-alauddin.ac.id/6344/1/ULIL%20INAYAH%20MUTHMAINNAH_opt.pdf 

![image](https://user-images.githubusercontent.com/90673012/180173309-80d60e8f-a6ec-4b43-bbac-93f817a2a332.png)

Formal - Mostly use by News/Magazines (Business Insider, Forbes)
Supporter - Use by a lot of websites that have a subscription service. Adds an option to support instead of removing the AdBlock ( Washington Post)
Humorous - Meme sites and other game portals. Uses swear words but I didn't apply it since its not in our brand. (Newgrounds & Know Your Meme)
Dramatic - Useful for guilt-tripping players (PC Gamer)

### Wording Ideas
![image](https://user-images.githubusercontent.com/90673012/180184467-cdf6119d-f7ce-41f6-889c-a1c094a94a55.png)

## Related Submissions
- https://github.com/colonistio/design/issues/118

## Related links
- https://github.com/colonistio/katan/issues/7730
- https://github.com/colonistio/katan/issues/7717

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77

**Comment by demiculus** [comment]
I like the categories. @JuanRoman77 would you like to do the edits now or after we implement each popup?

@samgawaran the popup buttons are still close to each other. This is the buttons we have on live server: https://i.imgur.com/mC8BU16.png

Is there an issue for closer buttons for popup?

**Comment by samgawaran** [comment]
> Is there an issue for closer buttons for popup?

Not yet. I can adjust the popups in the Figma file to reflect what's in the website. I'll reupload the images after I adjusted the spacing

**Comment by samgawaran** [comment]
I updated the popups @jashinjashua, let me know if the spacings are correct. My apologies for the earlier formats since the button spacing/etc. are not the same on the website. 

We should follow the format on the website

**Comment by JuanRoman77** [comment]
Header height, margins, spacing, buttons height... everything looks different than in the site. Consistency please.

**Comment by goktugyil** [comment]
Humorous is the way to go. Not just this particular humorous example, but any humorous will work. As long as it looks like it wasn't written by someone with a stick up in their ass

I gave some humorous examples, where are they @JuanRoman77 ?
