### ISSUE TITLE
Profile Revamp #1 - Overview Tab Design Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#120]
## Summary

as part of Goku's comment to improve the profile feature, I rechecked a bunch of profile pages in https://www.gameuidatabase.com/ and revisited some of the previous approved designs that I think could be improved. `Overview` is the most critical since its the "landing" page of the profile.

Drew inspiration from top AAA games like Apex, Fortnite, Overwatch, and games from gameui. I also checked mobile games like Mobile Legends to make sure it would work on mobile.

## Previous Design
![image](https://user-images.githubusercontent.com/90673012/181288005-178f49ee-bc1b-4c07-9131-b6ab5089dab3.png)

- Details are separated via cards. Problem with this design is that not a lot of details can be shown in overview since we have a specific tab for ranked, history, items, membership etc.
- It's just not too appealing to look at.
- Didn't consider the ability to check past season(s) performance vs current season

### Chart + Listing Down Stats
![image](https://user-images.githubusercontent.com/90673012/181290618-bac6f941-aa7c-46c7-ba6a-4fb07edf120a.png)

**IDEA: Let players compare themselves via the overview**
- an incentive to look at someone's profile (besides blocking them) is to check how their stats are compared to yours. I looked at a lot of examples of graphs/charts and I saw that having charts like these illustrates them the best visually instead of looking at plain text.
- This will apply when you're viewing another player's profile
_____
- I tried showing **six** stat line so I can illustrate a hex-shaped chart (stats are still not finalized) and used our CTA colors so we won't be introducing anything new besides the chart.
- Listing down stats would allow us to include more _fun stats_, like a fastest game, longest game, sheeps stolen etc.

### Breaking down Win %
![image](https://user-images.githubusercontent.com/90673012/181293689-d85e1163-8765-40f9-8fde-f37938c51571.png)
- Breaking down Win % could help players see what game modes players are good at. based on my exp playing ranked. I often wonder how I lose on players with 40%+ winrate then I checked their history and realize that they are playing a lot of 4P games which makes their 40%+ actually high compared to the 40% WR of a player who plays solely on 1v1
- Accounts to both ranked & unranked games. We have a ranked tab for a more specific look

### No Toggles + Hexed Shape Containers
![image](https://user-images.githubusercontent.com/90673012/181297093-e93b0c0b-f1b6-4275-a4e3-fda0c9f80806.png)

- I was inspired by looking at [Apex Legends](https://prnt.sc/ESP9xMmHt4bA) Profile, they don't show a toggle and show the account stats vs season stats. This could help the players identify whether they improved on a certain part of their game (ex. points per game) over the season vs the past seasons
- I highlighted win% and points per game on the hex-shaped containers. we can change this moving forward

### Other design studies with comparative chart
![image](https://user-images.githubusercontent.com/90673012/181299925-db9e76fa-6411-4c1c-b1b3-cc1efe30151e.png)

### Stat Breakdown
![image](https://user-images.githubusercontent.com/90673012/181300253-632025c6-9858-4be6-9781-d465a8686f06.png)
- Stat breakdowns for each game mode may be shown better via a scrollable page though not a lot of games do scrollable profiles so I'm just showing these for future explorations
______________________________________________________

I recommend using a chart like the one we have in the studies. I saw it on MOBA's and simulation games, which are data-oriented games like ours. + it looks really gamey which is the objective of this design revamp

## Related links

- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil 

also tagging @demiculus @JuanRoman77 here, I felt these suggestions are a big design change to our previous discussions so I think you would want to see this also.

**Comment by goktugyil** [comment]
> IDEA: Let players compare themselves via the overview

I really like the idea here. However is there a better tool to compare player stats? I don't think hex shaped chart is the best tool

> Breaking down Win %

Nice

> No Toggles + Hexed Shape Containers

Nice

===

There are many good things here, what I am thinking of is adding them all together and designing in a good way to incorporate them all.

However that might not be the best approach, when I think of the best approach, it might be to design all other tabs, and then overview tabs latest, with the best and most useful things we have used in other tabs. 

What do you think?

**Comment by demiculus** [comment]
As I understand overview will be visited after other tabs are finalized so closing this issue. 

@samgawaran while deciding the type of data to show consult competitive gamers. Send them screenshots and ask them if they could see only 5 data here which ones they would be. If they could see 10 data there which ones they would be. From the process you'll also run into a few people who are very smart and make a lot of sense send me links of those conversations.

**Comment by samgawaran** [comment]
@goktugyil 
> is there a better tool to compare player stats? I don't think hex shaped chart is the best tool
![image](https://user-images.githubusercontent.com/90673012/181493074-3075d5ba-c223-4cb9-9b12-041bc8801680.png)

This are the other comparison tools I found besides the chart. I'd still argue that having a hex shape chart makes it look more gamey but I have no problem using other comparsion tools besides the line graph

_____

Agree with all of Demi's comments as well
