### ISSUE TITLE
Friends Tab Rework Submission #2 - Fixes and No Followers/Following AB Test Idea

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#123]
## Summary
Change some few things based on this feedback:

> Fans -> Followers
I don't know what this button does: https://i.imgur.com/yo3KzAX.png it should write unfollow
Make all button green, I get more confused whenI see orange & green used in random ways
Should write follow back https://i.imgur.com/Us5OYRB.png

Applied all of this besides `Unfollow` as top social sites like Twitter and IG don't show that word. IG uses `Remove` but its a negative word so I'm not sure if it's better. 

Also did @JuanRoman77 suggestion of removing Followers/Following in the video

## Details
https://www.loom.com/share/f9c6b7c400fa4bda8ff78ac4f8518ee2

__________________________

### Guest View
![image](https://user-images.githubusercontent.com/90673012/182288233-1e12bcec-e3a0-4d07-bd7e-f7def20612c6.png)

### Owner View
![image](https://user-images.githubusercontent.com/90673012/182288256-b6fb4189-1938-4bbc-9a28-161ec066eec6.png)

### Moderator View
![image](https://user-images.githubusercontent.com/90673012/182288277-64dd3ea8-ade7-43a9-9e66-28cb50a00ccc.png)

____________________________________________

### A/B Test Idea: Removing Followers/Following Tab
![image](https://user-images.githubusercontent.com/90673012/182288448-592069d5-5539-4b4f-bce8-9c2cfc30eb0a.png)

- reduces complexity, no friend confirmation is needed. The con here is that players with privacy issues will don't want this as they don't have control over who could see their activity and online status.
- We can also remove the activity status and online status for phase one so there would be no problem^

## Related Submission
- https://github.com/colonistio/design/issues/122

## Related links
- https://github.com/colonistio/design/issues/2

## Resource
- https://www.figma.com/file/20FbrQgSFzrbNvBl7esLNf/Colonist-%2F-Profile-Tab?node-id=105%3A33001

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77

**Comment by demiculus** [comment]
> Applied all of this besides Unfollow as top social sites like Twitter and IG don't show that word. IG uses Remove but its a negative word so I'm not sure if it's better.

Look at all the other buttons, does it write verb, adjective, subject? And see which is the odd one. Then change that

**Comment by samgawaran** [comment]
Closing this issue as we are removing the follow/following system.

latest issue is here: https://github.com/colonistio/design/issues/126
