### ISSUE TITLE
Membership Popups #1 - Research and Initial Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#124]
## Summary
We want to increase the conversion rate of players availing of memberships. Showing them as popups could be a good way to increase it. https://popupsmart.com/blog/why-popups-convert-with-statistics

### Research
![Membership Popups](https://user-images.githubusercontent.com/90673012/182576643-579ad324-ddd0-4a5f-895f-f4fbebca7b50.png)

### Offering All Memberships
![image](https://user-images.githubusercontent.com/90673012/182576797-6da9bc6f-a0d0-432d-b45c-26c6fce677bd.png)

- **Recommended: Direct to Checkout** showing all memberships via a popup lets the player compare each tier. I think Paradox Inc. mentioned that showing 3 options boosted their conversion rate as well.
- Presentation is the same as how memberships are presented in the store
- can be directed to checkout immediately if they clicked a particular price tag

### Offering Individual Memberships
![image](https://user-images.githubusercontent.com/90673012/182576922-4c598039-fa10-4269-be94-26e1339c82e5.png)

- offering memberships individually can make us highlight each of the perks via images. 
- We can also show monthly vs annual discounts
- can be directed to checkout immediately if they clicked a particular price tag

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @goktugyil

**Comment by goktugyil** [comment]
- Discounts and limited offers are a business decision. It is usually not a good business decision overall unless the model is trying to milk players as soon as possible before they quit the game for good
- However something like, a timed offer where the first month of subscription is cheaper, and the rest is normal price, or something like that just to get people's foot in the door might work out for our case
- Listing out perks and colors are a design decision

**Comment by goktugyil** [comment]
- Direct to store popup is useless. It shows logo and prices, not interesting. No example game made such a useless popup, why are we making one?
- Direct to checkout poup is ehh.. We're trying to get them to commit early on right on the popup. It's showing exactly what the store is showing, so nothing special except being a popup?
- Show perks as images. I think idea is good, execution is bad here

---

Overall, explore more of direct to checkout popup, how can we improve it?

**Comment by samgawaran** [comment]
> Overall, explore more of direct to checkout popup, how can we improve it?

I agree that direct-to-checkout popups is the way to go. in terms of improving it, I did some research and would like to create some variations for the popup containers first. AAA games popups have really good designs I'd like to try. will tag you there before getting back on this.

**Comment by demiculus** [comment]
@samgawaran the stuff I want for the next iteration

1. `Direct to X` are good I'll get em implemented.
2. Iterate on this: https://user-images.githubusercontent.com/90673012/182576922-4c598039-fa10-4269-be94-26e1339c82e5.png
3. Design a fullscreen overlay, make sure to view it in your browser to see if it feels right, our current popup style will NOT feel right. The title & footer is designed so that it doesn't cover the whole screen. So you'll need to start from scratch and design a fullscreen overlay.
