### ISSUE TITLE
Profile Revamp #2 - Ranked Tab 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#125]
## Summary
to improve the profile tab. I did some research to find out how AAA games show their match history / ranked game history, I saw that all of them show the recent games and not just the overall stats.

## Previous Design
![image](https://user-images.githubusercontent.com/90673012/182659839-adaaedbe-893d-4a26-a3d9-cabd76be5c31.png)

- Previous designs don't have a feature where players can see their past season performances
- A lot of information is being shown at once. Showing all of the game modes makes it cluttered
- design doesn't show how they got into that level of MMR. whats their matches like, etc.
- didn't consider the possibility that not everyone will play all game modes so there's bound to be a lot of empty fields

### Research
![image](https://user-images.githubusercontent.com/90673012/182661925-44101c5d-7201-4e47-826c-5b7307049ab5.png)

### Show Overall Stats and Match History
![image](https://user-images.githubusercontent.com/90673012/182664737-420d6c21-be7d-4370-a1e4-cb7236569024.png)

1. Added Tabs instead of showing all game modes. Game Modes that are yet to be implemented like SF and C&K are unclickable.
2. Drop down bar for seasons
3. Overall Stats, followed how we present overall stats in the leaderboards. Clicking in that card also directs them to the leaderboards.
4. Ranked Game History for that game mode. Added MMR values. Clicking on the info icon for each card will expand to show more details
5. Placement Games will just show "Placement" with no MMR changes
6. Clicking on the drop-down bar for seasons will follow whats our current dropdown behavior

## Related Submissions

- https://github.com/colonistio/design/issues/86
- https://github.com/colonistio/design/issues/82

## Related Links 
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77

**Comment by goktugyil** [comment]
3. Overall stats should look different than the scrolling part below. It confused me for a good minute
4. Is game number needed? I don't think so? 
4. MMR: I am guessing, it was the MMR after the game? 
- 1 v 1 => 1v1 (Why not follow what is already in our site?)
- Season 1 Ranked => Game History
- What about turn and duration of the game in history?

**Comment by samgawaran** [comment]
> 3. Overall stats should look different than the scrolling part below. It confused me for a good minute
> 4. Is game number needed? I don't think so?
> 5. MMR: I am guessing, it was the MMR after the game?
> 
> * 1 v 1 => 1v1 (Why not follow what is already in our site?)
> * Season 1 Ranked => Game History
> * What about turn and duration of the game in history?

Hey Goku, answered most of these on the designs in the new submissions, but to answer some stuff:

> 1 v 1 => 1v1 (Why not follow what is already in our site?)
Leaderboard screen uses `1 v 1` instead of `1v1` Game mode popup uses 1v1 but the design is subject for improvement so I suggest using 1 v 1 instead

> Season 1 Ranked => Game History
Game History is better placed inside the history tab and not the ranked tab, I added `Recent games` instead as LOL and Dota 2 uses that wording

> What about turn and duration of the game in history?
I added them in the new designs, based on research duration is more important than the player names too.
