### ISSUE TITLE
Friends Tab Rework Submission #3 - Simpler Friends System + Scenarios

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#126]
## Summary
Based on the poll done here: https://ptb.discord.com/channels/605233308577562643/716512630705225798/1004535586150957086 

players want a simpler friend system without the following/followers tab. I based the design on Juan's logic that [players can add whoever they want to their friend list](https://github.com/colonistio/design/issues/122#issuecomment-1204727091). 

Also:

- Blocking a Player in your friend list automatically removes them from your friend list

### Guest View
![image](https://user-images.githubusercontent.com/90673012/182814275-ce94bf1b-5da4-40d6-8fff-0a57fff70e15.png)

### Owner View
![image](https://user-images.githubusercontent.com/90673012/182814304-a740cfa2-40a9-4864-8a58-fdd7e5db6e7e.png)
- profile owners can see the activity of their friends and can spectate or join depending on the activity.

### Moderator View
![image](https://user-images.githubusercontent.com/90673012/182814374-9bcb9aad-a038-4fca-ae5a-9292e5e9b65f.png)

___________________________________

### Adding a Friend
![image](https://user-images.githubusercontent.com/90673012/182814682-612b61ca-e85f-4929-9061-479ceb45015a.png)

### Removing a Friend
![image](https://user-images.githubusercontent.com/90673012/182814724-a399bc92-8e22-47ce-958d-3d9ebc7df728.png)

### Blocking a Player
![image](https://user-images.githubusercontent.com/90673012/182814781-790e3cb9-f3d1-4a61-b3b0-d44b2debe87e.png)

### Unblocking a Player
![image](https://user-images.githubusercontent.com/90673012/182814833-a6af9393-d4c2-4891-90b3-643c5e57017e.png)

### Reporting a Player
![image](https://user-images.githubusercontent.com/90673012/182814903-26a63e7c-0a69-474d-863c-ed06262e5dee.png)

## Related Submissions
- https://github.com/colonistio/design/issues/123
- https://github.com/colonistio/design/issues/122

## Related links
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @goktugyil @JuanRoman77 

if all is good, I'll populate the implementation issue here: https://github.com/colonistio/katan/issues/7822 based on this designs

**Comment by goktugyil** [comment]
I think guests should not see the 'Friends' tab. And should not be able to see the friend info of people. Thoughts @JuanRoman77 ?

**Comment by goktugyil** [comment]
Owner view, why following/followers there?

**Comment by goktugyil** [comment]
This looks like a better design, I'm going to change the implemntation issues after next comment

**Comment by samgawaran** [comment]
> Owner view, why following/followers there?

There shouldn't be, I fixed the image now 

> I think guests should not see the 'Friends' tab. And should not be able to see the friend info of people.

This is a nice solution for privacy. Either way, we could still show the # of friends an account has in the overview tab.

**Comment by JuanRoman77** [comment]
> I think guests should not see the 'Friends' tab. And should not be able to see the friend info of people. Thoughts @JuanRoman77 ?

I think friends lists should be private, only visible to own player and moderators.
