### ISSUE TITLE
Homepage Matchmaking Design #1 - Game Mode & Timer Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#127]
## Summary
I based the designs on @omarhurani 's PR: https://github.com/colonistio/katan/pull/7828 Omar also mentioned that there are some other tests to try out so I'll do additional studies in the future.

Polished the design and added a possible design when we add both SF and C&K

## Comparison
![image](https://user-images.githubusercontent.com/90673012/182907841-ac226e2b-b916-477f-ae5d-eb1230abdcf8.png)

1. Changed the tone of the cards to make it more blend with the blue bg more.
2. Added the info icon for game settings and descriptions
3. Retained current button scheme for player familiarity and reduce number of icons. Also changed some wordings to reflect what's based on the prototype

### Hover Animation
![Homepage Matchmaking - Hover Sample](https://user-images.githubusercontent.com/90673012/182908291-1fa8e345-33b4-409c-bfb2-6c3039cfcf41.gif)

- Added a sample animation here when the card is hovered. This won't be reflected in Mobile

### Adding Seafarers and C&K
![image](https://user-images.githubusercontent.com/90673012/182908640-a8cbbf09-bdef-4430-af36-195c449e4285.png)

### Timer Animations
**Popup Timer (Default)**
![Homepage Matchmaking - Popup Timer](https://user-images.githubusercontent.com/90673012/182908965-0105c079-8328-4ab9-ad5f-7379b11b576a.gif)

**"Widget" Timer**
![Homepage Matchmaking - Widget Timer](https://user-images.githubusercontent.com/90673012/182909104-74073480-c2bc-464a-b5df-2b489f7b8f3f.gif)

- I saw some games like Overwatch, Mobile Legends and Tetr.io uses a widget-type timer for matchmaking. That way, players can still explore the website while waiting to find their game.

## Related links

- https://github.com/colonistio/katan/pull/7828

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @goktugyil @JuanRoman77

**Comment by goktugyil** [comment]
@omarhurani your project, you review. tell us when you need feedback

**Comment by omarhurani** [comment]
Overall, I like this design. I really like the timer widget, I think it is a superior way to handling this than the pop-up. Some notes:
1. Do we want the "Create Game" CTA to be this distinct? Or should it be Play vs. Bots?
2. Animation looks nice, but I feel it's a bit too slow at the ending. Maybe a more aggresive curve would feel better?
3. I'm unsure about having Ranked and Unranked in different tabs, might need some testing.
4. I would use [the trophy symbol](https://user-images.githubusercontent.com/26940488/183090868-a7247059-91a1-47a2-a4dc-1b1af9663309.png) in the ranked games tab/icons, to make them more distinct.\
5. Widget should have a cancel button no?

On the side:
* I see the backgrounds of each are changed to add some variety, which I like, but it might look even nicer if the backgrounds combined into the base island.

**Comment by JuanRoman77** [comment]
I don't like it.
- Too many boxes
- No clear hierarchy, eyes don't know where to go
- There's a Play button and 4 boxes to click as well
- The biggest and more eye catching card, is a store ad

To note:
1. Widget-type timer for matchmaking will only work if anything that the player clicks on, is opened in the same tab without canceling the queue (Leaderboards, Community, profile, Store). Game access points should be greyed out (Create Room, Play vs Bots, joining public rooms).
2. `Public Lobby` -> `Lobby`

**Comment by samgawaran** [comment]
Closing this issue, will create a new submission for the new studies
