### ISSUE TITLE
Leaderboard Revamp #1 - Game Mode Tabs Improvement 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#128]
## Summary
Reworked how game mode tabs are presented in mobile and tablet versions based on @JuanRoman77 suggestions https://discord.com/channels/605233308577562643/790772223358402571/1004962292871479456

I edited some designs out of the example he made and added a tablet version as well. 

### Tabs Reworked
![image](https://user-images.githubusercontent.com/90673012/183096970-caefc3fc-71c1-4c35-93a3-7792697725f1.png)

- Instead of showing just the icon, we could show the game mode names with the icon as a background. To make the CTAs readable, I made all of the selectable buttons have a background with the current selected have a white stroke
- Inactive buttons such as SF and C&K won't have the backgrounds
- We will show: Seafarers = `SF` Cities & Knights = `C&K`
- We could also apply these in the store tabs as well... though it needs some iterations since `Expansions` and `Membership` cannot fit in that container. I'll try some other studies out

### Tablet Version
![image](https://user-images.githubusercontent.com/90673012/183097786-75fb43c8-1794-4b6a-817c-fc7153025c0a.png)

- Used the size of an Ipad Mini (744x1133) for this^

## Submission Checklist

- [ ] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
I don't like the buttons to be completely faded out. And the outline is inconsistent with the desktop version.. I'll think of other options
