### ISSUE TITLE
End Game MMR Improvement #1 - Showing Progress Bar 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#129]
## Summary
@JeffdEon mentioned that we would be adding divisions in the next update. here: https://github.com/colonistio/katan/issues/7867, sending this submission to show the intended animation and what it looks like if you ranked up/down

## Comparison:
![image](https://user-images.githubusercontent.com/90673012/183282482-3f9aaba6-5375-464f-ba91-0ec3a1cd641b.png)

1. Made the `time` and and `turns` smaller to make room for the division icon
2. Added division icon and reworked how we present MMR change
3. Added the progress bar I'll leave to @JeffdEon whats the cap for each divisions

### Ranked End Game - Victory
![End Game MMR - Victory V2](https://user-images.githubusercontent.com/90673012/183282935-9d2813a8-47f4-45d3-a419-977e946c016b.gif)

### Ranked End Game - Defeat
![End Game MMR - Defeat V2](https://user-images.githubusercontent.com/90673012/183282937-b8d9a6e4-6429-4bf0-a9d7-1a5bda812d38.gif)

- The progress bar should slide into something like those in the above^ having an animation there adds help in making the players feel a sense of progression in their ranks.  

### Ranked Up/Down
![image](https://user-images.githubusercontent.com/90673012/183282495-1865dcc2-a9b6-42cd-b6e6-f35109d1dcd6.png)

### Progress Bar in Lowest/Highest Ranks
![image](https://user-images.githubusercontent.com/90673012/183282499-42324a81-d41e-494b-930f-c1264f2798a9.png)
- For the lowest division (Bronze), we won't show any rankings on the left side of the progress bar
- For the highest division (Platinum) we will just show `#1` on the right side. We could calculate the progress bar depending on the highest ranked player. (ex. 2800 the entry level of Platinum, while the top-ranked player's MMR is 3300, the progress bar should reflect that so the progress if they win/lose will have lesser motion compared if the top player's MMR is just 2900)

### Top Ranked Player
![image](https://user-images.githubusercontent.com/90673012/183282537-7c396f68-f3aa-4eaa-9cff-a490748e598a.png)
- for players who are at the top of the foodchain, we could add a small gratification text in there that says that they are the top player in that game mode.
- We won't show any text if they lose.

**IDEA: Add a crown icon for the top players**
- No Design yet, but we could add some symbols on the top 3 players for each game mode, I saw some mobile games does this in their leaderboards. like showing a crown whenever they play in that game mode or when someone is visiting the leaderboards, they will see that the names of the top 3 have crowns. 

## Related links

- https://github.com/colonistio/katan/issues/7867

## Submission Checklist

- [ ] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by demiculus** [comment]
> Changed Continue button as the current button design in the end-game screen is inconsistent to what we're using in all of the other pages on the website

1. this is a separate issue
2. you need to post screenshots of all the other places as well that use this button style

**Comment by samgawaran** [comment]
for review:
@JuanRoman77 @JeffdEon 

> Changed Continue button as the current button design in the end-game screen is inconsistent to what we're using in all of the other pages on the website
> > this is a separate issue
you need to post screenshots of all the other places as well that use this button style

@demiculus got it. I updated the `continue` buttons in the design I added here.

**Comment by JeffdEon** [comment]
> Ranked Up/Down

I didn't get a chance to code whether user just got promoted or not in the backend. It should be ignored for this version and added next version.

**Comment by JuanRoman77** [comment]
Ranked Up -> Promoted
Ranked Down -> No text

Ranked up/down is not the best option, players rank up and down every time they win or lose. Here they are going to a higher division. Thoughts?

**Comment by JuanRoman77** [comment]
1- This is not a good design. When I see this it looks like I'm Bronze going for Gold. I don't think this is how other games do it? It should be clearer. I'd start by adding the divisions' names.
![image](https://user-images.githubusercontent.com/73320460/183581271-607bef26-615a-4f8e-b230-449c3022166e.png)

2- Silver icon in the middle of the bar is different size than the bronze and gold, that doesn't look great. Shouldn't it be the other way around?

3- The MMR for each division changes each season depending on number of players. I don't think we should show the limits, it might cause confusion

4- Current design for earned and new MMR (https://i.imgur.com/qOc0lpA.png) is clearer than the suggested. It's easy to read how much MMR has been earned in that game, and what the new value is. Keep current.

**Comment by samgawaran** [comment]
Closing this issue, latest iteration is in here: https://github.com/colonistio/design/issues/133
