### ISSUE TITLE
Friends Tab Rework Submission #4 - Friend Request System

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#130]
## Summary
based on the thread here: https://discord.com/channels/605233308577562643/1003395897851387924 Goku mentioned that there should be a friend request system. This submission highlights the scenario and designs of the screen for implementation

### Accept / Decline Studies
![image](https://user-images.githubusercontent.com/90673012/183646300-ef557b4d-4f3c-4b5a-b4e9-2caaf4efef10.png)

- I saw Facebook, Twitter, Steam, and other sites use text on their accept/decline button that's why I'm recommending it. 
- Still added an icon version since we use that on our popups (ex. change username)
- We can change `Accept` & `Decline` later. We could also use `Add Friend` and `Remove` here
- I used the TEXT design, for now to show the scenarios 
- Facebook, and Linkedin don't show their Friend Requests and Friends under a single tab. (Twitter, IG uses a following system)
_________________________________

### Guest View
![image](https://user-images.githubusercontent.com/90673012/183646890-bda53a9c-8c65-4fd1-9c36-ec78b01e3dd2.png)

- @demiculus, Goku, Juan and I were thinking that we could remove this for guest view, like the memberships tab, it will be for profile owners and moderator view only. what do you think?

### Owner View
![image](https://user-images.githubusercontent.com/90673012/183646930-17200db4-0fcc-44cb-8d08-f314e46ac3eb.png)

### Moderator View
![image](https://user-images.githubusercontent.com/90673012/183647115-c50afe94-cd67-4bde-9f38-a6979e611d53.png)

_________________________________________________________

### Accepting a Friend Request
![image](https://user-images.githubusercontent.com/90673012/183647540-633e4a63-6c1e-4c2f-8684-18bd5e9d72ba.png)

### Declining a Friend Request
![image](https://user-images.githubusercontent.com/90673012/183647578-56e494ca-e87c-4223-acdc-76289c36fabf.png)

### Adding a Player as a Friend
![image](https://user-images.githubusercontent.com/90673012/183647412-ed674f28-3133-4769-8c07-9fb548c409ba.png)

### Cancelling a Friend Request
![image](https://user-images.githubusercontent.com/90673012/183647493-29941796-ec74-4de8-b5f9-f76e4f3abb4d.png)

### Removing a Player as a Friend
![image](https://user-images.githubusercontent.com/90673012/183648409-e496af24-d035-4c2f-b523-128b3fe474da.png)

### A Player confirmed your friend request
![image](https://user-images.githubusercontent.com/90673012/183647605-45df9628-f698-42cb-8c2e-27702c642937.png)
- For 4 or more friend confirmations, we could just show the number. since it could block the screen when a player enters the site

_______________________________________

### Blocking a Player
![image](https://user-images.githubusercontent.com/90673012/183647886-f7c6eb97-8928-4788-a39f-cbea1bbc0f44.png)

### Unblocking a Player
![image](https://user-images.githubusercontent.com/90673012/183647934-3b84bff4-bc28-4693-a4c3-26147959ffa8.png)

### Reporting a Player
![image](https://user-images.githubusercontent.com/90673012/183647998-638926e2-ccad-4f8a-bf21-db1a7f9348e5.png)

## Related links

- https://github.com/colonistio/design/issues/126
- https://github.com/colonistio/design/issues/123
- https://github.com/colonistio/design/issues/122

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @goktugyil @JuanRoman77

**Comment by goktugyil** [comment]
Cancel is not clear. 
"Cancel Friend Request" might be better, however that is a new niche functionality. I don't think it is necessary

**Comment by goktugyil** [comment]
We decided not to have block

**Comment by goktugyil** [comment]
The most important thing here is, accept/decline on top of current friend list vs a new tab called Friend Requests

you've explored the 2nd scenario, but not the first scenario

**Comment by goktugyil** [comment]
Also it is very hard to review when you have 10% change with 90% old stuff. I don't know which I'm supposed to look at

**Comment by samgawaran** [comment]
> The most important thing here is, accept/decline on top of current friend list vs a new tab called Friend Requests
you've explored the 2nd scenario, but not the first scenario

first scenario, accept/decline on top of the friend list didn't follow how other games/sites do their friend requests. All of them show the requests on a separate tab.

> Also it is very hard to review when you have 10% change with 90% old stuff. I don't know which I'm supposed to look at. If you're doing incremental small iterations do them in the comments.

I agree, I'll create a finalized list on big submissions where I'll put all of the decided designs

**Comment by goktugyil** [comment]
Ok. Go with text different color, different tab
