### ISSUE TITLE
Indicate Missing Resource Cards - revised submission

### ISSUE THREAD

**Issue by seojoon-y** [colonistio/design#132]
## Summary
When playing colonist.io, I always have to think about which resource card I'm missing to build a settlement, road, etc... It would be super useful to indicate which resource cards you already have, and which you are missing. (Summary copied from https://github.com/colonistio/design/issues/131 )

## Details
Proposed designs are below. Suppose that you have a tree card but you don't have a brick card:

<img width="754" alt="p1" src="https://user-images.githubusercontent.com/83441512/184091245-6d83c6b3-2d4b-4e02-8f32-8e61e2e00c81.png">
<img width="754" alt="p2" src="https://user-images.githubusercontent.com/83441512/184091258-b24f027f-bcf2-4b20-9384-807629a332f5.png">

## Related links
- https://github.com/colonistio/design/issues/131

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by demiculus** [comment]
Here is how don't starve does it, doesn't quite work for our case 

<img width="488" alt="image" src="https://user-images.githubusercontent.com/6215305/184095684-78f4ebc4-4a99-4ba6-969c-6bccb23f9d56.png">

**Comment by goktugyil** [comment]
@seojoon-y also mention which one you recommend after your research and design

I liked v2 + v5. it highlights + lowers opacity.

@samgawaran give your inputs

let's decide on a design then you can work on a solution

**Comment by samgawaran** [comment]
Hey @seojoon-y, I like both v2 & v5 as well. though for your next submission, could you also create some specific scenarios like:

- What does it look like for settlements & cities, since the action bar is above them? this won't work for opacity for v2 : https://prnt.sc/XuPdEvSPlze1 
- How will it look for Cities and Knights and Seafarer assets?

Also try to check these similar catan games if ever: KatanDao, Catan Universe, Landover

**Comment by seojoon-y** [comment]
Completed this task here: https://github.com/colonistio/katan/pull/7941
