### ISSUE TITLE
End Game MMR Improvement - Showing Progress Bar Iteration #2 + Research

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#133]
## Summary
Made some changes based on @JuanRoman77 feedbacks here: https://github.com/colonistio/design/issues/129#issuecomment-1208978385 I agree with the feedback given and applied it here.

also checked how other AAA games do their ranked end-game screens.

## Research
![image](https://user-images.githubusercontent.com/90673012/184099448-f930bd05-25a3-4db0-b849-688c56776a72.png)

- Every game shows a progress bar of some sorts. either for player exp or in their MMR
- only Mobile Legends and Valorant shows a huge division icon in their ranked end-game screen. LoL and other games use small icons or just texts
- shooter games like Apex and Valorant shows a breakdown of how they got their MMR. (we won't be showing the breakdowns but this is good to know)

## Comparison
![image](https://user-images.githubusercontent.com/90673012/184099348-83d24904-7410-486a-a7cf-bc27bc6bd9de.png)

1.  Reverted back to the current flow of how we present MMR changes other games also present their MMR change this way. I just changed the color of the green text for contrast issues. I also removed the icon, research suggests that more AAA games don't show a large icon in their MMR screens
2.  simplified the details in the progress bar. It'll just show your current division and the next division while also showing how "close" you are to reaching a promotion or demotion. 

## Details
Changed the way some details are shown here, also for clarification:

- Players that are 2nd place or below will always show `Defeat`

### Victory / Defeat
![image](https://user-images.githubusercontent.com/90673012/184101836-21ac5e88-e721-48f0-a2ad-1a82ddca951d.png)

### Promoted / Demoted
![image](https://user-images.githubusercontent.com/90673012/184101887-24acad7f-cabd-4ad6-b678-d31e20c3190f.png)

- I agree with Juan's comments. LoL uses promoted/demoted when a player ranks up on their divisions. I suggest we do the same

### Platinum Division / Top Ranked Ranked Player 
![image](https://user-images.githubusercontent.com/90673012/184102279-4291c08c-386b-45a2-a41c-ca09963f2bbb.png)
_____________________________________________________

### IDEA: Valorant-like End Game Screen
Want to try out some idea I had while researching:
![image](https://user-images.githubusercontent.com/90673012/184102852-1a0cc65f-c785-4a8e-8980-c00222775226.png)

- Valorant shows the movement in the global leaderboards after each ranked game
- Don't show other icons beside your current division.

## Related links

- https://github.com/colonistio/design/issues/129

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JeffdEon @JuanRoman77

**Comment by JuanRoman77** [comment]
`Current division` -> `Silver Division`

Another idea could be dividing the bar in 3, showing current rank in the middle and lower/higher at the sides. I think this could be better UX, specially when players are in between divisions constantly going up and down.

Could you sketch this idea as well, @samgawaran ?

**Comment by JuanRoman77** [comment]
Valorant idea: no.

**Comment by samgawaran** [comment]
@JuanRoman77 @demiculus @JeffdEon 
Just adding there here since its some minor changes:

> Another idea could be dividing the bar in 3, showing current rank in the middle and lower/higher at the sides.

@JuanRoman77 do you mean something like this?
![image](https://user-images.githubusercontent.com/90673012/184322073-180ec11e-0649-45b0-bbd1-fdc56000d144.png)

progress bar designs don't deviate much besides this horizontal bar. only LOL does their progress bar differently with the circular design

**Comment by JeffdEon** [comment]
I think he means something like this?

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/58959537/184343952-8c82e56b-9bef-482e-9d61-c7c3a098616e.png">

**Comment by samgawaran** [comment]
https://user-images.githubusercontent.com/58959537/184343952-8c82e56b-9bef-482e-9d61-c7c3a098616e.png

This design is not good for scalability, if we would add more divisions in the future this would make the progress bar complicated, also the progress slider in this design would be really small since it would take into account all of the MMRs of other players. +8 MMR wouldn't move that much

**Comment by JuanRoman77** [comment]
That's why I said 3 divisions, previous current and following. That's scalable.
