### ISSUE TITLE
Adblock Ads - Full Screen Membership Perk

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#134]
## Summary
We would be adding a full-screen feature on memberships. We need an AdBlock image (160x600) to advertise it.

## Pegs Research
![image](https://user-images.githubusercontent.com/90673012/184115601-29ac2fd3-7d01-46fe-ad62-df7b2a8e5960.png)

- In making a colonist-themed full screen button, we need to use the way our arrows are presented. and also not make it look complicated to maintain visual cohesion with other elements on the site

- I didn't use the border design (one with no arrows, since its not as straightforward with those with the arrows pointing out)

### Studies
![image](https://user-images.githubusercontent.com/90673012/184116370-fcf7abb6-b52b-4cec-98b0-b780e9efc620.png)

### Implementation
![image](https://user-images.githubusercontent.com/90673012/184116708-c0a4a37d-9cb2-4bd3-845f-e3aeb2face51.png)

## Resource

- https://drive.google.com/drive/u/0/folders/16ABaxU2igyhgXZ0pBoKdRpERTpAsU8R2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77

**Comment by demiculus** [comment]
https://www.loom.com/share/1a10d1ae93fe4446a9db34f791366302?from_recorder=1&focus_title=1

**Comment by samgawaran** [comment]
@demiculus I updated adblock_fullscreen1. Yeah, margin was not centered by a few px
