### ISSUE TITLE
Profile Revamp - Ranked Tab #2 (Research + New Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#135]
## Summary
Updated my research and created new studies inspired by those. This submission is accompanied by the History tab revamp since both tabs are included in the research. 

I included stat tracker websites since they are good indicators of what hardcore players want to see. 

## Research
![Research - AAA Games-min](https://user-images.githubusercontent.com/90673012/184547594-57511730-b034-45cf-830d-95216cebb863.png)

- Games researched are: LOL, Dota 2, Overwatch, Fortnite, CS:GO, Starcraft II
- some are ultra-detailed (CS:GO) while others like Fortnite only show the basic info needed
- Most games show the date and duration of the match
- If possible, they will show the character the player used in the match with the KDAs and if the player win/lose
- All of them show the match history in a card format which is also scrollable
- Dota 2 shows the MMR change in their match history. Most games show the MMR change in their end-game screen | [Research](https://user-images.githubusercontent.com/90673012/184099448-f930bd05-25a3-4db0-b849-688c56776a72.png)
- All of them don’t show other players/opponents you played against
____________________
![Research - Stats-min](https://user-images.githubusercontent.com/90673012/184547619-3763b0e1-99de-4175-ae65-d9b03675cfff.png)

- Stat Tracker sites researched are: Mobalytics, U.GG, CS:GO 360, Leetify, Meta Stats
- All of them show games played and win rate/KDA
- Mobalytics and Meta Stats use pie graphs to illustrate the player's strength
- U.GG shows a line graph to show player progression
- Most of them show an overview of the player's performance
- - All of them don’t show other players/opponents you played against

## Previous Design
![image](https://user-images.githubusercontent.com/90673012/184548304-ff9447e6-73bd-4ba8-b15e-83238d568dc1.png)

- Initial Design doesn't take into account new decisions such as having a season selector, etc.
- Iteration 1 looked forced, which looked like a hybrid of an overview and history. Goku's comment mentioned that he's confused about the design since both sections looked the same 
- Iteration 1 has some details that are unneccessary (Game #) and sections that could be merged (MMR & Change) 
- using color indicators on MMR changes is not the best option at the moment since we use the same colors on player hyperlinks. 

### Iteration 1 V2
![image](https://user-images.githubusercontent.com/90673012/184548311-9c8f5917-d2d0-4489-bf34-4392e7fe0307.png)

- polished the idea from iteration 1 and cleaned it up. Removed `Players` as **no AAA games and stat trackers** show opponents on the main cards (you could click on their info to know who you play against.)
- removing the player section helps with standardizing the size of each card. initially its hard to put all usernames in the history tab for 8 player games.  (https://prnt.sc/W_9YqvNfP3BM)
- I followed how stat trackers partitioned their overview and game history

### Pie Graph
![image](https://user-images.githubusercontent.com/90673012/184548316-684c6476-a73a-43c3-84b7-1f6060fcdc7a.png)

- can be used to compare your stats to other players (not present in this design)
- Tried to emulate how LOL and Mobalitycs and other pegs present their match history screen
- show recent games in a much more compressed format 

## Related Submission

- https://github.com/colonistio/design/issues/125

## Related Links

- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
Pie graph: no

![image](https://user-images.githubusercontent.com/73320460/184696326-24695817-9a80-4d2f-8918-dc03b8b5e417.png)

**Comment by samgawaran** [comment]
> 3. All game history should be in the same tab. Don't add game history in other tabs

I based this design on the assumption that players would want to look at the recent games. I saw this on the research and designed based on that. I could send a sample where there is no recent games but I'd remove the tabs for the game modes and just show them all instead so there wouldn't be a huge space that has no content.

> 4. I didn't understand this

What did you mean by this? is it the image above? (the one with recent games) 

> On removing players
@demiculus @goktugyil thoughts on these?

I strongly suggest removing the player section and just adding them inside the expanded view. No other games show this in their match / ranked history unless the player clicks on the info, so we're not doing the industry standard at all.

**Comment by JuanRoman77** [comment]
> What did you mean by this

The text below. It was unclear to me. But I still believe we should keep the players' names where they are right now. That's what Colonist users are used to. What research indicated that people don't care enough about the players' list when going to the profile?

**Comment by loganstillings** [comment]
1. I agree that the recent games should just be in the history, otherwise the sections become slightly redundant. 
2. I think the players listed in the games should only be in the game info (i.e. in the expanded view of the history tab)

**Comment by JuanRoman77** [comment]
I'll make a poll 👍

**Comment by samgawaran** [comment]
@loganstillings @JuanRoman77 @goktugyil @demiculus 
![image](https://user-images.githubusercontent.com/90673012/185164171-6cd57c6f-0a48-4702-8550-f73cc46e90b6.png)

here are two more samples. posting this here since it's more or less of a preview than a submission.

`Horizontal Type` - based on the design in this submission, just fixed a couple of stuff based on Juan's comments. 

`Card Type` - this is the previous design, I changed the details to show the same details shown in the horizontal type which are based on the research I did. 

Suggested logic: 
don't show the game modes that the player didn't play yet. If the player hasn't played ranked at all we won't show the ranked tab or show them something like these instead:
![image](https://user-images.githubusercontent.com/90673012/185167655-9f78a87a-9f78-4cdf-ad3f-a6cd8721ff66.png)

**Comment by loganstillings** [comment]
I prefer the card type. I agree with the suggested logic for players who haven't played games yet

**Comment by goktugyil** [comment]
> I'll make a poll 👍

Was going to recommend this, you beat me to it 😅

**Comment by goktugyil** [comment]
> I prefer the card type. I agree with the suggested logic for players who haven't played games yet

agreed

**Comment by samgawaran** [comment]
Closing this issue. Will just wait for the poll results

**Comment by JuanRoman77** [comment]
> Closing this issue. Will just wait for the poll results

This issue is for Ranked tab, not History :D
