### ISSUE TITLE
End Game MMR Improvement #4 - Progress Bar Same Width

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#138]
## Summary
Based on the discussions made in #137 this submission shows the changes in some specific scenarios and on the overall progress bar. 

following Juan's suggestions, we would be showing **same width** on the bar, so its more straightforward 

Scenarios are the same as the previous iterations, research is [here](https://user-images.githubusercontent.com/90673012/184099448-f930bd05-25a3-4db0-b849-688c56776a72.png): 

## Changes
![image](https://user-images.githubusercontent.com/90673012/185071542-318d616b-1e29-49c1-8947-e0cbcc0576f0.png)

### Victory/Defeat
![image](https://user-images.githubusercontent.com/90673012/185071656-ed5d6989-0fc6-4637-9730-725f7d2f7a78.png)
- No changes in Victory/Defeat besides the progress bar

### Promoted/Demoted
![image](https://user-images.githubusercontent.com/90673012/185072038-9a7cd83b-7e6a-4cb9-af75-a2b884a9d19d.png)

- changes for promoted/demoted: **We would always show 3 divisions at any point in the progress bar** if the player is on bronze, show `Bronze, Silver, Gold` 
- reason for showing 3 divisions is that the same-width style does not suit well in showing just 2 divisions like in the previous iteration. | [Sample](https://prnt.sc/PSAvzG0QtTmA)
- If player gets promoted on the gold division. The next ranked game they will play will show Silver on the left-most instead of bronze, if player is demoted to Silver, it will show Bronze on the left-most

### Platinum / Top Ranked Player
![image](https://user-images.githubusercontent.com/90673012/185073157-bb5145e2-badc-4554-bbae-32da9799c83c.png)

- changes in platinum and top-ranked is the same with promoted/demoted

________________________________

### MMR Change Indicator
![image](https://user-images.githubusercontent.com/90673012/185076850-9e1de6cc-bb1e-4b50-871a-487bfc7b7039.png)

> The shiny thing is a nice idea but I'm sure there are a few other ones as well. I recommend exploring those designs after the main one is approved.

- besides the shimmer, I also saw games like Mobile Legends and League do some sort of `Damage` type of indicator. yeah, some RPG games do this well on their character's HP bars too. 

## Related links
- https://github.com/colonistio/design/issues/137
- https://github.com/colonistio/design/issues/133
- https://github.com/colonistio/design/issues/129

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JeffdEon @JuanRoman77 

let me know if all is good. added an idea for the change indicators too. It can be modified during the implementation easily if ever.

**Comment by JeffdEon** [comment]
I'm still not a fan of the multi-bar approach and think I prefer the single bar approach from previous iterations. I'll let the others weigh in.

**Comment by samgawaran** [comment]
I'll leave this as is for now. Maybe we could talk more on this on the meeting or I'll post it in the #design channel. Anyhow, I'll do some other stuff first

**Comment by JeffdEon** [comment]
The design is the only thing preventing #7867 from being completed. What is the status? I think this should be ready for next update because we will begin showing divisions in the leaderboard next season.

**Comment by JuanRoman77** [comment]
@samgawaran what's the view for a player in Bronze division?

**Comment by samgawaran** [comment]
> @samgawaran what's the view for a player in Bronze division?

![image](https://user-images.githubusercontent.com/90673012/185735309-c200401f-0eb3-47ac-a22e-aa12afdc1f8c.png)

- When Player is Bronze:
from left to right - `Bronze, Silver, Gold`
- When Player is Silver:
from left to right - `Bronze, Silver, Gold`
- When player is Gold
from left to right - `Bronze, Silver, Gold`
- If player reaches Platinum
from left to right - `Silver, Gold, Platinum`

**Comment by JeffdEon** [comment]
Every time I see this design i don't like it. I'm going to again re-emphasize that equal sizes bars does NOT make sense. Progress is not scaled linearly, divisions are different widths, its not intuitive and confusing. 

I see 2 options

1. Small equal widths on side.

<img width="902" alt="Screen Shot 2022-08-20 at 7 57 05 AM" src="https://user-images.githubusercontent.com/58959537/185745088-e16f2f63-2051-4755-beec-914d24f7b14d.png">

2. Back to original design.3. 


<img width="974" alt="image" src="https://user-images.githubusercontent.com/58959537/185745134-7e8286b0-4039-414a-a8bc-e08ab4d3ab4d.png">


People want to know the progress of their current division scaled to the correct values. I've never seen a non-linear scale bar broken into 3 arbitrary widths.

**Comment by JeffdEon** [comment]
I'd like to finalize design soon so this can be implemented. Next build is getting made in a week and I'd like this to get implemented for next version. 

@demiculus can you go over these issues, pick the best one and update the implementation task and assign? https://github.com/colonistio/katan/issues/7867

**Comment by JuanRoman77** [comment]
It doesn't matter if it's simpler and easier to implement, when it's confusing and inconsistent

https://user-images.githubusercontent.com/58959537/185745134-7e8286b0-4039-414a-a8bc-e08ab4d3ab4d.png

Items in that design have different sizes, different relative positions, no clear limits, no division names. Feels like it will take ages to reach the next level.

**Comment by demiculus** [comment]
@samgawaran Go with the stuff here: https://github.com/colonistio/design/issues/129

1. There is only gifs to Victory & Defeat, show the gifs to Ranked Up/Down 
2. Write the names of the tiers https://i.imgur.com/XpkTKbu.png bronze, gold etc..
4. Make sure to show all possible cases clearly in images
5. Update the implementation issue: https://github.com/colonistio/katan/issues/7867
6. Send me a message on discord you updated
7. I'll edit and assign it to someone
