### ISSUE TITLE
Profile Revamp - Items Tab (Research + Initial Look)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#141]
## Summary
As part of the revamp being done on the existing profile page designs. I researched more games to inventory pages. Ranging from AAA games to mobile

## Research
![Research - Stats-min](https://user-images.githubusercontent.com/90673012/185574297-bd291cff-c4e2-4d33-91c2-f62f58bd6003.png)

- Almost all games use the term `Inventory` on their owned items
- A lot of games show the item description when hovered, some of those are showing it on a description box
- A lot of games also show the `equipped` item of the player inside the inventory
- All games use an organizing feature. Most of them are organized via tabs (categories) and some of them use icons or text

## Previous Design
![image](https://user-images.githubusercontent.com/90673012/185574634-9f1a60b6-cf9b-4052-b0ce-a241e22cdcaf.png)

- the current tab uses a long scrollable format instead of showing it via tabs
- May take it longer to load since the current design needs to load all store assets with large dimensions in a single page

## Details
- I'm using `Inventory` instead of `Items` in all of these studies. (Almost all games I saw uses the word Inventory)
- Using our current tab design for the tabs. 
- For studies with a description box, we need to write copies to every item so it won't be empty when an item is clicked

### Tabs & Equipped Items
![image](https://user-images.githubusercontent.com/90673012/185589078-5abbef83-850d-428e-aaea-d767d7d0667e.png)

- `Tabs` While researching, I saw that most games organize their inventory via categories/tabs 
- `Equipped Items` Not that good of a sample, but I want to show the possibility if we would put a default "gear setup" inside the tab like most RPG games

### Tabs with Description Box
![image](https://user-images.githubusercontent.com/90673012/185589207-3cff1e6c-b322-423d-afae-6e8ea6291ae9.png)

- Part of our roadmap is players having the ability to gift an item to a friend. We can show this in a description box instead of a popup so players can send items as a gift with less clicks
- I removed unowned items, we could still show unowned items in this format and when a player clicks on them the description box will show `Buy in Store` instead

### Smaller Images with Description Box (Recommended)
![image](https://user-images.githubusercontent.com/90673012/185589317-ba6fec5b-6a7d-4aba-ba0a-4be677a0a0d4.png)

- I removed the item name in this study. since we have a description box here, we can show the item name if the player click on an item in the box instead.
- Removed the tabs, we don't have that many items in some categories (colors) so its wise to reduce the number of clickable tabs on the screen.

## Related links

- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
@demiculus @goktugyil @JuanRoman77

**Comment by goktugyil** [comment]
I have weak opinions and am unsure. I'll leave feedback to others

**Comment by JuanRoman77** [comment]
1. Inventory -> Items
2. Remove these, they won't go to the profile page to check their default stuff https://i.imgur.com/j1VEDiV.png 
3. Shouldn't gifting and descriptions stay in the Store? 🤔 I'm not sure about having those in the profile.

**Comment by goktugyil** [comment]
> Inventory -> Items

why?

**Comment by JuanRoman77** [comment]
> > Inventory -> Items
> 
> why?

Because the research is wrong. He presented ingame menus of a different type of game, showing usable and collectable ingame elements. Not player profiles showing owned game modes and aesthetics. It's a different concept.

Show me how other games call the same thing we have and we can go with that name 🤷‍♂️  otherwise there's no reason to change.

**Comment by demiculus** [comment]
This is a bit risky. If we design this well it might push more people to purchase items instead of subscribing. Lets go the safe route for initial implementation if we feel like we should optimize this then we'll do an ABTest making sure its not decreasing our store revenue. 

We will go with the easiest option: https://github.com/colonistio/katan/issues/8331

**Comment by goktugyil** [comment]
From paradox what we learned was, people want to both own and subscribe, especially high spenders
