### ISSUE TITLE
Profile Revamp - Ranked (Card Type Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#142]
## Summary
This submission is the study that's been finalized for the `Ranked` tab. It covers all possible screens/scenarios for it.

Research is done [here](https://github.com/colonistio/design/issues/135)

### If a player had played at least one ranked game
![image](https://user-images.githubusercontent.com/90673012/185594693-3a49e3a9-a56f-4f61-8a4c-f676f3b4f646.png)

- Every access level shows the same screen
- Follows game mode naming convention in our [Leaderboards tab
](https://colonist.io/leaderboards/Classic4P/)

### If a player hasn't played any ranked games
![image](https://user-images.githubusercontent.com/90673012/185595260-0415f4fc-d7b9-4448-a784-06622e66a9e2.png)

### Player clicks on a card
![image](https://user-images.githubusercontent.com/90673012/185595668-e0b5a7d4-91ec-44a4-ad3e-354164fe36f5.png)

- we will redirect them to the specified game mode's leaderboard tab via a new tab
- suggested logic: viewer will be directed in the player's rank. (If player rank is # 200, the leaderboard will show players on the # 200 range)

### Player clicks on season selector
![image](https://user-images.githubusercontent.com/90673012/185596617-3445c1a6-68e0-4fd3-9e94-cc7a16ccd8cf.png)

- by default, the ranked tab will always show the current season.
- previous season ranked mode cards are all unclickable

## Related Submission
- https://github.com/colonistio/design/issues/135
- https://github.com/colonistio/design/issues/125

## Related links
- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77 

let me know if there other specific/edge scenarios I might have missed out on. Otherwise, I'll be putting this submission in this [finalized checklist](https://github.com/colonistio/design/issues/139)

**Comment by goktugyil** [comment]
Looks good. @JeffdEon take a look here

**Comment by JeffdEon** [comment]
I don't think we should be showing this number in the cards since it might promote people getting more pts over trying to win. Probably not but we'd rather people try to win.

<img width="171" alt="image" src="https://user-images.githubusercontent.com/58959537/185744304-033e7228-6d2c-43b3-9d17-f998018c2ece.png">

**Comment by JeffdEon** [comment]
> previous season ranked mode cards are all unclickable

We could make a view for the older leaderboards if we want to but I agree we should probably make clicking old seasons do nothing. 

Otherwise this looks good!

**Comment by goktugyil** [comment]
> I don't think we should be showing this number in the cards since it might promote people getting more pts over trying to win. Probably not but we'd rather people try to win.
> 
> <img alt="image" width="171" src="https://user-images.githubusercontent.com/58959537/185744304-033e7228-6d2c-43b3-9d17-f998018c2ece.png">

@JuanRoman77 thoughts?

**Comment by JuanRoman77** [comment]
> 

I requested to remove that stat in the first iterations a few months ago. It should be removed again :)

**Comment by JuanRoman77** [comment]
1. All cards should appear even if the player hasn't played a ranked game of that type. The ones they haven't played, show a __Play this mode__ text here: https://i.imgur.com/VNQuEwh.png
2.

**Comment by goktugyil** [comment]
3. And state rank

**Comment by JuanRoman77** [comment]
Something important, I think we should show the divisions progress bar in the profile as well. Same thing we show in the end game screen. That's how players would know how much they've got left to rank up.

**Comment by samgawaran** [comment]
Closing these issue as an updated issue has been submitted here #151
