### ISSUE TITLE
Profile Revamp - Membership Tab (Direct to Payment Portal Screen + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#143]
## Summary
To simplify the flow for the membership tab, instead of having a dropdown, the team decided to have players clicking on the manage cta be [directed to the payment portal instead](https://github.com/colonistio/katan/issues/7671)

## Screens
![image](https://user-images.githubusercontent.com/90673012/185602988-ea44d9a8-15c0-4155-bde9-90755577ce8a.png)

- `Become a Member` & `Manage` cta sizes is the same with the [store tabs](https://colonist.io/store) membership cta

### Non-Member clicks on Become a Member CTA
![image](https://user-images.githubusercontent.com/90673012/185602510-8357c62c-4b62-48d3-8f24-73f97e5c7f1a.png)

### Member clicks on Manage CTA
![image](https://user-images.githubusercontent.com/90673012/185603207-2a45d535-b3ee-4d32-93a8-6d6b57809756.png)

- player will always be directed to the Stripe payment portal (atm, we don't allow Non-stripe payments for membership), players can change payment method, change billing plan, cancellation plan, and invoice history from there

## Related Submission

- https://github.com/colonistio/katan/issues/7671

## Related links

- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
@goktugyil @demiculus @JuanRoman77 

let me know if there other specific/edge scenarios I might have missed out on. Otherwise, I'll be putting this submission in the checklist

**Comment by JuanRoman77** [comment]
Looks good to me
