### ISSUE TITLE
Rent expansions with Coins instead of fully purchasing them

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#146]
## Description

Problem: People purchase once and use forever
Goal: Experiment with a pay per use model to see if it generates more revenue/player
Goal: Experiment micro transactions to see if it generates more revenue/player
Goal: It shouldn't decrease our subscriptions, if it does, it should be generating much more revenue than getting them to subscribe.

We want to make people rent expansions instead of purchasing them once and using forever. And we want to see if people are more willing to purchase & spend coins if the purchases are micro transactions.

Create a few designs/patterns. Make sure to go through the designer checklist:
  - https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md
  - https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md
  - https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md

This will be an abtest. We'll show it to 50% of the players to see what they do. Some ideas 

- Expansions for 1 day for 100 coins
- Maps for 1 day for 20 coins
- Expansion for 1 use for 10 coins
- Map for 1 use for 5 coins
- Change player count for 5 coins
- or maybe, just allow them to change any premium settings in room for 50 coins? or 25 coins? per game

## Steps for Alex
1. Design the system
2. Get Sam to design the UI
3. Create implementation issue
4. Implement the issue
5. Create metabase charts
6. Wait for it to go live and get data
7. Create a report on the result and how to move forward

## Resources
- https://github.com/colonistio/design/issues/167
- https://www.gameuidatabase.com/

## Reviewer 
@alexcoleman7 @demiculus

**Comment by leahwalkiewicz** [comment]
Following. 

+ have we considered a per use model instead of time limited? X coins = X number of uses similar to how fitness studios monetize + expiration date to make sure that revenue remains steady (expires in 30, 60, 90 days). similar to coins, more you purchase the more of a discount you get

**Comment by alexcoleman7** [comment]
@samgawaran can you do a little research with our competitors or any similar games on how they offer their microtransaction products? Would be good to know if they use premium currencies or tokens and whether they are time or per-use.
I gather you have a list of desktop based games that you compare against so if you can do that and I will have a look through mobile games as they more commonly use microtransactions.

**Comment by JuanRoman77** [comment]
> Goal: Experiment with a pay per use model to see if it generates more revenue/player
> We want to make people rent expansions instead of purchasing them once and using forever.

Isn't this the equivalent of a Battlepass? Users paying once per season to enter Ranked, access exclusive content, etc.
I think both systems are not compatible with each other, that's why most sites chose either one or the other, never both. Correct me if I'm wrong.
