### ISSUE TITLE
End Game MMR - Progress Bar (Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#147]
## Summary
design submission for the finalized list for the End Game MMR. Populating this issue: https://github.com/colonistio/katan/issues/7867 afterward. 

Made the following changes that have been decided on this: https://github.com/colonistio/design/issues/138#issuecomment-1221389509. I just retained the placement of the text below the icon

### Victory
![Victory](https://user-images.githubusercontent.com/90673012/185808001-d5d574b6-3f2d-4efd-95d0-05a9e03a3343.gif)

### Defeat
![Defeat](https://user-images.githubusercontent.com/90673012/185808011-2099734d-f984-47c3-b80c-b0dad4fc8343.gif)

- Both `Victory` and `Defeat` animations use sliding animations. the icon and MMR will slide alongside the progress bar

### Promoted
![Promoted](https://user-images.githubusercontent.com/90673012/185808020-25013278-6990-4ab7-8135-1d36f9738ef4.gif)

### Demoted
![Demoted](https://user-images.githubusercontent.com/90673012/185808031-adc633d3-3ba5-4f81-a402-f30633d842b6.gif)

- `Demoted` and `Promoted` follows the sliding animations of the previous GIFs. 
- slide MMR first before showing the text then change the previous and next division.

### Victory / Defeat
![image](https://user-images.githubusercontent.com/90673012/185808591-eb416361-f589-4a19-aee1-5047589f367e.png)

### Promoted / Demoted-Bronze Ranked
![image](https://user-images.githubusercontent.com/90673012/185807218-8846a735-3925-4135-8599-ea3274580002.png)

- if the player reaches `Bronze` don't show the lowest MMR in that game mode.

### Platinum / Top Ranked Player
![image](https://user-images.githubusercontent.com/90673012/185807221-7ecadb0f-c119-4e2f-83ab-f21922f50cc4.png)

- if the player reaches `Platinum` set the `# 1` as the MMR of the top ranked player in that game mode

## Related links

- https://github.com/colonistio/katan/issues/7867

## Related Submissions

- https://github.com/colonistio/design/issues/138
- https://github.com/colonistio/design/issues/137
- https://github.com/colonistio/design/issues/133
- https://github.com/colonistio/design/issues/129

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
@demiculus @JeffdEon @JuanRoman77 

let me know if I missed something. I'll add the details in this issue https://github.com/colonistio/katan/issues/7867 after a few hours

**Comment by JuanRoman77** [comment]
1. Current division has no name. It looks like you are going from Bronze to Gold.
2. I still don't get why the Silver icon needs to be a fourth of the size of the lower and higher divisions icons. It's not less important.

What about something like this?
![image](https://user-images.githubusercontent.com/73320460/185810950-1ab1f695-139b-4780-9105-1e8c88e20a33.png)

**Comment by JeffdEon** [comment]
Other than icon size it seems good. Poll for other style is winning currently in Discord. But the reason people are saying they like it (being able to see progress in other leagues) is wrong because all the bars would be same size.

**Comment by JuanRoman77** [comment]
It's not wrong, it's what they like. And they are aware about the size thing you mention. They just don't care about it.

**Comment by samgawaran** [comment]
Closing this issue for the more updated one here: #148
