### ISSUE TITLE
End Game MMR - Progress Bar Iteration #2 (Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#148]
## Summary
Redid the progress bar based on Juan's feedback in: https://github.com/colonistio/design/issues/147. Also redid a few things in the `Promoted` `Demoted` animation to make it more fluid.

## Comparison
![image](https://user-images.githubusercontent.com/90673012/186061827-7c67cb18-166b-47fa-b712-e5f48d679643.png)

1. Darkened the green bar a little bit so the MMR will have a better contrast
2. Made the current division icon the same size with the prev / next division
3. made the progress bar slightly taller to place the MMR inside the bar

## Animation / Flow
- No changes besides the look for victory & defeat
### Victory
![Victory V2](https://user-images.githubusercontent.com/90673012/186066442-a3c77cc8-3d54-4bf0-bdd8-b6e890abe053.gif)
### Defeat
![Defeat V2](https://user-images.githubusercontent.com/90673012/186066446-42dee966-7e7f-4a24-89b1-98935914e003.gif)

### Promoted
![Promoted V2](https://user-images.githubusercontent.com/90673012/186066451-f1015ce6-5f1c-4ee5-b44a-829f687eb5dd.gif)
### Demoted
![Demoted V2](https://user-images.githubusercontent.com/90673012/186066461-6d7f374b-d590-4313-8ae8-6250d86d36bb.gif)

- Suggested Animation: show a "continuous" slider if the bar reaches the rightmost end, it should smoothly transition into the leftmost and vice versa. 

## Screens
- not much has changed from Iteration 1 to 2 besides the progress bar

### Victory / Defeat
![image](https://user-images.githubusercontent.com/90673012/186062271-9c6b44db-7aa6-49b2-a92b-ca54c04b6a13.png)

### Promoted / Defeat
![image](https://user-images.githubusercontent.com/90673012/186062249-eb1afefd-2221-4aa6-9392-f645c98a0682.png)

### Platinum Ranked / Bronze Ranked
![image](https://user-images.githubusercontent.com/90673012/186062286-74e4b624-0077-4956-8fd4-9d368e05438f.png)

- if the player reaches `Bronze` don't show the lowest MMR in that game mode.
- if the player reaches `Platinum` set the `# 1` as the "next division" MMR of the top-ranked player in that game mode

### Top Ranked Player
![image](https://user-images.githubusercontent.com/90673012/186062391-d23844e7-e191-4bb5-b334-9c0b6261fd4a.png)

## Related links

- https://github.com/colonistio/katan/issues/7867

## Related Submissions

- https://github.com/colonistio/design/issues/147
- https://github.com/colonistio/design/issues/138
- https://github.com/colonistio/design/issues/137
- https://github.com/colonistio/design/issues/133
- https://github.com/colonistio/design/issues/129

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JeffdEon @JuanRoman77 

since it's just some minor fixes, I'll go ahead and add the details here https://github.com/colonistio/katan/issues/7867 so a dev can code it already. I'll just tweak from that issue if ever there are some minor comments

**Comment by JeffdEon** [comment]
Looks good!
