### ISSUE TITLE
Profile Revamp - Items Tab (Tab Design Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#149]
## Summary
DM'ed @JuanRoman77 and discussed what study here: https://github.com/colonistio/design/issues/141 should we focus on for the Item tab design, we decided to go with `Tabs` as its the simplest and most straightforward out of the bunch

Research is done [here](https://user-images.githubusercontent.com/90673012/185574297-bd291cff-c4e2-4d33-91c2-f62f58bd6003.png)

## Screens
![image](https://user-images.githubusercontent.com/90673012/186165841-5aa75af9-2396-44c6-8b29-b0ee112be472.png)

- shows all items currently at the store regardless if the player owns them.
- if an item is unowed, it will be shown in a reduced opacity state

## Scenarios

- if player doesn't own any item, show all items in a reduced opacity sate

### Player clicks on an item inside the item tab
![image](https://user-images.githubusercontent.com/90673012/186166256-9dbc279a-64e0-4f55-a887-817efa7ba24e.png)

- Gifting feature ready: we can remove it in during development and just add it once we have the gifting system in place
- Clicking on an unowned item directs them to https://colonist.io/store
- for `Expansions` and `Maps` show an info icon. don't show an info icon for `Colors` and `Avatars`

### Player owns presale packs
![image](https://user-images.githubusercontent.com/90673012/186665222-38dc8d9e-65df-416d-a97a-20a01e48d19e.png)

- for presale pack owners, add a `Packs` tab beside the expansion tab. Don't show `Packs` if the player doesn't own any presale pack
- _Update_ Following Juan's comments, don't show Packs that a player doesn't own since they can't purchase them.
- Created a sample of the popup if there's no `Gift` CTA in place

## Related Submission

- https://github.com/colonistio/design/issues/141

## Related links

- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77

let me know if there other specific/edge scenarios I might have missed out on. Otherwise, I'll be putting this submission in this the [profile checklist](https://github.com/colonistio/design/issues/139)

**Comment by JuanRoman77** [comment]
Also only show the Packs the player owns, not the ones they don't. Since they can't purchase them.

**Comment by samgawaran** [comment]
> Also only show the Packs the player owns, not the ones they don't. Since they can't purchase them.

Noted on this, I updated the image on the scenario.
