### ISSUE TITLE
Profile Revamp - Profile Sticky & Search Bar (Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#150]
## Summary
Sending this submission for the profile sticky, which includes the dropdown and search bar. 

I designed the dropdown with features that are yet to be developed like `Gifting` and `Messaging` though I created screens for them for a preview.

### Owner / Guest Views
![image](https://user-images.githubusercontent.com/90673012/186463389-59605b47-0114-45bd-8d28-783f117d6e7b.png)
### Dropdown Views
![image](https://user-images.githubusercontent.com/90673012/186463577-ccf339e2-b187-4987-b008-c4a85d44f248.png)

## Scenarios
- Adding, removing, and accepting friend requests scenarios are all included in this submission: https://github.com/colonistio/design/issues/144

### Gifting a Player
![image](https://user-images.githubusercontent.com/90673012/186464028-33217ed3-3821-4c1f-a21a-289e829d143e.png)

### Messaging a Player
![image](https://user-images.githubusercontent.com/90673012/186464071-42105302-dca6-47e6-a323-85e0f84ff39a.png)

- made a sample messenger screen, and I pegged social media sites like Facebook and Instagram for the design

### Reporting a Player
![image](https://user-images.githubusercontent.com/90673012/186464273-c2fe5a03-81e7-4f12-ad0f-4a1ab8fdf42e.png)

### Using the Search Bar
![image](https://user-images.githubusercontent.com/90673012/186468355-5684c11f-7612-43e8-84b1-fa944cfa85ed.png)

- I followed the search behavior/restrictions of our leaderboard search bar

## Related links

- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77 

added a potential screen for the messaging feature here. though it's not a priority. Besides that, let me know if I missed some edge cases and I'll add those in the checklist

**Comment by JuanRoman77** [comment]
Pro tip: when these are the same, just post 1 image and title it `Owner/Guest View`, so you don't get Goku commenting "I spend 4 minutes trying to find the difference between both images"
![image](https://user-images.githubusercontent.com/73320460/186562668-04c69e02-f978-4988-9094-2cd7c81e9380.png)

**Comment by JuanRoman77** [comment]
1. Remove Cancel Request and replace it for `Pending`. This will prevent spamming requests, and also make it clearer that the request is pending acceptance.
2. The popup radius seems excessive and the spacing between text is inconsistent. Same as margins.
3. Typo https://i.imgur.com/vtvr73O.png

I'll not review the private messaging part, it's out of the scope, needs an issue of its own. Better focus on the friends list for now.

**Comment by samgawaran** [comment]
Closing this submission. adjusted the designs in this issue: https://github.com/colonistio/design/issues/152
