### ISSUE TITLE
Profile Revamp - Ranked (Card Type Screens + Scenarios) Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#151]
## Summary
Adjusted the design based on the feedback given on #142 and changed some details on each card. 

Edit: Made few more changes to this issue based on some discussions and some designs in the overview tab

## Comparison
![image](https://user-images.githubusercontent.com/90673012/188473896-02f7d8f7-b302-4c2f-86f5-7e8cb1508887.png)

- Remove `Points per game` and added both `Country Rank` and `State Rank`
- Followed Juan's suggestion on showing game modes you haven't played yet. This could boost the number of players playing ranked
- retained placement games orientation
- Added the progress bar designed here: https://discord.com/channels/605233308577562643/790772223358402571/1015368484684832998

### Player didn't play any ranked games yet
![image](https://user-images.githubusercontent.com/90673012/188473816-7502877f-f7e7-470a-b987-b8c81a70d936.png)

- for `own profile` show a play this game mode CTA
- for `other profile player` just show no games played

### Player clicks on a card
![image](https://user-images.githubusercontent.com/90673012/188473651-7482f6e8-5225-4467-9e1a-11cb0f13c05a.png)

- if player clicks on a ranked game mode they haven't played in their profile, redirect them to matchmaking
- if player clicks on a ranked game mode they played, redirect them to the leaderboards tab. 
- if player is viewing another player's profile, all cards clicked (played, not played, placement) should redirect them to the leaderboards tab

### Player clicks on the season selector
![image](https://user-images.githubusercontent.com/90673012/188473673-2b361ea9-10c7-4bb6-b794-89e123af99c5.png)

- no changes for season selector flow

## Related Submission
- https://github.com/colonistio/design/issues/142
- https://github.com/colonistio/design/issues/135
- https://github.com/colonistio/design/issues/125

## Related links
- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @JuanRoman77 @demiculus 

updated the profile checklist with this one. also

>  we should show the divisions progress bar in the profile as well. Same thing we show in the end game screen. That's how players would know how much they've got left to rank up.

I created a study for this here:
![image](https://user-images.githubusercontent.com/90673012/186727141-dd985be6-98ca-4b48-abfe-35eb91b51d4c.png)

didn't include this one in these submissions since showing player progression in the dimensions of each card would make the progress bar really small. It could also make noobs feel insecure if everyone can see a visual that they are at the bottom of the rankings. 

if we want to show the progress bar, I think we could include that in the overview tab along with some general info or pursue a horizontal card type instead(https://prnt.sc/PwUW_zkSHJME), since we can make the progress bar better in that layout.

should I include the progress bar? in any case I can update the images here to reflect that

**Comment by goktugyil** [comment]
How would it look in overview vs here?

**Comment by samgawaran** [comment]
> How would it look in overview vs here?

currently doing some designs, will show them in awhile

**Comment by JuanRoman77** [comment]
@samgawaran seems like you removed the Leaderboards access point from the cards? Why was that? There was a Go to Leaderboards text at the bottom of each.

**Comment by samgawaran** [comment]
> seems like you removed the Leaderboards access point from the cards? Why was that? There was a Go to Leaderboards text at the bottom of each.

I mentioned this in one of the scenarios. The whole card when clicked should go to either Leaderboards or the Matchmaking popup. 

____________________________

I added the progress bar in each of the cards
