### ISSUE TITLE
Profile Revamp - Profile Sticky & Search Bar (Screens + Scenarios) Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#152]
## Summary
Minor fixes for the profile sticky based on Juan's feedback: https://github.com/colonistio/design/issues/150#issuecomment-1226710960

## Screen
![image](https://user-images.githubusercontent.com/90673012/186741656-d14035dc-78b4-4716-8764-799f197e88d7.png)
- for `other profile` add a dropdown for add friend and report, for future purposes, we can also add a send a gift and messaging here.

### Dropdown Views
![image](https://user-images.githubusercontent.com/90673012/186741860-364780aa-d853-4336-908a-d685634a3317.png)

- Changed `Cancel Request` to `Pending` 
- If the player clicked on Pending, the friend request will be canceled and becomes `Add Friend` again

## Scenarios
- Gifting and Messaging Scenarios are for sample purposes only. Not required for implementation
### Gifting and Messaging
![image](https://user-images.githubusercontent.com/90673012/186742298-c6cb7f60-1076-4370-a609-fc160a1eaef2.png)
![image](https://user-images.githubusercontent.com/90673012/186742316-ad9c2a52-5068-40a2-a245-c32dca655bad.png)

### Reporting a Player
![image](https://user-images.githubusercontent.com/90673012/186742440-ba5d9bd6-43b4-4b5e-ba99-4d6d4d28d23d.png)

- no changes besides popup width and height

### Search Bar Scenarios
![image](https://user-images.githubusercontent.com/90673012/186742467-496f4a29-c87a-4215-8d58-b75e402faae0.png)

- no changes besides popup width and height
- I followed the search behavior/restrictions of our leaderboard search bar

## Related Submission
- https://github.com/colonistio/design/issues/150

## Related links
- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
For review:
@goktugyil @demiculus @JuanRoman77 

Iteration 1 is here: https://github.com/colonistio/design/issues/150, I'll update the profile checklist with this submission

**Comment by JuanRoman77** [comment]
I think it looks good, just make the word Pending be grey, or black at 0.7 opacity, and italic.

**Comment by goktugyil** [comment]
Does other games write Bronze Division? I don't think so but double check, it looks odd. Maybe if we hover over the image, if it shows bronze division text, that might be better

**Comment by JuanRoman77** [comment]
> Does other games write Bronze Division? I don't think so but double check, it looks odd. Maybe if we hover over the image, if it shows bronze division text, that might be better 


If you mean remove the word Division and just show the names, I think it makes sense.

**Comment by samgawaran** [comment]
> Does other games write Bronze Division? I don't think so but double check,
![image](https://user-images.githubusercontent.com/90673012/186823096-a0e0c2be-1984-47b3-bbba-a861539cddbe.png)

I did a quick check on some other games and I can confirm that **they don't use the word division in their division names**

> Maybe if we hover over the image if it shows bronze division text
I tried this idea out too, but we have some details like the placement games that need to be shown on that line of text so we can't remove it.

I'll go change the naming conventions to `Bronze, Silver, Gold, etc.` instead of `Bronze Division` on the screens

**Comment by miraul** [comment]
I think we should remove "Bronze" and make lowest league "Silver". Most of players played these new games with leagues and playing in "Bronze League" as a "Bronze" player is disturbing and frustrating. Make bad players happy by placing them to "Silver".

Silver >> Gold >> Platinum >> Diamond

**Comment by JuanRoman77** [comment]
> I think we should remove "Bronze" and make lowest league "Silver". Most of players played these new games with leagues and playing in "Bronze League" as a "Bronze" player is disturbing and frustrating. Make bad players happy by placing them to "Silver".
> 
> Silver >> Gold >> Platinum >> Diamond

- Silver is more populated than Bronze. It's easier/faster to go from Bronze to Silver, than from Silver to Gold.
- We will add more divisions in the future, so it makes sense for Bronze to be the lowest tier. It's accurate and how many games call it.

**Comment by goktugyil** [comment]
Any other comments guys? Otherwise let's finalize this

**Comment by samgawaran** [comment]
Updated `Dropdown Views` changed the look of `Pending`
