### ISSUE TITLE
In-game Remove Ads GIF - Clicking Animation

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#153]
## Summary
Sending this submission for this design issue: https://github.com/colonistio/design/issues/140, added a couple of studies for both boxed-shaped gold and desert since that's what we're using at the website.

![image](https://user-images.githubusercontent.com/90673012/186858321-084955d2-fa61-4160-a1b3-69589b5589bb.png)
samples shown here and the default clicking icon is the `hand` instead of a `cursor` Google and Mozilla web browsers also follow the hand icon so all of the studies are based on that.

### Desert
**Study 1**
![gif-removeads_desert-mouse_study1](https://user-images.githubusercontent.com/90673012/186858659-7902a828-3888-490d-9729-0ee9580cf467.gif)

**Study 2 (Disappearing)**
![gif-removeads_desert-mouse_study2](https://user-images.githubusercontent.com/90673012/186858678-e6f4dee9-95a0-4ec8-852f-449eb9db551d.gif)

### Gold
**Study 1**
![gif-removeads_gold-mouse_study1](https://user-images.githubusercontent.com/90673012/186858765-8bfb1951-26bc-4355-a435-08dafda090d3.gif)

**Study 2 (Disappearing)**
![gif-removeads_gold-mouse_study2](https://user-images.githubusercontent.com/90673012/186858772-d26a3909-3e4b-4708-a093-ce7abee5cd92.gif)

- I can't remove the clipping on the disappearing mouse when I convert it from MP4 to GIF

## Resources
- https://drive.google.com/drive/folders/18uwUGfyxHlqNxgMZXwA76641llgHPnCi?usp=sharing

Compressed to its fullest via freeconvert.com

## Related links
- https://github.com/colonistio/design/issues/140

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77

**Comment by demiculus** [comment]
Study 1 is better
- [ ] the hand moving out of the image means that the image overall is smaller with respect to the gif so make the hand on top of the image. 
- [ ] Make sure the whole gif widht & height sizes are the same as before
- [ ] The kb sizes are as low as possible.

Post the images here and tag me.

**Comment by miraul** [comment]
Study 1 is better

**Comment by JuanRoman77** [comment]
> Study 1 is better

Why?

**Comment by samgawaran** [comment]
@demiculus I revised the GIFs to fit the checklist:

### Desert
![gif-removeads_desert_v2](https://user-images.githubusercontent.com/90673012/189329296-cf6afeca-d5bb-4e3e-ad05-993a20617d71.gif)

### Gold
![gif-removeads_gold_v2](https://user-images.githubusercontent.com/90673012/189329319-efebcbb2-52f1-43de-ad65-c0b60f468c2b.gif)

### Overlayed in End-Game
![Remove Ads GIF](https://user-images.githubusercontent.com/90673012/189329158-6463faf9-de4e-4092-aacb-bdfb2c5cbf1c.gif)

> the kb sizes are as low as possible.

I managed to make it around 40% smaller. previous one was 800KB when compressed, this iteration is around 480KB when compressed. I tried to make it smaller than this but some of the color in the BG began to glitch.

**Comment by demiculus** [comment]
Can you follow the steps here: https://github.com/colonistio/design/issues/166#issuecomment-1241246457 
also make the gdrive links for those public so devs who dont have colonist emails can access them

**Comment by samgawaran** [comment]
closing this issue, implementation here: https://github.com/colonistio/katan/issues/8165
