### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by miraul** [colonistio/design#154]
## Summary
I got permission denied while trying to create new design-submit folder and add my new gameplay design into it.
## Details

git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags --set-upstream origin main:main
remote: Permission to colonistio/design.git denied to miraul.
fatal: unable to access 'https://github.com/colonistio/design.git/': The requested URL returned error: 403

Pushing to https://github.com/colonistio/design.git
Completed with errors, see above.

## Related links

- 

## Submission Checklist

- [ ] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by goktugyil** [comment]
there is no folder, create a new isuse

**Comment by goktugyil** [comment]
where is the issue?

**Comment by miraul** [comment]
> there is no folder, create a new issue. you don't need to deal with .git

i already opened an issue, dont understand what will be my next issue

**Comment by goktugyil** [comment]
You made a design.
Where is the design?
