### ISSUE TITLE
In Game - Keyboard Shortcuts

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#155]
## Description
We will be launching keyboard shortcuts. https://discord.com/channels/605233308577562643/716512630705225798/1008611965427527685, do some research on how other games do their shortcuts/keybindings and create some studies from those.

## Resource

- https://discord.com/channels/605233308577562643/716512630705225798/1008611965427527685

## Ideas from Feature Suggestion

- https://colonist.featureupvote.com/suggestions/73058/keyboard-shortcuts
- https://colonist.featureupvote.com/suggestions/311214/make-the-game-keyboard-only-playable

## Reviewer
@demiculus @goktugyil @omarhurani

**Comment by goktugyil** [comment]
Status of this?

**Comment by samgawaran** [comment]
next in my queue after the profile tabs. Could probably send a submission by tomorrow

**Comment by goktugyil** [comment]
> Another relevant comment in the polls was related to the browser addon. I have messaged the user Meranaldar and he sent me the addon link (https://gist.github.com/Silvyre/7e73756f108dc987a0d12d609e615371)
