### ISSUE TITLE
Ranked Season Rewards - Ads, Banner & Social Media Posts

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#158]
## Summary
As discussed here: https://github.com/colonistio/katan/pull/7979, we will be launching seasonal rewards for our ranked games. I created a couple of studies and created previews along with them.

**EDIT** After Juan's comments, I added the finalized list here as well.

## Finalized List
![image](https://user-images.githubusercontent.com/90673012/187905488-5bbc40e1-4d81-46a1-891b-ff35464d2d2b.png)

- Changed from `Plus` to `Premium`
- minor copy changes based on @JuanRoman77 comments
- Changed from `Season 2 Ranked Rewards` to `Ranked Season 2 Rewards`

### Overlay Preview
![image](https://user-images.githubusercontent.com/90673012/187905741-38e734a1-1821-4f9c-9323-373227d9fa2d.png)

_______________________________________________________________

## Other Studies

We can also interchange some of the BGs for the banner and social media postings

### Store Ads (Left and Right)
![image](https://user-images.githubusercontent.com/90673012/187652395-755617d4-24f0-4b48-b3c5-a4a2b701fae2.png)

### Adblock Ads
![image](https://user-images.githubusercontent.com/90673012/187652487-d51439c2-2579-4eb6-99b1-f5604595b295.png)

### Announcement Banner 
![image](https://user-images.githubusercontent.com/90673012/187652589-86965e0c-2c36-4312-ab4f-620e885912df.png)

### Social Media Posts
![Social Media Posts-min](https://user-images.githubusercontent.com/90673012/187653469-8e62ab7c-eb2b-4b53-a8b2-49d5c90b65d9.png)

## Related links
- https://github.com/colonistio/katan/pull/7979

## Resource
- https://drive.google.com/drive/folders/1DX0svaA02IINuka7L7Oiw1u4TnMKAcCL?usp=sharing

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 

tagging @JeffdEon as well. 

if the feedback are minimal, I'll just edit the images here so there's no need to create a new submission

**Comment by JuanRoman77** [comment]
For the lobby ads, this image is ok 
![image](https://user-images.githubusercontent.com/73320460/187748921-6136a2ee-77f8-4848-a4ef-606297b37961.png)

For the side banner ads, this image is ok. 
membership -> Membership
Remove `2 months`
![image](https://user-images.githubusercontent.com/73320460/187749081-95e20d78-4d75-43ac-99be-111d92faf97e.png)

For the announcement banner, this image is ok.
Text:
Top 10 players of each game mode 
will be rewarded with a Plus Membership!
![image](https://user-images.githubusercontent.com/73320460/187749461-3cab08df-5a79-4771-9763-c92440e54f98.png)

For social media posts, this image is ok.
Reduce the size of the icons in the middle and add the following text below:
Get a FREE Membership!
![image](https://user-images.githubusercontent.com/73320460/187750451-19222bb9-6903-45b3-a138-a412c1c7a61c.png)

**Comment by samgawaran** [comment]
@JuanRoman77 @demiculus 

I added the revised assets/materials here: https://drive.google.com/drive/folders/1DX0svaA02IINuka7L7Oiw1u4TnMKAcCL?usp=sharing

compressed all of them besides the `SM post`, since we won't upload to the website. `Banner` when compressed too much makes the image grainy so I stopped at 36kb

**Comment by demiculus** [comment]
use this: https://github.com/colonistio/katan/issues/8086#issue-1358119017
