### ISSUE TITLE
Leaderboards - Ranked Games Info + Play Now (Research and Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#159]
## Summary

I looked into how other games display how their ranked games work. I initially based my ideas in finding a spot for it inside the leaderboards but in my research, **none of the 3 AAA games show their ranked info inside the leaderboards**

I also added `Play Now` ideas as it is also requested in the #design channel

These are a few sketches I had in mind. I will update this issue depending on the initial comments/feedback given and when I redesign the popup in the matchmaking screens

## Research
![image](https://user-images.githubusercontent.com/90673012/188162924-ab1645d8-2acf-4e6c-938b-e6cbfb41c695.png)

- I linked the buttons that direct them to the games ranked info/how ranked games work
- all of them are popups
- all of them are inside the matchmaking or within the matchmaking screen

### Current Design
![image](https://user-images.githubusercontent.com/90673012/188158540-6f1d3d72-c181-4b9c-b727-119956ae35de.png)

- Awkward spacing at the bottom
- 2 orange CTAs makes the CTA color less effective

### Revised CTA Placement
![image](https://user-images.githubusercontent.com/90673012/188160033-ccb87cbe-858c-45b0-b092-bac958d15ec2.png)

- same implementation with what we currently have, changed CTA color spacing, and added ranked info

### Header Play Now
![image](https://user-images.githubusercontent.com/90673012/188160458-df733fb7-6995-49c6-a25d-cfa8308b1953.png)

### Play Now in Header
![image](https://user-images.githubusercontent.com/90673012/188158576-965db987-0249-4725-92ff-4b11059a26bc.png)

- AB Test Idea: Add a `Play Now in the header so every player can matchmake on any page in the website

## Related links

- https://discord.com/channels/605233308577562643/790772223358402571/1014813215651270668
- https://github.com/colonistio/katan/issues/8088

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 

the research above shows that AAA games don't show ranked info in their leaderboards. I'd still check some other games but all of the games that show their ranked info inside their game show it in their matchmaking screens

**Comment by demiculus** [comment]
- Do another iteration
- go through the level2 designer checklist
- ask yourself questions like "does this make sense" "what would make more sense" for every single part of the item
- include juans design as well
