### ISSUE TITLE
Store & Checkout Page A/B Test Ideas

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#16]
## Description
Creating this page to organize A/B Test Ideas for design issue https://github.com/colonistio/design/issues/6

## Resource

- https://www.figma.com/file/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?node-id=3245%3A57499

### Subscription
- Monthly Subscription (All of the plans have the same tiers but with different lengths, ex. annual has a bigger discount than monthly)
- Tiered Subscription (Different set of tiers, ex. Common, Premium, VIP with VIP having the most perks)
- Monthly and Tiered (using them both allows players to have more options but we haven't tested enough on https://github.com/colonistio/katan/issues/6265 if a Tiered subscription would be better)

- Listing out all of the perks each vs. showing it as _all of previous rewards_

### Checkout
- Selecting a subscription length here if we're using Tiered Subscription
- Showing a guarantee badge vs a simple lock icon
- Adding a payment journey (Step 1: select a subscription length, Step 2: selecting a payment method, Step 3: Reviewing your order)
- Showing the payment methods as cards vs showing them as a list (listing them is more widely used)
- Adding an info icon in the Xsolla/Stripe payment methods vs. without

### Coins Topup Access Point
- Clicking on coins section will direct the players into a popup and they can buy coins from there (they can be in the Lobby and top up coins)
- Clicking on coins section will transfer the players into the buy coin tab at the store. (better access point if we want players to see what they can buy after they top-up

### Store Cards
- Changing the styles of the store cards from [this](https://prnt.sc/CGEiXi4_S6xe) to [this](https://prnt.sc/Xbbowey7xpY9) (applying these design allows us to be more consistent in the placements of our info icon, easier to see prices, add our best value [tag](https://prnt.sc/kiz7qI1H1XPX) without worrying it would overlap with the item name)

### Guest/Signed User State
- Showing the store page to a guest user vs not showing the store page until player signs in

**Comment by samgawaran** [comment]
> Are the ideas inside figma? :D 

Yes! I'll send some screenshots in a few hours. Just polishing things up

**Comment by goktugyil** [comment]
I think idea list should be text, actual a/b tests and results should be in image/figma format. right @demiculus ?

**Comment by samgawaran** [comment]
**Listing out all of the perks each vs. showing it as all of previous rewards**
- only applicable if we're using tiered subscriptions

![image](https://user-images.githubusercontent.com/90673012/165400954-cc80bf89-6b4b-48de-b081-e6a32550bc28.png)

- Listed Juan/Chess idea here of showing all of the perks vs showing `All of "Tier Name"`
- I would prefer using showing `All of "Tier Name"` if we are listing out a lot of perks since the spacing would be hard to maintain on the more expensive plan

**Comment by samgawaran** [comment]
### Subscription Icons

![image](https://user-images.githubusercontent.com/90673012/165402974-b00b5738-c265-4aeb-aa34-430b6a1b9859.png)

- I prefer using the Game Assets as an icon. it advertises our `colors` and works in this color scheme since we have similar colors.

**Comment by samgawaran** [comment]
### Monthly and Tiered
![image](https://user-images.githubusercontent.com/90673012/165410506-909573cd-4668-4c61-89e3-4fc628cd318e.png)

- If we would be both using monthly and tiered plans, I suggest we should stick on using Annual and Monthly only. More options could lead to players not choosing anything at all.

### Monthly Subscription
![image](https://user-images.githubusercontent.com/90673012/165411625-6e69c877-2284-45b6-a6b4-25cbc9499785.png)

- I recommend using these option for now due to not having enough information on what players would buy if we would opt for Tiered https://github.com/colonistio/katan/issues/6265

**Comment by samgawaran** [comment]
### Checkout

- This layout is applicable for both Tiered and Monthly subscriptions

![image](https://user-images.githubusercontent.com/90673012/165412608-5c527245-1650-4f5a-8ddd-471086587a34.png)

- I prefer using the 1140px grid layout since we are using those all throughout the website. Though the Centered one also works since the checkout page is a special page.

- @goktugyil I added `Bitpay` in the payment method but removed `Amazon Pay` to retain 8 payment methods. (better alignment instead of 9) so we won't be having scrollable checkout. 

- I followed this [chart ](https://prnt.sc/BEqj5TTGLFML) for the order

**Comment by demiculus** [comment]
> I think idea list should be text, actual a/b tests and results should be in image/figma format. right @demiculus ?

This place should just have screenshots & text. We won't have the resources to do 90% of the tests here. So they should be clear.

**Comment by samgawaran** [comment]
### Showing the payment methods as a list

- Applicable if we're not allowing players to select subscription length in Checkout

![image](https://user-images.githubusercontent.com/90673012/165425828-755293ce-401b-4bcc-9a49-b439ac9190f4.png)

- I recommend using this option over the cards and prefer the `Left Aligned` since it looks more balanced
- Steam, Roblox, GOG also use lists in showing their payment methods

**Comment by samgawaran** [comment]
### Store Popup 

![image](https://user-images.githubusercontent.com/90673012/165504322-751e640f-4df2-4af7-a7f0-346ae1784d4e.png)

- Checked out some possible ideas with these [color combinations](https://prnt.sc/HGk-g6EVB76M) since our current one has a shit color like Goku mentioned.

- Didn't add an `owned` popup since you cannot click on an owned item in the new designs. to reduce the number of popup scenarios

**Comment by goktugyil** [comment]
Wow a lot of stuff. Good work!

> Game Assets as an icon
> Left Aligned Payment
> Proposed Store Popups & Color

Approved. You can add these to the main design

**Comment by goktugyil** [comment]
> I would prefer using All of "previous rewards" if we are listing out a lot of perks since the spacing would be hard to maintain on the more expensive plan

We will show all perks until we add more things to sell. The reasoning is at first we're not going to have many things to sell and it does look clearer. Add this to the things of decisions to add into `store-design-decisions.md`. You will be editing the file and adding our feedback and knowledge there

**Comment by goktugyil** [comment]
> If we would be both using monthly and tiered plans, I suggest we should stick on using Annual and Monthly only. More options could lead to players not choosing anything at all.

https://github.com/colonistio/design/issues/16#issuecomment-1110361622

### Discussion: 

When billed yearly, is a positive thing, I think we should show that

Options:
1. Tabs for Annual/Monthly
2. 1/3/12 Months showing
3. 3 separate tiers showing, having yearly selected as default and an annual/yearly check in stripe/xsolla (I'm not 100% sure if we can add into xsolla)

I'm leaning towards 3. What do you think @demiculus

**Comment by goktugyil** [comment]
> Customize your checkout page with new branding features. You’ll be able to select from a range of colors, fonts, and border styles to match your brand. If you're interested in trying this feature out, please reach out to [checkout-branding-beta@stripe.com](https://info-link.stripe.com/MDcyLU1ESy0yODMAAAGCDHeYikZsmTycjnxPp7slg4FVhIr3oWVOqzLof2-exgvTAZyw7chx4DNXKe0aTphs4WjapS4=).
thoughts?

**Comment by goktugyil** [comment]
A/B test idea:

<img width="752" alt="Screen Shot 2022-04-27 at 16 48 33" src="https://user-images.githubusercontent.com/5816878/165628304-a5607a8f-350d-40d2-abbd-b8bd87c46e97.png">

**Comment by demiculus** [comment]
> Proposed Store Popups & Color

Hold off on this. Create a separate issue and dump related stuff there. Don't work on popup colors! Always decrease scope. I'll give popup color feedback in that issue.

**Comment by demiculus** [comment]
> 3 separate tiers showing, having yearly selected as default and an annual/yearly check in stripe/xsolla (I'm not 100% sure if we can add into xsolla)
I'm leaning towards 3. What do you think @demiculus

Agree

**Comment by demiculus** [comment]
> Customize your checkout page with new branding features. You’ll be able to select from a range of colors, fonts, and border styles to match your brand. If you're interested in trying this feature out, please reach out to [checkout-branding-beta@stripe.com](https://info-link.stripe.com/MDcyLU1ESy0yODMAAAGCDHeYikZsmTycjnxPp7slg4FVhIr3oWVOqzLof2-exgvTAZyw7chx4DNXKe0aTphs4WjapS4=).
> thoughts?

Decrease the scope, do this after its launched.

**Comment by samgawaran** [comment]
> 3 separate tiers showing, having yearly selected as default and an annual/yearly check in stripe/xsolla (I'm not 100% sure if we can add into xsolla)

To be clear... We're not showing the renewal options on the subscription page and checkout page right? we will just put them inside the Stripe/Xsolla pages?

**Comment by samgawaran** [comment]
**Subscription Cards for Idea 3**

- https://github.com/colonistio/design/issues/16#issuecomment-1111376209 for the ideas

![image](https://user-images.githubusercontent.com/90673012/165712904-861b6582-fd6d-4090-856f-9c901cda27ba.png)

- This is what our subscription page will look base on the idea. subscription perk listing is base [here](https://github.com/colonistio/design/issues/16#issuecomment-1111355960)

If this is good, I'll put this in the current finalized list in [Store/Checkout](https://github.com/colonistio/design/issues/6) Main Thread

**Comment by goktugyil** [comment]
> > 3 separate tiers showing, having yearly selected as default and an annual/yearly check in stripe/xsolla (I'm not 100% sure if we can add into xsolla)
> 
> To be clear... We're not showing the renewal options on the subscription page and checkout page right? we will just put them inside the Stripe/Xsolla pages?

yes

**Comment by goktugyil** [comment]
https://user-images.githubusercontent.com/90673012/165410506-909573cd-4668-4c61-89e3-4fc628cd318e.png

@samgawaran We're going forward with tabs for monthly/annual. Add this to the final design

**Comment by goktugyil** [comment]
https://user-images.githubusercontent.com/90673012/165425828-755293ce-401b-4bcc-9a49-b439ac9190f4.png

This is amazon:
<img width="119" alt="Screen Shot 2022-04-28 at 21 49 45" src="https://user-images.githubusercontent.com/5816878/165873627-36c0e47f-e018-4f66-a4b6-6204d2aaad22.png">

there are no checkmarks, only circle buttons. Change our checkmarks to these

**Comment by samgawaran** [comment]
## Radio Buttons

- Created some ideas for the radio buttons

![image](https://user-images.githubusercontent.com/90673012/165933214-7249fe20-4d00-4d57-b571-2414c945289a.png)

- Tested out some colors but like what Goku posted in Amazon's button, I recommend using `Blue` since it blends well with our website and is the standard color for radio buttons

**Comment by samgawaran** [comment]
## Simplify Review Your Order

- During our 1on1 Demi suggested removing the `pay via` section inside review your order since its already selected in the payment method 

![image](https://user-images.githubusercontent.com/90673012/165937451-b2095ea6-df1e-4d52-8aa3-e7e7dfcc8a67.png)

- I recommend removing the Pay via and moving the price in the same line with the item name and image

**Comment by samgawaran** [comment]
## Tabs for Monthly/Annual

- Before adding this to the finalized design, just want to show some adjustments I made for the subscription cards.
- Made the Tier Level shorter and reduce the spacing in-between each perk listing

![image](https://user-images.githubusercontent.com/90673012/165941953-534b578e-d774-49cc-95db-26172a1c3364.png)

- If all is good, I'll change the sizes in the finalized list and add the tabs there as well

**Comment by goktugyil** [comment]
About subscriptions trophy icon, how can we improve that?

**Comment by JuanRoman77** [comment]
> About subscriptions trophy icon, how can we improve that?

What subscription trophy icon?

**Comment by goktugyil** [comment]
<img width="80" alt="Screen Shot 2022-04-29 at 22 40 02" src="https://user-images.githubusercontent.com/5816878/166087281-9237f16e-0ccc-4859-98d8-7f2b91325fa5.png">

**Comment by samgawaran** [comment]
Closing this issue as all-new uploaded versions will be in this issue: https://github.com/colonistio/design/issues/37

includes both the finalized list for Desktop and Mobile Versions

**Comment by goktugyil** [comment]
what about future a/b test ideas?
