### ISSUE TITLE
Gifs for Lobby Ads

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#160]
## Description

Read this: https://github.com/colonistio/katan/issues/8098

We think that the end game item box is receiving more clicks because it is a gif. We will test this out.

Make these images into gifs
![image](https://user-images.githubusercontent.com/6215305/188263597-196fea26-05c2-4fad-9970-c1a723e01278.png)
![image](https://user-images.githubusercontent.com/6215305/188263622-428f7df4-8541-453a-891c-8f201ac606f1.png)
![image](https://user-images.githubusercontent.com/6215305/188263630-74350c24-7a52-4e69-aded-07a46b56cc4f.png)

We'll run an a/b test to see how much more conversion gifs bring vs pngs.

## Submissions

- https://github.com/colonistio/design/issues/166

**Comment by samgawaran** [comment]
closing this issue, implementation is here: https://github.com/colonistio/katan/issues/8154
