### ISSUE TITLE
Profile Revamp - History Tab Players + Images (Screens and Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#162]
## Summary
Following the discussions at the team meeting and comments on the previous submission, this submission shows the screens + scenarios of the agreed design.

Research for the history tab is done [here](https://github.com/colonistio/design/issues/135)

## Screens
![image](https://user-images.githubusercontent.com/90673012/188458552-b03ef743-03f7-4bc6-ae47-acb4263a495d.png)

- Used the game mode images instead of plain text for (Base, 1v1, SF, C&K etc.)
- Position used `#1,#2,#3) instead of `1/4, 2/4, 3/4) to reduce the amount of text and make it bold
- Games with 5 or more players will have their cards expand in height to accommodate player names
- Date reduced from `10/8/2022, 10:58AM` to `10/8/2022` full date can still be seen via the expanded view
- for player names, that's awfully long like `WWWWWWWWWWWW` show them as `WWWWWW...` instead
- Added `MMR` as one of the sections, for scalability, we want players to eventually play Ranked all the time so adding a placement for the MMR in the main sections will make it easier for the players to know how much their MMR increase/decrease (this can also be changed to other sections like Duration or Turns if we don't want to show MMR there)
- Expanded View: show MMR changes for all players, if its unranked, show `-` 

### No Games Played
![image](https://user-images.githubusercontent.com/90673012/188458851-d736bf9e-304a-4e86-ac61-4bc7a22b9a1d.png)

- Owner View: clicking on `Play Now!` redirects you to the matchmaking popup

### Fewer than 7 Games
![image](https://user-images.githubusercontent.com/90673012/188459046-7efa5886-a450-414c-b340-f3089041989e.png)

- remove the scroller

## Related Submission

- https://github.com/colonistio/design/issues/136

## Related links

- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77 

let me know if I missed out on anything. Otherwise I'm adding this on the checklist: https://github.com/colonistio/design/issues/139

**Comment by JuanRoman77** [comment]
1. There are too many game modes, and more will come in the future. Images are not good representations of any of them. Remove the images and add the names. If the full expansion names don't fit, change them for C&K, C&K 5-6, SF+C&K, etc.
2. I prefer 1/4 over # 1. That's used in the Leaderboards, plus it doesn't indicate how many players that game had. I don't want to count names, I want to look at a number to know the amount of players.

**Comment by demiculus** [comment]
1. Remove the mode section completely
2. Position I agree with Juan and and it should be same font style as the rest
3. Can you list out all the types?
