### ISSUE TITLE
End Game MMR - Progress Bar Iteration #3 (Screens + Scenarios) 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#164]
## Summary
@JuanRoman77 and I discussed some changes here: https://discord.com/channels/605233308577562643/790772223358402571/1015368484684832998 via DM

current design still confuses some people. This design tries to simplify the rank changes and based on the polls here: https://discord.com/channels/605233308577562643/716512630705225798/1011015191288348682 is more favored by our players.

## Comparison
![image](https://user-images.githubusercontent.com/90673012/188591661-64501dfd-1f1c-4b0a-bf5f-8921e8df53aa.png)

1. Divisions are now on top of the progress bar. MMR change is inside the progress bar and your current rank is at the center.
2.  if a player wins/loses the progress bar shows a bright green color if they win and a dark shade if they lose to indicate if they gain MMR (most games does this [here](https://user-images.githubusercontent.com/90673012/188592391-1f9d5ea7-9dbd-429c-83bf-c5a1aade1e84.png) ) this also can help us reduce the animations here since players can easily see how much MMR they received. @JeffdEon @JuanRoman77 let me know what you think

### Victory / Defeat
![image](https://user-images.githubusercontent.com/90673012/188593073-91eb6b8a-dd75-420a-b6b5-23e76dd0e6c1.png)

### Promoted / Defeat
![image](https://user-images.githubusercontent.com/90673012/188593096-dbe31fea-f575-42b9-bd52-fceb23b9de53.png)

The game after they got promoted/demoted their next game should show the corresponding new rank in the middle. 

ex. if the player got promoted to gold, the gold tier will now be at the center in their next game and platinum will be on the right side and vice versa.

### Platinum / Bronze Ranked
![image](https://user-images.githubusercontent.com/90673012/188593133-c5bbce4b-4881-46ae-8912-a5997842c827.png)

### Top Rank Player
![image](https://user-images.githubusercontent.com/90673012/188593183-5fc4aaeb-638a-44fb-9402-1c42467eade2.png)

## Related Submission

- https://github.com/colonistio/design/issues/148

## Related link

- https://github.com/colonistio/katan/issues/7867

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus @JeffdEon @JuanRoman77

**Comment by JuanRoman77** [comment]
Looks good to me. Leaving the final approval to @JeffdEon

**Comment by JeffdEon** [comment]
> The game after they got promoted/demoted their next game should show the corresponding new rank in the middle.

Only question, why not just show new rank in the middle now?

**Comment by JuanRoman77** [comment]
> why not just show new rank in the middle now?
That will be the case, yes, from the following game onwards. It is likely that a player goes up and down divisions when they are in the middle so I guess this makes sense.

**Comment by demiculus** [comment]
According to the research Sam has done, this iteration & the previous one do not fit the other games. 
@samgawaran do another iteration with what we talked about. 
Copy the styles from existing games
