### ISSUE TITLE
Matchmaking Optimization

### ISSUE THREAD

**Issue by omarhurani** [colonistio/design#165]
## Description

After conducting 3 tests, with results shown here:
- https://github.com/colonistio/katan/issues/7917
- https://github.com/colonistio/katan/issues/8048
- https://github.com/colonistio/katan/issues/8130

General conclusion is:
* Highest priority to optimize matchmaking is to make lobby harder to access than matchmaking games.
* Next comes making matchmaking easier to access in general.
* Having "Play" inside CTAs isn't worth optimizing at the moment, might explore later with improved designs.

After talking with Goku, now it makes sense to move on from testing ideas to testing designs.

From the conclusions we need (an) optimized design(s) in that direction

## Related Submissions
- https://github.com/colonistio/design/issues/168

## References:
- #115

**Comment by samgawaran** [comment]
@omarhurani could you paste the screenshots of the prototypes you did here? thanks

**Comment by omarhurani** [comment]
## HOMEPAGE_MATCHMAKING
Large buttons
<img width="500px" src="https://user-images.githubusercontent.com/26940488/184158257-e762e9b2-0e3d-4a8b-bd26-e4aa981928d8.png"></img>

## MATCHMAKING_OPTIMIZATION
### Large buttons
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187053444-b537aef6-74ba-4959-87f5-06abc9b9a6e5.png"></img>

### Small buttons, summary under
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187053411-9e4afaa0-13b6-4695-bf1e-daf0f7a04bc9.png"></img>

### Hide lobby, show summary instead, lobby inside Play CTA
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187053456-e3e82481-5418-4ac4-aeaf-b06f60fc305e.png"></img>
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187053458-791e8a0d-5a99-42a4-bcdd-dc1050292f09.png"></img>

## MATCHMAKING_OPTIMIZATION_2
All small buttons

### Show lobby
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187120442-906f73de-d1ea-4784-965e-df886a73e7e6.png"></img>

### Show lobby, add "play" to buttons
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187120443-f2e846d2-2017-4c56-8de0-0657b2604d6b.png"></img>

### Show summary
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187120446-5c6e08ee-7794-4c58-8d6d-69752e6a6774.png"></img>

### Show summary, add "play" to buttons
<img width="500px" src="https://user-images.githubusercontent.com/26940488/187120449-959383de-7ee2-4a88-a4a6-6a317924c19b.png"></img>

**Comment by samgawaran** [comment]
created an implementation issue for this:
https://github.com/colonistio/katan/issues/8295

closing this issue
