### ISSUE TITLE
Lobby Ads - GIF Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#166]
## Summary
Based on the report here: https://github.com/colonistio/katan/issues/8098 the itembox in the end-game screen garnered a lot more clicks compared to other ads. 

GIFs made here will be subjected to AB-Test to check if players click them more compared to static

I looked at how some other sites use GIFs and they don't make it super animated, I assume that they don't want the players to be distracted enough to leave their websites

## Details
![sample](https://user-images.githubusercontent.com/90673012/189149651-cefded24-d982-49c8-b27c-2c9e2331ab59.gif)

- I did some faster versions for the Memberships, not sure if the speed is enough to grab attention in the first one

### Overlay in Lobby
**Leaderboards / Membership (Normal Speed)**
![global - normal speed](https://user-images.githubusercontent.com/90673012/189151744-3dd37112-edc9-4aa1-8f2a-e1aa2cc65cef.gif)

**Ranked Leaderboards / Membership (Faster Speed)**
![ranked - faster speed](https://user-images.githubusercontent.com/90673012/189151817-fcaac105-49b9-4f98-8deb-551791c6490f.gif)

## Related links

- https://github.com/colonistio/design/issues/160

## Resources
Compressed GIFs here:
- https://drive.google.com/drive/folders/124IGjRqrtKl6uAZW1A1onPX6zDWNX_OA?usp=sharing

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review:
@demiculus 

I can still edit the animation speed if you want. I'll just update this issue so no need to tag you again.

**Comment by demiculus** [comment]
They're fine, can you 
1. Create a development issue
2. Decrease size of all gifs
3. Add the gifs to the issue for the dev to download
4. Tag me in the issue so i'll edit it
5. Close this issue

**Comment by samgawaran** [comment]
closing this issue, implementation is here: https://github.com/colonistio/katan/issues/8154
