### ISSUE TITLE
Store AB Test - Daily Pass Expansions and Items (Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#167]
## Summary

- We want to test Expansions and Maps purchasable as a trial. I created some samples based on the requirements in here: https://github.com/colonistio/design/issues/146

## Research
![image](https://user-images.githubusercontent.com/90673012/189586213-46f53dc6-6f23-4acf-ac7e-1fb0dd119d10.png)

- If we would let players pay for the trial, it should be named `Daily Pass` instead. 
- More games allow free trials. Chess.com model is good sample for this, you need to pay after the trial has been used. If you cancelled before the date, you won't be allowed to try a "free" trial again.

### Toggles
![image](https://user-images.githubusercontent.com/90673012/189584224-fa8d3813-5181-4edc-a163-f1b83ce87bd8.png)

- Uses the setup we use for the toggles in `expansions`
- no changes in card layout

### 2 CTAs
![image](https://user-images.githubusercontent.com/90673012/189585173-28050548-c7f1-4002-a90d-a52a660f91a0.png)

- Lifetime Pass and Game Pass show different pricing

### No Permanent
![image](https://user-images.githubusercontent.com/90673012/189585163-0a7292f1-d346-4c3d-b139-b1f09e0aedd7.png)

- Only show daily pass as an option
- show a subcopy that says `want to skip daily pass? Be a Member`
- Could also use a 7 day, 30 day pass

### Modified Free Trial
![image](https://user-images.githubusercontent.com/90673012/189624270-1786fd18-da46-47d5-8387-78401b053639.png)

- Let the players try the expansion/map for free
- After 1 day, they need to pay the full price
- I still think having a `Daily Pass` is better at it could generate more value since they won't have ownership on the item like a subscription.

## Related links

- https://github.com/colonistio/design/issues/146

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
for review
@demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
Remove dark background..
try -> Try
than -> then
day -> day,

**Comment by samgawaran** [comment]
> try -> Try
than -> then
day -> day,

I updated the samples for this one above^

> Remove dark background..
It didn't look good but I tried to still execute it in this way:
![image](https://user-images.githubusercontent.com/90673012/189624510-09e7451a-ff16-48f6-b3bc-ee1c083a6c74.png)

we can remove the image also, but I don't recommend this option

**Comment by JuanRoman77** [comment]
I meant this one
 ![Screenshot_20220912-121113_Opera.jpg](https://user-images.githubusercontent.com/73320460/189690529-c3be2216-c5ce-4dcf-ab42-bc6a34775243.jpg)

**Comment by demiculus** [comment]
@samgawaran I change the main issue, @alexcoleman7 will take over the lead for this, you can follow his instructions
