### ISSUE TITLE
Profile - Add registered date somewhere on the profile

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#170]
## Description

If we add a registered date on the profile, people will be more likely to register. 

## Examples
Twitter: https://twitter.com/demiculus
Youtube: https://www.youtube.com/c/ycombinator/about
Facebook used to have this as well I'm not sure why not anymore

## During
- [ ] Check out examples of websites having this
- [ ] Read abtest on this feature and include it in the submission
  - [ ] Try to find why facebook doesn't have this anymore
- [ ] Create designs according to your research

## Reviewer
@demiculus

**Comment by aalmadan** [comment]
Is this still relevant?

**Comment by demiculus** [comment]
> How do we know that this is true? and what the user's motivation?

We don't know. 

> Do these reasons also apply to Colonist?

- Personalization: Yes
- Show off: Yes (older players would want to show they've been a Colonist user since early days)
- Build trust: Yes (karma also does an okay job)
- Celebrate anniversary: In the future

**Comment by demiculus** [comment]
> Date joined 

Not sure of the value showing it on all pages

> the registered date, karma, and maybe the total game play are used to built trust among users. therefore these should be group together and should not be hidden from the profile landing page.

This makes a lot of sense, can you try putting them together?

> twitter and instagram profile section contain the trust-building metrics like join dates, usernames, followers, and post counts

Extra idea, should we also add, connected accounts to increase trust? Add their membership status to increase trust? 
There is already an issue for membership icon : https://github.com/colonistio/katan/issues/16556

> decorative badge ie 1 year anniversary, early adopter, etc these can be a fun way to incentivize users to showcase their milestones.

Yes, reddit has these, gives a nice feeling. Makes it so that people don't create a lot of fake accounts and stick to single account. Reddit has lots of trouble with fakes. But we don't want to complicate much. 

-----

Also lets not increase the scope much if there isn't that much value.

**Comment by demiculus** [comment]
> I don't think a redesign of the profile page is necessary at this time, as there are no significant user complaints or use cases justifying it. The proposed changes is for overall UX improvements.
for the registration date, we should add it to either the header or the overview -> track the analytic to see if there's any positive improvement -> if yes, we could revisit the profile page redesign.

Cool, can you create a development issue on the main repository? When we have suitable dev time, they'll take the issue and deliver it.
