### ISSUE TITLE
Matchmaking Optimization Submission #2 - Design Studies + Refinement

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#171]
## Summary
Omar did a couple of tests here: https://github.com/colonistio/katan/issues/8048 , https://github.com/colonistio/katan/issues/8130

The following designs are based on the comments the previous issue here: https://github.com/colonistio/design/issues/168#issuecomment-1250249312

## Studies

- I didn't create comparisons from before as the studies here are based on the thread of the prev issue.
- `Overview` is the general stats of the player (based on the design of the revamped profile pages) I added a slot for a random stat to make it 2x3
- studies that show game types now shows a revised card. (this card design was approved before during ranked integration but was never developed)

### A. Lobby as a text button

![image](https://user-images.githubusercontent.com/90673012/190950762-fa2b7997-fc77-42d2-8e2a-7de00fa367d8.png)

- Added `Friends` as just using overview will leave as a lot of empty space. We can interchange on to other features as well
- `Play` CTA will show the current one being used in the website https://prnt.sc/V2wt_D5if3QU

### B. Lobby as additional card in `Play`

![image](https://user-images.githubusercontent.com/90673012/190951040-6273c719-e6fb-4d1e-9f25-14609b73cd56.png)

- I used Omar's icon atm. I checked Lobby icons and Game lobby icons on the web and I found a hotel concierge icons

### C. Lobby in the header
![image](https://user-images.githubusercontent.com/90673012/190951215-bb2d73cc-b4c4-4a08-b041-51456fc1264b.png)

- Moved `Ranked` Game Types in the homepage
- added a subcopy in the `Play` to indicate it only shows `Unranked` Game types

###  D. Lobby as sub CTA V1

![image](https://user-images.githubusercontent.com/90673012/190951733-9e715966-8697-48cc-ae33-30e7b4eef2eb.png)

- made `Create Game` as main CTA. majority of players play with friends on private rooms and just send links to their friends
- Clicking on `Enter Lobby` will remove Overview and Ranked Game Types https://prnt.sc/R7vUNMW8lmZ_

### E. Lobby as sub CTA V2
![image](https://user-images.githubusercontent.com/90673012/190951975-615dcebf-a9bf-492d-8ec3-55843fe1d8eb.png)

- Add toggle for ranked/unranked. no scroller (toggle style in store)
- made the overview smaller. removed `karma` since its already showing in your profile header

## Related Submission

- https://github.com/colonistio/design/issues/168

## Related links

- https://github.com/colonistio/katan/issues/8130
- https://github.com/colonistio/design/issues/165

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@omarhurani @demiculus

**Comment by demiculus** [comment]
@omarhurani A or C? why?

**Comment by samgawaran** [comment]
C.

- Much more flexible `Play` button (we can show unranked C&K and SF as coming soon)
- **Ranked Games are on the homepage** and each card doesn't take much space

I can also make the cards smaller:
![image](https://user-images.githubusercontent.com/90673012/190961555-cccb15a7-4b4a-46fa-9228-2a218baa53c5.png)

so there's no need for scrollbars
