### ISSUE TITLE
Discord Game Labs - Colonist (Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#173]
## Summary
Master Issue:
- https://github.com/colonistio/katan/issues/8173

We will be launching as part of Discord Game Labs, the following design + scenarios are base on the initial sketches done by @seojoon-y here: https://github.com/colonistio/katan/issues/8219#issuecomment-1250324811

## Screens
- Dimensions used in the design is 1280x720. Discord doesn't allow full screens in their game lab's activities so its a good measure to design on a small screen

- No need for Mobile versions as Game Labs doesn't support mobile & Tablet OS

### Landing
![image](https://user-images.githubusercontent.com/90673012/191470122-3894fbc2-4ab9-4ffe-81c8-d6f23244ed33.png)

### Lobby / Room
![image](https://user-images.githubusercontent.com/90673012/191470786-1b7d6e37-811a-4571-a042-c10b69ed1c87.png)

- Clicking on the `arrow_icon` will get the player back to the landing page
- Clicking on the `book_icon` will redirect the player to the rules page
- Remove `Karma` on all player cards
- **NOTE:** I changed the layout for advance settings. I figured it would look better this way compared if I just follow the layout in the website currently. See this: https://prnt.sc/12D8SHswXtrc

### In-Game
![image](https://user-images.githubusercontent.com/90673012/191470837-c0c83849-8f74-4f40-a6d8-68e8ab66acd3.png)

- created an in-game version where there is no `chat`. instead, this version expands the `game logs`

## Scenarios

Header
- Clicking on `Leaderboards` `Community` and `Store` will redirect the player to our website

Landing
- Clicking on `Play vs Bots` will make the player proceed to a 4P game with bots (current logic in Website)
- Clicking on `More Game Modes`will direct the players to our site. Specifically the store page.

### Host / Guest View
![image](https://user-images.githubusercontent.com/90673012/191474498-5f35178f-17ac-4452-8c6c-b2d8a897f9a9.png)

- The first player to click on `Create Room` will always be the host (you can be 8 players in the lobby and still see Create Room if no one clicks it yet)
- after a player click on `Create Room` the copy will show `Join Room` instead
- Only the `Host` can start the game and change the game settings

### Expanding the player viewer
![image](https://user-images.githubusercontent.com/90673012/191472537-4bb2769c-3d25-4811-8fe9-7a7ea7913d70.png)

- see player viewer in `Poker Nights` in Discord Game Labs

### Player clicks the rules icon
![image](https://user-images.githubusercontent.com/90673012/191476994-eb4e1b8a-8b99-41a7-9fd2-c8196a7d3378.png)

- as suggested above: show this popup: https://prnt.sc/wL82nOEsXIgn but remove the other game modes or make them unclickable

### Player clicks on advanced settings
![image](https://user-images.githubusercontent.com/90673012/191477222-7af95aba-7a45-402a-82b1-fad1e1bedbe9.png)

- if the player is not the `Host`. show this version thats not clickable: https://prnt.sc/6X55p5o4ATGh

### Host change a game setting
![image](https://user-images.githubusercontent.com/90673012/191478039-232822b9-c764-4cbf-a8e5-253b96c10774.png)

- whenever the `Host` changes a setting. follow usual logic that every player changes from `ready` to `not ready`

### Player clicks on his profile dropdown
![image](https://user-images.githubusercontent.com/90673012/191484881-c1935a4c-76f1-4109-b699-b01818a8e31a.png)

- clicking on all of the options here will redirect them to our website

## Related links

- https://github.com/colonistio/katan/issues/8173
- https://github.com/colonistio/katan/issues/8219
- https://github.com/colonistio/katan/issues/8224

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @seojoon-y

**Comment by samgawaran** [comment]
@seojoon-y

> User discord username on username in header
I forgot to mention this in our DMs: https://prnt.sc/lOFNP-EI_pMU

- I think it's better to use random usernames and just have them edit their names in the room. The reason for this is that we only allow limited characters in our player usernames. some discord names are longer than what we allow so it may look bad on the UI

**Comment by seojoon-y** [comment]
From our discord DM:
![download-1](https://user-images.githubusercontent.com/83441512/191486687-a97a1c6a-3afe-4d59-9521-18d5abf45b11.png)


> @seojoon-y
> 
> > User discord username on username in header
> 
> I forgot to mention this in our DMs: https://prnt.sc/lOFNP-EI_pMU
> 
> I think it's better to use random usernames and just have them edit their names in the room. The reason for this is that we only allow limited characters in our player usernames. some discord names are longer than what we allow so it may look bad on the UI

for the avatars and usernames, let's keep everything to be discord profile pic + username because i think it's what demi / goku wanted during the meeting. Also I think it'll be more consistent with the landing page discord profile pic horizontal bar. And we already discussed removing avatars from store for discord users. We can trim the username at a certain length.

**Comment by demiculus** [comment]
>  let's keep everything to be discord profile pic + username because i think it's what demi / goku wanted during the meeting.

Discord probably wants it. 

>  We can trim the username at a certain length.

Yes

1. Add `Rules` to header as most left option -> I'm assuming most players will not know/remember how to play. Having it in Landing Page, Room & Game will be convenient. Since I'm assuming such a player will want to check it multiple times.
2. Game expansions names are long, what will happen after clicking on dropdown? https://www.loom.com/share/2413265286e147a297cb408e41659d8a @seojoon-y I leave this UX to you. 
3. I can't see the value of showing the player icons in Landing Page. https://i.imgur.com/gmknpwZ.png We shouldn't do it because all the other games are doing it. Players already see each other inside of the discord channel. I don't get the benefit of this feature. I propose to remove it unless @seojoon-y you see a clear benefit of it.  

Rest seems fine

**Comment by seojoon-y** [comment]
The reason I proposed showing player icons in landing page was to make it clear where to find the other players. I was concerned that some players in your discord voice call would click "Play vs. Bots" or "Matchmaking"

We can solve this by renaming "Play vs. Bots" into "Singleplayer", and getting rid of the player icons in the landing page. What do you think @demiculus @samgawaran  ?

**Comment by demiculus** [comment]
> We can solve this by renaming "Play vs. Bots" into "Singleplayer", and getting rid of the player icons in the landing page. What do you think @demiculus @samgawaran ?

Makes sense 👍

**Comment by samgawaran** [comment]
Closing this issue, more updated submission here: https://github.com/colonistio/design/issues/176
