### ISSUE TITLE
Design Login Flow With Google + Facebook + Extendable to other forms

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#174]
## Description

We only have google login.

- [x] List out all the places where login is prompted
- [x] Design a login for the top right (a button and a popup in the middle of the page)
  - [x] Have google & facebook and for show include 2 others
- [ ] Try to scale that login solution to all the other places where login is requested
  - [ ] It might not scale to some places so try to create a mutual solution for them as well

__________________

These are the sections where Google Sign In is currently prompted
- All user dropdown functions
- Clicking on Ranked 4P or Ranked1v1
- All purchase CTAs in the store
- Player cell in Leaderboards

## From Feature Suggestions
**Login Method Variety**
- https://colonist.featureupvote.com/suggestions/84005/add-more-log-in-methods-other-than-google
- https://colonist.featureupvote.com/suggestions/129035/sign-up-with-non-gmail-emails
- https://colonist.featureupvote.com/suggestions/169337/login-with-metamaskethereum

## Related Submission
- https://github.com/colonistio/design/issues/175

## Resources
- https://github.com/colonistio/katan/issues/8318
- https://jagiya.notion.site/SSO-Can-Improve-Conversion-Rates-d72db9998f494319a309e39613e83954

## Reviewer
@demiculus

**Comment by samgawaran** [comment]
Close this issue? we already have the final submission here: https://github.com/colonistio/design/issues/220

also implementation is ongoing with Mau handling it.
