### ISSUE TITLE
Social Login Flow Submission #1 - (Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#175]
## Summary
- Having different login methods will increase our guest-to-player conversion rate. 

- Top comments in this [feature suggestion](https://colonist.featureupvote.com/suggestions/84005/add-more-log-in-methods-other-than-google) said that they want to buy expansions and maps but don't want to create a google account just for it.

Designs made here are based on this [report ](https://github.com/colonistio/katan/issues/8318) and research below

### Social Login UI
![image](https://user-images.githubusercontent.com/90673012/191966048-be96d67f-e507-4e04-ac64-0afbbafedc95.png)

- Uses button for options. The button color is either monochromatic (black or white) or follows the brand colors of the social login

### How other websites/games show social logins
![image](https://user-images.githubusercontent.com/90673012/191960631-b6ab206d-cec6-4908-8550-86fa45201ab4.png)

- Most websites either go by `Sign In` or `Log In`
- If the website has several CTAs on the header. The Sign In button is the only one with BG/different color

## Current Design
![image](https://user-images.githubusercontent.com/90673012/191954184-ad7ff7d5-6fff-4846-a695-70d09aa33d4a.png)

- design are on top of one another
- Sign In with google uses a different font size/style
- Shows a lot of options in the dropdown that the player cannot use unless logged in. Its better that if they click on the dropdown, they'll be directed to the login options for fewer clicks. 

### A. White CTA Login - Dropdown & Popup
![image](https://user-images.githubusercontent.com/90673012/191960873-160c1490-84f6-471d-8e80-485e0a14e6b8.png)

- No Guest Details
- Most common social login layout
- `Log In to Colonist` will expand to show the options. This can be prototyped if this is selected
- **White cta version** - This reduce the number of colors seen at the dropdown

### B. Login w/o containers - Popup w/ Perks
![image](https://user-images.githubusercontent.com/90673012/191960960-029e171f-99e5-4137-9f55-d3c1f7511a73.png)
- `Log In / Sign Up` with Guest info at the bottom
- Login Popup showing features exclusive to signed players. something like these: https://prnt.sc/Fh1iN_WOEF6x

### C. Green Main CTA button
![image](https://user-images.githubusercontent.com/90673012/191961173-7e39d6ea-b72f-4957-a628-04970b9fe5a8.png)

- Subcopy on the button can be removed
- Uses dropdown colors
- Adds sub-copy on the popup depending on where the players click (if player click on store, show you need to login to access store)
- can also use circular icons like in `E.`

### D. Login CTA w/ dropdown 
![image](https://user-images.githubusercontent.com/90673012/191962621-ac7f68b9-96f9-4ca4-901a-994c2fc99b02.png)

- changed format of Guest info. Added a separate login button
- Can also show assorted cta color version

### E. Login CTA -  Circular Icons
![image](https://user-images.githubusercontent.com/90673012/191963086-6b20bbe3-aa73-47eb-8841-e13e94ac9750.png)

- Can also show assorted cta color version
- **Circular icons**: this format is often used with one-form login.

_____________________________________

- Design is moddable can use Login button from A with dropdown in E
- I'll add the mobile versions during the implementation issue. I'll copy how the websites I check show their popup options

## Related links
- https://github.com/colonistio/design/issues/174
- https://github.com/colonistio/katan/issues/8318

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@demiculus

**Comment by demiculus** [comment]
## Todos

1. In the top right just have a button that says Login (do a few versions, green text with white background doesn't look good)
2. When clicking on the Login button have a popup in the middle of the page
3. Use this module https://i.imgur.com/jRFYrq2.png

## ABTest Ideas
- Change the top right button name to Login/Signup or just Signup and see difference in conversions
- Abtest login popup: https://user-images.githubusercontent.com/90673012/191960960-029e171f-99e5-4137-9f55-d3c1f7511a73.png & https://user-images.githubusercontent.com/90673012/191961173-7e39d6ea-b72f-4957-a628-04970b9fe5a8.png
