### ISSUE TITLE
Profile Revamp - Friends Tab Update

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#177]
## Summary
We will be adding a `Sent Requests` Tab and a Friend Limit Popup in the friends tab. This submission is accompanied by this implementation issue: https://github.com/colonistio/katan/issues/8366

### Player View
![image](https://user-images.githubusercontent.com/90673012/192454476-2e260f7d-5def-4829-a741-99b91c68b813.png)

### Moderator View
![image](https://user-images.githubusercontent.com/90673012/192454590-d0fe1cdd-722d-46f3-881f-bb1bc34edfd3.png)
- Same with the player view but without the CTAs

### No Friend Requests
![image](https://user-images.githubusercontent.com/90673012/192454695-e4a29ce3-e6ac-4018-81c0-1ea878c75954.png)

### Exceeded Friend Limit
![image](https://user-images.githubusercontent.com/90673012/192454817-d8d10ac1-edc5-419c-8574-e6e934fa33aa.png)
- Only show this if a non-member player exceeds 30 friends

### Adding a Player as a Friend
![image](https://user-images.githubusercontent.com/90673012/192455314-e0a50c00-75c3-4506-a4ff-2b45687ccd93.png)

### Cancelling a Friend Request
![image](https://user-images.githubusercontent.com/90673012/192455492-1b59cd7c-8004-4e8b-a02f-3855df1f308b.png)

### Accepting a Friend Request
![image](https://user-images.githubusercontent.com/90673012/192455575-6f2e97cd-1550-45ec-be5b-94a5e68d8884.png)

### Declining a Friend Request
![image](https://user-images.githubusercontent.com/90673012/192455658-e6e99211-e7a1-40ba-b5af-25233bb9cd18.png)

## Related links

- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/katan/issues/8325
- https://github.com/colonistio/katan/issues/8295

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@demiculus

**Comment by samgawaran** [comment]
for reference purposes. This shows the other scenarios too. I'll closed this once the implementation is done.

**Comment by demiculus** [comment]
1. The red is shiny af. Why that red? What other colors that we're using fit there more? 
  - Try not to introduce new colors
  - Find a good color that red is awful
 2. Orange button on popup. Make it green.

**Comment by samgawaran** [comment]
@demiculus 

> The red is shiny af. Why that red? What other colors that we're using fit there more?
![image](https://user-images.githubusercontent.com/90673012/193558649-f6a7ab23-312b-44e8-b260-5616360c265b.png)


We can either go with these two:

Blue: `$color-store-partition-tab-active` `#2b6187` with hover: `#2f6993`
Light Red: `$color-profile-friends-decline-button` `#ef3f2a` with hover `#c11104` 

The `Light Red` one is from the colors I'm using at the figma file before. We can either update our `$color-profile-dropdown-text-logout` to this color or remove this in our variables. Either way this red color is more mild compared to `#F00000`
