### ISSUE TITLE
Social Login Flow Submission #2 - (Refinement)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#178]
## Summary
Based on the comment given at the first iteration: https://github.com/colonistio/design/issues/175#issuecomment-1256951268 I adjusted and polished the designs that were promising, and looked how I could improve the naming of the CTA better.

research was done on the previous iteration as well. 

## CTA Adjustment
![image](https://user-images.githubusercontent.com/90673012/192540830-106bc45a-a3c0-41d0-9c97-3b01cc1e2393.png)

- Simplified the social login CTA layout. Remove the lines and made the button smaller

### Overlay
![image](https://user-images.githubusercontent.com/90673012/192541023-15f545a9-774d-424d-aef0-95f10e5653a8.png)
- Feel free to adjust the copy on this popup

### B1 - Login/Signup
![image](https://user-images.githubusercontent.com/90673012/192541489-d9009734-0951-41f1-83c6-fffeea94b03c.png)
- Taken directly from Demi's feedback, removed the spacing for the initial design `B`

### B2 - Login
![image](https://user-images.githubusercontent.com/90673012/192542582-7c5fc5ce-4e99-451a-b687-58e755111a07.png)
- Based on my research the term `Login` is more widely used compared to Sign in / Signup

### B3 - Login Now
![image](https://user-images.githubusercontent.com/90673012/192543527-9a5ba370-d97c-41e2-928c-510d96d04670.png)
- based on this [article ](https://blog.wishpond.com/post/103290853633/the-25-best-words-to-use-in-your-call-to-action#:~:text=Order%20Now,them%20to%20take%20the%20action.) adding the word `Now` adds urgency.

### C1 - Login Now
![image](https://user-images.githubusercontent.com/90673012/192545761-b5dc0cbb-1176-4930-953a-883be320ae7b.png)
- same with `B3` but uses a Green CTA. I made the CTA smaller so it's not that visually intrusive compared to the prev. iteration

### C2 - Login + Animation
![C2 - Social Login](https://user-images.githubusercontent.com/90673012/192545037-d82bf42a-5cfd-4ab8-8605-1efae0e573dd.gif)

- Animation is for sample only. I think using the `Shining` animation that was ABtested before could work better here.
- Adding an animation would attract players in that section of the website which could lead them to login

### F - White Outline
![image](https://user-images.githubusercontent.com/90673012/192546218-ee997964-5e8c-487c-b822-da6352fa218e.png)

- Added a new study that uses a white outline instead. Some websites like Linkedin and Reddit does this to highlight their particular button.
- Cons for this is that we're adding a new CTA style solely for the Login CTA
 
## Related links
- https://github.com/colonistio/design/issues/174
- https://github.com/colonistio/katan/issues/8318

## Related Submission

- https://github.com/colonistio/design/issues/175

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@demiculus

**Comment by samgawaran** [comment]
Let me know if I can go with one of the studies here so I can create an ABtest implementation issue

**Comment by demiculus** [comment]
https://github.com/colonistio/katan/issues/8402

**Comment by demiculus** [comment]
We'll do these stuff once we have facebook login. That might take a while..
