### ISSUE TITLE
Profile Revamp - History Tab (Screens + Mobile)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#179]
## Summary
Got feedback on the previous submission here: https://github.com/colonistio/design/issues/162#issuecomment-1256967061 to make the history tab simpler. Added mobile versions on each as well

> List out all `Types`

1. Ranked - All games via Ranked Matchmaking after placement games
2. Placement - first 10 games on a game mode via Ranked Matchmaking
3. Unranked - games on unranked matchmaking, games in lobby, created games
4. Bot - games via play vs bots, created games with every player besides the host is a bot

### Comparison
![image](https://user-images.githubusercontent.com/90673012/193004127-4d04898b-f650-4b08-9083-9f4018ad129c.png)

- Removed `Mode`
- Changed font size/style of `Position` to be the same as the other sections
- Changed `Players` to `Opponents` to reflect the section name in the current design at the website

## Screens
![image](https://user-images.githubusercontent.com/90673012/193005219-95facbf2-370d-4bf1-b2de-28c4d09a11ce.png)

- For Mobile Portrait, don't show `Opponents`

### Player clicks on the info icon
![image](https://user-images.githubusercontent.com/90673012/193005309-a813f0fc-a6f9-48e2-9d55-5390dab6c8a1.png)

- Show the expanded view
- for Mobile Portrait. Show the expanded view on a stack like these: https://prnt.sc/LUsZWPaz3hp1

### Player has just played a few games
![image](https://user-images.githubusercontent.com/90673012/193006543-c844b2da-7090-4683-8c5c-66c67f5302e3.png)

- Show these lengths for the game_cells if the player hasn't played much games yet.

### Player has no games played
![image](https://user-images.githubusercontent.com/90673012/193006854-237039ac-ad8e-4fb8-9da8-e681cee4fbeb.png)

## Related Submission

- https://github.com/colonistio/design/issues/162

## Related links

- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
> Changed Players to Opponents to reflect the section name in the current design at the website
If `Players` is better we can change it to that, we don't need to follow the current wording.

`2022` -> `22`

`MMR` -> `Rating`

----

1. I think we should add the mode, not sure why you requested its removal, @demiculus . When I enter another player's profile and check his stats, I take a look at the history to know what type of games they've played. It is really annoying to click on the info button of every single game to know if they played base, ranked, or an expansion. I really think we should add a Mode column.
2. How about merging Ranked and MMR columns? That should save space. Have a single column labeled Ranked, and show either MMR value if it was a ranked game, or - if it was unranked. And bots just say `Bots`.
3. Can we remove the info button and make the row click-to-expand instead?

**Comment by samgawaran** [comment]
> Can we remove the info button and make the row click-to-expand instead? 

Yes, I think I'd like these better since it reduces the icons seen in each cell.

> If Players is better we can change it to that

I think `Opponents` works well for us. the opponent tag makes it clear that the players being shown there is the players you played against.

---
I created a sample here: I didn't add `Modes` and merging ranked & rating columns yet. I'll wait for Demi's feedback

![image](https://user-images.githubusercontent.com/90673012/193216484-8bd0b0d9-781e-4c5c-8590-a38c10ce0dbd.png)

**Comment by demiculus** [comment]
1. Remove `Type` add `Mode` just like before
  1a. List out all the possible Modes  
2. 2022 -> 22 -> In only 1 screenshot shows as `2022` the rest of the games dont have it: https://github.com/colonistio/design/issues/135 find other games to see if they use 2022 or 22 and go with the most common pattern
3. MMR -> Rating 👍
4. Remove info icon -> It looks like other games use an expand icon, create one and use that https://github.com/colonistio/design/issues/135 
5. Opponents / Players -> Here are some research, check out other games and go with the most common pattern https://github.com/colonistio/design/issues/135

**Comment by JuanRoman77** [comment]
@samgawaran Fyi 
![Screenshot_20221001-194657_Opera.jpg](https://user-images.githubusercontent.com/73320460/193431007-73e36bd3-bda0-4ebe-a925-d0182348e59f.jpg)

**Comment by demiculus** [comment]
Show the icons of all of these as well
