### ISSUE TITLE
In-Game - Setting Pages Redesign

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#180]
## Summary
The design was pre-approved by @demiculus during our 1v1. I cleaned up some of the elements used and change some assets to reflect the UI on our other pages.

The initial design was done by Huan here: https://www.figma.com/file/bgi8QryS3z1XUCNKcFotlt/Untitled?node-id=0%3A1

## Comparison
![image](https://user-images.githubusercontent.com/90673012/193067908-50d15350-8fe2-4563-a591-8ff13ab4692a.png)

- Changed the icon for controls from a Tetris icon to an adjuster_icon
- Made unselected tabs icons use less opacity
- Remove the underline to make it simpler
- Added a button for Quit game. Previous layout don't have a button for it.
- Adjusted font style/size to use our font library

### In-Game Screen / Controls
![image](https://user-images.githubusercontent.com/90673012/193069697-5afc6db2-b7af-4ded-a462-cb8f92bf2daf.png)

- Can add/remove other shortcuts in control

### Audio / Display
![image](https://user-images.githubusercontent.com/90673012/193069755-a1bfb13d-941d-4b2c-b4c4-d405f2290e88.png)

- Music setting will be useful once H5KY finalized the in-game music

### Game Info / Quit Game
![image](https://user-images.githubusercontent.com/90673012/193070094-a7d500fb-897e-4415-b879-cbbe370d19f7.png)

### Rules
![image](https://user-images.githubusercontent.com/90673012/193071668-b5879762-326b-4a77-94eb-1277278274c7.png)

- Clicking the rulebook icon redirect to this screen. Same logic with the current one. 

## Related links

- https://github.com/colonistio/design/issues/172

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@demiculus

**Comment by samgawaran** [comment]
creating the implementation issue shortly after

**Comment by demiculus** [comment]
Can you go back to the initial design? Open a new submission.
