### ISSUE TITLE
Ranked Progress Bar - (Ranked End Game + Ranked Tab) Research & Design

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#181]
## Summary
During our past 1v1, Demi mentioned that the current progress bar in-game isn't what most games are doing and the initial research shows it too.

The following designs are based on the research from AAA games and most popular games right now at Steam

## Current
![image](https://user-images.githubusercontent.com/90673012/193511737-eff26fa8-cf60-4e03-96a6-4ccc2fb0dfba.png)

- Shows a lot of visual load in the progress bar. 3 Icons with names below them.

### Horizontal Progress Bar
![Study A-min](https://user-images.githubusercontent.com/90673012/193512524-8a62d505-aa1d-4960-b50d-76ee8f51031f.png)

- Most games use this kind of presentation. AAA, Console, and even Mobile
- Besides `Apex Legends` I didn't see any other games that use our current format. They just show the division icon and `how many more EXP/Games to get promoted
- Most games use the progress bar for `Leveling Up` instead of Ranked Divisions
- Console games use a progress bar to show the time limit for a scenario/round

### Circular Progression
![image](https://user-images.githubusercontent.com/90673012/193512591-1673c4bb-9f36-44db-89c1-9121f3ca4ce1.png)

- Games that use this kind of progression are more competitive AAA games. (Overwatch, LOL, HOTS) 
- Circular progression is used primarily to indicate divisions

### Suggestions
- Remove different divisions that you're not in. Show the next progression as text instead
- No games show your previous rank. Don't show them as well

### Study 1 & 2
![image](https://user-images.githubusercontent.com/90673012/193521353-53c4967f-bfa6-4510-a9a0-83dbf33fe42e.png)

- `Study 1` Closest design we got from the current version. removed other divisions and use how other games show progress (XXX more to level up)
- `Study 2` follows Valorant, Tetrio format that shows the player Global rank changes after they won in a ranked game
- `Ranked Tab` both studies can use this format. simplified the progress bar the players voted in the poll. (https://discord.com/channels/605233308577562643/716512630705225798/1021579965147381801)

### Study 3
![image](https://user-images.githubusercontent.com/90673012/193522584-5e9a76c2-1890-488e-b21a-d682c791e834.png)

- Circular bars are more catered to ranked game progress compared to horizontal
- Added division icon inside the circle + Rating and changes

### Study 4
![image](https://user-images.githubusercontent.com/90673012/193522679-ff426353-429f-42cb-a2fa-4df6245bcc62.png)

- Based on the designs from `Overwatch` which shows how much exp is needed to get promoted

## Related links

- https://github.com/colonistio/design/issues/151

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@demiculus

**Comment by demiculus** [comment]
Definitely not circular since people can progress backwards as well. Somewhere along the lines of study 1 & 2 will be better but then again, its not gonna be improving our metrics from the current end game animation we have so we can call this task a small potential improvement and postpone it 1-2 years.

**Comment by samgawaran** [comment]
Alright. I'd go with `Study 1` for the implementation issue.

**Comment by demiculus** [comment]
> Alright. I'd go with `Study 1` for the implementation issue.

We won't do an implementation issue. Better to use dev resources elsewhere that is more likely to give bigger impact
