### ISSUE TITLE
Store - Limited Use Items (Research)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#182]
## Summary
@alexcoleman7 requested research on how other games do micro-transactions in the thread here: https://github.com/colonistio/design/issues/146 

this research checks what possible offering of `limited use` transactions could be effective for us.

You can also check some previous studies here: https://github.com/colonistio/design/issues/167

### Browser & Mobile Games
![image](https://user-images.githubusercontent.com/90673012/193754966-6bddd0a6-35e8-4674-920b-af2618515acc.png)

**Chess.com** - 7-day `Free Trial` promo for their memberships. You need to input your CC/Debit beforehand to avail
**Venge.io** - uses `Limited Time Offer` which features ceratin items that are discounted on a limited time
**Krunker.io** - Sells `Gift Packs` which offers random items based on the tier. also get free coins to purchase the packs via `daily login`
**Agar.io** - uses `$/$$$(Best Value)` format. same with our membership toggles, buying annual saves more money
**LittleBigSnake** - `Gamepass` model. Similar to their subscription but no monthly/annual renewals
**Zombs Royale** - uses `Limited Time Offer` which features certain items that may contain premium cosmetics

### AAA Games
![image](https://user-images.githubusercontent.com/90673012/193753072-087133fb-dd1b-4a6b-a771-4c179385ac06.png)
**Mobile Legends** -  `Play to FREE Items` players need to finish daily challenges to get limited-use items
**Call of Duty Mobile** - `Play to get FREE items` same with Mobile Legends
**League of Legends** - `Play to get FREE items` player earns in-game currency they can use to `Raffle` skins
**CS:GO** - `Play to get FREE items` same with CODM and Mobile Legends
**Dota 2** - `Gamepass` model. Earn unique titles and items when you buy a pay-per-use battlepass

### Results
**Top 3**
`Play to get FREE Items` - 4 out of 5 AAA games. 
- Create Daily Challenges for players to get a 24hr use of Maps and Expansions. Will affect Items Tab in Profile, we will also need to create a daily challenge feature (will boost revenue from ads instead of store sales since players will stay more at the website)

`Game Pass` - LittleBIgSnake, Agar.io (for Booster Packs) and Dota 2 
- Similar to a subscription but with no renewals. We can offer timed access to Expansions and Maps for 1 day, 3 days, 7 days. Will affect store tab, add a new section for Game Pass. this is also Juan's and Leahwalkiewicz suggestion in the thread.

`Limited Time Offer` - Venge.io and Zombs Royale
- Offer discounts for certain items from a certain period of time to create urgency. This can be added along with `Game Pass` (ex. Get Cities & Knights for X days 30% Off for a limited time only) We can create banners for this to raise visibility.

## Related links
- https://github.com/colonistio/design/issues/146

## Related Submission
- https://github.com/colonistio/design/issues/167

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

@demiculus @alexcoleman7

**Comment by samgawaran** [comment]
@alexcoleman7 
Based on the research and amount of work it would take both for devs and designers. I suggest going to a `Game Pass` option instead. and have `Limited time offers` to boost sales.

`Play to get FREE Items` will be more useful if we already have a daily challenge system in place so it may take longer to implement. 

Let me know what you think so I can go ahead with the designs

**Comment by demiculus** [comment]
A comment from founder of venge.io

> Nice research, as far as I can see, looking at someone else's shop does not work well, the best method is to put yourself in the actor's place and think what would there need to be that compels me to buy
We put a lot of effort into doing the things we see in other shops.
Battle pass, free item or something is a lie
You need 100 more mechanics to make those mechanics work
If it was with 5 screenshots, everyone would be rich.

**Comment by goktugyil** [comment]
Limited time offers is not a product decision, it is a business decision.

As soon as you have limited time offers, it means that people will not buy stuff and wait for a limited time offer to appear. You will have short term increased revenue, long time decreased revenue. 

Most of these games are short term optimized, that's why they have limited time offers. 

I am against this, unless we can back it up with data and individualize each limited time offer to the specific person, rather than season and site weide
