### ISSUE TITLE
Ranked Cities & Knights Announcement - Ads, Banners & Social Media Post

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#183]
## Summary
We will be launching Ranked C&K soon. https://discord.com/channels/605233308577562643/790772223358402571/1026598892051107871

This submission shows some proposals on the design collaterals we could for ads and marketing

### Store Ads / Adblock 1
![image](https://user-images.githubusercontent.com/90673012/194311993-64de0c0c-6c95-42a5-a908-03423acb2e0c.png)

### Store Ads / Adblock 2
![image](https://user-images.githubusercontent.com/90673012/194312027-e9bc68e0-80a2-45f3-b41e-4075b5aa8465.png)

### Store Ads / Adblock 3
![image](https://user-images.githubusercontent.com/90673012/194312091-22aa3b59-4dd6-4d32-9c9a-56c00f18dfee.png)

### Social Media Post
![image](https://user-images.githubusercontent.com/90673012/194312166-fb9a5a10-cefc-4d2c-b1c6-6c145ed6f142.png)

### Banner 
![image](https://user-images.githubusercontent.com/90673012/194312248-80e92d89-cf85-4a11-9f53-bac96f1412b1.png)

____________________________________

- Copy is still subject to change. especially for the `Store Ads` @JuanRoman77 let me know what I should edit

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@JuanRoman77 @demiculus

**Comment by samgawaran** [comment]
I'll wait for the feedback before I send the final gdrive link

**Comment by demiculus** [comment]
Remove this: https://i.imgur.com/tMrFDyv.png

Try to keep the assets upto date with the website. To do that you need to follow implementation PRs and ask questions if something changes.

----

use this: https://i.imgur.com/siaZSJI.png

Make the cards symmetric

-----

use the check marks https://i.imgur.com/YbzgyVS.png

-----

use study A with gold tiles & new cards https://user-images.githubusercontent.com/90673012/194312248-80e92d89-cf85-4a11-9f53-bac96f1412b1.png

once done send the files to Juan

**Comment by JuanRoman77** [comment]
Be a Member -> Become a Member
