### ISSUE TITLE
Ranked Cities & Knights Announcement - Ads, Banners & Social Media Post Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#184]
## Summary
Adjusted the designs based on comments on the thread here: https://github.com/colonistio/design/issues/183

### Social Media & Banner Ad
![image](https://user-images.githubusercontent.com/90673012/194511471-15e57411-fcf7-4bc9-95f8-b5ad916a34e0.png)

- @JuanRoman77 commented on not using the `Gold` tile so I used a `Wheat` tile instead
- Made the cards symmetrical. left, center, right on the same height
- I added 3 additional cards in the design as @demiculus wanted this: https://imgur.com/YbzgyVS it would be redundant to show the same cards on the side again
- followed the other feedback of Demi

### Store Ads & Adblock
![image](https://user-images.githubusercontent.com/90673012/194512053-a3e3cdc9-7b33-41d3-a7fd-f60d83e9ed34.png)

- made the cards symmetrical

## Related Links
- Link for assets:
https://drive.google.com/drive/u/0/folders/1vLNirpxY6u-ZORbMX3X65f5LHzCFzHPG

## Related Submission

- https://github.com/colonistio/design/issues/183

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@JuanRoman77 @demiculus

**Comment by samgawaran** [comment]
I didn't compress both banner and social media post in the drivelink. I double-checked and it pixelates when its compressed.

**Comment by demiculus** [comment]
My bad, do this for all https://i.imgur.com/eo1iKNS.jpg

1. Remove the 3 extra cards (there are too many)
2. Move the coin,paper,cloth cards
3. For the tile, i donno you decide w juan

You can move forward with juan for the rest of this
