### ISSUE TITLE
In-Game - Setting Pages Redesign # Iteration 2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#185]
## Summary
Redone the flow from the previous iteration here: https://github.com/colonistio/design/issues/180 using the original flow that Huan did. 

I still maintained the consistency of the fonts, colors, and other stuff in the previous iteration. Just did the original flow

## Flow
![image](https://user-images.githubusercontent.com/90673012/194542510-32e5a574-c21a-4b61-a5d4-a47bc0cac8fa.png)

- `Disable Karma` and `Pause Game` will follow our current flow for those features

### Controls / Audio
![image](https://user-images.githubusercontent.com/90673012/194543436-fcbb6b94-1e09-4acd-92ad-9826b22cb860.png)

### Display / Game Info
![image](https://user-images.githubusercontent.com/90673012/194543674-764b0906-a786-43d5-90ed-a3b9d38a4966.png)

## Related Submission

- https://github.com/colonistio/design/issues/180

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@demiculus

**Comment by samgawaran** [comment]
Let me know if all is good so I can update the implementation issue

**Comment by demiculus** [comment]
1. Use our dropdown module instead of the blue one huan did. https://i.imgur.com/1fAovjA.png https://i.imgur.com/2uKk4Ia.png
2. Remove these: https://i.imgur.com/2uKk4Ia.png
3. In implementation make sure to write that the number on the top right is paused game timer only in bot games
4. Consider all other possibilities and create designs for the ones which can be a problem.

**Comment by samgawaran** [comment]
due to minor feedback, I just updated the screens here and will proceed to the implementation issue.
