### ISSUE TITLE
Goals for Players - Research and Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#189]
## Summary

based on research, setting up a goal increases user engagement and gamification of the product. 

This submission covers the research and initial studies for the feature. Also added Mobile comparisons as well so its faster to do implementation issues.

## Research

- Progress Bars increases engagement, players has something to look forward to.
https://www.hoopla.net/blog/the-science-of-progress-bars-why-are-they-great-motivators/

- By incorporating game-like aspects like the progress bar, user engagement improves drastically. Think about when you play a video game, and it shows you on a map where you are in the process of meeting the next boss.
https://neilpatel.com/blog/the-progress-bar/

### Samples from websites/pegs
![image](https://user-images.githubusercontent.com/90673012/194763817-36594495-08b3-460c-b22a-d8756fc86546.png)

### Desktop Games
![Desktop Games](https://user-images.githubusercontent.com/90673012/194763757-8eff62df-c257-4eb2-a4c5-a3e332ca1d7b.png)

### Mobile/Tablet Games
![Tablet Games](https://user-images.githubusercontent.com/90673012/194763758-979a0b6d-2164-40c5-9d5c-e58abc71f559.png)

### Findings
- all of the games either use a `progress bar` or a `counter` or a blend of both
- The title of the section depends on the game. `Quests` are used often for Mobile games though I think "Challenges" is better for us since ours won't replenish after they finish the challenge
- Mobile games use popups for their goal toggles while Desktop and AAA games show the goal toggles in a seperate screen

## Studies

- After completing the challenge the section will be removed from the homepage on all studies

### Study 1 (Progress Bar)
![image](https://user-images.githubusercontent.com/90673012/194859164-4e97bb34-afd9-45a4-aed8-e6a6febc1b40.png)

- Uses our progress bar layout. 
- Followed how some games show a completed goal. Either a checkmark or the word claimed but I used `challenge complete!` to make it more fun

### Study 2 (Counters)
![image](https://user-images.githubusercontent.com/90673012/194860794-5da54c9b-3de3-4948-83a6-61d2b62caea9.png)

- removed the word challenges. this is for flexibility if we would want to show more challenges in the homepage screen
- I use Counters here. Could also be more flexible if the players are resizing their browser

### Study 3 (Circle Indicators)
![image](https://user-images.githubusercontent.com/90673012/194861371-7d58e539-24c4-475e-acaf-ecf2e0723ab9.png)

- Based the design of the counteres on how other platforms show a progress bar (non-games)
- I figured this is worth the look since its more straightforward that you're reaching for that particular reward

### Study 4 (Counters + Progress Bar)
![image](https://user-images.githubusercontent.com/90673012/194863303-1b6cc683-4ce1-42c6-bdab-657b9d0a5c62.png)

- Most mobile games are using this layout, and some Desktop games as well
- I recommend this design, cause based on the stuff I gathered, this is flexible while also keeping it straightforward

## Checklist
- [x] Consider short screen devices and see where & how you can put it 
_- For mobile and tablet, we can put it above the Play Ranked section_
- [x] What happens after they reach X amount of games to get the goal?
_- After completing the challenge the section will be removed from the homepage on all studies_
- [x] How would it look for Guest Players?
_- Some studies will show that they need to sign in to see the challenge, they could also click that section and be redirected to the login flow_
- [x] For `Finish 5 Games to Unlock Ranked Games` how do the cards on the Homepage will look?
_- Add a copy that they need to finish the challenge first to play ranked_

## Related links

- https://github.com/colonistio/design/issues/186

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus

**Comment by samgawaran** [comment]
Change how I present the submission. Let me know if I should keep doing this, suggesting this so we can reduce the number of edge cases we might miss out

**Comment by demiculus** [comment]
I like the stuff you write under the studies but categorize them from now on as Pros & Cons cause you're currently missing some cons. Its better to have that.

**Comment by demiculus** [comment]
Go with study 4

- [ ] Even if it is empty it should have 3-5% green bar at the start https://i.imgur.com/9otHBvw.png. Make sure to let the dev know what % 

Do 2 screens in this order
- [ ] A new player with less than 5 games: 0 - 5 finish to unlock ranked games
- [ ] Finish 10 placement games to unlock black
  - [ ] Once this is completed there should be a claim button where the UI should clearly show it is for claiming the black color
  - [ ] Let me know any case I've missed
  - [ ] Please do not change other parts like this https://i.imgur.com/xLhV3Pl.png and confuse the developers 

Create an implementation issue with these and let me know.
