### ISSUE TITLE
Translation (Change Language) Button - Research and Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#190]
## Summary
We're going to have translations. We need a way for people to change languages on-site. 

its a relatively suggested feature in here as well. https://colonist.featureupvote.com/suggestions/73686/add-more-languages

### Desktop
![image](https://user-images.githubusercontent.com/90673012/194910960-04f75bfa-1029-4bac-9c38-19d832c0d48d.png)

### Mobile
![image](https://user-images.githubusercontent.com/90673012/194911287-ee5eba9c-251e-4cd6-9f07-8e74c24cddf7.png)

### Findings

- None of the sites/games I checked uses `Flags` 
- `Stripe` and `Apex Legends/Playstation` uses the same language directory. not sure if we checked this
- `Steam Games` and `Twitter` also uses the same language directory. they show something like: https://prnt.sc/2YwyCd8wopKk (Native Language - English Name)
- Mobile versions can be shown as popup instead, like in Steam

## Designs
- Mobile Design will follow the selected studies. 
- Followed Steam and Twitter language style. Feel free to adjust this

### Dark Blue Bar
![image](https://user-images.githubusercontent.com/90673012/194908312-58bcdd31-553c-4042-bb7e-135edcd2002a.png)

- Showing it on a container makes it look clickable

### Dropdown
![image](https://user-images.githubusercontent.com/90673012/194908344-5559b050-9dec-4175-882a-0ba0ec33fed3.png)

- Recommending this design. Easy to adapt it to Mobile
- No new section at the footer since the language changer is inside the dropdown
- Can add `change language` as a reason to sign up

### Patchnotes on Center
![image](https://user-images.githubusercontent.com/90673012/194908369-21a303fd-8c32-42e2-93b8-f8ceef6f1d03.png)

- Moved patchnotes to center to create space for language
- followed Stripe's use of icons. either click the language or icon to open the dropdown

### Patchnotes on Left
![image](https://user-images.githubusercontent.com/90673012/194908447-82e947bb-21dc-4568-acba-a07389c8b63b.png)

- Retained placement of patchnotes. 
- Same with patchnotes of center on everything

### Checklist
- [ ] how can the flags be scalable?
_We won't use flags. no other websites do this and it reduces visual overload if its not there_
- [x] look how big sites do their languages, check games too, where do they put it?
_Most sites add them inside the `Settings` but at the moment, we don't show this in our profile so we can either put it inside the dropdown. Stripe shows it at the bottom._ 
- [ ] how would it look like for countries that have long names, do most sites use abbreviations?
_- I didn't see a lot of websites use abbreviations. Based on the research, it seems that adding abbreviations and flags on languages are not that widely used anymore by top sites. moreover. The longest word I see is `Bahasa Indonesia` so we can just set the margins for that language if its supported_
- [ ] after being translated to another language not using the roman alphabet (ex. Japan, Korea) will they show the word `English` in their language?
_- No. Twitter and Steam already add something like (French - Francaise) so there's always English characters on the language dropdown_
- [ ] How can players change their language while in-game?
_- We can add an option inside the settings module where they can change their language_
## Related links

- https://github.com/colonistio/design/issues/187

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewer
@demiculus @JuanRoman77

**Comment by samgawaran** [comment]
@demiculus @JuanRoman77 

following up on this^ let me know what design we could use/iterate so I can move forward with this

**Comment by demiculus** [comment]
https://www.loom.com/share/ac90aab327c74c73a2b070450c1013f8
