### ISSUE TITLE
Blog - Player Interview Series (Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#191]
## Summary
We will be launching player interviews at https://blog.colonist.io/ we need a design that is catchy while maintaining our brand.

- Design should also work for social media if we want to advertise it

### Study 1
![image](https://user-images.githubusercontent.com/90673012/195035168-b3d3437a-a1c8-47d5-b6a5-990952641916.png)

- slight edits on current placeholder in this article https://blog.colonist.io/interview-series-1-dylighted/
- interviewee logo smaller
- Mic icon does not use a harsh blue color now

### Study 2
![image](https://user-images.githubusercontent.com/90673012/195035250-4e037ec3-257b-4d09-93ce-afc34a0d9c4a.png)

- Alternate study for interview series text, uses our icons

### Study 3
![image](https://user-images.githubusercontent.com/90673012/195036650-86ccffe4-6400-4ed8-b012-08b93ff1c14a.png)

- Added icons on the islands, slight variation from study 1

## Related links

Gdrive Link:
- https://drive.google.com/drive/u/0/folders/1aOm1WZxRC02N6w3VFwzUCdBBXhyJnXJu

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
I like the third one

**Comment by demiculus** [comment]
I leave it to simon & juan

**Comment by SimonH321** [comment]
> I like the third one; the mic is a must. I'd reduce the size of the resource tiles and avatars tho, so they don't take attention from the middle section.
> Also make sure to leave this block free at the sides, because some guests might have longer usernames https://i.imgur.com/lgmMCns.jpg
Agreed. I spoke with Sam, he will handle when he wakes up.

**Comment by samgawaran** [comment]
closing these issue, final design is detailed here: https://github.com/colonistio/design/issues/193
