### ISSUE TITLE
Blog - Player Interview Series (Final Design)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#193]
## Summary
Based on comments from the previous iteration: https://github.com/colonistio/design/issues/191 Juan and Simon both agreed to pick version 3 for the final design.

This submission list out possible cases for the said design

### Comparison
![image](https://user-images.githubusercontent.com/90673012/195313963-b2bdfb33-98b3-4616-b2d9-3df4da0d654f.png)

- Followed Juan's suggestions from these thread: https://github.com/colonistio/design/issues/191#issuecomment-1274806149

### Other samples
![image](https://user-images.githubusercontent.com/90673012/195314417-8b38403e-f129-4cf3-b20b-fc24ca0108b3.png)

- did some other samples for the design. I did a sample if Treeck is the one being interviewed and another one which shows a very long username like WWWWWWWWWWWWWWW

## Related Submissions
- https://github.com/colonistio/design/issues/191

## Resource
- https://drive.google.com/drive/u/0/folders/1aOm1WZxRC02N6w3VFwzUCdBBXhyJnXJu

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by samgawaran** [comment]
link for the banner is in here:
https://drive.google.com/drive/u/0/folders/1aOm1WZxRC02N6w3VFwzUCdBBXhyJnXJu

**Comment by demiculus** [comment]
@SimonH321 you got notif?

**Comment by SimonH321** [comment]
Yes, it’s been added
