### ISSUE TITLE
Profile - Revised Ranked Tab

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#194]
## Summary
During last Friday's team meeting @JeffdEon asked if the profile ranked tab is ready. There are already some designs made but it doesn't cover all possible scenarios that the ranked tab will show. 

This design submission tries to cover all possible scenes we may come up, as well as how it would look on Mobile.

## Screens
![image](https://user-images.githubusercontent.com/90673012/196038150-77c4f5d8-7d0d-4dce-b42b-cd706fafc496.png)

### Clicking on a played mode
![image](https://user-images.githubusercontent.com/90673012/196038185-781ba9a1-ade0-4ee0-960e-613e383c6652.png)

- players will be directed to the leaderboards page. I suggest opening the page as a new window

### Clicking on an unplayed game mode
![image](https://user-images.githubusercontent.com/90673012/196038231-bf459097-8873-403d-869c-3685fcd55a73.png)

- players will be directed to the homepage, ideally it should show the ads first (if non-member) but if not, find game on that game mode after they click `Play Now!`

### Clicking on C&K while being a non-member
![image](https://user-images.githubusercontent.com/90673012/196038770-42ca3b19-952a-4313-8fda-032ca4013de1.png)

- Show the popup we're showing if player is not a member
- if player is a member, show the flow from clicking an unplayed game mode
- I move it in the homepage, I'm not sure if it would be easier to do the popup inside the ranked tab 

### Clicking on the season selector
![image](https://user-images.githubusercontent.com/90673012/196038995-c4abc72a-14f0-44a3-a028-c454c7b193e2.png)

- If the player is looking at an older season, the ranked cards cannot be clicked. 
- show at most 5 seasons per dropdown so it would be consistent with the mobile version

_________
### Mobile Landscape
![image](https://user-images.githubusercontent.com/90673012/196039019-04e24878-7d8f-4d38-a282-12442dab3619.png)

### Mobile Portrait
![image](https://user-images.githubusercontent.com/90673012/196039026-5f3c6a23-3cad-4024-b3fc-5fa36939a944.png)

## Related Submissions
- https://github.com/colonistio/design/issues/139
- https://github.com/colonistio/design/issues/151

## Submission Checklist
- [x] what does this submission cover?
- _this submission covers the whole section of the ranked tab. from the dropdown to the ranked cards_
- [x] How would it look if a player didn't play any ranked games yet
- [x] Will there be a progress bar? how would we show it?
- _https://discord.com/channels/605233308577562643/716512630705225798/1021579965147381801 based on the result, players like to show the poll. The design above is a simplified version which me and Juan did, its also consistent with our end-game ranked change_
- [x] How can other players see their past season rankings
- _dropdown selector_
- [x] How would it look on Mobile
- [x] How would it look for placement games, no games played, and game modes that are coming soon
- _shown in scenarios_
- [x] Will the ranked tab be linked on any other pages/popups? 
- _shown in scenarios, game mode popup, become a member popup_
- [ ] any other scenarios you could think of? 
_________

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JeffdEon

**Comment by JeffdEon** [comment]
This all looks good to me! What is our process? Can I assign this for implementation? Does it need another review?

**Comment by demiculus** [comment]
@samgawaran add a version where the player has played some placement games but doesn't have an elo yet

Revisit these stuff to see if you missed any other scenario.

@samgawaran create implementation issue, then message jeff on discord to edit it

**Comment by samgawaran** [comment]
Created the implementation issue for this here: https://github.com/colonistio/katan/issues/8625
