### ISSUE TITLE
Premium Rooms

### ISSUE THREAD

**Issue by alexcoleman7** [colonistio/design#195]
## Description
We are looking to test out how players will welcome renting our premium assets (maps and expansions).
Renting will also provide a bridge between those who are willing to spend but are not sure of owning something they don't know if they like.
We want to test this slowly by keeping it as simple and restricted as possible and expand on it if its successful, so we are ging to add a 'Premium Room' when creating a game, so players can choose any map or expansion if they choose to purchase a premium room for one game.

I have come up with a couple of ways to show this on the room page as below:
The upgrade button will look similar to the big 'Play' button in the lobby.
I think the three containers should have some sort of highlight when the player makes it a premium room, I've shown this as a new background colour, in this case the colour of one of our subscriptions (although I don't like this one too much). We could also have a special border around instead. @samgawaran can you make a few versions of how to highlight the room when it is a Premium Room?
<img width="985" alt="image" src="https://user-images.githubusercontent.com/60288677/196060805-3721a0a5-ebe1-4928-b91a-bc6099b6b6cb.png">

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/60288677/196058942-37595b09-3236-4403-95a3-b6b43a701154.png">

Option 2 is to have the button next to the others at the bottom although I don't think it works as well and it's not highlighted as much as the first one.
<img width="993" alt="image" src="https://user-images.githubusercontent.com/60288677/196059275-c77ca90c-f858-44b4-8409-86d795dcb9ff.png">

When clicking the premium button we have to explain to players what they get and the price of course. We could just do that in a popup or we could temporarily make the chat container into a 'store card' and add any details and some images. I think this is quite seamless compared to a popup but its obviously limited to the size of the box. It also will probably be less effective in smaller screens where we should probably show a pop up instead. @samgawaran can you help make some options for this too?
<img width="984" alt="image" src="https://user-images.githubusercontent.com/60288677/196060675-fc2922cf-7084-496f-98b4-ba0f75b78ce3.png">

## Reviewer
@demiculus @goktugyil

**Comment by alexcoleman7** [comment]
If the premium rooms are successfull I would like to improve the dropdown menus to something like this: https://www.w3schools.com/howto/howto_custom_select.asp
We can use this to edit the menus to show better which items are owned and which are premium. But I don't want to do this if we aren't implementing this as it's a big-ish piece of code to add in.

**Comment by demiculus** [comment]
@samgawaran 

1. We don't want to change the whole thing to purple, find a simpler way of showing the room is premium
2. The button to change can be next to start button, with popup showing details. If the feature succeeds we'll iterate more
3. @alexcoleman7 you should come up with the success scenario. What would mark this as a successful feature or failed?
4. @alexcoleman7 you should come up with all the possible cases and outline them (guests who have it enabled, hosts who have it enabled, hosts who have it enabled then leave it to guests who don't have it, logged in, logged out, prompts, words everything)

**Comment by samgawaran** [comment]
@alexcoleman7 @demiculus some clarifications

- will this feature be purchasable at the store?
- does `premium room` means they can use all expansions and map in a game? are we adding new features too?
- are different colors also available to all guests if they are in a premium room?
- How much coins is needed to access this feature
- Does it tie on certain membership perk? like Plus Members get 3 free premium rooms per month... etc.

________

I'm assuming besides the room, we should also design how it would look in the Lobby and Mobile

**Comment by demiculus** [comment]
> * will this feature be purchasable at the store?

Not for abtest

> * does `premium room` means they can use all expansions and map in a game? are we adding new features too?

they can use all expansion map and player count, we're not adding new features

> * are different colors also available to all guests if they are in a premium room?

Yes

> * How much coins is needed to access this feature

I'll let alex calculate that, go with 100 for designs

> * Does it tie on certain membership perk? like Plus Members get 3 free premium rooms per month... etc.

No, its separate

> I'm assuming besides the room, we should also design how it would look in the Lobby and Mobile

No need, don't complicate the abtest
