### ISSUE TITLE
Premium Rooms - Design Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#196]
## Summary
- We will try out a `Premium Room` idea where players can upgrade their room to access all maps and expansion for one game. 
- Price is not finalized but for a placeholder, we decided to use 100 coins

### From Design Issue
![image](https://user-images.githubusercontent.com/90673012/196370428-874802b3-589a-434b-b756-12eabfb3b510.png)

- we can't leave out room chat
- Room design can be improved without making big changes

## Other Games
![image](https://user-images.githubusercontent.com/90673012/196367329-c78cb113-c884-43ef-9b79-37bd67a5181c.png)
- Some ideas for future room layouts and such. We can do future iterations after we do the premium room MVP

### Popup 
![image](https://user-images.githubusercontent.com/90673012/196369638-a151f5b7-8190-4767-955b-8144b0bf0480.png)

- We can show a popup to show more of the details of the premium room

### Study 1
![image](https://user-images.githubusercontent.com/90673012/196366373-d801fe05-936e-4861-a7c0-ed86ffda7512.png)
- Based on initial studies but uses the green color of our sub-cta's and replace the color of the buttons to our main-cta
- I use green to not introduce new colors for this ABTest
- added white outlines for each container. can also be removed
- Placement of a new section for premium rooms. Same size with small lobby-ads (300x300px) took some space out of the room chat.

### Study 2
![image](https://user-images.githubusercontent.com/90673012/196366393-88f63ce8-19c1-4df5-a838-f008b3efe82d.png)
- same with initial study colors, used a different shade of purple that uses better contrast

### Study 3
![image](https://user-images.githubusercontent.com/90673012/196366410-9ca92e7d-f69e-42eb-afcd-8f2ab58ec9c4.png)
- Added a skin for the container after they purchase premium. 
- Uses a darker shade of blue. same with our popup colors

### Study 4
![Study 4](https://user-images.githubusercontent.com/90673012/196365563-5a4051ff-a099-4481-91d1-e0a82358cd46.gif)
- Created a GIF for a star. Could be modified to show other icons
- Shows price already

## Related Links

- https://github.com/colonistio/design/issues/195

## Submission Checklist

- [x] how would it look on Mobile?
_- https://prnt.sc/Q0ivmvxiAu8d, can be further refined after we go with a specific study_ 
- [x] have you tried other colors for the rooms?
_- yes, but I decided to use colors that would fit well with the `not ready` tag. There's only a few colors that could work with that color scheme so it narrowed down my options_
- [x] how can we show more details for the premium room?
_- Showing a popup or creating social media ads and banners for it. Add a new room style in the public lobby, can be refined after we see the results of the test_
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @alexcoleman7

**Comment by samgawaran** [comment]
@demiculus 
![image](https://user-images.githubusercontent.com/90673012/196584157-31bf1a36-0282-499a-b696-6e14d255f3a2.png)

For the room visuals, is this what you mean?

> Bought premium button & locks unlocked
I suggest removing the locks instead and show in the room chat the features of the upgraded room. I also suggest both the host and other players see the `upgrade room` for more conversion chances

Questions for this:
- if we would lock the expansions and maps, are the players subjected to the ABtest those that haven't purchased anything at the store?

**Comment by JuanRoman77** [comment]
We already use Premium for the tier 2 Membership. I don't think we should use the same name for this thing.

**Comment by demiculus** [comment]
> For the room visuals, is this what you mean?

The locks, yes. Shouldn't you put it at the left side of the word? What does other games do?

Also its not fully locked, they can access the ones that they bought. Don't gray it out. They can also change the discard limit and VP. 

> if we would lock the expansions and maps, are the players subjected to the ABtest those that haven't purchased anything at the store?

Its not full lock. Obv. people who purchased or subscribed have access.

> We already use Premium for the tier 2 Membership. I don't think we should use the same name for this thing.

`Premium room` works if no better name

> Second image changes colors and such

- Just unlock the locks in second image. 
- The text posted at the chat is alright @alexcoleman7 can optimize it
- The `Upgrade` button should still be there but turned to only `text`? or something else? thats like not clickable but gives a satisfactory. Like the player has achieved it. 

> Upgrade Room

Unlock Room? Upgrade Premium?
