### ISSUE TITLE
Cleanup CSS Color Variable

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#197]
## Description
Current [CSS variables](https://github.com/colonistio/katan/blob/development/code/client/css/settings/_variables.scss) are a mess
clean up the code, @samgawaran will provide what could be removed or merged.

### Current CSS Variables
![image](https://user-images.githubusercontent.com/90673012/196432724-fe59b870-1081-495b-b713-6f7a1b311aea.png)

## Resources

- https://github.com/colonistio/katan/blob/development/code/client/css/settings/_variables.scss

## Reviewer
@demiculus @JuanRoman77

**Comment by aalmadan** [comment]
@samgawaran is this still live? link doesn't exist

**Comment by samgawaran** [comment]
> is this still live? link doesn't exist

hey @aalmadan this is an old issue, closing this now as still has been already implemented :)
