### ISSUE TITLE
End Game CTA Cleanup - Submission #1

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#200]
## Summary
Our current end-game stat CTAs does not use our current CTA design and font-color

![image](https://user-images.githubusercontent.com/90673012/197564773-a5be557d-a784-49ac-b274-baec98cd26ff.png)

This submission proposes a minor change on the end-game CTAs to make it flexible to change in the future

## Comparison
![image](https://user-images.githubusercontent.com/90673012/197569817-acaebd7d-64b1-4328-9ef0-1107de856a24.png)

### Bot and Lobby Games
![image](https://user-images.githubusercontent.com/90673012/197569675-b1c524a0-c238-4872-9f96-1c1ae1a5df64.png)

### Ranked Games
![image](https://user-images.githubusercontent.com/90673012/197569698-9beed2c2-bd13-46d3-86fa-93eee92f942f.png)

### Hover on Desktop
![Loom _ Free Screen  Video Recording Software _ Loom - 24 October 2022](https://user-images.githubusercontent.com/90673012/197566778-febdadfa-1697-499b-a298-5606829b7047.gif)

______
- Adjust the color of the selected CTA into $color-cta-sub
- retain the brown color for now. we don't want the players to be confused on the new color scheme so the update should be gradual
- Make the text use white colors

## Related Links

- https://github.com/colonistio/design/issues/11

## Submission Checklist
- [x] whats the scope of this submission?
_this submission covers the end-game CTAs. specifically the overview, dice, res card, etc. and proposed changes to make it look more cohesive with our CTAs_
- [x] how will it look on Mobile?
_Provided on the sample images_
- [x] what would hover states look like?
_Provided a gif sample on how it would look like_

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus

**Comment by JuanRoman77** [comment]
This is not a CTA, it's a tab. If selected it shouldn't be the same color of the CTAs. It should look like the other tabs but on its enabled mode.
![image](https://user-images.githubusercontent.com/73320460/197612252-c66ebc81-9d18-4f3e-9e8a-f8f909056877.png)

**Comment by samgawaran** [comment]
@JuanRoman77 
> This is not a CTA, it's a tab. If selected it shouldn't be the same color of the CTAs. It should look like the other tabs but on its enabled mode.

something like this?

I can't make the text white, it won't be readable on the enabled state of the tabs.
![image](https://user-images.githubusercontent.com/90673012/197692697-3c98a1a2-b19b-40b2-88de-000afeec401f.png)

I also adjusted the text: 
`Back to Lobby` to `Lobby` 
`Return to Map` to `View` Board` (its less wordy than return to map, we can also do View Map if ever)
