### ISSUE TITLE
Premium Rooms Pricing

### ISSUE THREAD

**Issue by alexcoleman7** [colonistio/design#201]
## Description
Related to Issues: #146,#195, #196 and #198 
I've been going through metabase to try and find how should we compare the renting format of the premium rooms with the purchase format of the store which we have atm. I have come up with a method below but let me know what you think or if you have any other ideas for me to investigate.

The graphs below are the sales per month for expansions and maps.

Expansions
<img width="1046" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/60288677/198404379-6625c068-3160-40ec-8e3d-a72dc8a9cd7c.png">

Maps
<img width="1041" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/60288677/198404422-a7573455-d8de-4694-8f72-e61c8f4552a9.png">

Both assets are trending down. This may be for various reasons:
* Users that have already purchased the items don’t have to purchase them again.
* No new assets are being introduced either so users eventually run out of items to buy.
* Memberships allow users to use these assets without purchasing them, reducing the purchase of individual items.

This could be useful to measure the performance of premium rooms. We can check how many premium rooms are played and compare the revenue of premium rooms to the trending revenue of map and expansion sales as above.

The ‘target to beat’ for premium rooms to be successful could be for example 400 expansions and 500 maps in a month, based on the trending numbers above. Therefore a total of 1,370,000Cc. If the premium rooms were 100Cc, we would need 13,700 rooms to become premium rooms to make a revenue that matches our current intake.

The graph below is the number of games per month that have no premium features. So base map, base game mode and only 4P. Roughly on average, we have about 400,000 games of this kind per month. Targeting 13,700 of these games at 100Cc to become premium rooms would be 3.4% of these games. Other numbers to consider:
Premium Room Price | Games to target to beat | % of games to target
-- | -- | --
10 | 137,000 | 34.25
25 | 54,800 | 13.7
50 | 27,400 | 6.85
75 | 18,267 | 4.57
100 | 13,700 | 3.425
125 | 10,960 | 2.74
150 | 9134 | 2.28
<img width="1051" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/60288677/198404497-cf5a2a49-f856-40ab-9648-8318ccf81658.png">

Considering that we have a total of about 660,000 registered emails and about 151,000 of them have made purchases, that means roughly 23% of the player base is willing to purchase on Colonist. We just have to find the right stuff to sell.

We are still going to be selling maps and expansions though and it is possible that players will buy an asset after testing on the premium rooms so the formula to compare the two and determine if the premium rooms are successful would be:

(400 expansions * 2800Cc + 500 maps * 500Cc) * Handicap < expansions bought * 2800Cc + maps bought * 500Cc + premium rooms bought * 100Cc

The Handicap is whether we expect the premium rooms to already be successful from the moment they come out or whether we think for example that if the premium rooms perform to 80% we can optimize the premium rooms in the future to achieve 100% or more. I think the Handicap should be quite low as we are not going to do much to advertise the premium rooms, just adding a button and description to the rooms page. Maybe 50%?

I also think there is room to consider the 50Cc, 75Cc, and 100Cc prices for the premium rooms. The number of games that need to be upgraded to meet the success factor is still fairly small but they will work well with our current Coins offers. For example, if someone is planning on buying a map but wants to test a few first they will get the 650Cc. Maps are 500Cc so they are left with 150Cc. If the rooms are 100Cc they would only get to test it once, but with 75Cc and 50Cc they will get a few chances and can even compare 2 or 3 maps first. We could keep it at 100Cc though and maybe hope that they will buy the 1380Cc instead.

This is similar with expansions. If they buy the 3000Cc they would have 200Cc spare to test an expansion. 100Cc and 75Cc only give you 2 chances to test an expansion which might not be enough to decide if they like it. But the 50Cc gives them 4 chances instead. Do we have a metric of how many games it takes for someone to get the hang of the expansions?

## Reviewer
@goktugyil @demiculus @samgawaran @JeffdEon

**Comment by demiculus** [comment]
Nice research :)

> The ‘target to beat’ for premium rooms to be successful could be for example 400 expansions and 500 maps in a month, based on the trending numbers above. Therefore a total of 1,370,000Cc. If the premium rooms were 100Cc, we would need 13,700 rooms to become premium rooms to make a revenue that matches our current intake.

Note that we don't need it to match our current intake. Since if people are renting, it'll slowly build up over time. So maybe 1/2 of that is fine for the first month.

> The graph below is the number of games per month that have no premium features. So base map, base game mode and only 4P. Roughly on average, we have about 400,000 games of this kind per month. Targeting 13,700 of these games at 100Cc to become premium rooms would be 3.4% of these games. Other numbers to consider:

Shouldn't we be looking at premium rooms and how many there are per month? 

> 151,000 of them have made purchases

Those are probably people getting the free icon & free color. A lot less people actually paid money. To see who paid money look at their transactions table to see if they spent on stripe or xsolla.

> Maybe 50%?

I like the formula, handicap sounds alright. 

> Do we have a metric of how many games it takes for someone to get the hang of the expansions?

Nope

> I also think there is room to consider the 50Cc, 75Cc, and 100Cc prices for the premium rooms. 

They can be followup tests if it shows promise.

**Comment by alexcoleman7** [comment]
Thanks :)

> Shouldn't we be looking at premium rooms and how many there are per month?
We don't have any premium rooms yet, and rooms, where people are using premium items, are not our target as it means that they already own the asset. 

> Fyi the most important thing to consider is, this should not decrease membership sales. So I would add other formulas there as well comparing it with membership sales.
Cool, I'll see if I can find something else to compare against that.

**Comment by samgawaran** [comment]
> or example, if someone is planning on buying a map but wants to test a few first they will get the 650Cc. Maps are 500Cc so they are left with 150Cc. If the rooms are 100Cc they would only get to test it once, but with 75Cc and 50Cc they will get a few chances and can even compare 2 or 3 maps first.

I agree with this. I think its good to assume that the players will buy the 650 coin pack. making the premium rooms `75cc` might make it a better alternative than buying maps outright. We have a player base that only play with their friends and want to try out maps and/or expansions with them. also here's a study where pricing that ends with odd numbers sounds cheaper compared to items that end with even numbers: https://en.wikipedia.org/wiki/Psychological_pricing

Lastly, maybe we can also check the players who bought items at the store but doesn't play any ranked or matchmaking games as well?. Since they would be benefit the most here and they are the most likely to pay on upgraded rooms.

**Comment by JeffdEon** [comment]
I'm wondering how many people will buy coins for this versus people that use their leftover coins to try something. So 2 key metrics I can think of are:

1. Was the FIRST purchase they made after purchasing coins a premium room? If so it means they bought just for this feature, if not then they're just using leftover coins they don't know what to do with.
2. If trying a premium mode leads to a purchase of subscription or expansion => the real success metric

**Comment by demiculus** [comment]
>> Shouldn't we be looking at premium rooms and how many there are per month?

> We don't have any premium rooms yet, and rooms, where people are using premium items, are not our target as it means that they already own the asset.

I meant that we have rooms which use premium items. That will give us an idea.

> 151,000 of them have made purchases

There is no way we have that many purchasers. https://metabase.colonist.io/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo0LCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjM1LCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDI5NCxudWxsXSwwLDMsOV1dLCJhZ2dyZWdhdGlvbiI6W1siZGlzdGluY3QiLFsiZmllbGQiLDI4MixudWxsXV1dfSwidHlwZSI6InF1ZXJ5In0sImRpc3BsYXkiOiJzY2FsYXIiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0= looks like its 39k players. Not sure what query you ran.

**Comment by goktugyil** [comment]
What's the status and next steps for this?
