### ISSUE TITLE
Premium Rooms - Iteration 3 (Screens + Scenarios)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#202]
## Summary
Created a new iteration for this task due to comments given by @alexcoleman7 here: https://github.com/colonistio/design/issues/198#issuecomment-1294187860

Adjusted the screens and added new scenarios from the feedback received. 

## Screens
- Adjusted popup checkmarks to include "all" (all expansions, all maps, etc.)
- Reverted to full lock icon if players don't upgrade their room yet. 
- _added new popup after Upgrade Popup_
- _lessened colors based on feedback_

### Upgrade Room Popup
![image](https://user-images.githubusercontent.com/90673012/201290678-7bb0b6b3-2d2d-487c-b156-0d0e2e49f721.png)

- I recommend `Study 3` but I'm not sure if we can add an image in the popup. if not we should go with `Study 2` players should be incentivized to upgrade to premium rooms by showing their names. @demiculus @alexcoleman7 thoughts on this?

### Desktop
![image](https://user-images.githubusercontent.com/90673012/201289570-7990e69d-7c1a-4bb4-8bc2-8c1c9aeabdf6.png)

### Mobile
![image](https://user-images.githubusercontent.com/90673012/201289736-42542a1b-695d-400f-baed-c500789f564f.png)

### Clicking on Dropdowns / Hover on Lock
![image](https://user-images.githubusercontent.com/90673012/198573599-24744e6d-0431-4652-9b49-b884c97984f6.png)

- When hovering on the lock icon. Unlock all (subject) for 1 game when you upgrade this room
- For mobile, players need to click the locked icon to show the infobox

### Clicking on an item a player doesn't "Own"
![image](https://user-images.githubusercontent.com/90673012/198574245-c2cff20c-9c7c-4de7-adcb-ac48d70e0db0.png)

- For items that the player owned. Add `Owned` on dropdown, as Alex mentioned items you don't own will follow our current format of showing in the chatbox.
- Adjusted the text to accommodate upgrading the room. `(Item) is only available for people who have purchased it or upgraded this room. Upgrade now!`

### Upgraded Room
![image](https://user-images.githubusercontent.com/90673012/201291484-c383c2c1-97d5-42da-8776-39a75714b58a.png)

### Players who don't have enough coins
![image](https://user-images.githubusercontent.com/90673012/201291769-39a913ab-0535-4629-80c7-9d4bb022bb75.png)

- Follow the current behavior. Show the coin popup module if the player has less than `(x) amount of price per premium room` 

### Players who are not signed in
![image](https://user-images.githubusercontent.com/90673012/201291797-e829b658-3fb4-42a3-9ad8-86f4e9cc0d4b.png)

- show current login module. I suggest adding to this module design since the ABtest has a good response here: https://github.com/colonistio/katan/issues/8850

## Related Submissions
- https://github.com/colonistio/design/issues/198
- https://github.com/colonistio/design/issues/196

## Related Links
- https://github.com/colonistio/design/issues/195

## Submission Checklist
- [x] submission checklist is done on the previous iterations
- [x] Will the tutorial game mode also be shown as "Owned"?
_Currently its not showing as owned. Low prio, but we can also show it as (owned) since everyone should be able to use the tutorial_
- [x] What would happen if the player has no coins or not signed in?
_provided the scenarios for this. But we should use the current behavior of how we handle this kind of scenarios_
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@alexcoleman7 @demiculus

**Comment by samgawaran** [comment]
I didn't add the new pricing research mentioned here: https://github.com/colonistio/design/issues/201. This can be changed in the implementation issue when its made

**Comment by alexcoleman7** [comment]
So the text on the chat box when you click an unowned item only has a link to upgrade the room.
![image](https://user-images.githubusercontent.com/60288677/198579930-0ef63044-1243-4ca2-98a9-21b8d76afb97.png)


@demiculus are you happy to promote only the Premium Room or should we still direct them to the store too?

Everything else looks great! thanks Sam

**Comment by demiculus** [comment]
1. Remove the extra background colors, thats confusing https://i.imgur.com/3XUXSPE.png
2. Fyi: https://www.loom.com/share/7a38b938e2684d5888baa95cc4706cc7 I told mau to implement this

> are you happy to promote only the Premium Room or should we still direct them to the store too?

I think premium room is better for now. Lets see how it works
@samgawaran after players click on purchasing preemium games
-> Players who have enough coins (done)
-> players who don't have enough coins (not done)
-> players who haven't logged in (not done)

cover all cases

**Comment by samgawaran** [comment]
Pasting this comment. this is the outdated screens + scenarios from the previous iteration

## Screens
### Desktop
![image](https://user-images.githubusercontent.com/90673012/198571916-fd80ecec-04a4-43f0-8ceb-b641772b8876.png)

- Adjusted popup checkmarks to include "all" (all expansions, all maps, etc.)
- Reverted to full lock icon if players don't upgrade their room yet. 

### Mobile
![image](https://user-images.githubusercontent.com/90673012/198572207-ab367521-49df-47ce-893f-943d261d36db.png)

## Scenarios
### Clicking on Dropdowns / Hover on Lock
![image](https://user-images.githubusercontent.com/90673012/198573599-24744e6d-0431-4652-9b49-b884c97984f6.png)

- When hovering on the lock icon. Unlock all (subject) for 1 game when you upgrade this room
- For mobile, players need to click the locked icon to show the infobox

### Clicking on an item a player doesn't "Own"
![image](https://user-images.githubusercontent.com/90673012/198574245-c2cff20c-9c7c-4de7-adcb-ac48d70e0db0.png)

- For items that the player owned. Add `Owned` on dropdown, as Alex mentioned items you don't own will follow our current format of showing in the chatbox.
- Adjusted the text to accommodate upgrading the room. `(Item) is only available for people who have purchased it or upgraded this room. Upgrade now!`

### Upgraded Room
![image](https://user-images.githubusercontent.com/90673012/198574610-61fd2f80-d4bb-4a7d-9456-bd8c03b97436.png)

**Comment by samgawaran** [comment]
@demiculus @alexcoleman7 
I updated the screens above based on the feedback here: https://github.com/colonistio/design/issues/202#issuecomment-1295895995

not sure if you're both notified. Should I go ahead and create implementation issue?
