### ISSUE TITLE
Show Resource Cost for New Players - Research & Studies 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#205]
## Summary
We need to show the resource cost for new players. based on the video here: https://www.loom.com/share/6cd1cb2b622948ffbf7d08c193ba2ccd
We should assume that most first time users doesn't know how to build certain pieces to win which reduces player retention for beginners.

- Feature must be easy to implement, I still researched a bunch of games (desktop + mobile) but didn't try to use those as they are quite complicated

## Research
![image](https://user-images.githubusercontent.com/90673012/199797618-7d195507-aca4-4831-bbd9-3a4e46991cc8.png)

![image](https://user-images.githubusercontent.com/90673012/199798172-10a5ed00-3ddc-419a-9a47-7d7deabf084c.png)

- I searched games that have `crafting` mechanics since it would show the resource cost for each item
- out of the games I found, games that fit the Colonist brand are mostly games on Mobile (Had a hard time to check games since there are more samples on gameuidatabase.com of browser games
- I followed the initial designs from `Catan Universe` since its the easiest to implement in our current game screen. Let me know if you want me to try other studies that are a bit more complex.

### Resource Cost Styles
![image](https://user-images.githubusercontent.com/90673012/199804868-f1d183c5-3c63-4f80-90c2-f741d0f6cefe.png)
- For these studies, I'm limited on having the resource cost list to be noticeable by players who are not used to our UI. hence it needs to be shown after the game start without clicking anything else.
- all studies should not intersect with other elements (ex. player opening the trade tab, in-game menu, etc.)
- I used `build cost` over `resource cost` since its shorter

### Study 1
![image](https://user-images.githubusercontent.com/90673012/199805356-7946769b-e2e4-4f84-8884-a1d7b7ac8ecc.png)

### Study 2
![image](https://user-images.githubusercontent.com/90673012/199805568-46131c19-13cf-4ea7-b9e4-3aaa8dd3496e.png)

### Study 3
![image](https://user-images.githubusercontent.com/90673012/199805592-1a7fbf53-1a8b-4dea-85e6-768f45224a58.png)
- added a collapsible arrow. First-time players will see the 2nd image first

### Study 4
![image](https://user-images.githubusercontent.com/90673012/199805871-f5322de2-c339-4d10-9f00-d938200fac37.png)

- added a `build` icon in the current in-game menu. Could be move inside another section once we implement the new settings tab

## Related Links
- https://github.com/colonistio/design/issues/203

## Submission Checklist
- [ ] how would it look on mobile?
_the resource style studies I sent all fit the size of the small android device (360x640) if a design is approved, I can show the mobile versions for it next_
- [x] what happens if the player opens up the trade tab, ingame box, etc.
_all studies have samples where the player opens up the trade tab. these ensures that the placement of the resource cost_
- [x] how could we move forward after initial design?
_create a tutorial flow soon? refine resource cost along an in-game redesign following the designs of top games_
- [x] how does other games show resource cost?
_most of them show the current amount of "resource" the player has in hand. this is too complex for our game which only has 5 resource tiles on the base game so we should follow how CU and mobile games do their games_
- [ ] C&K and SF resource cost?
_task are designed for newbies. (player who play v bots) creating something like this for C&K might make it hard to place since C&K has a lot of thing going on with its other mechanics._
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus

**Comment by demiculus** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6215305/199917694-bc70bfd7-a7ff-4cab-8c09-6aafcd70dd72.png">

Bruh...

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6215305/199917743-844dbf1f-89b6-48fc-8743-90c4b3170267.png">

https://i.imgur.com/yh4SbS5.jpg

**Comment by demiculus** [comment]
Create an abtest implementation issue https://www.loom.com/share/78d019bd57ee4a7d8d5886e095b6ea87
