### ISSUE TITLE
Show Resource Cost for New Players - Screens + Scenarios

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#208]
## Summary
Adjusted the design based on Demi's feedback: 
https://www.loom.com/share/78d019bd57ee4a7d8d5886e095b6ea87

- Build cost should be easily visible
- Show build cost title
- item name should be aligned left
- Make sure it won't intersect with dev cards
- can be closed so it won't clutter the in-game board

Research is done on the issue here: https://github.com/colonistio/design/issues/205

## Screens
![image](https://user-images.githubusercontent.com/90673012/200172785-0e865414-2696-466f-a3ef-c30e82600491.png)

- Modified the build cost infobox based on the feedback on the loom
- both text and resource cards are aligned left. it looks much more organized this way. For context, this is how it looks like when text is aligned left while resource cards are aligned right (https://prnt.sc/IXqvd9bg2glj)
- for beginners, `Show build cost` will be opened in-game start
- show build cost only applies on base game

### Trade
![image](https://user-images.githubusercontent.com/90673012/200172841-1a5ed793-204a-40da-8cd5-3733f8010168.png)

### Dev Cards (Year of Plenty, Monopoly)
![image](https://user-images.githubusercontent.com/90673012/200172867-d42ec8e9-a0e8-41b0-8064-0b1cb315e4b5.png)

- placed in this position so it won't intersect with bigger dev card UI like monopoly and year of plenty

## Related Submissions
- https://github.com/colonistio/design/issues/205

## Related Links
- https://github.com/colonistio/design/issues/203

## Submission Checklist
- [x] This submission applies all of the checklists in the previous iteration
- [x] Make sure the positioning of the build cost dropdown won't intersect with other elements in the board
_I ran and tested scenarios like clicking the knight, error messages and such and I saw that the devcard screen for both Year of Plenty and Monopoly has the biggest popup box so its what I considered in the scenarios_
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77

**Comment by samgawaran** [comment]
Reference design submission for implementation issue. Will change this along with the implementation issue if there are any further feedback

**Comment by demiculus** [comment]
Moving the button here will save more space for the game screen. Do that. And create an implementation issue with it.

**Comment by samgawaran** [comment]
Old Designs before the Demi's feedback here: https://github.com/colonistio/design/issues/208#issuecomment-1304840013

## Screens
![image](https://user-images.githubusercontent.com/90673012/200172785-0e865414-2696-466f-a3ef-c30e82600491.png)

- Modified the build cost infobox based on the feedback on the loom
- both text and resource cards are aligned left. it looks much more organized this way. For context, this is how it looks like when text is aligned left while resource cards are aligned right (https://prnt.sc/IXqvd9bg2glj)
- for beginners, `Show build cost` will be opened in-game start
- show build cost only applies on base game

## Scenarios
### Trade
![image](https://user-images.githubusercontent.com/90673012/200172841-1a5ed793-204a-40da-8cd5-3733f8010168.png)

### Dev Cards (Year of Plenty, Monopoly)
![image](https://user-images.githubusercontent.com/90673012/200172867-d42ec8e9-a0e8-41b0-8064-0b1cb315e4b5.png)

- placed in this position so it won't intersect with bigger dev card UI like monopoly and year of plenty
