### ISSUE TITLE
Sign-in Lobby Ads - Design Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#209]
## Summary
Created some design studies based on the instructions given here: https://www.loom.com/share/11341c0b39cb4ffaa11b2b829fbbd90e, this may increase our player signup conversion chance if they will know the perks of signing in to Colonist

- Sign In (Title)
    - Track progress
    - Add friends
    - Play ranked

## Details
![image](https://user-images.githubusercontent.com/90673012/200572511-2caa9dac-c925-4ab6-a909-90c7615ecc98.png)

### Study 1
![image](https://user-images.githubusercontent.com/90673012/200351033-025476fe-2a87-4715-bed8-cd62159846f4.png)

### Study 2
![image](https://user-images.githubusercontent.com/90673012/200351072-724666b0-b96f-42b3-b3cc-5f19067eff29.png)

- common icon style for signing in (https://prnt.sc/bTX1ePUKpB0T)

### Study 3
![image](https://user-images.githubusercontent.com/90673012/200351117-959a3abe-741c-4848-8cf4-4156fcb5c1ec.png)

- Experimented with using other avatars for the sign-in for Study 3 & 4. Could also possibly boost avatar sales

### Study 4
![image](https://user-images.githubusercontent.com/90673012/200351288-e2f6f8c5-bb48-4774-bb2c-5da64c4c9c81.png)

- Experimented with using other avatars for the sign-in for Study 3 & 4. Could also possibly boost avatar sales

### Study 5
![image](https://user-images.githubusercontent.com/90673012/200573016-d0f9f833-c531-4684-8d68-b42d44e46626.png)

- _added study 5 based on @JuanRoman77 suggestions: https://github.com/colonistio/design/issues/209#issuecomment-1306549894_

## Related Links

- https://github.com/colonistio/katan/issues/8317

## Submission Checklist

- [x] Whats the research behind the design studies?
_I look on the commonly used iconography for sign in assets and I based my designs from that. I also checked how other games and websites do theirs and they commonly show them as buttons/CTAs but in our case, Colonist used icons on our Lobby Ads view so I opted to follow the pegs I saw from Google_ 
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77

**Comment by JuanRoman77** [comment]
Could you try something like these? 
![image](https://user-images.githubusercontent.com/73320460/200463522-b34b871d-0581-41bc-9326-c2083981e227.png)

**Comment by demiculus** [comment]
@JuanRoman77 you can handle the review & implementation of this

**Comment by demiculus** [comment]
I also removed the abtesting parts of this: https://github.com/colonistio/katan/issues/8317 
No need to abtest its gonna work regardless.

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/203471855-233d627e-cd2d-45b0-bc0a-4825307fa89f.png)
1. Track **your** progress
2. `add`
3. `play`
4. remove word *your*
5. `Ranked`
6. `in`

**Comment by demiculus** [comment]
Once you do the feedbacks, create an implementation issue

**Comment by samgawaran** [comment]
Closing this issue, created the implementation here: https://github.com/colonistio/katan/issues/9058
