### ISSUE TITLE
Translation (Change Language) Button - Desktop + Mobile Screens

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#210]
## Summary
adjusted the design based on the feedback given here: https://www.loom.com/share/ac90aab327c74c73a2b070450c1013f8

from the previous issue:
- Use “Dark Blue Bar” or anything much  less visible because a lot of players won't ever click this 
- after clicking on the language, we should show a popup. This is more modular than showing a dropdown in an awkward place

Research is done on the previous issue: https://github.com/colonistio/design/issues/190

### Desktop
![image](https://user-images.githubusercontent.com/90673012/200561505-201296fa-e643-4273-9cf4-a8882db988b2.png)

### Mobile
![image](https://user-images.githubusercontent.com/90673012/200562757-f167a991-82ea-423f-8f31-cffbbab7a866.png)

## Related Submissions
- https://github.com/colonistio/design/issues/190

## Scenarios
- the change language CTA will always be present on the footer. After the player click on the Language CTA. It will show a dropdown so there's not much of an edge case/scenarios that I can think of except this: https://github.com/colonistio/katan/issues/8635

## Related Links

- https://github.com/colonistio/design/issues/187

## Submission Checklist

- [x] can players change their language while playing?
_not at the moment. We are in the process of also changing the settings page. After that is implemented, we can put a change language section in the dropdown for players to change language_
- [x] any other edge cases you can think of?
_when the player immediately clicks on the language cta before the `become a member` popup shows up. this is will be done https://github.com/colonistio/katan/issues/8635 so it won't be a problem as an edge case in the future_ 
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus

**Comment by demiculus** [comment]
Good, create 2 implementation issues
1. Implementing this design
2. Removing this https://i.imgur.com/pKjWiV2.jpg and making rulebook language work with the new design

Once you create both issues, ask omar to edit the issue descriptions so other devs can take it.
