### ISSUE TITLE
v146 - Profile Ranked Tab Announcement and Banners

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#214]
## Summary
we will be launching the Profile ranked tab in the upcoming version. This submission compiles the marketing materials we could use to advertise the feature

___________________________________________

## Recommendation
![image](https://user-images.githubusercontent.com/90673012/202917305-4b90843e-a278-4ff1-b86e-14375693536e.png)

![image](https://user-images.githubusercontent.com/90673012/202723585-2bf45e63-ea03-4bbe-a929-e2a4edeac4ff.png)

- While designing, I tried to include the `profile ranked tab cards` on all of the ads like Demi suggested, but its dimensions is hard to showcase besides the social media post. I decided to use the ranked tab icon surrounded by the division helmets instead as it's more eye catchy.
- Copy is subject to change. I'll send this templates to Mayla so she can edit

### Overlayed on screen
**Social Media**
![image](https://user-images.githubusercontent.com/90673012/202917289-aa7b7130-d8da-4ba2-b871-1f6f2edc4a2f.png)

**Banner**
![image](https://user-images.githubusercontent.com/90673012/202724858-b01e0267-a915-4a98-a948-1326ec39cb4c.png)
**Home/Lobby Ads & Adblock**
![image](https://user-images.githubusercontent.com/90673012/202724887-f88ae9f2-16d2-4653-9cea-3ea0adfbad05.png)

______________________________________
### Other design studies
Sending some of the other designs I made so you guys can take a look
![image](https://user-images.githubusercontent.com/90673012/202725671-45a1451a-2e6f-436e-b90d-b72973a45979.png)

## Resource

- Discord post: https://discord.com/channels/605233308577562643/729052183013621810/1043105646700134460
- Gdrive link: https://drive.google.com/drive/u/0/folders/1SzpDYwpXbWxVTWOMZMkBZL9vJ0nZINsN

## Submission Checklist
- [x] why do the other design studies only have the banners?
_doing the banner design is the hardest to create out of all of this. Designing on the most akward size will make it easier to adjust on the other sizes. If it looks good on the banner than its most likely would also work well in the other formats_
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by JuanRoman77** [comment]
![Screenshot_20221118_233420_Opera beta.jpg](https://user-images.githubusercontent.com/73320460/202830338-85b7e19c-9939-4853-aeba-a4c38e693873.jpg)

- Remove `is now available`
- Increase the size of the title (`Ranked profile`) to fit the new available space

**Comment by SimonH321** [comment]
@JuanRoman77 Why do we use homepage space to advertise something that doesn't generate revenue? If we're trying to motivate users to play more ranked we should give a popup about this feature after they finish ranked games, but home page seems more valuable for membership ads or general ads

**Comment by demiculus** [comment]
@samgawaran 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/6215305/202897670-dcdef14e-2888-4d9a-bcad-86c3c8772e7e.png">

**Comment by samgawaran** [comment]
Don't compress the banner. It pixelates the whole design

**Comment by samgawaran** [comment]
@JuanRoman77 
Updated the drive link: https://drive.google.com/drive/u/0/folders/1SzpDYwpXbWxVTWOMZMkBZL9vJ0nZINsN for the social media. 

recompressed the adblock ads to squeeze out 2kb more
