### ISSUE TITLE
CU Blog Post Banner

### ISSUE THREAD

**Issue by SimonH321** [colonistio/design#215]
## Description
Next week we are releasing a blog post that recaps what happened with CU, and discussing how we prevent issues like these at Colonist. I don't have anything specifically in mind for the image, but the goal of the blog is to make people think "wow, CU sucks and Colonist is better. I now understand better why that is." Important not to seem like we're gloating though. If this is too broad @ me and I can try to give ideas. 

## Resources
Sizing/Blog Color Scheme: https://github.com/colonistio/design/issues/193 was perfect
CU Logo and Screenshots: https://www.catan.com/catan-universe
Blog Draft: https://blog.colonist.io/ghost/#/editor/post/637188f7b1d80904a2b00ea6

## Reviewer
@samgawaran @JuanRoman77

**Comment by samgawaran** [comment]
I would need more pegs for this, not sure if its something like a comparison style like `Colonist vs CU` or something that's more subtle.

for the comparison style, I was thinking of something like this:
![image](https://user-images.githubusercontent.com/90673012/202914717-38d5fbfd-8723-4e00-ad22-ae5933da1f7e.png)

Colonist vs Catan Universe
- stat 1 is higher % | stat 1 is lower %
- same 
- features done 100+ | features done 10+

**Comment by SimonH321** [comment]
This is too obvious for what I had in mind. I actually think a simple screenshot from CU discord will get the point across better than anything designed. Sorry about that

**Comment by SimonH321** [comment]
Apologies for going back and forth, but for the overall blog look I think we need a design here. Could you make something simple with the Colonist logo, could have some text like "24/7 uptime" or "always online" or something to that tune. Don't think we benefit from having CU in the actual image, so it can be something simple just so it doesn't stick out in the blog stream

**Comment by samgawaran** [comment]
closing the issue since the blog has already been posted
