### ISSUE TITLE
Translation Blog Post Banner

### ISSUE THREAD

**Issue by SimonH321** [colonistio/design#216]
## Description
Next week we will be releasing a blog post announcing translations. It will be a short blog post, done for SEO reasons, listing out all the languages. I'd love a banner that has the Colonist logo with some country flags or something like that integrated with it. 

## Resources
Sizing/Blog Color Scheme: https://github.com/colonistio/design/issues/193 was perfect
Blog Draft: https://blog.colonist.io/ghost/#/editor/post/63792f11b1d80904a2b00f4c

## Reviewer
@samgawaran

**Comment by demiculus** [comment]
> If you are a Colonist player fluent in any language on this list please contact me at simon@colonist.io or SimonH#3311 on discord. 

1. You should be able to direct them to the translation place right away without them needing to contact you.
2. The below people filled out the contribution form in the past 2 years that they want to translated. Most of them will probably have moved on by now. 

@omarhurani fyi

| nearing.charles@gmail.com | https://colonist.io/profile/mywood       | Japanese |   |   |   |   |   |   |   |
|---------------------------|------------------------------------------|----------|---|---|---|---|---|---|---|
| renebulsara@gmail.com     | https://colonist.io/profile/renebulsara  | Spanish  |   |   |   |   |   |   |   |
| pielblateron@gmail.com    | https://colonist.io/profile/EtoranB      | French   |   |   |   |   |   |   |   |
| shubhayankabir@gmail.com  | colonist.io/profile/buckyisalive         | ??       |   |   |   |   |   |   |   |
| diogotarasconi@gmail.com  | https://colonist.io/profile/LunaticFlaw  | ??       |   |   |   |   |   |   |   |
| brebrejs@gmail.com        | https://colonist.io/profile/Brebre       | ??       |   |   |   |   |   |   |   |
| kapil29bahadur@gmail.com  | https://colonist.io/profile/kapswashere  | ??       |   |   |   |   |   |   |   |
| Thomas.juressen@gmail.com | https://colonist.io/profile/ThommieZ5045 | ??       |   |   |   |   |   |   |   |
| luizacolhon@gmail.com     | https://colonist.io/profile/aziul1804    | ??       |   |   |   |   |   |   |   |
| robertsoiu@yahoo.com      | https://colonist.io/profile/GGigel       | ??       |   |   |   |   |   |   |   |
| tevin.froese@gmail.com      | https://colonist.io/profile/tevv       | ??       |   |   |   |   |   |   |   |

**Comment by SimonH321** [comment]
What do you mean by translation place right away? We don't have that online yet

**Comment by demiculus** [comment]
> What do you mean by translation place right away? We don't have that online yet

I meant whatever the reason you want players to reach out to you. Create a system so you are not the bottleneck and they can do whatever they need to do without needing to reach out to you. I'm assuming they're gonna translate certain stuff in crowdin.

**Comment by samgawaran** [comment]
closing this issue, blogpost has already been posted here: https://blog.colonist.io/new-colonist-languages/
