### ISSUE TITLE
Translation Blog Post - Submission

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#217]
## Summary
Submitting this design based on Simon's design request. I followed the idea based on his idea and finalized that this design is the best out of all the studies I made

___________________

## Design

![image](https://user-images.githubusercontent.com/90673012/202916085-4e89a064-9f67-48f3-b9b4-1cc6506753a9.png)

- `Play in your language` is a better title than the word translation. I think the copy is also straightforward, I can adjust the text if ever.
- Added a globe icon as the main design for the text
- Added a couple of national flags in the post. Added the flags based on the home languages of players that plays the game. (ex. Spanish = Spanish Flag)
- In the drive link, I added a version without the flags

### Overlayed in Blog
![image](https://user-images.githubusercontent.com/90673012/202916104-789e2225-5c88-45ca-8d20-65cdaaf0cf41.png)

_________________________

**Other designs:**
this are the other designs I made. Feel free to have a look:
![image](https://user-images.githubusercontent.com/90673012/202916572-e97638f5-2168-49c6-b74d-3b75dc108f51.png)

- `Colonist is now playable in your language` design, I think adding a lot of flags in a single letter is cool but it would leave the other area plain and redundant since we also have a Colonist logo above.
- `Flags beside the title` design is messy when I looked at it a second time. might also be bias since some other flags are bigger

## Related Links
- https://github.com/colonistio/design/issues/216
- Gdrive Link: https://drive.google.com/drive/u/0/folders/1VqHxnrhf18fxuwV7gyL3oo3NXn6pYQ8Q

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@simonH321 @JuanRoman77 @demiculus

**Comment by SimonH321** [comment]
I think I prefer 
<img width="277" alt="Screen Shot 2022-11-20 at 2 49 53 PM" src="https://user-images.githubusercontent.com/112735505/202925438-45e02a1b-4f31-4dd7-91b8-22548265df8a.png">
Interested to hear what Juan thinks

**Comment by JuanRoman77** [comment]
I'll reply on Tuesday

**Comment by demiculus** [comment]
![image](https://user-images.githubusercontent.com/6215305/203191130-727a4880-f9de-4479-b202-584c09199772.png)

decrease the chaos, one reason its chaotic is because no breathing room. Sam you should know well how `breathing room` works in designs.

**Comment by SimonH321** [comment]
Uploaded with the suggested image, waiting for Juan's input though

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/203441479-647db5c4-31f9-443c-8f70-3acb3b01cb49.png)

1, 2, 3. Reduce size
4. Center vertically. Margins are off.

**Comment by samgawaran** [comment]
was on vacation a few days ago so I haven't seen the comments about the design here, nevertheless, will take this into consideration. but for now, I'm closing the issue since the blog post has already been posted. 

I assume this is on low-prio now, but re-open if we need to adjust the design,

**Comment by JuanRoman77** [comment]
> was on vacation a few days ago so I haven't seen the comments about the design here, nevertheless, will take this into consideration. but for now, I'm closing the issue since the blog post has already been posted.
> 
> I assume this is on low-prio now, but re-open if we need to adjust the design,

The image in the blog post can still be updated
