### ISSUE TITLE
Mobile Problems Ideas Dump

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#218]
## Description

Dump mobile related stuff

**Comment by loganstillings** [comment]
Dumping a list of things I came across while playing a game on mobile:	

1. chats font size is too large and most of the time only one word is visible on a line
2. resolution isn't great
    * look into the algorithm for this
3. friendly robber popup on c&k takes up too much space and is not easy to click out of
4. Stuff that we usually get with mouse hover functionality is missing
    * such as seeing progress cards/types, cost of buildings

**Comment by samgawaran** [comment]
- hard to click on the placement blips if you have fat fingers
- some assets not optimized for mobile (ex. the best value tag in store is really huge)
- pages that are imbalance.
     - single pages like `about` `community` etc. uses around 40% of space for the shortcuts tab and only around 60% for the content

**Comment by samgawaran** [comment]
- Devcards:
    - playing in mobile and getting a devcard is a chore. text are so small and item images are hard to be seen. 
    - C&K Dev cards, color of the progress cards cannot be seen

**Comment by goktugyil** [comment]
Moving these to discord channel?

**Comment by goktugyil** [comment]
Doc: https://docs.google.com/document/d/1yu9QJXsYZqfG8PSHF-kfASGvVU0PuqP19jl7vH4y8hc/edit

**Comment by demiculus** [comment]
@samgawaran you can move them to the channel and close this issue
