### ISSUE TITLE
CU Blog Post Banner - Submission 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#219]
## Summary
The blog for this banner will talk about the downtime of CU in recent weeks. The design as requested by Simon shouldn't be too gloating or show CU.

## Design
![image](https://user-images.githubusercontent.com/90673012/204112392-319d9197-8b94-40a0-aedd-b7b14203207a.png)

- We could either go with an option with `We are 24/7 Online` or without. I think using words `uptime` are jargons for some people so I opted in the word Online which is more generally used
- Calendar asset uses our number tile font style for branding
- the same color is used in the clock asset

### Overlayed in Blog
![image](https://user-images.githubusercontent.com/90673012/204112402-e9ed8b21-05a5-4a3f-8147-a33383c39e88.png)

______

### Other Design I made
![image](https://user-images.githubusercontent.com/90673012/204088109-aa08b4c5-8cc5-46c3-a270-d1d0485005c9.png)
- I tried using other elements and include a clock asset in the wording, but some people may mistake it with `we are online 24 / 70` 
### Edit from before:
![image](https://user-images.githubusercontent.com/90673012/204112339-7e1bb49b-6ce4-461a-90d2-2f1446d12081.png)
- Increase/decrease sizes of particular assets based on Juan's Feedback
## Related Links

- https://github.com/colonistio/design/issues/215
- resource: https://drive.google.com/drive/folders/1AP6FaA2WfodJgufeacekhOARQdcf1EYl?usp=sharing

## Submission Checklist

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/204090297-5fe42ca5-800b-44f7-b182-0af69f851663.png)

1. Increase size
2. 3. Reduce size

**Comment by samgawaran** [comment]
Adjusted the sizes based on the feedback here: https://github.com/colonistio/design/issues/219#issuecomment-1328042628

applied the edits on the Gdrive link

**Comment by samgawaran** [comment]
closing this issue as the blogpost is now up: https://blog.colonist.io/how-we-avoid-downtime/
