### ISSUE TITLE
Lobby/Homepage Ads Improvement - Research & Design

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#223]
## Summary
Our current ads in the website are lackluster compared to how other games do their ads. Moreso, Goku commented during one of the past team meetings that our store ads doesn't look like its clickable.

This submission looks on ways on how we can improve our ad design

### Store Ads
![image](https://user-images.githubusercontent.com/90673012/204943524-dc70ae34-af74-426d-a73c-6ccc4161fcea.png)
![image](https://user-images.githubusercontent.com/90673012/204943324-5b898a94-c5f4-4ee5-b0a5-6265f3ac4f28.png)
![image](https://user-images.githubusercontent.com/90673012/204943720-0c3e2f76-08ec-4f38-971e-497e0de05f64.png)

- All of the games shows a hint of gradient in the cards to make it look more appealing
- **More games** shows their title below the item they are promoting
- They add a lot of textures and additional assets as well

**Things I considered:**
- how _big_ the filesizes would get if I tried creating assets that are of the same detail with the samples above
- designs should be _responsive_ if the player is playing with different browser sizes
- Consider how we're currently doing it right now. which is to right the text and placed the asset in a container
- the new design shouldn't be too obnoxious when placed with our other components (ex. Play now CTAs, lobby list, etc.)

### Adblock
![image](https://user-images.githubusercontent.com/90673012/204971204-7f983522-23ec-4b70-adba-0aeec4407258.png)

- I checked 160x600 ads for our same sizing
- Most ads of this size has a button that indicates that it can be clicked
- Logos are above, since most ads of this size are use by advertising companies 

**Things I considered**
- make it consistent with how we present our store ads
- follow usual 160x600 ads conventions, besides adding the logo since this ads will be shown exclusively in Colonist
- flexible design if ever we would want to put up ads in other websites

### Comparison: Containers
![image](https://user-images.githubusercontent.com/90673012/204963469-7068700d-e444-4b99-88fa-c7387e15fa5a.png)

- to reduce the file size and make it easier to adjust, I just added bg texture and gradient on the container template
- I didn't adjust the sizing of the containers since its not on the scope of the task
- removed the rectangular bar at the bottom, it didn't look good and looks cheap compared to the other samples on the research

### Comparison: Design/Layout
![image](https://user-images.githubusercontent.com/90673012/204964542-0e6dba74-a92e-458b-9f6d-bef033087941.png)

- adjusted the layout, made the title use `$font-landingpage-title` so its bigger. left enough space for 2-3 liners for the store ads and lg-header for the adblock
- featured asset/item will add a shimmer gradient in its surroundings so its more emphasize. 
- title for store ads are at the bottom. to identify adblocks, it will have a button and a title above. 
- all new designs should have some designs at the border (designer should provide the files for this and make sure its flexible)
- it will closely resemble how we design for social media posts and banners. in this comment: https://discord.com/channels/605233308577562643/740506662628229160/1047047262171316304 Demi suggested that we increase our store sales to `20%` each time we post new updates. By doing this design change in our store ads, it could also increase clicks as well. 
_________________________

### How it would look:
![image](https://user-images.githubusercontent.com/90673012/204964997-84063e23-839e-4aad-accd-de306a65a228.png)

### How it would look: 2 liners or long titles
![image](https://user-images.githubusercontent.com/90673012/204965131-5b532a46-069a-4685-ac03-2d9034bec3dd.png)

### Hover States
**Current**
![Current Hover State](https://user-images.githubusercontent.com/90673012/204967714-c29417ce-1aca-47ed-a338-426f14078728.gif)

- only the rectangular bar lights up. this is not great UX since players might think thats the only clickable area in the ad even though its clickable as a whole

**Proposed**
![Proposed Hover State](https://user-images.githubusercontent.com/90673012/204967743-a8ad1426-1849-40ad-9fc8-048f3829a898.gif)

- Ideal implementation: Image is enlarged by 10% and text and subtext are move aside to make it more engaging. + change the color of the background. add an overlay of `#000000` in 10% so it looks clickable
- Easy implementation: change the color of the background. add an overlay of `#000000` in 10% so it looks clickable

### Adblocks
- we don't animate our adblocks since we are using .png on them. 
- if we would show in-game adblocks in the game-screen, don't show the remove ads CTA at their bottom

### Screenbreaks
![image](https://user-images.githubusercontent.com/90673012/204970407-ce86d22a-4ae7-44a6-91f6-3307e96b5ffa.png)
- I followed our current logic here, if the screen past a certain width, the whole store ad won't be shown so I didn't create one for that. 

## Related Links
- https://github.com/colonistio/design/issues/211

## Submission Checklist
- [x] How it will look on mobile?
we are not showing store ads at our mobile browser at the moment. We can focus on mobile-specific ads once we start the mobile app
- [x] How it will look on different screen sizes?
see screenbreaks, feature asset and title must be the last to be removed. 
- [x] How other games advertise some of their items?
answered this on the research above. they add gradients/textures to not make it look flat, also, they are all showing their adds on containers like us
- [x] Pros and Cons of the design studies you made
Pros;
more eye-catchy compared to our current
store ads and adblocks has a consistent bg so its easier to adjust in the future
hover state for desktop adds information that its clickable
Cons: 
more time is needed to create an ad moving forward
We can only use less text to explain the ads since its now bigger
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus

**Comment by demiculus** [comment]
https://www.loom.com/share/8eb3f17eadf2403ca2b57a09301e3c45

**Comment by samgawaran** [comment]
reviewing this loom: https://www.loom.com/share/8eb3f17eadf2403ca2b57a09301e3c45
> Why does Adblock have a button on it and not on the lobby ads?

In the research, I sent, **store / item ads of games don't use any button** since they can only be seen inside the website itself. The AdBlock in this submission also considers the probability that we would advertise on other websites/games that's why it needs to have a button to make it look like a literal ad.

> Our current store ads use HTML, do you want us to use backgrounds?

**Yes, I'll provide the backgrounds for each** In one of the sections in this submission, I showed screen break cases for desktop screens since players can change their browser screen sizes. 

What I would recommend is we don't use HTML anymore for the ads. top games and gaming platforms don't do it. That said, should I still do a new iteration or not?

**Comment by demiculus** [comment]
1. Adblock ads all should have Green CTA button
