### ISSUE TITLE
End-Game Stat Screen Improvement

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#224]
## Description

![image](https://user-images.githubusercontent.com/90673012/205002791-ac849b46-3ff9-45c4-9c1d-6e0898e4f9f6.png)

- Make the other screens of the end-game stats consistent and up-to-date with how the pages in the website look.
- Try removing certain elements/design that clutters the page, or propose new ones that would make it look pleasing

## Ideas from Feature Suggestion
- https://colonist.featureupvote.com/suggestions/105432/include-a-line-graph-that-shows-points-by-turn-in-the-endgame-statistics

### Issues to be fixed
- https://colonist.featureupvote.com/suggestions/186207/resource-stats-get-cut-off
- https://colonist.featureupvote.com/suggestions/175593/grammatical-error-on-endgame-stats

## Reviewer
@demiculus

**Comment by aalmadan** [comment]
Close issue?
