### ISSUE TITLE
Collapsible Action Logs & Chat - Screens (Desktop & Mobile)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#229]
## Summary
As part of the [priority list](https://docs.google.com/document/d/1yu9QJXsYZqfG8PSHF-kfASGvVU0PuqP19jl7vH4y8hc/edit) for the ongoing mobile app optimizations. We will allow the players to have collapsible Action / Game Logs to reduce the space needed for Mobile

The design is based on the idea Juan made here: https://discord.com/channels/605233308577562643/1010487830268624937/1011910088665088020

## Comparison
![image](https://user-images.githubusercontent.com/90673012/205862167-da3816c8-3eac-40dd-8d13-78e89ef92b69.png)

- same logic with the resource cost dropdown
- If that tab has new content, it will have the `blip` indicator. same with our Careers page

### Both Expanded
![image](https://user-images.githubusercontent.com/90673012/205866839-644e3744-49d6-4924-8b25-03be0e6a5fc6.png)
- This design made sure that either Chat or Action Log will use a large enough font size so it isn't hard to read on Mobile

### One tab expanded
![image](https://user-images.githubusercontent.com/90673012/205866933-75c71842-2caf-4a39-83fc-89151f604933.png)

## Related Links
Mobile Dev Master List
- https://github.com/colonistio/katan/projects/5#card-87070048

## Submission Checklist
- [x] What would happen if the player collapses both sections?
_it should open the other one. At least one section should always be expanded to avoid spacing issues_
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @devyeshtandon

**Comment by samgawaran** [comment]
Reference issue for https://github.com/colonistio/katan/issues/9125

---

closing this issue, re-open this for feedback

**Comment by demiculus** [comment]
@samgawaran 
1. What problem is this solving?
2. What are other solutions to the problem?
3. What are the second order effects of those solutions?

**Comment by samgawaran** [comment]
> What problem is this solving?
Letting the players increase the size of their event log or chat log by minimizing the other. There are a lot of cases where players don't use the chat feature at all, so minimizing that can make better UX for those kinds of players

Also in the case of our Mobile browser screens, its hard to read since we try to squeeze in a lot of details https://prnt.sc/dcLjJIUvdSzt

> What are other solutions to the problem?
The submission is just a quick fix to this problem. There are a bunch of better solutions but it might take a lot of dev and design work since we would need to overhaul the game-screen UI. I can look more into it once we get going in designing the mobile app game screens 

> What are the second order effects of those solutions?
some players might not know how to expand/minimize their chat and event logs. Ways to minimize this is to have both chat and event opened by default 

Another consequence is that we would need to add a dropdown/minimize icon to each so it looks clickable

**Comment by demiculus** [comment]
> Letting the players increase the size of their event log or chat log by minimizing the other. There are a lot of cases where players don't use the chat feature at all, so minimizing that can make better UX for those kinds of players

That is not a problem

> Also in the case of our Mobile browser screens, its hard to read since we try to squeeze in a lot of details https://prnt.sc/dcLjJIUvdSzt

"It is hard to read" is a problem. 

We have 20 other more important problems than this. I gave them to you through discord. Do those.
