### ISSUE TITLE
Profile - Account Linking (Research + Screens)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#230]
## Summary
We will be adding an account linking feature to enhance the player experience in our game. Now players can choose whether they want to login via google or select a new option like Discord and other options

## Current 
![image](https://user-images.githubusercontent.com/90673012/205983277-f8a73962-859b-44c7-941f-d9c0bf78e3fa.png)

## Research
![image](https://user-images.githubusercontent.com/90673012/205984204-92ad3ef2-da58-4e33-864c-463fd11d3f80.png)

- I searched popular mobile games in part of our transition to website to app priority. + searching in Mobile lets me see if its workable in our browser version
- Most games uses the words `Settings` where players can access their account links
- They say `Connect` if that account is still not connected and `Connected` if it already is.

## Proposed
![image](https://user-images.githubusercontent.com/90673012/206410045-c5d9cfe6-af19-4c32-8637-7f614ed3970d.png)

- Change `Membership` to `Settings` since Accounts has already been added there.
- _Edit - Followed Mobile Legends style of showing connected accounts in the right side of each card. We can redo its orientation on the mobile app optimization_

### Main Flow
![image](https://user-images.githubusercontent.com/90673012/206410442-285eba03-d00f-4abf-b5b2-aee35f4c802c.png)

- To unlink an account, the player needs to click on the card of an account that's already been linked

### If only 1 account has been linked
![image](https://user-images.githubusercontent.com/90673012/206411793-403d6620-945e-42f5-95b9-1ff27c984102.png)

- This is the default screen for most people. They can't unlink if there's only 1 email connected to their account
- for players who want to delete their accounts, they should go the usual way and contact support so we don't incentivize account deletion

### Linking an account thats already been linked
![image](https://user-images.githubusercontent.com/90673012/206411913-6e37fac7-2088-45b3-904b-e4700d73bc3a.png)

## Related Links
- https://github.com/colonistio/design/issues/225

## Submission Checklist
- [x] any other edge cases you think of?
_besides players forgetting what email they used to login at Colonist, I'm thinking of email address that are way too long, ex. sampleaccount12345678901234567890@gmail.com might overlap on smaller screens like in Mobile but not alot of players do this so it might not that be relevant_
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77 @Mau-MD

**Comment by samgawaran** [comment]
Creating an implementation in a few hours if there are no major requested changes.

**Comment by demiculus** [comment]
Do something similar to this: https://i.imgur.com/hiUgwQw.png

**Comment by samgawaran** [comment]
Old Iteration: 

## Proposed
![image](https://user-images.githubusercontent.com/90673012/205983330-2a5fde7c-d69b-40e7-9ee7-fe97d59a7a85.png)

- Change `Membership` to `Settings` since Accounts has already been added there.
- Add `Connected with...` to make it more straightforward. I think leaving them as Connect might make some players who don't know the icons of Discord or other social logins be confused.

### Main Flow
![image](https://user-images.githubusercontent.com/90673012/205985010-d56af95b-7f0a-46e7-b8d8-cad6153cbf04.png)

- To unlink an account, the player needs to click a `Connected` account and confirm on a popup
- An edge case is that people might forgot what email they used to login, but I'm not sure if we would show the email used by the player soI opted to add an asterisk like in MLBB for privacy if ever the player wants to unlink an account

### If only 1 account has been linked
![image](https://user-images.githubusercontent.com/90673012/205985805-bd89804d-a061-4552-9052-d8b3e5f80113.png)

- This is the default screen for most people. They can't unlink if there's only 1 email connected to their account
- for players who want to delete their accounts, they should go the usual way and contact support so we don't incentivize account deletion

**Comment by samgawaran** [comment]
Updated the `accounts` section. I retained the orange google icon for consistency since its what we use in the social login popup

**Comment by Mau-MD** [comment]
@samgawaran looking forward for implementation issue

**Comment by samgawaran** [comment]
Closing this issue, updated the images in the implementation issue here: https://github.com/colonistio/katan/issues/9207
