### ISSUE TITLE
Google Play Store Images

### ISSUE THREAD

**Issue by SimonH321** [colonistio/design#231]
## Description
We're posting Colonist mobile to the app store and want the layout to be ASO (app store optimized.) 

## Checklist
- [x] App Icon
- [x] Feature Graphic
- [x] Phone Screenshots
- Tablet Screenshots 
- [x] 7-Inch Tablet
- [x] 10-Inch Tablet 
- [x] Chromebook Screenshots

 ## Resources
### App Icon
**Current Design:** 
<img width="207" alt="Screen Shot 2022-12-06 at 12 29 02 PM" src="https://user-images.githubusercontent.com/112735505/205992488-1aece12e-4fe6-4466-b1fb-87b04e9d3029.png">
**Issues**: Pretty bland, white background is ugly. I remember seeing a gold version of this design which looked better. This is the most important part of the design by far so spend the most time on this. Please come up with a few versions that are different from each other so we can make sure we get it right
**Guidelines:** https://developer.android.com/distribute/google-play/resources/icon-design-specifications follow this for the icon
### Feature Graphic
**Current Design:** 
<img width="630" alt="Screen Shot 2022-12-06 at 12 33 07 PM" src="https://user-images.githubusercontent.com/112735505/205993269-7fde5ce3-b9f3-4d36-b099-e54a8f44e51a.png">
**Issues**: This is just a brand logo, feature design is meant to be an image that best conveys the value of the app. In our case, this should be a screenshot of the game that makes it look good
**Guidelines:** "Your feature graphic must be a PNG or JPEG, up to 15 MB, and 1,024 px by 500 px"
### Phone Screenshots
**Current Design:** 
<img width="691" alt="Screen Shot 2022-12-06 at 12 36 09 PM" src="https://user-images.githubusercontent.com/112735505/205993877-0342c549-5d7f-4272-b1c8-40dc1bb9efb5.png">
<img width="499" alt="Screen Shot 2022-12-06 at 12 36 16 PM" src="https://user-images.githubusercontent.com/112735505/205993888-ce135e21-3221-43e4-8024-f13e19cb8feb.png">
**Issues:** These are just screenshots of the current app. In the top right they have the "debug" banner which is not acceptable. Also it shows FPS in the bottom right of the 4th image. Content-wise these are good, but just cleaner figma renders of these images is what we want.
**Guidelines:** Technical: Upload 2-8 phone screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px
More detail: https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots
Note: Since our UI is currently still in the updating phase, this isn't the most urgent thing. Talk with Mau/Devyesh about the UI timeline.
### Tablet Screenshots
**Current Design:** N/A
**Issues:** N/A
**Guidelines:** 
**7-inch:** Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px
**10-Inch:** Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 1,080 px and 7,680 px
These should be the same as the phone screenshots, just rendered for a bigger screen. 
### Chromebook Screenshots
**Current Design:** N/A
**Issues:** N/A
**Guidelines:** Upload 4-8 screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 1,080 px and 7,680 px
I don't believe we're optimizing for Chromebook (at least not yet) and it's not required for us to post, so this is very much last priority. That said, it's important and should be included eventually. 

## Reviewers
@goktugyil @demiculus @JuanRoman77

**Comment by samgawaran** [comment]
for the app logo/icon. I'm recreating our logo since it doesn't follow the format Simon mentioned here: https://developer.android.com/distribute/google-play/resources/icon-design-specifications

I'll upload it to the drive after.
