### ISSUE TITLE
Mobile App Banners

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#234]
## Description

Create the necessary banners for the desktop version that announces our mobile apps. Note that they are beta version.

## Ideas from Feature Suggestion
- Get ideas from feature upvote

## Reviewer
@devyesh (he isn't on this repo so tag him in discord)
@JuanRoman77 @simon

**Comment by samgawaran** [comment]
Implementation issue is in here: https://github.com/colonistio/katan/issues/9299

closing this issue
