### ISSUE TITLE
Play Store Images - Feature Graphic 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#235]
## Summary
We're posting Colonist mobile to the app store and want the layout to be ASO (app store optimized.)

Posting my recommendation for the feature graphic we could use for the play store.

## Guidelines & Research
https://splitmetrics.com/glossary/google-play-store-feature-graphic-best-practices/
https://seoasoorm.com/feature-graphic/

- top apps usually change their feature graphic seasonally. Mostly for new app updates, I recommend we'd follow this structure when releasing large features
- They don't use a lot of longform texts, they only use text for short phrases like new July update
- Image screenshot usually follow the branding of the Feature Graphic
- We can also show a video preview for the game by attaching a link via Youtube

## Details
![image](https://user-images.githubusercontent.com/90673012/206706454-a99a17ff-1240-411f-84ab-497a1fd589b1.png)

### Recommended Designs
![image](https://user-images.githubusercontent.com/90673012/206711314-b28d0ddf-c0aa-48bc-9d4b-4b34a4decbe2.png)

- I'm not sure what would work best for the app store introduction, I leave this @SimonH321 but here are my suggestions, we can use something like "Now on Mobile!" or use a study that shows avatars, tiles and logo. (We can show the board, other pages the image screenshots for the next submission)

### Overlayed in Google Play Store
![image](https://user-images.githubusercontent.com/90673012/206711025-8988654a-aa75-41c9-92c3-2887fce6a1f7.png)

## Related Links
Master issue:
https://github.com/colonistio/design/issues/231

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@SimonH321 @JuanRoman77 @demiculus

**Comment by demiculus** [comment]
Comment on study 1: https://static.wikia.nocookie.net/meme/images/c/ce/You-dont-say-meme.png/revision/latest/scale-to-width-down/500?cb=20200518000007

Comment on study 2: Colonist is not lots of characters. Colonist is hextiles in the shape of a map and Settlement, City, Roads on top of them. Make sure your next submission shows these.

**Comment by demiculus** [comment]
What I would do is, remove the tiles from the logo. 
Do the map settlement stuff
Then add the logo somewhere it makes sense

**Comment by JuanRoman77** [comment]
Remove "Is now on mobile".
