### ISSUE TITLE
Play Store Images - Feature Graphic Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#236]
## Summary
Adjusted the designs based on the feedback given in the last submission, I tested out a bunch of our logos studies to make it more appealing

Guidelines and research are in here: https://github.com/colonistio/design/issues/235

## Recommended Design
![image](https://user-images.githubusercontent.com/90673012/207095363-a1d64ced-e47c-4d13-8562-b635661761d6.png)

- Modified our banner logo to remove gems and other details. I made the `C` pop out of the plank
- making it a bit diagonal looks better than it being straight: https://prnt.sc/ws-Lo_MR35P8 
- Show our main cards, dice, city, settlement road etc.
_- adjusted some details based on the feedback_
Cons:
- its a new logo design based from our main banner logo. I'm not sure if this would be okay to do since its a business decision for logo changes. Let me know your thoughts here @demiculus 

### Other Designs you would want to check:
![image](https://user-images.githubusercontent.com/90673012/207015446-05f8f630-5f65-41ae-aceb-e92e760f0f07.png)
Left side:
- Removed the `Now on mobile` retained everything else

Right side:
- Tried using the square logo. I can't make the hexs bigger since it would go off-screen
- the tiles use outdated designs, I need to adjust it to a new one. (will create an updated one as well)

### Overlayed in Playstore
![image](https://user-images.githubusercontent.com/90673012/207095580-d990c33d-798e-43ae-abc0-356eacf8a8d9.png)

## Related Submissions
- https://github.com/colonistio/design/issues/235

## Related Links
- https://github.com/colonistio/design/issues/231
- drive link: https://drive.google.com/drive/folders/1VVqmxiMve-xZjAbyJpbwOr5la1vJ8zto?usp=sharing

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by demiculus** [comment]
Make it as thick as the below one 

![image](https://user-images.githubusercontent.com/6215305/207041416-fabf95cd-ffe4-4329-bc0e-81e469498a8a.png)

**Comment by SimonH321** [comment]
They still look thrown together, while the left side is a nice group the right looks like a bunch of random icons sitting next to one another. Is there a way to stack them like the left where it makes more sense?

**Comment by samgawaran** [comment]
![image](https://user-images.githubusercontent.com/90673012/207100034-c1c738ef-463e-4d1d-a280-4d877e1e27c6.png)

something like these? its harder to stack them like those on the cards since they have different shapes but I tried to emulate it here. I'll update the links with these design if all is good

**Comment by samgawaran** [comment]
@SimonH321 I updated the image again, I checked and saw removing the cities makes it look more cohesive than the previous one.
![image](https://user-images.githubusercontent.com/90673012/207241777-d1eb17bc-427d-4b84-afb2-923b6f6a084b.png)


I uploaded both of these in the drive link
