### ISSUE TITLE
Play Store Images - App Screenshots

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#237]
## Summary
We're posting Colonist mobile to the app store and want the layout to be ASO (app store optimized.)

Posting polished app screenshots that we could use for the play store.

@SimonH321, I checked the guideline link you sent and I found out that the 1920x1080 size for the screenshots also works on tablets so this **submission is for both Mobile and Tablets**

## Guidelines
https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots

- Add taglines only if necessary to convey the key characteristics of the app or game. Taglines should not take up more than 20% of the image.
- For games, you must provide at least three 16:9 landscape screenshots (minimum 1920x1080px) or three 9:16 portrait screenshots (minimum 1080x1920px). Make sure that these screenshots depict the in-game experience so users can get a sense of what the gameplay will be like if they download and play
- Stylized screenshots that break UI across multiple uploaded images are allowed, but prioritize UI in the first three screenshots as much as possible.
_____

### Current App Screenshots
![image](https://user-images.githubusercontent.com/90673012/207084291-fbaa9124-9b93-4d7d-89d8-90f29a760457.png)

### Modified App Screenshots
![image](https://user-images.githubusercontent.com/90673012/207067327-a0b98302-0d2b-4732-bb20-85de9e5b58e9.png)

- 1920x1080 frame size but modified for mobile landscape
- follows the requirements stated by Simon here: https://github.com/colonistio/design/issues/231
- Links are in here: https://drive.google.com/drive/folders/1yMSY88jK-GoxGyPg3FXJ58Gx_MuilnOw?usp=sharing

### Creative App Screenshots (Recommended)
![image](https://user-images.githubusercontent.com/90673012/207072031-6fa94cbb-905e-44bc-962d-30d4d5c4a359.png)
![image](https://user-images.githubusercontent.com/90673012/207072070-7e822829-5e52-475a-b090-e13d6629e13e.png)

- I followed the creative guidelines stated in [here](https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots)
- all screenshots are 1920x1080
- Links are in here: https://drive.google.com/drive/u/0/folders/1XbyjYIxiP0p8q0yO4nWnjN4iMf6s9GPx

### Overlayed in Mobile
**Mobile Screenshot**
![mobile screenshot](https://user-images.githubusercontent.com/90673012/207083076-8eaaf944-1687-4b4b-9a00-a0ca52dfaf11.gif)
**Creative**
![creative](https://user-images.githubusercontent.com/90673012/207083064-026d6854-929e-4fc7-a08f-3993d8bfdd17.gif)

## Related Links
- https://github.com/colonistio/design/issues/231
- Drive Link: https://drive.google.com/drive/u/0/folders/1XbyjYIxiP0p8q0yO4nWnjN4iMf6s9GPx

## Submission Checklist
- [x] I followed all guidelines stated on the play store and recommended a design that utilizes the style allowed on the app page 
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by SimonH321** [comment]
These look amazing, only comment is could you change "optimized in mobile" to "optimized **for** mobile"?
