### ISSUE TITLE
Play Store Images - Finalized List

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#240]
## Summary
Compiled all of the requirements stated in this design issue: https://github.com/colonistio/design/issues/231 and listed out all approved designs in this submission

## Details
![image](https://user-images.githubusercontent.com/90673012/207486495-1c2997a7-db49-4d57-b003-ab02d0ce66a8.png)

- `App Icon` - Will submit both flat PNG and one with the background 
- `App Screenshots` - Images are 1920x1080 which are the recommended size for both Mobile and Tablet
- all of the designs shown here checked by Demi already.

### How it would look
![How it Would Look](https://user-images.githubusercontent.com/90673012/207486710-f0ce1c63-8627-4db0-b2f7-3d7fe1cb590d.png)

![Screenshots](https://user-images.githubusercontent.com/90673012/207486904-6e2bb64b-7687-4d87-9530-1705a5617ae4.gif)

## Related Submissions
- https://github.com/colonistio/design/issues/233
- https://github.com/colonistio/design/issues/235
- https://github.com/colonistio/design/issues/236
- https://github.com/colonistio/design/issues/237

## Related Links

- Google Drive Link: https://drive.google.com/drive/folders/1QfKxukb2MT7wpLC5fsbSCuja4PWdFWAP?usp=sharing
- https://github.com/colonistio/design/issues/231

## Submission Checklist
Write other checklists here

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@SimonH321 @demiculus @JuanRoman77

**Comment by JuanRoman77** [comment]
Why not something like this one 🤷🏻‍♂️
![square_logo](https://user-images.githubusercontent.com/73320460/207496178-8e651310-3316-4393-8a04-cbb526ebb2d7.png)

**Comment by demiculus** [comment]
> Why not something like this one 🤷🏻‍♂️

Too small on phone. Lets go with the above stuff, we'll optimize them later. We got a lot of other UX problems to be fixed first.

**Comment by SimonH321** [comment]
Could we get one more app screenshot? Maybe something from the store about maps or expansions... We need at least 4 images to be eligible for promotion

**Comment by SimonH321** [comment]
Also, none of these screenshots fulfill the requirements for 10-inch tablet screenshots (Upload up to eight 10-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 1,080 px and 7,680 px). Can you please create versions of the 3 (or 4, once the 4th is made) app screenshots so we can upload that?
