### ISSUE TITLE
Mobile App - Announcement Banners & Ads

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#242]
## Summary
The Mobile app is now available to download. We need ads in the website and our Social Media to let the players be aware of it

### Homepage Ads & Adblock
![image](https://user-images.githubusercontent.com/90673012/208403149-b9f394c0-e8c5-48f9-87c4-7f00927b29b2.png)

- Added the new AdBlock look, talked with Demi about this during our 1v1, and the template is already checked.
- Added an icon for the tablet as well

### Announcement Banner and Social Media Posting
![image](https://user-images.githubusercontent.com/90673012/208296837-bdaacaeb-3513-4cec-afa1-affe6b2dba45.png)
- For Social Media, I added the optimized Mobile screens so players can see how it would look. I can't put those in the banner due to the limited space. 

### Suggestion: Add a download banner or App Deeplinking
![image](https://user-images.githubusercontent.com/90673012/208298777-4c77ff20-6104-4fe0-88b3-2b18cdf8c5e7.png)

- for players who are playing on Mobile browser, add a banner at the bottom, games like slither.io does this to advertise their app on their mobile browser versions
- Better suggestion: when the player types colonist.io on their mobile browser. redirect them to the app store or play store depending on their OS

## Related Links
- https://github.com/colonistio/design/issues/234
- GDrive: https://drive.google.com/drive/folders/1cx9WwjNKGwmRVqaaxlqdi5FNUzwGpHkO?usp=sharing

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by demiculus** [comment]
1. Edit like this: https://i.imgur.com/EW2HeNy.png
2. https://i.imgur.com/zgalgED.png

**Comment by samgawaran** [comment]
The implementation issue is here: https://github.com/colonistio/katan/issues/9299

closing this issue now. Will re-open if there are other major comments
