### ISSUE TITLE
Discord Login - Announcement Banner & Ads

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#243]
## Summary
Along with Discord Integration, we will also be allowing Discord login for our players. This submission shows the recommended ad designs to advertise the new feature

Edited design based on Demi's feedback here: https://github.com/colonistio/design/issues/243#issuecomment-1359117904

### Homepage Ads & Adblock
![image](https://user-images.githubusercontent.com/90673012/210200589-b3462a0e-415e-4da6-9940-d81d7f2db53e.png)

### Social Media & Announcement Banner
![image](https://user-images.githubusercontent.com/90673012/210200688-663a802b-4827-47b6-b556-aa66832a2e15.png)

- Did the designs along with Mayla and Juan, we used the Discord icon with the hex bg like in our footer and the Colonist `C`
- adjusted design based on Demi's feedback here: https://github.com/colonistio/design/issues/243#issuecomment-1359117904 used the main_cta button style for Link

## Related Links:
- GDrive: https://drive.google.com/drive/folders/1FhmJb1R35WzN9ZUd1xsXr-PrBWH3Adcp?usp=sharing

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77 @demiculus @SimonH321

**Comment by demiculus** [comment]
Lets aim for v149
1. Mau is working on account linking and he'll probably be done by v149.
2. Instead of Login with Discord it should be link your discord account. Edit the texts accordingly. 
  - [ ] https://i.imgur.com/fknwtjH.png 
  - [ ] https://i.imgur.com/qnigDna.png
  - [ ] Same change to Instagram post
4. Create an implementation issue
  - [ ] It should send the players to account linking section https://github.com/colonistio/katan/pull/9311
5. Tell Logan to handle the issue

**Comment by demiculus** [comment]
@samgawaran I added these in edit the image so Juan can replace them.

**Comment by samgawaran** [comment]
`Old Iteration` 
## Design
### Homepage Ads & Adblock
![image](https://user-images.githubusercontent.com/90673012/208614574-9b80c24a-73f9-4126-954b-cfde3e7bea01.png)

### Social Media & Announcement Banner
![image](https://user-images.githubusercontent.com/90673012/208614601-4f1d65f5-c81e-4c4c-9073-ac772499892a.png)

- Did the designs along with Mayla and Juan, we used the Discord icon with the hex bg like in our footer and the Colonist `C`

**Comment by samgawaran** [comment]
added implementation issue here: https://github.com/colonistio/katan/issues/9423
