### ISSUE TITLE
Play Store Images - Additional Screenshots and Tablet Versions

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#244]
## Summary

We're posting Colonist mobile to the app store and want the layout to be ASO (app store optimized.) Added additional screenshots for mobile based on Simon's feedback here: https://github.com/colonistio/design/issues/240#issuecomment-1355683393

Posting polished app screenshots that we could use for the play store. Guidelines research is in [here](https://github.com/colonistio/design/issues/237)

for **10 inch tablets and up** I decided to go through the biggest screen size shown in the specs here: https://help.apple.com/app-store-connect/#/devd274dd925 which is `2732 x 2048` 

- Created 2 other screenshots for `Expansions` and `Fun Maps`
- Added its tablet counterparts 

### Phone Screenshots
![image](https://user-images.githubusercontent.com/90673012/208929856-68647560-de08-4001-bab8-17cf34c19a0d.png)

### Tablet Screenshots
![image](https://user-images.githubusercontent.com/90673012/208929898-8f665ec7-7a65-49c9-b5d3-1728650a14a7.png)
- tablet sizes are all `2732 x 2048` works on 12-inch, 10.5 and 9 inch tablets
- added a separate version for 11-inch tablets as it is not divisible to 2732 x 2048

### How it would look
![image](https://user-images.githubusercontent.com/90673012/208933956-307c3c8e-24fe-482c-bbc0-3a84f326421b.png)

## Related Submissions
- https://github.com/colonistio/design/issues/237

## Related Links
- GDrive: https://drive.google.com/drive/folders/1QfKxukb2MT7wpLC5fsbSCuja4PWdFWAP
- https://github.com/colonistio/design/issues/240
- https://github.com/colonistio/design/issues/241
- https://help.apple.com/app-store-connect/#/devd274dd925

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by JuanRoman77** [comment]
Make the order of the images be:
1. Friends
2. Leaderboards
3. Optimized
4. Expansions
5. Maps

----

Put the end game screen image in the Leaderboards image
![image](https://user-images.githubusercontent.com/73320460/209289326-1bc583a3-d618-4cbb-b217-b5865770605d.png)

----

Remove background
![image](https://user-images.githubusercontent.com/73320460/209289406-7f3b7a4c-b7d8-457e-b7e9-d05b643e8a4e.png)

----

4th image should say `Try out Expansions...` and 5th image should say `...and tons of Maps!`
![image](https://user-images.githubusercontent.com/73320460/209289522-784e518f-e1ae-460b-bbaf-edbddb6ee3c3.png)

----

Add a different image here. Options: room or profile (either history or ranked section. Ranked might look better)
![image](https://user-images.githubusercontent.com/73320460/209289758-b55b3386-6dc3-4d91-bf30-d23678c55229.png)

**Comment by samgawaran** [comment]
closing this issue, updated one is here: https://github.com/colonistio/design/issues/251
