### ISSUE TITLE
Blog - Catan House Rules Design Submission 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#245]
## Summary
We will be launching a blogpost that explains the fun rules we have in the game. 

This submission shows the recommended design I suggest for the blog post.

### Studies
![image](https://user-images.githubusercontent.com/90673012/208956974-7b644db9-225a-4299-9e9b-c5e1a159f2d5.png)

- I use `icon_book` for the rules icon. and added the check and x marks like those shown [here](https://prnt.sc/xryAXrvu52mP)

### How it would look
![image](https://user-images.githubusercontent.com/90673012/208957099-7ff9e886-efba-4cc0-b4c6-0bf30068c877.png)

## Related Links
- GDrive: https://drive.google.com/drive/u/0/folders/1rB3BeEe3PLbBtIbpcFp6iqQBhVelwt_H
- https://github.com/colonistio/design/issues/238

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77 @demiculus @SimonH321

**Comment by JuanRoman77** [comment]
- Not the wavy one
- HOUSE and RULES should be the same size, that's the term to emphasize.

**Comment by samgawaran** [comment]
> HOUSE and RULES should be the same size, that's the term to emphasize.

![blog_besthouserules_edit](https://user-images.githubusercontent.com/90673012/209665628-d33c0568-9b2f-41a3-b82c-2b1b4a6b0d2c.png)

Added this version in the gdrive link here: https://drive.google.com/file/d/10dJ160UM1zoXrnqg0j0qh_nIldMOtfkZ/view?usp=sharing
