### ISSUE TITLE
Mobile App - P0: How other Games Look

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#247]
## Summary
https://discord.com/channels/605233308577562643/1054792032117329951/1055244619178315888
The team decided to focus more on the portrait version for our mobile app. Attached in this submission is a compiled list of popular games that we can draw inspiration from. 

I prioritized games that are `Fun` & `Social` to fit our brand. and also `Board` and `Dice` games to see how games with similar mechanics like ours fare as well. 

## How other games look
- Games are tested on an Android phone
- Rating besides the names are the rating scores from Google Playstore

### Candy Crush |  4.6/5
![image](https://user-images.githubusercontent.com/90673012/209149077-0c9f9cef-4169-472a-985e-1cf3430fe00d.png)
- over a billion downloads since 2012
- can play as guest, can also login using email or facebook
- Huge campaign mode with over 12000+ levels as of July 2022

### Chess.com | 4.7/5
![image](https://user-images.githubusercontent.com/90673012/209150886-eb29605a-664b-4081-91c5-01e59b1a4459.png)
- 10 million downloads since 2010
- Extensive AI choices from low ELO to Grandmaster
- Has a Desktop version, allow adding of friends and subscriptions

### Scrabble GO-Classic Word Game | 3.9/5
![image](https://user-images.githubusercontent.com/90673012/209157321-8653f40c-f354-46d4-8960-98cafb52365a.png)
- over 10 millions downloads since 2017
- official scrabble board game
- has a lot of ads and UI could be better
- allows landscape mode but lackluster in implementation

### Roblox | 4.3/5
![image](https://user-images.githubusercontent.com/90673012/209277481-1cb33baa-0da5-4c1d-a7a2-d91184599ab4.png)
- over 500 millions downloads since 2014
- requires 2FA to log-in
- Menu is locked on portrait mode but the games made in Roblox can either be Landscape or Portrait
- Basic UI. Also has a desktop app
- Extensive social system, you can add friends and message them inside the app

### Clash of Clans | 4.6/5
![image](https://user-images.githubusercontent.com/90673012/209148806-af538f54-c5cd-4924-828f-1e7e01450dd3.png)
- 500 million downloads since 2013
- allows account linking of supercell ID and Google Play 
- Tower defense and conquering game which you can also add friends
- intuitive touch controls

### Brawl Stars | 4/5
![image](https://user-images.githubusercontent.com/90673012/209162488-bf97e93c-5e2f-4667-809c-f5e59b9377b8.png)
- over 100 million downloads since 2018
- shooter game with a lot of game modes and special events
- same developers of Clash of Clans so a lot of popups and modules looks the same

### Catan Universe | 3.4/5
![image](https://user-images.githubusercontent.com/90673012/209152352-07345e2d-5c8f-4127-aa77-a1a9435fabc4.png)
- over a million downloads since 2017
- top competitor for Catan-based mobile game
- Has a lot of issues hence the low rating. Also has a desktop version
- 
### Angry Birds 2 | 4.3/5
- over 100 million downloads since 2015
- gorgeous graphics and UI
- allows account linking from facebook and google play store
- extensive customization of player avatar

### Risk: Global Domination | 4/5
![image](https://user-images.githubusercontent.com/90673012/209160894-a588f2b7-64e6-4f1d-8e78-fe15e6e4857e.png)

- over 10 million downloads since 2017
- have a lot of game modes, can play ranked or with friends
- each game mode has a ranked/unranked version
- offers a lot of playable maps

### Uno! | 4.6/5
- over 100 million downloads since 2019
- official mobile app version of the Uno card game
- lot of social features, players can add friends and message them in the app
- several game modes to choose from, game modes are in the landing page

### Domino Go | 4.6/5
![image](https://user-images.githubusercontent.com/90673012/209169048-55e68f83-fc61-49d6-8915-146364264275.png)
- competitive 1v1 game mode
- doesn't allow pinching to maximize the size of the board. the board is always maximized on the screen
- you need to play a certain number of games to unlock other game modes

### Farmville 2: Country Escape | 4.5/5
![image](https://user-images.githubusercontent.com/90673012/209185771-ebc99a61-87d9-4509-a74f-9b20c24180d2.png)

- over 50 million downloads since 2014
- same developer with Word With Friends
- intuitive touch controls
- daily challenges keeps you engage 

### Marvel Contest of Champions
![image](https://user-images.githubusercontent.com/90673012/209281885-80f15e98-4371-48a9-b398-2e983072fd3d.png)

- over 100 million downloads since 2014
- Tekken-like PVP game with a lot of touch controls
- Need to play tutorial to unlock the whole game
- UI is a bit outdated or out of our brand

### Genshin Impact | 4.3/5
![image](https://user-images.githubusercontent.com/90673012/209287360-ebef0691-e540-4e3d-b5be-167ed0e981e1.png)
- over 50 million downloads since 2020
- earned 17 million dollars in the app store as of September 2022
- Multi-compatible, available on almost all platforms, PS5, Switch, Desktop, Mobile etc.
- MMORPG/Gacha Game which needs a huge chunk of data to download 20GB file size
- Amazing graphics and UI
- didn't finish the download as it my CP's memory is full so gameplay screenshots came from the web. 

### Fate / Grand Order | 3.9/5
![image](https://user-images.githubusercontent.com/90673012/209290250-ca8b920a-decf-47ab-bf8e-150fbaab5398.png)
- over 1 million downloads since 2018
- earned 13 million dollars in the app store as of September 2022
- Hero-summoning game/Gacha game needs atleast 500MB of additional resource to play the game
- game based from the popular visual novel game
- Lackluster UI. Basic UX
- 

### Temple Run 2 | 4.2/5
![image](https://user-images.githubusercontent.com/90673012/209170645-6ad729d4-db87-4bc3-bb45-6f5037dd8e2d.png)

- over 500 million downloads since 2013
- intuitive touch controls
- has motion controls, when you move right, the game also leans on the right and vice versa
- can connect your facebook account

### Board Kings | 4.6/5
![image](https://user-images.githubusercontent.com/90673012/209171537-5e08767e-ea7f-483e-a5d2-239b47429a85.png)
- Gorgeous Art
- UI is kept to a minimum, a lot of actionable buttons are placed inside the board
- I didn't understand the gameplay much. No landing page or other game modes

### Pokemon Go | 3.9/5
![image](https://user-images.githubusercontent.com/90673012/209172155-c2334b61-48fb-45bf-8e51-5b86dd94d20c.png)
- over 100 million downloads since 2016
- intuitive touch controls
- gorgeous art
- a bit buggy, it could be the cause of the low rating
- very customizable avatar

### Ludo Club | 4.3/5
![image](https://user-images.githubusercontent.com/90673012/209153402-96d62748-533f-4eaf-a83a-fb4e7f8123b7.png)
- over 100 million downloads since 2017
- doesn't allow pinching to maximize the size of the board. the board is always maximized on the screen
- Game modes are on the landing page
- Allows account linking

### Match Masters | 4.5/5
![image](https://user-images.githubusercontent.com/90673012/209154358-9a07f8d4-c55a-40d6-a16b-aa8dc86bf84c.png)

- over 10 million downloads since 2017
- Gorgeous graphics and UI
- Game modes are unlocked by playing set of tutorials
- can add friends and play with them, game is derived from Candy Crush with more competitive mechanics

### Word with Friends 2 Classic | 4.2/5
![image](https://user-images.githubusercontent.com/90673012/209156456-0c8f5b2b-8c92-479a-bb6b-ecbd1f26ad57.png)
- over 10 million downloads since 2017
- game based from Scrabble
- has a lot of ads. UI isn't that pleasing as well

### Royal Match | 4.7/5
![image](https://user-images.githubusercontent.com/90673012/209279927-76fc6a43-35d1-4ade-895b-7de6aea24f76.png)

- over 10 million downloads since 2021
- similar to Candy Crush but with more PVP features, contains rankings and leaderboards and guilds
- Seamless and quick tutorial. Big campaign mode with aesthetic rewards

### Coin Master | 4.3/5
![image](https://user-images.githubusercontent.com/90673012/209283201-fb015629-8bbf-4e70-8a75-250f5683e769.png)

- over 100 million downloads since 2016
- Clash of Clans like game but simplified and puts an emphasis on roulette
- Pleasing graphics and UI. easy to understand tutorial and has a lot of touch controls
- A bit forceful in the player signing in to facebook, a lot of popups once they enter

__________________________

## Findings
- `4` out of 23 games allow hybrid orientation, `11` are landscape only while `8` are portrait only
- Board games and casual games uses a lot of intuitive touch controls. Pinching, sliding, dragging can be use to improve the experience in our app
- games that have low ratings, CU, and Pokemon Go have a lot of issues. This could be the reason why it has a low rating
- All of the games contain in-app purchases
- almost all of the games allow players to link their facebook accounts
- Games that feature a lot of game modes usually show the game modes in the homepage either via cards or icons
![image](https://user-images.githubusercontent.com/90673012/209290521-5b5976a8-6f5e-405f-bc78-9fd960642f56.png)
- added games from this data. Most of the higher earning games are `Gacha-based` games or games that has a lot of coin purchases
- Some of the top games there are restricted in my region (Philippines) so I can't download it

## Related Links
- https://github.com/colonistio/design/issues/226

## Submission Checklist
- [x] have you tried to check other games via gameuidatabase?
- I checked some games in the gameuidatabase but I think that the mobile games there are more of a single player experience compared to multiplayer like in all of the games I tested out here.
- [x] Have you tried asking openchat.ai? 
- Yes, but the problem is that a lot of the stuff the AI chatbot mentioned isn't factual, it mentioned Fortnite but we can't play Fortnite on the mobile app (or its not  available for Android) and other stuff.  
- [x] what are the next steps?
- develop the UI further. Focus on exploring the portrait version as discussed in the discord channels
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

**Comment by samgawaran** [comment]
Added 6 more games. 

- Roblox
- Royal Match
- Marvel Contest of Champions
- Coin master
- Genshin Impact
- Fate/Grand Order

**Comment by Jakayla13** [comment]
+*********59
