### ISSUE TITLE
Subdivision Rankings - Design & Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#248]
## Summary
We will be launching sub-division to improve ranked matchmaking. This submission shows the suggested design that we could use for the subdivision icons for the game

_Edit: adjusted design based on Juan's feedback in the comment thread below. https://github.com/colonistio/design/issues/248#issuecomment-1363704115_

## How other games look
![image](https://user-images.githubusercontent.com/90673012/209474015-caa39bcb-0bec-4915-889e-cf0e7deade02.png)

- games either use I-IV or I-V for their tiers
- All of them show sub-divisions as Roman Numerals

## Recommended Design
![image](https://user-images.githubusercontent.com/90673012/209473814-f3e6f223-ad5e-43e3-893f-b8b084be0158.png)

- White is simple and doesn't take too much the attention away to the divisions itself
- Added a dark stroke besides the letter. I feel its a little bit flat without it (will show some screenshots)
- based on feedback, I used the same Gilroy font we're using. just added the strokes to differentiate it with the normal text. For implementation we can just state the font weight to be `extra-bold` to make it more "simpler"

### Leaderboards & Profile Ranked
![image](https://user-images.githubusercontent.com/90673012/209473835-74d6dba7-66ab-4db1-b371-8af13059b85f.png)

### End Game Screen
![image](https://user-images.githubusercontent.com/90673012/209473876-8265902d-02de-4202-8e34-1df030db0b99.png)

- Based on Juan's suggestion, I'd recommend using our normal text style and just add `subdivision#` below the division icon since it would be redundant to show alot of Bronze III, Bronze II, Bronze I etc. just having the I, II, III should be enough 

### Mobile Versions
![image](https://user-images.githubusercontent.com/90673012/209473910-aa2720f2-3b0c-4d59-a7d9-3359038052ac.png)

- mobile versions of its recommended desktop counterparts

## Related Links

- Gdrive Link: https://drive.google.com/drive/u/0/folders/102RyzIvoWBb3y1_IRCYJxb1GCP2Adzzp

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JeffdEon @JuanRoman77

**Comment by JuanRoman77** [comment]
These look really bad 
![image](https://user-images.githubusercontent.com/73320460/209295085-2307ea71-c613-4aa8-a429-2f3ea9b2c6c3.png)
Let's just go with simple text instead, as in  
![image](https://user-images.githubusercontent.com/73320460/209295169-7afbad56-4c01-44d0-9765-c8f0cd864607.png)

**Comment by samgawaran** [comment]
`Old Design from Iteration 1`

## Recommended Design
![image](https://user-images.githubusercontent.com/90673012/209270976-d19b0e74-f60e-4651-aa1d-d1528824fc39.png)

- White is simple and doesn't take too much the attention away to the divisions itself
- Added a dark stroke besides the letter. I feel its a little bit flat without it (will show some screenshots)
- uploaded 2 variants in this drivelink: https://drive.google.com/drive/u/0/folders/102RyzIvoWBb3y1_IRCYJxb1GCP2Adzzp one that shows centered and left-aligned

## Overlayed in Scenarios
### Leaderboards
![image](https://user-images.githubusercontent.com/90673012/209271902-dc5c6eb6-a269-456a-9095-9e541c4c61cf.png)

- compared the recommended design to other looks. Gold is good but there's contrast issues

### End Game Screen
![image](https://user-images.githubusercontent.com/90673012/209272036-ef4df4b1-62d4-40d5-9b5c-ae11666363bd.png)

- proposed removing the division names and instead add the subdivision icons instead

### Profile
![image](https://user-images.githubusercontent.com/90673012/209272510-0bfd3cd9-36ac-427f-baa8-1482c54ce3ac.png)

- didn't do the besides the division icon as games like Mobile Legends add them at the bottom as well. 

### Mobile Versions
![image](https://user-images.githubusercontent.com/90673012/209275411-c203d066-9d40-4e0c-8f75-510014a8485e.png)

- mobile versions of its recommended desktop counterparts

**Comment by samgawaran** [comment]
Updated the submission based on Juan's feedback. Give a thumbs up if all is good so I can create an implementation issue

**Comment by demiculus** [comment]
These still look bulky 
<img width="121" alt="image" src="https://user-images.githubusercontent.com/6215305/209532202-f69e7fc4-f3d4-4805-ac4f-919a602cd6ca.png">

**Comment by JeffdEon** [comment]
I would also add it here

<img width="386" alt="image" src="https://user-images.githubusercontent.com/58959537/209557951-03e63b27-ea7b-4cdc-8419-5dc0c6703a59.png">

**Comment by JeffdEon** [comment]
In my current branch it looks like this with the most up to date assets

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/58959537/209558001-a19e4821-b508-4921-9e40-907c7fd3c6ee.png">

**Comment by JuanRoman77** [comment]
@samgawaran They need to be smaller and less bulky. Closer to just regular text, but maybe bold.

**Comment by samgawaran** [comment]
`Old Iteration 2`

## Recommended Design
![image](https://user-images.githubusercontent.com/90673012/209473814-f3e6f223-ad5e-43e3-893f-b8b084be0158.png)

- White is simple and doesn't take too much the attention away to the divisions itself
- Added a dark stroke besides the letter. I feel its a little bit flat without it (will show some screenshots)
- based on feedback, I used the same Gilroy font we're using. just added the strokes to differentiate it with the normal text. For implementation we can just state the font weight to be `extra-bold` to make it more "simpler"

## Overlayed in Scenarios
### Leaderboards & Profile Ranked
![image](https://user-images.githubusercontent.com/90673012/209473835-74d6dba7-66ab-4db1-b371-8af13059b85f.png)

### End Game Screen
![image](https://user-images.githubusercontent.com/90673012/209473876-8265902d-02de-4202-8e34-1df030db0b99.png)

- Based on Juan's suggestion, I'd recommend using our normal text style and just add `subdivision#` below the division icon since it would be redundant to show alot of Bronze III, Bronze II, Bronze I etc. just having the I, II, III should be enough 

### Mobile Versions
![image](https://user-images.githubusercontent.com/90673012/209473910-aa2720f2-3b0c-4d59-a7d9-3359038052ac.png)

- mobile versions of its recommended desktop counterparts

**Comment by samgawaran** [comment]
closing this issue, as the thread is getting long. We can continue here: https://github.com/colonistio/design/issues/249
