### ISSUE TITLE
Adblock Revamp - Update Old Adblock Designs

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#250]
## Summary
We created new adblock designs to improve the UI quality but a lot of our old assets doesn't follow the same format that was approved.
https://discord.com/channels/605233308577562643/790772223358402571/1057056889948602378

This submission updates all of the adblock designs we have here: https://github.com/colonistio/katan/tree/development/code/client/static/images and suggests a standard file naming.

Currently we either use the naming `ab_(design)` & `adblock_(design)` for our adblocks
 
### Old Designs
![image](https://user-images.githubusercontent.com/90673012/209650382-986ca37d-8666-4f0d-8815-ba3a2ac81d40.png)

### Updated with the new template
![image](https://user-images.githubusercontent.com/90673012/209650475-8e9e761b-e518-4e26-8169-9c0daca6bb7c.png)

- I updated everything for now besides ad_contributor 2 since that whole layout makes it hard to work on the new template and we already have ad_contributor 1, I'm not sure what else should we delete but here's what I suggest:
- Remove this following adblocks as they are outdated anymore. (ex. remove old banners in the database for ranked season 1 and add them in an archive instead)
    - `ab_contributor2`
    - `adblock_ranked_banner`
    - `ab_cnk`

## Related Links
- Discord: https://discord.com/channels/605233308577562643/790772223358402571/1057056889948602378 
- GDrive Link: https://drive.google.com/drive/u/0/folders/19l0wiPI4NkfceuTN42OFGEls66bG0Rja

## Submission Checklist
- [x] all of the adblock images are compressed and follow the suggested naming conventions in the static file naming md
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77 @demiculus

**Comment by demiculus** [comment]
1. All names should be `ab_(design)` format
2. Do these changes
![image](https://user-images.githubusercontent.com/6215305/209965235-ed760651-d3af-4518-8ca6-fbf766af16ad.png)

3. Create an implementation issue

**Comment by samgawaran** [comment]
done, created the implementation issue here: https://github.com/colonistio/katan/issues/9415
