### ISSUE TITLE
Playstore Images - Iteration 2 & Playstore Resizing

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#251]
## Summary
- Adjusted the design for the play/appstore images based on Juan's feedback here: https://github.com/colonistio/design/issues/244#issuecomment-1363684227

- During importation of the screenshots in the playstore by Devyesh the size was a bit off. It looked like this: 
![image](https://user-images.githubusercontent.com/90673012/209896126-fa973621-1d31-45a7-bf21-23a2340c1c5b.png)

which looks a bit cropped so I asked him of the exact dimensions we are uploading it. Those said dimensions are the sizing used in this submission.

### Old
![image](https://user-images.githubusercontent.com/90673012/209896489-d12c9a3f-9fb8-4ab6-977d-fdb62a30708e.png)

### New
![image](https://user-images.githubusercontent.com/90673012/209896522-e4007f66-0050-4be7-aef2-bccc3d84a44a.png)

- Adjusted the copy and added additional screenshots.
- followed the feedback here: https://github.com/colonistio/design/issues/244#issuecomment-1363684227
- sizing are as follow:
     - 2208x1242
     - 2668x1242
     - 2796x1290

### How it would look
![image](https://user-images.githubusercontent.com/90673012/209897908-8b2cf57d-13ca-421f-9f54-ab8535fcc386.png)

## Related Links

- https://drive.google.com/drive/folders/1IbgkCoDWFUAxqGTGUTAdG5envqOcVU8l

## Related Submissions

- https://github.com/colonistio/design/issues/244

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by samgawaran** [comment]
tagging Devyesh via Discord

**Comment by SimonH321** [comment]
Images are updated in the playstore
