### ISSUE TITLE
Mobile App - Play CTA Studies + Popup, Menu Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#254]
## Summary
Did some changes based on feedback here: https://github.com/colonistio/design/issues/253#issuecomment-1372116616 from Footer Menu to what our header will look like

focused first on the Homepage. Creating a couple more studies that uses our button style and such, and created samples using our popup for scenarios when a player is on a winning streak/hardcore

### Play CTA Studies
- I left out editing the header part for now. This focuses more on the Play CTA and how players will enter the game
- Studies with open space can have some additional elements we can explore later on
- Early mockups only. Will expound on promising studies after
- `Play` is near wherever the game mode selection is.

![image](https://user-images.githubusercontent.com/90673012/210938407-ebaa7dac-2c29-4bbc-abb2-332461e2e85c.png)

`A` - From iteration 1, players can click on `Play` to matchmake with the current selected game mode. (Studies with game mode popups will have a seperate submission or added later on here.)
`B` - Based from MMORTS games like Mobile Legends, infobox provides a description for new players which can be removed later on after a player plays an X amount of games. Ranked Game Modes also show their current division, rating and progress bar. Play CTA uses the game mode name as title
`C` - Based from Clash Mini, similar to A but the game mode selection is on top. Shows the amount of players in that game mode beneath the name
`D` - Slide/Carousel type, infobox provides instructions on how to use the feature which can be removed after X amount of games. Ranked Game Modes show division icon, rating and ranking on global leaderboards. Clicking on the ranking redirects them to leaderboard page
`E` - From desktop version, removed ads from previous iteration and improved the spacing. Play Unranked CTA will show a popup of all unranked game modes. Clicking on a ranked game card will begin matchmaking

### Popup & Menu
- some elements from iteration 1 like the ads and membership are moved here to increase space for more important things in the homepage.
- Added a popup scenario for players who always win or just simply addicted with the game
![image](https://user-images.githubusercontent.com/90673012/210938758-80225289-fa5e-42dd-b32c-ccbb483b5b1f.png)

`Hardcore Player Popup` - After winning X amount of games, this popup will show after a game. Advertises more competitive game modes like 1v1, this wont show if the player plays 1v1 already
`Non-Member Popup` - similar to the ABTest in our desktop version. Remove the membership banner from the homepage and move it here. this can show after initializing the game or after each game as long as the player isn't a member
`Menu` - adjusted based from feedback, removed patch notes and make it whole screen. I made the buttons bigger so there won't be alot of open space but we can revert it to smaller icons once we added additional features later on. (ex. Account linking can be shown here similar to other games)

## Related Submissions
- https://github.com/colonistio/design/issues/253

## Related Links
- https://github.com/colonistio/design/issues/226

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77

**Comment by demiculus** [comment]
1. Bottom menu from left to right Leaderboards, Lobby, Home, Store, Profile
2. Move the menu button to the top right just like before
3. Iterate on D1 just like how the video says

**Comment by samgawaran** [comment]
closing this issue, latest one is in here: https://github.com/colonistio/design/issues/256
