### ISSUE TITLE
Mobile App: Homescreen & Game Modes

### ISSUE THREAD

**Issue by huaniebun** [colonistio/design#257]
### **Summary**
Designed login screen and 2 flows for home screen and game modes (on different pages vs same page)
P.S. I also included a new font style - more for eye-catching display or areas that require attention like buttons and title of game modes.

### **Log in Screen**
Included login options via google, apple and discord as well as option to play as guest
Game board on top half of screen to give some context to player who are new to colonist

![Signin Screen](https://user-images.githubusercontent.com/98397645/211736971-c1a0a5dd-6e32-45d0-8761-f55f72a40ab4.png)

### **Homescreen & Game modes on different pages**
Having fewer buttons on each screen allows players to focus on which decision to make without feeling overwhelmed
- Win rates & Total games played at top right of screen: easy tracking on player game stats
-  Coin at top center of screen: easy tracking of amount of coins player has + easy access to store when "add coins" button is clicked
- Profile and Karma at top left of screen: helps players to know if they are logged in, what's their username and their karma + easy access to their profile for overview and customisation of username/colour/avatar etc.
- Rules at bottom right of screen: helps new players to understand and know how to play the game
- Settings at bottom left of screen: easy toggle of audio/music etc settings 

**Homescreen (sign-in & guest)**
Gameboard should include animation (same as desktop) to give context to players what the game is about
3 main CTA buttons: helps players to quickly decide what they want to do in the game

![Simple Mainscreen v1 (1)](https://user-images.githubusercontent.com/98397645/211737862-91f88c61-adf9-431b-adef-7e1fe4b1e2e8.png) ![Simple Mainscreen-Guest v1](https://user-images.githubusercontent.com/98397645/211737489-ff22e520-4081-46de-b0dc-5037652ecf35.png)

**Game mode screen (carousel)**
Upon clicking play, players will go to gamemode selection screen and swipe to select the game mode and type accordingly.
Allows players to focus on each game mode and select after swiping through the all the game modes.

![inactive ranked v2](https://user-images.githubusercontent.com/98397645/211742408-d7f6443a-e70a-4c6d-afbf-4fb805334561.png) ![Gamemodescreen v2](https://user-images.githubusercontent.com/98397645/211738193-e60508e7-c4e3-46a7-8dad-92d81589338b.png) ![Gamemodescreen v2 (1)](https://user-images.githubusercontent.com/98397645/211738235-775a90d5-bdd0-4c92-81e3-bee7ed20c600.png)

**Alternative Game mode screen (list)**
Allows players to have an overview of all their options before selecting one to play.

![SelectBotGame](https://user-images.githubusercontent.com/98397645/211740316-73311792-4b44-444e-a172-cb65ab8240d8.png) ![SelectRanked](https://user-images.githubusercontent.com/98397645/211740338-514ec47d-b4fa-4510-8c78-bfb1f8c19712.png) ![InfoPopup](https://user-images.githubusercontent.com/98397645/211742919-42615ca8-2d8e-45f7-a985-4add329422ec.png)

### **Homescreen & Game mode on same page**
Bottom Navbar: help players to navigate between different pages without having to go back to the homescreen
Players can go straight into game mode selection and start game
Carousel option also includes creating game 

![Mainscreen w Bottom Nav V2](https://user-images.githubusercontent.com/98397645/211740966-4643aed2-4e94-4122-b004-07d14e47ad73.png) 

### **Decision to make**
- homescreen & game modes - **different pages** or **same page**
- game mode selection - **carousel** or **list**
- feedback on designs

@demiculus

**Comment by samgawaran** [comment]
Hey Huan! I think Steve commented on your designs here: https://github.com/colonistio/design/issues/256#issuecomment-1378719336

some comments:
- as far as I know we're focusing on `carousel` types moving forward so the `list` types should be banked somewhere, I created this dump https://github.com/colonistio/design/issues/260 and post some of the ideas here :)
- the details in this info popup is better than our current one in my opinion https://prnt.sc/cCvcYqF6eXHj. But I suggest using our current color scheme in the website for now so the other guys have lesser decisions to make
- `homescreen & game modes - different pages or same page` - most mobile games that have game modes show their game modes in the homepage of their game so I think its a good rule of thumb to follow it, also, less clicks if its on the homepage already.

Suggesting of putting this screen/ideas in the idea dump: https://github.com/colonistio/design/issues/260
- game info popup: https://prnt.sc/6b_ws6BS9hyj
- Play 5 games to play ranked : https://prnt.sc/VoWmTU8r0Zha
- game mode list type: https://prnt.sc/z4T5WqOhNPWh

**Comment by demiculus** [comment]
@woodifred @5econds review please
