### ISSUE TITLE
Mobile App: Homepage (Game Mode Selection) Iteration 2 - Screen & Scenarios

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#258]
## Summary
Based on the feedbacks given on https://github.com/colonistio/design/issues/256 I focused on Study 2 and how it can be optimized further.

### Comparison
![image](https://user-images.githubusercontent.com/90673012/211970672-3da5f0c7-0bf5-4d09-abf7-1bd23e933f24.png)

`Header:` - I agree with what steve said [here](https://github.com/colonistio/design/issues/256#issuecomment-1378719336) but atleast one of them should be `Karma` for consistency. I'll expound on this more on a separate issue discussing headers
`Reason for moving toggle on top of game modes:` - Some players have larger fingers than most and having the toggle near the carousel might cause accidental clicks. 

### Game Mode States
![image](https://user-images.githubusercontent.com/90673012/211972008-917df10a-5ee1-4bab-914b-dbdaa373a8ae.png)

### Clicking on Info Icon
![image](https://user-images.githubusercontent.com/90673012/211973486-69478db0-a3e8-47ec-bd88-4f09df518d7e.png)

`Unranked Games` - We don't have this popup but I included it here since this is easy to implement. 

### Game Modes without Ranked/Unranked
![image](https://user-images.githubusercontent.com/90673012/211977798-2e65d511-2e22-4d47-8e93-31edcf137e54.png)

`Create Game` - Copy and icon is subject to change. Adding some ideas in a mobile idea dump for copy ideas. 
`Why is create game in game modes?` - some players may not know that they can create or host their own game in the lobby so adding it in the carousel is ideal. Clicking on this will redirect them to the Create Room screen  

### Clicking on `Play`
![image](https://user-images.githubusercontent.com/90673012/211987682-5498630f-2611-4d8d-9b38-7ca8c512af82.png)

`Play vs Bots` - Clicking on play directs them straight to the game

### Carousel Animation

![Sliding Animation (2)](https://user-images.githubusercontent.com/90673012/211977126-7d2e23b0-449a-4f83-b5d3-b5a0e88063c3.gif)

Try it yourself:
https://www.figma.com/proto/4sPdkWQrqoiGgFkMLtVSqr/Colonist-UI%2FUX-App?page-id=397%3A55617&node-id=426%3A54972&viewport=378%2C-859%2C0.5&scaling=contain&starting-point-node-id=426%3A54972
- for better viewing experience. Download the Figma app on Android or iOS
- animations are not final. but this style is the basis for future iterations and optimizations

## Decisions to Make
- Removing the toggle for game modes without ranked/unranked
- Create Game will have both CTAs in Home and Lobby page
     - Create Game inside the Lobby is a must. All of the games inside the lobby are from players who like to host custom games and with friends. 
- Leave the info popup as is for MVP
    - can be further optimized down the line. We can focus more on optimization of more critical pages 

## Related Submissions
- https://github.com/colonistio/design/issues/256

## Related Links
- https://github.com/colonistio/design/issues/226

## Submission Checklist
Write other checklists here

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @woodifred @5econds

**Comment by samgawaran** [comment]
_Edit:_ Added the scenario when a player clicks on `Play`

**Comment by JuanRoman77** [comment]
About carrousels:
1. The UX is awful. You don't know how many options there are, you can't compare the options at the same time, you take longer to get where you want, and swapping fast enough will make you skip the option you want and having to go back or keep going until you get back to the mode you want. 
2. We currently have 9 total game modes, and might add more in the future. Think long term. A carrousel with this amount of options is ~~a pain in the ass~~ really bad UX.
3. Specifically for the Lobby, I don't think a carrousel is a good idea. Expansion games represent less than 5% of the Lobby games. This means that most of the time there won't be any Expansion room to join, leaving those tabs empty, and making the player spend more time waiting for a lobby instead of joining something else in the list (current user behavior).

**Comment by samgawaran** [comment]
> We currently have 9 total game modes, and might add more in the future. Think long term

I get what you mean with the cons of the `carousel` but what I see on other games are mostly cards like in the `Play` CTA in our Desktop and most of those games uses landscape orientation so they have more space to show it. 

furthermore: 
- showing 9 options at once or more in the future would be overwhelming to our players. Think of food ordering apps e-commerce or Netflix, showing alot of options may make the player have a harder time in choosing what to play or may not choose anything at all. 

- I made a quick sketch of a possible card type orientation and here's how it looks: 
![image](https://user-images.githubusercontent.com/90673012/212454121-ec9524ca-38bc-4121-a057-93f2cbb10d10.png)

at a glance I would say that its harder to select something since there's a lot more options. ofcourse we can optimize this to have something like their most played game mode on top but its still a lot of options to choose from rather than showing it in a carousel. We can also show a list type but like what Steve mentioned in a [loom video](https://www.loom.com/share/5f6afab42e09423ca373366a57a50bad) we won't really utilize the pros of being a mobile app

this comment is for the homepage btw, I agree with what you said in the Lobby

thoughts @demiculus?

**Comment by JuanRoman77** [comment]
How about Ranked - Unranked - Custom (lobby + create room) tabs?
(By the way, there's no C&K unranked)

**Comment by samgawaran** [comment]
Ex. Player loves to play Ranked 4P
if carousel:
step 1 - just click on play. since ranked is preset and 4player mode is first in options

if tabs: assuming its the same preset with carousel (ranked is first preloaded tab after opening the app)
step 1 - pick 4 player game mode

same steps but I would argue carousel has a better UX since there's the word `Play` there. players might be surprise they will be matchmaked automatically after clicking on a card and wouldn't know what to expect. If we add Play on every card then it would be very redundant.

Carousel is a safer option imo and portrait games have them. (ex. Ludo Club). I have saw card formats (showing all modes) on landscape games (Angry Birds 2, Risk, Uno) but it works better on that orientation and for their ranked games, you need to select more options inside the card which we don't do.

Only mobile game I know that resembles a tab-type selection is Call of Duty Mobile which is a landscape-view gameand their tabs is like: first Tab select game mode, 2nd screen, select maps but we don't allow that at the moment on our matchmake game modes so its hard to consider the suggestion in my perspective.

**Comment by demiculus** [comment]
https://user-images.githubusercontent.com/6215305/212462183-6c8640ae-a433-45c2-80cb-c8a776a265b2.MOV

@samgawaran 
- Write our needs/goals
- write principles
- write possible layouts(solutions)
- if you've done the first 3 steps correctly the answer will be obvious. 

I dont want any room for discussion. Only expansion to the need-princple-solution framework
