### ISSUE TITLE
Mobile App: Idea Dump (Screens)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#260]
## Summary
Pasting all ideas that I have screens created for it. 

## Criteria
- Designs are too complex or low value at the moment to consider. (ex. changing the popup color, creating a matchmaking animation, etc.)
- Sketches that have good concepts but no designs yet.

### Matchmaking Flow Revamp
![image](https://user-images.githubusercontent.com/90673012/211989813-4c740d24-d5d4-47f4-bd07-64f44fe0e50c.png)
- make the matchmaking flow similar on top mobile games like Clash Royale, MLBB and make it mobile native
- Add estimated time on how long you'll matchmake
- From Devyesh and Sam discussions during our collaborative talks

### Reduce header details even more
![image](https://user-images.githubusercontent.com/90673012/211990662-bfe8c39a-219a-4ce7-b202-e159e71be3cc.png)
- just add Karma and Memberships
- Membership detail can be longer to attract more attention and have more animations and design

### Don't show avatars on Mobile app Lobby
![image](https://user-images.githubusercontent.com/90673012/212456665-b5fbe301-b422-4f53-84c1-0b92056f7376.png)
- Show them as (X/4) instead, same with our matchmaking counter
- more space for more important details

### Compile low value pages in a settings popup
![image](https://user-images.githubusercontent.com/90673012/212537487-7d760f5e-dceb-47e9-af51-4513b9b62e58.png)
- show medium-value buttons in the menu and put all low-value options inside an additional Setting button 
- no mobile games show their About or Careers, they have websites for that
- Privacy is usually shown in the loading page or after the game has been installed
- Remove social media icons on the Menu. none of the games I researched has a button to redirect them to a social media platform besides signing in or sharing their achievements after a game and we don't want to them to leave the app for another 

## Related Links

- https://github.com/colonistio/design/issues/226

**Comment by woodifred** [comment]
@samgawaran I'm definitely a fan of your suggestion to reduce header details even further. (There is a lot of info on this screen)

- Another option would be to make the stats expand/collapse on tap? 
- Would it be possible to put all of the player stats in the menu or profile?

**Comment by goktugyil** [comment]
At this stage wouldn't it better to focus on the general outlines. A general:
- `header & user info` section on the top without details
- `play & CTA` section in middle
- `footer & menu` section at bottom
then fill this out for all screens. After decisions there is given then dive deeper into the details of `sections`?

**Comment by demiculus** [comment]
1. For headers create a new submission with the new template
2. Before the flow make sure the game mode screen is perfect. Look at the size of that play button... isn't that too big? Create a new submission just for the game mode part.
3. For lobby, use icons
