### ISSUE TITLE
Create New Ads for Hiring

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#261]
## Description
We need specific ads targeted for roles we're looking for here: https://colonist.io/careers

## Checklist
- [x] Homepage Ad for Product Manager
- [x] Homepage Ad for QA Tester (do this last)
- [x] Homepage Ad for Product/UX Designer
- [x] Adblock versions for all of the above
- [ ] follow naming for adblock here https://github.com/colonistio/katan/tree/development/code/client/static/images

## Figma link with images 
https://www.figma.com/file/Zx0djbRrWXyUsJlhOfDBv3/Colonist-Marketing-Files?node-id=713%3A9745&t=GwDqER59I98kGDrn-1

## Reviewer
@JuanRoman77 @demiculus

**Comment by Ioseffagundes** [comment]
@samgawaran I'm having trouble opening the link 
I didn't understand what is the adblock version?

 I made a first proposal in this link here, let me know what you think [Figma Link](https://www.figma.com/file/Zx0djbRrWXyUsJlhOfDBv3/Colonist-Marketing-Files?node-id=702%3A10232&t=ankcA8M943O9p3de-1)

**Comment by samgawaran** [comment]
here's a sample of all ads we designer are tasked in making:
https://www.figma.com/file/Zx0djbRrWXyUsJlhOfDBv3/Colonist-Marketing-Files?node-id=705%3A11457&t=LiX0eSuVJfDtRp35-1

attached there is a sample of dimensions and file naming we are using including the adblock. let me know if it helps!

**Comment by zer07777** [comment]
https://github.com/colonistio/katan/pull/9956
@samgawaran I've created this PR to add the ads to the img folders.
Once they're there I'll try to add them to the game.

Requested your review.

Good job btw guys, the ads look nice!

**Comment by zer07777** [comment]
@Ioseffagundes 
These are @JuanRoman77 comments on the ads images.
Could you please fix them?
![image](https://user-images.githubusercontent.com/112039099/219857088-53ea3c0d-f3c0-404c-8c7f-a5964ecd1886.png)
![image](https://user-images.githubusercontent.com/112039099/219857101-d98da45b-37fe-4f5f-a254-62b441843a3f.png)
![image](https://user-images.githubusercontent.com/112039099/219857109-8c739b78-b77c-466f-9b15-0404ae99e92d.png)
![image](https://user-images.githubusercontent.com/112039099/219857118-4c127a84-6f1c-4e71-979b-9792279595e4.png)
![image](https://user-images.githubusercontent.com/112039099/219857126-16647d23-d3a3-46ea-bd85-7901e32dd241.png)

**Comment by Ioseffagundes** [comment]
ok, I updated the Figma file
https://www.figma.com/file/Zx0djbRrWXyUsJlhOfDBv3/Colonist-Marketing-Files?node-id=749%3A14954&t=U77J0luXmJAK2eXF-1

**Comment by aalmadan** [comment]
Close issue?
