### ISSUE TITLE
Mobile App - Menu Screen (Studies)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#262]
## Summary
We decided to put the `Menu` in the header, same with most orientations.

This submission covers some suggestion on what we could do on our Menu

### Current Design
![image](https://user-images.githubusercontent.com/90673012/212459709-87fabf36-1fa5-46db-a841-83f0186a1652.png)

## Studies
![image](https://user-images.githubusercontent.com/90673012/212459986-c0acfd89-4375-49db-9e27-fe921e36e9ff.png)

`1` - same version/logic with current design but will add images on this to make it have a better UI. 

`2A & B`  - Recommended design. other games do this orientation, show medium-value buttons in the menu and put all low-value options inside an additional Setting button, most of the time its a popup so its good to add it hear. Also: add a volume control so players can mute sounds before going inside the game or if there's homepage music in the future

## Decisions to Make:
- Putting every low-value pages inside settings, reason:
    - no mobile games show their About or Careers, they have websites for that
    - Privacy is usually shown in the loading page or after the game has been installed
- remove social media icons in the Menu
    - none of the games I researched has a button to redirect them to a social media platform besides signing in or sharing their achievements after a game
    - We don't want players to leave the app

## Related Links

- https://github.com/colonistio/design/issues/226

## Submission Checklist
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @woodifred @5econds

**Comment by demiculus** [comment]
Go with option 1

**Comment by samgawaran** [comment]
For option 1, I'll remove the Social Media buttons at the footer.

- No other games does that, because it will redirect them to another app. We can leave the space open for the future for options with better value for us like moving the Account Linking in the Menu

**Comment by demiculus** [comment]
![image](https://user-images.githubusercontent.com/6215305/212602247-33b3cbbd-1ab5-41a8-a8ee-2adc39363fed.png)

Keep social media.
Most games dont have it cause people dont care about the genre. After they stop playing they'll never go back to that game. Those games can be replaced easily.
Chess is not, once a chess player is a lifetime chess player.
Colonist is not chess. But its not other games as well. Keep it.
