### ISSUE TITLE
Mobile App: what we have so far (Finalized List)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#264]
## Goals
Submit all decisions agreed upon on Mobile
- make it easy to implement as much as possible
- decisions are optimized for mobile portrait

## Needs
High Priority pages:
- Home
- Lobby
- Create Room
- Menu
- Matchmaking
- Footer Navigation
- Header

### Header
![image](https://user-images.githubusercontent.com/90673012/212551977-36e717f6-7f7e-450f-af73-4eb8c465f538.png)

Benefits: 
- same elements we have on the desktop
- Doesn't take too much space = more space for content

Tapping on:
- Username and Avatar redirects you to a new popup that will show this: https://prnt.sc/BNxrirkaCBXw
- Coins Topup will redirect you to the store, coins tab
- Menu will show all buttons not shown in the Footer Nav

Potential Risks: 
- Membership status are not shown. 

### Footer Navigation
![image](https://user-images.githubusercontent.com/90673012/212557882-0275daad-86de-4c5a-bda0-1964e160d485.png)

Benefits: 
- Easy access to important pages
- Most games on Portrait mode has footer navs

Potential Risks: 
- Long button names (ex. Leaderboards) needs to be renamed to fit which needs to be adjusted on the desktop version too

### Home
- https://github.com/colonistio/design/issues/269 Check

### Matchmaking
![image](https://user-images.githubusercontent.com/90673012/212558040-a0940d0f-f7a2-45ac-84b2-a5ec031aa054.png)

Benefits: 
- Easy implementation, same logic with desktop version but on a popup optimized for mobile

Potential Risks: 
- Not interactive enough. Further revamp is needed to make it up-to-standard with other matchmaking screens of top games

### Lobby
![image](https://user-images.githubusercontent.com/90673012/212558938-dd2208db-059f-4924-9511-0a1fac2a77e6.png)

Benefits:
- Easy implementation, same assets/containers and layout used in the website version, making it seamless and viable for cross-platform games
- Hover interaction from desktop can be translated to tapping mechanics until further redesign is made

Potential Risks:
- Room containers doesn't have a standard height. Rooms with long map/expansion names have larger containers
- Need to adjust `mode` names in Desktop. ex. Seafarers + Cities and Knights 5-6 player must be renamed to SF+C&K 5-6P to make it consistent with Mobile

### Create Room
- https://github.com/colonistio/design/issues/263

waiting for feedback before decision

### Menu
![image](https://user-images.githubusercontent.com/90673012/212559656-16b275a0-7723-40df-b457-23d0b9272b84.png)

Benefits:
- Easy implementation. same logic, bg and animation with current mobile web browser
- Adds icon along with the button name, similar on how we do store categories in desktop to make it more contextual

Potential Risks:
- A lot of the pages in the menu is not something usually seen in mobile apps. (ex. Careers, About, FAQ) those pages are seen on the games official website. Added some ideas https://github.com/colonistio/design/issues/260 for future optimizations

## Reviewers
@demiculus @JuanRoman77 @woodifred @5econds

**Comment by goktugyil** [comment]
Please use any other username than that in your future designs

**Comment by goktugyil** [comment]
> Potential Risks:
> Membership status are not shown.

That's not a risk and not a critical info

**Comment by goktugyil** [comment]
> Long button names (ex. Leaderboards) needs to be renamed to fit which needs to be adjusted on the desktop version too

Agreed on this. But we should still use the work `Leaderboards` in our SEO stuff and some part in the web page as well

**Comment by goktugyil** [comment]
> Matchmaking
> Not interactive enough. Further revamp is needed to make it up-to-standard with other matchmaking screens of top games

I'd like this to be iterated a bit more. I don't like the final result

**Comment by goktugyil** [comment]
> Footer Navigation
I think the order should be: Store Rankings Home Lobby Profile
from my past experiences with games. However I don't have a strong opinion or solid data to back this up

**Comment by SimonH321** [comment]
Matchmaking Comment: 
Not clear to me how to toggle between ranked and unranked. It looks like I should swipe right or left, but that will change game mode. If we're expecting them to press it then we should change how the ranked/unranked buttons look

**Comment by JuanRoman77** [comment]
Remove the Coins in the header. Coins are useless and it clogs the UI.

**Comment by demiculus** [comment]
> Goal
Submit all decisions agreed upon on Mobile
make it easy to implement as much as possible
decisions are optimized for mobile portrait

Thats your goal not the submissions goal. Each of these parts should be a different submission having their own goals. 

> Needs
High Priority pages:
Home
Lobby
Create Room
Menu
Matchmaking
Footer Navigation
Header

Those are your needs not the users needs.

-----

Header:

> Membership status are not shown.

Then show it on top of the icon. We already have that in our website.

The rest is good. Can move forward.

Footer Navigation:

Home should be "Play"

Menu:

Make it full screen all the way to the bottom. 

-----

Create a separate submission for all of these. Make sure to write the right goals so you'll know the right stuff to do.

**Comment by samgawaran** [comment]
Added homepage submission here: https://github.com/colonistio/design/issues/269

Some few things:

> Please use any other username than that in your future designs
- I'll change the name once we finalize all of the pages here. A good rule of thumb in UX design is designing with the longest name possible so we can make sure edge cases are always considered.

> Remove the Coins in the header. Coins are useless and it clogs the UI.
- I disagree, coins provide potential revenue opportunities. Also almost all mobile games have a in-game currency topup in their header somewhere. Maybe it looks clogged due to the username? it will look like this if the name is not long:
![image](https://user-images.githubusercontent.com/90673012/213037988-c2ac67a1-7ee7-4276-9b8e-0847e6b08d5f.png)
we can also remove that additional stat info to further clean up the header part.

> Menu: Make it full screen all the way to the bottom.
-  I disagree, James and I considered that making it all the way to the bottom will leave a lot of empty spaces in the menu. Only thing that it would make sense is if making it all the way to the bottom is easier to implement

> Matchmaking Flow optimization
- next in my prio list. Will add it here after I'm done.

**Comment by JuanRoman77** [comment]
The store is disabled in mobile, and will stay like that for the next 2-3 months at least. Remove until the monetization strategy for mobile is decided, we can add it back later if we consider it necessary.

**Comment by demiculus** [comment]
> Only thing that it would make sense is if making it all the way to the bottom is easier to implement

It is, its also less bug prone. We develop according to best UX. and menu will not effect any metric

**Comment by woodifred** [comment]
To clarify, I expected the menu to function like a standard slide-in menu drawer when I was looking at it in Figma. 

Like this: https://m2.material.io/components/navigation-drawer

(From the left or the right is ok)

**Comment by woodifred** [comment]
In terms of simplifying the header, do you need the green + button on mobile? 

I'd expect players to know to tap on the coin number (32550) to see their wallet and/or buy more, etc? 

![image](https://user-images.githubusercontent.com/51459338/213281373-c67fe8a2-dab3-4436-9756-a23438c4ccad.png)

- Would tapping on the user name trigger another view/modal?
- Do the green + and the coin # currently take you to two different views? 

If possible, try not to cram too many tap targets into a small area on mobile. Can be tricky to hit the right spot with your thumb.

**Comment by JuanRoman77** [comment]
> Would tapping on the user name trigger another view/modal?

Yes, these 
![image](https://user-images.githubusercontent.com/73320460/213349872-62d399e8-a5a1-4546-a637-51e0bdc68f0a.png)


> Do the green + and the coin # currently take you to two different views?

No, both lead to the coins section of the store https://colonist.io/store#coins

----

> I'd expect players to know to tap on the coin number (32550) to see their wallet and/or buy more, etc?

Are plain texts enough indicator of a tap target? Shouldn't they have some sort of arrow, or background, etc.?

**Comment by woodifred** [comment]
This is great context thanks @JuanRoman77 

I think that, in terms of tap targets and affordances that imply something is interactive, we have more flexibility on mobile than desktop. 

There's certainly no harm in adding visual cues - but take avatars and user names in social apps, or a like count, these don't have any obvious affordances they're interactive but are a learned behaviour. I think there's the same learned behaviours in games.

I would only do it for elements that are common place across similar user experiences.
