### ISSUE TITLE
Bo Peng interview #4 blog post

### ISSUE THREAD

**Issue by SimonH321** [colonistio/design#265]
## Description
v150 blog post is my interview with Bo Peng, need an image

## Resources
Example to use: https://github.com/colonistio/design/issues/252
For image use his linkedin pfp https://www.linkedin.com/in/bopeng1

Need by Thursday

## Reviewer
@samgawaran

**Comment by JuanRoman77** [comment]
v150 has already been created, hence the need to edit `staging` to add the blog post, which is highly discouraged. For future blog posts **please** make sure they are added to the patch notes before the version is created. If the deadlines are tight, we can still make the exception and branch off staging, but __definitely__ not on a Thursday (24 hours before launching to Colonist).

**Comment by SimonH321** [comment]
> v150 has already been created, hence the need to edit `staging` to add the blog post, which is highly discouraged. For future blog posts **please** make sure they are added to the patch notes before the version is created. If the deadlines are tight, we can still make the exception and branch off staging, but **definitely** not on a Thursday (24 hours before launching to Colonist).

I apologize for branching off staging, the decision for which blog post to include in this release was made late because of the 2022 summary possibly being ready. I'll make the PR tomorrow, only the image is due by tuesday (image not required for patch notes.)

**Comment by samgawaran** [comment]
is this still on? I have the image here: https://github.com/colonistio/design/issues/271

**Comment by JuanRoman77** [comment]
@SimonH321 please close both issues when the blog post is done
