### ISSUE TITLE
Blog - Player Interview #4 Bo Peng 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#271]
## Goal
- Create an image that we can use for the article

## Needs

- Make sure that Bo Peng's name and the image are correct.
- Follow the usual dimensions and template for player interview 

## Principles
- Consistency

## Proposed Design
![image](https://user-images.githubusercontent.com/90673012/213402095-8969f1e0-c237-468a-8ebb-cde722f0a732.png)

### Overlayed in Blog

![image](https://user-images.githubusercontent.com/90673012/213402047-be141312-05a5-4454-8882-545c4cdd9ed6.png)

## Considered

- [x]  This proposal fits [[company vision](https://github.com/colonistio/katan/blob/development/docs/company/company-values.md)](https://github.com/colonistio/katan/blob/development/docs/company/company-values.md)
- [x]  This proposal is impactful according to [[Prioritizer Sheet](https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=0)](https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=0)
- [x]  This submission abides by [[Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md)](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [[Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md)](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [[Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)]

## Related Link
- GDrive: https://drive.google.com/drive/folders/1KAKK-fWTs_V_YkbgBXHYvHKX1zfetyfi?usp=sharing

## Reviewer
@SimonH321 @JuanRoman77

**Comment by SimonH321** [comment]
Great, thanks (@samgawaran can close issue)
