### ISSUE TITLE
Mobile App: Matchmaking (Finalized Screens)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#278]
## Goals
- get players inside the game

## Needs
- A button for them to go back if necessary
- Indicators that they are matchmaking
    - Game Mode Icon
    - Rating & Division (for ranked)
    - Number of players

## Principles
[Contrast](https://www.toptal.com/designers/gui/principles-of-design-infographic#:~:text=There%20are%20twelve%20basic%20principles,that%20make%20sense%20to%20users.)
[Visibility of system status](https://www.nngroup.com/articles/ten-usability-heuristics/)
[Movement](https://www.toptal.com/designers/gui/principles-of-design-infographic#:~:text=There%20are%20twelve%20basic%20principles,that%20make%20sense%20to%20users.)

## Research
See here: https://github.com/colonistio/design/issues/272

## Proposed Solution: Full Screen: Show Elapsed Time

- removed tips, I'd consider space limitations on the smallest android devices (360x640) and removed it. It provides no value compared to the other elements in the screen.

### iOS Screen (375x812)
![image](https://user-images.githubusercontent.com/90673012/213981985-8341c9a8-1753-4af7-a6f8-2214fc435ec0.png)

### Android (360x640) 
![image](https://user-images.githubusercontent.com/90673012/213981936-f88c69c0-37d3-450d-9923-bc0912bc5352.png)

### Search icon animation
![Matchmaking Search Animation](https://user-images.githubusercontent.com/90673012/213982754-76052936-64c9-4dd1-93b9-93afd79cb7c5.gif)

GIF link: https://drive.google.com/drive/folders/1VjowPWO1SPb-huOojgwRF-lTa1pooGYk?usp=sharing

### Flow
![image](https://user-images.githubusercontent.com/90673012/213983219-a9c65d4e-4205-4101-ad56-37c2b99cce6c.png)

- when player number reach (4/4) or (2/2) they cannot press the cancel cta. Similar to desktop, it will automatically jump to the game. 

- How we show ads (Idea):
    - For Non-Members, after the player clicks on `Play` from the homepage, we will show a short video ad (15-seconds) before they matchmake.

Benefits: 
- Easy dev time, full screen, and just add the search animation I'll provide, or create a CSS animation for better quality
- Full screen is a standard to most matchmaking screens in games, checked on smaller android screens and spacing works
- Potential for revenue: show video ads for non-members if they click on `Play` in the homepage

Potential Risks: 
- Animations not working

Figma link: 
https://www.figma.com/proto/4sPdkWQrqoiGgFkMLtVSqr/Colonist-UI%2FUX-App?page-id=405%3A52350&node-id=794%3A97484&viewport=-110%2C-4013%2C0.25&scaling=scale-down&starting-point-node-id=794%3A97334

## Considered
- [x] This proposal fits [company vision](https://github.com/colonistio/katan/blob/development/docs/company/company-values.md)
- [x] This proposal is impactful according to [Prioritizer Sheet](https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=0)
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @woodifred @5econds

**Comment by demiculus** [comment]
Looks nice, you can close this and link it in the main issue.
