### ISSUE TITLE
Reddit Ad - Submission

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#286]
## Goals
- Create an animated Ad for Reddit
- flow suggested by Simon in parent issue: https://github.com/colonistio/design/issues/277

## Needs
- Show gameplay
- Show Division and Leaderboards
- Show Fun Maps

Proposed Solution: 
![Reddit GIF Test](https://user-images.githubusercontent.com/90673012/215731871-0ce46064-eb61-41c7-add2-7ca5ba34442b.gif)

See Figma link for higher quality vid:
Figma link: https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=12316%3A202236&node-id=12318%3A211719&viewport=300%2C55%2C0.03&scaling=scale-down&starting-point-node-id=12318%3A202239

## Considered
- [x] This proposal fits [company vision](https://github.com/colonistio/katan/blob/development/docs/company/company-values.md)
- [x] This proposal is impactful according to [Prioritizer Sheet](https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=0)
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

### GDrive Link:
https://drive.google.com/drive/folders/1aoEc3JxAQNLvks7sdY_eie6OUztSyD29?usp=sharing

## Reviewers
@JuanRoman77 @demiculus @SimonH321

**Comment by samgawaran** [comment]
for checking before I sent the cropped GIF. removing the black BG in the GIF takes time so I like to finalize the look before I go with it.

**Comment by SimonH321** [comment]
> for checking before I sent the cropped GIF. removing the black BG in the GIF takes time so I like to finalize the look before I go with it.

In the first part where you demo the city getting all the resources, could you instead have a dice roll animation showing a 4, for example, and then two wheat pop up? The current thing is a bit confusing, would never occur during gameplay. Other than that it looks amazing!

**Comment by samgawaran** [comment]
Will do! I can get it to you by tomorrow on my timezone. Will upload it here

**Comment by demiculus** [comment]
@SimonH321 fyi:

You should have hypothesis for multiple parts of the ad. For design, something like

Target users: Players who already know Catan and will want to play

- They need to see the word "Catan" in the ad.
- They don't need to see the word "Catan" in the ad.
- They are interested in extra features.
- They are interested to know its free.
- They are interested to know its multiplayer.
- They are interested to know if they can play with their friends.
... 

According to your hypothesis you generate 2-8 types of ads. To test and validate. 
Ofc the ads are not just gifs they have texts and other stuff as well so the tests can use those since its cheaper to test out texts rather than getting Sam to create 8 versions of the gif.

**Comment by simonhorowitz** [comment]
> @SimonH321 fyi:
> 
> You should have hypothesis for multiple parts of the ad. For design, something like
> 
> Target users: Players who already know Catan and will want to play
> 
> * They need to see the word "Catan" in the ad.
> * They don't need to see the word "Catan" in the ad.
> * They are interested in extra features.
> * They are interested to know its free.
> * They are interested to know its multiplayer.
> * They are interested to know if they can play with their friends.
>   ...
> 
> According to your hypothesis you generate 2-8 types of ads. To test and validate. Ofc the ads are not just gifs they have texts and other stuff as well so the tests can use those since its cheaper to test out texts rather than getting Sam to create 8 versions of the gif.

This is just a trial to see if Reddit advertising is viable at all. That's why I decided to just have one, well-made gif. If this goes well, we can start testing a variety of ads and seeing how different ones convert.

**Comment by SimonH321** [comment]
> @SimonH321 fyi:
> 
> You should have hypothesis for multiple parts of the ad. For design, something like
> 
> Target users: Players who already know Catan and will want to play
> 
> * They need to see the word "Catan" in the ad.
> * They don't need to see the word "Catan" in the ad.
> * They are interested in extra features.
> * They are interested to know its free.
> * They are interested to know its multiplayer.
> * They are interested to know if they can play with their friends.
>   ...
> 
> According to your hypothesis you generate 2-8 types of ads. To test and validate. Ofc the ads are not just gifs they have texts and other stuff as well so the tests can use those since its cheaper to test out texts rather than getting Sam to create 8 versions of the gif.

This is just a trial to see if Reddit advertising is viable at all. That's why I decided to just have one, well-made gif. If this goes well, we can start testing a variety of ads and seeing how different ones convert. (sorry for double comment, was on wrong account.)

**Comment by samgawaran** [comment]
@SimonH321

I'm having a hard time keeping the size of the GIF below 3MB to meet reddit ad standards. https://redditinc.force.com/helpcenter/s/article/Reddit-Ad-Unit-Specifications

![image](https://user-images.githubusercontent.com/90673012/216309136-242fed4d-8dc9-4725-af91-9a5849b56ca1.png)


Can we do an MP4 version instead? I'll make the quality higher so it will look sharper. maximum size limit in Reddit is 1GB so its viable. here is the look of the revised ad btw.

https://user-images.githubusercontent.com/90673012/216309276-3664a759-11a1-4b17-ac94-09f682659d11.mp4

**Comment by samgawaran** [comment]
@SimonH321

I'm having a hard time keeping the size of the GIF below 3MB to meet reddit ad standards. https://redditinc.force.com/helpcenter/s/article/Reddit-Ad-Unit-Specifications

![image](https://user-images.githubusercontent.com/90673012/216309136-242fed4d-8dc9-4725-af91-9a5849b56ca1.png)


Can we do an MP4 version instead? I'll make the quality higher so it will look sharper. maximum size limit in Reddit is 1GB so its viable. here is the look of the revised ad as .mp4 

https://user-images.githubusercontent.com/90673012/216309276-3664a759-11a1-4b17-ac94-09f682659d11.mp4

**Comment by SimonH321** [comment]
If Reddit allows it, like good to me

**Comment by samgawaran** [comment]
uploaded the files here:
https://drive.google.com/drive/folders/1aoEc3JxAQNLvks7sdY_eie6OUztSyD29?usp=sharing
