### ISSUE TITLE
Board actions

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#290]
As a player, I should be able understand the available actions available to me based on my cards.

## Steps

- [ ] Look at other turn-based multiplayer strategy games and collect examples in both video & screenshot forms
- [ ] Brainstorm and list multiple <rough> designs that meet the acceptance criteria of the task to a satisfactory level. At this stage more exotic designs can be considered as it’s important to widen our view of the solution landscape before focusing too much on details. 
- [ ] For each design rate values below from 0 to 5
  - Clarity: How clear is it: https://www.liamcharlton.com/post/signs-feedback-and-the-ux 
  - Ease of use: Number of needed interactions with the UI, complexity of interactions, number of hands needed to complete the actions, thumb zone etc.
  - Acceptance criteria met: 
- [ ] Implement changes to update the rating values of the above designs
- [ ] Identify any new player issues that may arise from each of your rough designs and the potential for them to be mitigated.
- [ ] Decide on 1-2 designs that have the greatest potential to work by analyzing the results from previous steps.
- [ ] Share all your results from the previous steps with the team in a table containing concise information; It’s important to also show your thought process for the design decisions you have made.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance criteria:

- [ ] Players should have a clear understanding of what actions they can take 
  - build (road, settlement, city, city wall, ship, metropolis, destroy their city, knight
  - trade
  - buy dev card
  - play dev card
  - Moving a knight, pirate 
  - Using a knight to move a robber
  - Activating a knight
  - Buying city improvements
  - Reposition ships
- [ ] Players should have clear understanding of what each of the actions cost
- [ ] The design of this feature should be sensitive to the limited screen space on mobile devices. Refer to: https://github.com/colonistio/design/issues/17
- [ ] Players should be able to take actions with a single hand (mind the "thumb zone).
- [ ] SF and C&K actions should be considered

**Comment by AlfredTimmer** [comment]
Design documentation work for this task is still ongoing but here is the current progress:
https://docs.google.com/spreadsheets/d/1GX_6zr_wbwa6Nsn6ScmDIjK9otVCN1Sw8gCkuY1Gy3U/edit?usp=sharing

Same situation for the rough Figma sketches:
https://www.figma.com/file/SkflgpJdHl3crvc5Lg488a/Mobile-App---Board-Game-Actions?node-id=201%3A28398&t=aHg3oLcPC0yYzEn9-1
