### ISSUE TITLE
SF extras  (ships, SF map)

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#291]
As a player in the Seafarers game mode, I should be able to interact the SF game board (islands + sea grid + pirate), ships / sea routes, and SF-specific game actions (build ship, reposition ship).

![Image](https://user-images.githubusercontent.com/33302207/218581764-04af853e-3b72-49b6-b34b-6c2b2a0b48aa.png)

Acceptance criteria
- [ ] All SF game board features should be considered and designed, including but not limited to:
1. Sea routes / grid
2. Pirate
3. Islands
4. Gold resource
- [ ] Navigability of the game board should be intuitive to players (most of the heavy lifting should be done here: https://github.com/orgs/colonistio/projects/4/views/1?pane=issue&itemId=20209624)
- [ ] All SF actions should be considered and designed, including but not limited to:
1. Building ships
2. Moving ships
3. Moving the pirate
4. Selecting resources from gold

**Comment by demiculus** [comment]
Merged into https://github.com/colonistio/design/issues/290
