### ISSUE TITLE
Chat (& hide chat)

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#292]
As a player, I want to be aware of chat messages from other players and have the ability to write my own messages to other players, so that I can work effectively with other players (e.g. "red is about to win, we need to block 9 ore!") and have a fun social experience.

![Image](https://user-images.githubusercontent.com/33302207/218584716-ddac8dbc-673e-4c79-b673-e318571b21ba.png)

In the browser, Colonist's chat is always there, but we should strongly consider

1. Showing and hiding chat (and giving the user control over this)
2. How to notify the user of incoming chat messages when chat is hidden (new messages should probably be visible even when chat is minimized/hidden, to reduce the need for more interactions)
3. What the messaging experience will be like with a mobile keyboard (which covers ~1/3 of the screen)
4. If users should be able to send different types of messages (e.g. reactions) to reduce the need for typing, which is generally slower and more cumbersome on mobile

## Steps
- [ ] Look at other mobile multiplayer games and collect examples in both video & screenshot forms
- [ ] Brainstorm and list multiple <rough> designs that meet the acceptance criteria of the task to a satisfactory level. At this stage more exotic designs can be considered as it’s important to widen our view of the solution landscape before focusing too much on details. 
- [ ] For each design rate values below from 0 to 5
  - Clarity: How clear is it: https://www.liamcharlton.com/post/signs-feedback-and-the-ux 
  - Ease of use: Number of needed interactions with the UI, complexity of interactions, number of hands needed to complete the actions, thumb zone etc.
  - Acceptance criteria met: 
- [ ] Implement changes to update the rating values of the above designs
- [ ] Identify any new player issues that may arise from each of your rough designs and the potential for them to be mitigated.
- [ ] Decide on 1-2 designs that have the greatest potential to work by analyzing the results from previous steps.
- [ ] Share all your results from the previous steps with the team in a table containing concise information; It’s important to also show your thought process for the design decisions you have made.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance criteria:

- [ ] Players should be aware of incoming messages (including a series of messages)
- [ ] It should be obvious how to view and hide the chat (keep in mind the limited screen real estate)
- [ ] Players should be able to view historical chat messages
- [ ] When typing a chat message, players should be able to see what they are responding to (if anything).
- [ ] As designers, we should consider building mobile-friendly chat features like emoji responses, message reactions, canned responses, etc.
- [ ] Chat should be a fun experience!

**Comment by johnsillings** [comment]
Chatters generally want to _see the messages they're responding to_ when composing messages of their own.

We should be mindful of how much screen space the native mobile keyboards take up when designing this. It's a lot!

See Facebook messenger for example:

![Image](https://user-images.githubusercontent.com/33302207/218586610-440ee287-a13a-485a-b43b-a8f83d9cfd56.PNG)
![Image](https://user-images.githubusercontent.com/33302207/218586611-00767ba9-8429-412a-b4c7-76e2fa6420da.PNG)

**Comment by johnsillings** [comment]
Message reactions can be a nice way to respond to chat messages without typing a full message out. Consider Discord:



![Image](https://user-images.githubusercontent.com/33302207/218587308-8486db1c-eed3-4df2-adfb-0c5faa0b2ea2.png)

**Comment by demiculus** [comment]
https://github.com/colonistio/design/issues/29

**Comment by huaniebun** [comment]
Design file: https://www.figma.com/file/up1U35QOvkl2aCfD0cJXGW/Colonist-Mobile?node-id=763%3A499825&t=depVDtXCzukB7Kgp-0

Shortlisted Option 1:

![Image](https://user-images.githubusercontent.com/98397645/222203910-5fa3ec3a-5661-46b4-9d6f-d8d640998351.png)

**Comment by johnsillings** [comment]
I feel pretty good about the designs, but the big unresolved question for me is:

Are we going to show users notifications for incoming chat messages? And if so, how?

I feel pretty strongly that I want these notifications as a player – in real time, and without having to take additional actions.

I'm going to do a little research into how some popular social mobile games are handling this... will add design inspo studies here.

**Comment by johnsillings** [comment]
Added a handful of chat examples here: https://imgur.com/a/QKtUlQ9. I wanted to see how other multiplayer games handle new messages / incoming messages.

Chess.com app: shows new messages with a chat bubble, they fade out after a second.
8 ball pool: shows new messages with a chat bubble, they fade out after a second.
Uno app:  shows new messages with a chat bubble, they fade out after a second.

I will look for a couple more but this seems like a pretty common way to handle (and IMO a pretty good way).
