### ISSUE TITLE
Info and action boxes on dev cards (card information & descriptions)

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#299]
Players need to use and get information on dev cards. Some examples below:

![Image](https://user-images.githubusercontent.com/6215305/219316213-f18a0914-cef4-44a6-87d7-74bc3b1d9daf.png)

![Image](https://user-images.githubusercontent.com/6215305/219316424-9b440d87-10a4-46e3-bcd8-54536432c54b.png)

![Image](https://user-images.githubusercontent.com/6215305/219316499-90b30212-58f5-4de5-aead-018b2d61fcfc.png)

![Image](https://user-images.githubusercontent.com/6215305/219316820-687ee659-259a-4077-ae29-468a58abebaf.png)

## Steps

- [ ] Look at other turn-based multiplayer strategy games and collect examples in both video & screenshot forms
- [ ] Brainstorm and list multiple <rough> designs that meet the acceptance criteria of the task to a satisfactory level. At this stage more exotic designs can be considered as it’s important to widen our view of the solution landscape before focusing too much on details. 
- [ ] For each design rate values below from 0 to 5
  - Clarity: How clear is it: https://www.liamcharlton.com/post/signs-feedback-and-the-ux 
  - Ease of use: Number of needed interactions with the UI, complexity of interactions, number of hands needed to complete the actions, thumb zone etc.
  - Acceptance criteria met: 
- [ ] Implement changes to update the rating values of the above designs
- [ ] Identify any new player issues that may arise from each of your rough designs and the potential for them to be mitigated.
- [ ] Decide on 1-2 designs that have the greatest potential to work by analyzing the results from previous steps.
- [ ] Share all your results from the previous steps with the team in a table containing concise information; It’s important to also show your thought process for the design decisions you have made.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance criteria:

- [ ] Players should have a clear understanding of what each card does
- [ ] Players should be able to use each card easily
- [ ] Players should be able to see the information they need to see while using the card

**Comment by johnsillings** [comment]
Propose to add to acceptance criteria:

- [ ] Viewing and dismissing tooltips (e.g. on development cards) should be easy and intuitive
