### ISSUE TITLE
Most Popular Expansion Blog Post - Design Submission

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#300]
## Goals
- v152 blog post is going to be about the most popular catan expansion. This design can be super simple, just fitting with the overall blog theme

### Design
![image](https://user-images.githubusercontent.com/90673012/219603146-1618eccb-8f96-4204-ad09-c2623410e36d.png)

- Added icons of our expansions current game icons (C&K, SF)

### Overlayed in Blog
![image](https://user-images.githubusercontent.com/90673012/219603683-b5c4412d-6583-4fe7-b4b1-ab7224e2117a.png)

## Considered

- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Link
Gdrive: https://drive.google.com/drive/folders/1i7NzeXUBLDDE0GYMi5Ocb1aNwJMC-sbC?usp=sharing

## Reviewers
@demiculus @JuanRoman77 @SimonH321

**Comment by JuanRoman77** [comment]
I wouldn't mention nor reference Seafarers. Better focus on C&K, which is estimated to be 150% more popular than SF.
