### ISSUE TITLE
Player profiles

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#301]
As a player, I want to be able to look at my opponent's profiles, so I can take certain actions (e.g. add as friend) and see more information about them.

## Steps:

- [ ] Look at other multiplayer mobile games and collect examples of viewing player profiles (video & screenshots).
- [ ] Brainstorm and list multiple designs that meet the acceptance criteria of the task to a satisfactory level.
- [ ] For each design rate values below from 0 (worst) to 5 (best):
  - Clarity: How clear is it: https://www.liamcharlton.com/post/signs-feedback-and-the-ux 
  - Ease of use: Number of needed interactions with the UI, complexity of interactions, number of hands needed to complete the actions, thumb zone etc.
  - Acceptance criteria met:
- [ ] Implement changes to update the rating values of the above designs
- [ ] Identify any new player issues that may arise from each of your rough designs and the potential for them to be mitigated.
- [ ] Decide on 1-2 designs that have the greatest potential to work by analyzing the results from previous steps.
- [ ] Share all your results from the previous steps with the team in a table containing concise information; It’s important to also show your thought process for the design decisions you have made.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance criteria:

- [ ] It should be easy to view a player profile, and it should be easy to return back to the game.
- [ ] Viewing a player profile should not totally remove a player from the in-game experience.
- [ ] Player profiles should be skimmable and include most important player information in the most prominent places, including:
 - Rank and win-rate
 - Number of games played
 - Game history
 - Most-played game types
 - Avatar
- [ ] Players should be able to take actions on another player's profile, such as:
 - Add friend
 - Remove friend
 - Report

![Image](https://user-images.githubusercontent.com/6215305/218233611-82a54ce6-9c10-447c-9372-bb1891653ed8.png)

![Image](https://user-images.githubusercontent.com/33302207/219718873-e84653d4-65a1-4fdd-b851-04c37dcd91c0.png)

**Comment by demiculus** [comment]
We'll just show the default player profile overlay when clicking on the profile picture of the player.
