### ISSUE TITLE
Achievements (largest army, longest road, etc.)

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#303]
As a player, I should be aware of major in-game achievements (e.g. largest army, longest road), so that I can adapt my strategy accordingly, keep track of the game state, and feel an emotion (celebratory, concern, jealousy, etc).

## Steps

- [ ] Look at other multiplayer mobile games and collect examples of in-game achievement notifications (video & screenshots).
- [ ] Brainstorm and list multiple designs that meet the acceptance criteria of the task to a satisfactory level.
- [ ] Decide on 1-2 designs that have the greatest potential to work in the mobile Colonist UI.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance criteria:

- [ ] Achievements should be noticeable and easy to understand.
  - Players should be able to answer the question: "What just happened?"
- [ ] Achievements should feel significant and should elicit an emotional reaction from players (celebratory, concern, jealousy, etc).
- [ ] Achievement notifications should dismiss themselves after a short period, and/or be easily dismissed by the player.

**Comment by AlfredTimmer** [comment]
Here is the design file:
https://docs.google.com/spreadsheets/d/1zd7Yor2jNnEfIw7P86UvjBse54tRLdSWnZXYVqbuICA/edit?usp=sharing
