### ISSUE TITLE
End game

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#305]
At the end of a game, as a player, I should be able to understand who won the game and how they won, as well as review details of the game. This is both for the purpose of learning and improving, but also because it is interesting and fun.

## Steps

- [ ] Look at other multiplayer game "end game" screens and collect examples in both video & screenshot forms
- [ ] Brainstorm and list multiple <rough> designs that meet the acceptance criteria of the task to a satisfactory level. At this stage more exotic designs can be considered as it’s important to widen our view of the solution landscape before focusing too much on details. 
- [ ] For each design rate values below from 0 to 5
  - Clarity: How clear is it: https://www.liamcharlton.com/post/signs-feedback-and-the-ux 
  - Ease of use: Number of needed interactions with the UI, complexity of interactions, number of hands needed to complete the actions, thumb zone etc.
  - Acceptance criteria met: 
- [ ] Implement changes to update the rating values of the above designs
- [ ] Identify any new player issues that may arise from each of your rough designs and the potential for them to be mitigated.
- [ ] Decide on 1-2 designs that have the greatest potential to work by analyzing the results from previous steps.
- [ ] Share all your results from the previous steps with the team in a table containing concise information; It’s important to also show your thought process for the design decisions you have made.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance Criteria

- [ ] The most important end-game information should be the easiest to find and review.
- [ ] Information should be represented in a way that is both beautiful and easy to understand.
- [ ] Detailed information (if we make it available) should be clearly and thoughtfully categorized.
- [ ] Players should be able to easily and intuitively find information that they are interested in.

![Image](https://user-images.githubusercontent.com/33302207/219766801-ba276feb-d7fb-4e50-97db-f915efd684f4.png)

![Image](https://user-images.githubusercontent.com/33302207/219766838-4794be31-31b2-4219-885b-9ac0c2a45faf.png)

![Image](https://user-images.githubusercontent.com/33302207/219766858-ca30d4d2-b4cd-4c86-b990-2c388c206641.png)

![Image](https://user-images.githubusercontent.com/33302207/219766883-5a5d7247-cd42-4e48-99be-f79744940854.png)

![Image](https://user-images.githubusercontent.com/33302207/219766907-9f741c1a-11aa-44ea-b571-0cb4634e4e3b.png)

![Image](https://user-images.githubusercontent.com/33302207/219766927-4dd172a7-ca1c-4e2c-8adc-e2fd84bdb9ad.png)

**Comment by demiculus** [comment]
The screenshots don't show everything.

On Web
1. When it is 8 players the player section scrolls
2. The chat box is not shown here, but it is useful because people message each other saying, `gg, wp, nice game, fuk you, you were lucky, hahahahahah, wow` and other stuff.
3. The buttons show `Play & Leaderboards` if its a ranked game. 
  The buttons show `Rematch & Lobby` if its a room game.
4. The medals are useless we can remove them

There might be other stuff I've missed.

**Comment by aalmadan** [comment]
Close issue? https://www.figma.com/file/KjHdwcS3tBLtE3DXFKyJQK/Mobile-Game-Master-File?node-id=76-44635&t=791X6x2emstHH7t2-4
