### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#306]
Includes /disablekarma vote and /pause vote & state, along with all other settings.

As a player, I should be able to edit my settings at any time during a game, so I can customize my game experience.

As a player, I should also have some control over in-game settings that affect other players, like disabling karma and pausing the game.

## Steps

- [ ] Look at other mobile multiplayer game settings screens and collect examples in both video & screenshot forms
- [ ] Brainstorm and list multiple rough designs that meet the acceptance criteria of the task to a satisfactory level. At this stage more exotic designs can be considered as it’s important to widen our view of the solution landscape before focusing too much on details. 
- [ ] For each design rate values below from 0 to 5
  - Clarity: How clear is it: https://www.liamcharlton.com/post/signs-feedback-and-the-ux 
  - Ease of use: Number of needed interactions with the UI, complexity of interactions, number of hands needed to complete the actions, thumb zone etc.
  - Acceptance criteria met: 
- [ ] Implement changes to update the rating values of the above designs
- [ ] Identify any new player issues that may arise from each of your rough designs and the potential for them to be mitigated.
- [ ] Decide on 1-2 designs that have the greatest potential to work by analyzing the results from previous steps.
- [ ] Share all your results from the previous steps with the team in a table containing concise information; It’s important to also show your thought process for the design decisions you have made.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance Criteria

- [ ] It should be easy to find, open, and close the settings menu.
- [ ] Settings (if there are a lot of them) should be easy to navigate, and clearly and thoughtfully categorized.
- [ ] Settings should be easy to change, and users should get clear feedback about when settings have been changed and/or saved.
- [ ] Users should be able to view and customize a variety of settings, including:
  - Game settings (reviewing only)
  - Display settings
  - Controls (with thoughtfulness around which settings make sense on mobile)
  - Audio settings
  - Disable Karma vote
  - Pause vote

![Image](https://user-images.githubusercontent.com/33302207/219804800-3bad6572-1ed0-4979-833b-e864c408b3ed.png)

![Image](https://user-images.githubusercontent.com/33302207/219804909-fe487c42-e691-4256-9c9e-70f2a03f81ed.png)

![Image](https://user-images.githubusercontent.com/33302207/219805122-0567ed28-c2d0-47a2-8c3d-99fe404b0d8f.png)

![Image](https://user-images.githubusercontent.com/33302207/219805061-e8c249a1-11de-4086-9101-3e09c98778a6.png)

**Comment by Ioseffagundes** [comment]
https://www.figma.com/file/KjHdwcS3tBLtE3DXFKyJQK/Mobile-Game-Master-File?node-id=76%3A47450&t=BmysyjboazM2oY1W-1
