### ISSUE TITLE
Resource costs

### ISSUE THREAD

**Issue by johnsillings** [colonistio/design#307]
As a player, I need to understand what improvements I can and can't build, and which resources are consumed and/or required for building improvements.

_Note: In the Colonist's browser version, this is accomplished on-hover, but we'll need to be thoughtful about how we implement this on mobile._

## Steps

- [ ] Look at other resource-strategy mobile games handle building costs and tooltips.
- [ ] Brainstorm and list multiple rough designs that meet the acceptance criteria of the task to a satisfactory level.
- [ ] For each design rate values below from 0 to 5
  - Clarity: How clear is it: https://www.liamcharlton.com/post/signs-feedback-and-the-ux 
  - Ease of use: Number of needed interactions with the UI, complexity of interactions, number of hands needed to complete the actions, thumb zone etc.
  - Acceptance criteria met: 
- [ ] Implement changes to update the rating values of the above designs
- [ ] Identify any new player issues that may arise from each of your rough designs and the potential for them to be mitigated.
- [ ] Decide on 1-2 designs that have the greatest potential to work by analyzing the results from previous steps.
- [ ] Share all your results from the previous steps with the team in a table containing concise information; It’s important to also show your thought process for the design decisions you have made.
- [ ] Get the greenlight from project owners to start work on a detailed Figma prototype for one of the high potential rough designs.

## Acceptance Criteria

- [ ] Players should know which improvements they can and cannot build, given the resources they have.
- [ ] Players should know what resources will be consumed when they build an improvement.
- [ ] Players should know what resources they need (and which resources are missing) to build an improvement.

![Image](https://user-images.githubusercontent.com/6215305/218233354-fa408626-305d-4b8f-8f84-df2f27275ae0.png)

Players with less than 5 games get to see this

![Image](https://user-images.githubusercontent.com/6215305/218233400-0c36a6e0-b803-44f4-b16f-9a1df3f90358.png)

In CU they show it here which is bad UX

![Image](https://user-images.githubusercontent.com/6215305/218233448-9a8be659-0520-462d-8308-7f45954b2558.png)

**Comment by aalmadan** [comment]
Close issue? https://www.figma.com/file/aYC5kDvd3xfiITGCoyAmrO/Mobile-App---(Iosef)-File?node-id=1957-421907&t=JE5oHaxbawnLdukg-4
