### ISSUE TITLE
Blog: Interview Series - (ThePhantomCatan) Submission

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#312]
## Goals
- Create a cover art for Colonist Blog interview series.
- Highlight who's being interviewed via their username and profile picture

### Design
![image](https://user-images.githubusercontent.com/90673012/221801706-262c01c6-7b6d-4252-b3e5-d14cb21c14f5.png)

### Overlayed in Blog
![image](https://user-images.githubusercontent.com/90673012/221801758-e3e0eefc-cc14-4b16-a6dc-aa11283aea05.png)

## Resource:
Google Drive Link: https://drive.google.com/file/d/1oXr_Yj8N0x-1EeBmgC0gOuizOai1FcqI/view?usp=sharing
Figma link: https://www.figma.com/file/Zx0djbRrWXyUsJlhOfDBv3/Colonist-Marketing-Files?node-id=794%3A15023&t=KJ4oHkiGBfxcGxEg-1
Main Issue: https://github.com/colonistio/design/issues/308
## Considered

- [x] This proposal fits [company vision](https://github.com/colonistio/katan/blob/development/docs/company/company-values.md)
- [x] This proposal is impactful according to [Prioritizer Sheet](https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=0)
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@JuanRoman77 @SimonH321

**Comment by aalmadan** [comment]
Closed, done
