### ISSUE TITLE
Mobile Game UX

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#318]
Voting screen
Pause votes, disable karma votes etc..

![Image](https://user-images.githubusercontent.com/6215305/228145994-bcc428bf-b398-414b-93aa-4f43277c1e82.png)

![Image](https://user-images.githubusercontent.com/6215305/228146077-6e612018-73b1-4555-a865-70ec09e038d0.png)

![Image](https://user-images.githubusercontent.com/6215305/228146150-bb905500-2e2f-4644-93d1-19c28db27eef.png)

![Image](https://user-images.githubusercontent.com/6215305/228146251-804e859d-1d6e-493d-ba13-2f068433e852.png)

**Comment by aalmadan** [comment]
Close issue? https://www.figma.com/file/KjHdwcS3tBLtE3DXFKyJQK/Mobile-Game-Master-File?node-id=76-44456&t=791X6x2emstHH7t2-4
