### ISSUE TITLE
Discord Implementation - Design Assets

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#321]
## Summary
Discord asked us to provide assets for a game BG, Cover Art, and a preview video: https://discord.com/channels/605233308577562643/1055023081845968926/1094323221844738048

## Embedded Background
![image](https://user-images.githubusercontent.com/90673012/231721364-6a15812b-babe-4ea2-b77a-50534840c6da.png)

### Overlayed in Discord
![image](https://user-images.githubusercontent.com/90673012/231722280-f7cf5281-d072-4631-84f3-aedcd1d222bf.png)

Figma Link: https://www.figma.com/file/SysB628vRorzV7E9Pp9JuR/Colonist---(Sam)-File?node-id=1813%3A338569&t=Lo5ta5ZXBwqmGOTr-1
____________________________________________________

## Cover Art
![image](https://user-images.githubusercontent.com/90673012/231721448-f45506cc-90c1-475d-b038-aec6aea03e98.png)

### Overlayed in Discord
![image](https://user-images.githubusercontent.com/90673012/231722884-d1d6b5e8-3ef3-468c-b297-fa35cfddbc33.png)

Figma Link: https://www.figma.com/file/SysB628vRorzV7E9Pp9JuR/Colonist---(Sam)-File?node-id=1813%3A338646&t=Lo5ta5ZXBwqmGOTr-1

## Preview Video

https://user-images.githubusercontent.com/90673012/231732942-02362790-5e12-46a4-ae23-bbd5b70a7f50.mp4

### Overlayed in Discord
![Preview GIF](https://user-images.githubusercontent.com/90673012/231737921-d5e06691-2e78-4917-9c17-b433c70113cb.gif)

Prototype Link: https://www.figma.com/proto/SysB628vRorzV7E9Pp9JuR/Colonist---(Sam)-File?page-id=1772%3A312365&node-id=1816-332900&viewport=5047%2C-3267%2C0.5&scaling=scale-down-width&starting-point-node-id=1816%3A332898

## Conclusion

- for both **Cover Art** and **Embedded Background** The designers (Huan, Sam, Iosef) prefer `Study C` but feel free to use any study that's more appropriate

- I took a while in creating the Discord Preview since the original style I planned to do was to show the whole board. Turns out the preview is only shows a small screen so I need to readjust it to show how tile and road placement works.

## Gdrive Link:
- https://drive.google.com/drive/u/0/folders/1fihPUstpuYTmGTtIEqGc-kYpigcnpK1c

## Considered
- [x] This proposal fits [company vision](https://github.com/colonistio/katan/blob/development/docs/company/company-values.md)
- [x] This proposal is impactful according to [Prioritizer Sheet](https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=0)
- [x] This submission abides by [Des-lvl-1](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-1.md), [Des-lvl-2](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-2.md) & [Des-lvl-3](https://github.com/colonistio/katan/blob/development/docs/process/designer-level-3.md)

## Reviewers
@demiculus @JuanRoman77 @Mau-MD

**Comment by Mau-MD** [comment]
Wow Study C is amazing! I love it. Thanks!!

**Comment by rgsthethird** [comment]
These look amazing! 💪

**Comment by Esqarrouth** [comment]
I like B corners with C background

**Comment by rgsthethird** [comment]
I also like C. For the preview video, would it be better to have the resource tiles/card be more vertically centered? It seems like they're a bit close to the bottom
