### ISSUE TITLE
Buy Dev Card Button

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#328]
## Description

During playtesting player was confused about the `buy development card button` 

Considered making this icon the actual card back, not just the hand with a hammer.

![image](https://github.com/colonistio/design/assets/6215305/e35d9c0b-df79-4b83-8ee3-b13c878998d9)

## Actions

- [ ] Come up with button ideas
- [ ] Verify if the current players will like the button
- [ ] Ask new players "What do you think this button does" and verify which of the designs is the most understandable

## Reviewer

@demiculus @huaniebun @rgsthethird @samanthax7

**Comment by JuanRoman77** [comment]
I think it's safe to update the icon to the actual dev card back, like so:
![image](https://github.com/colonistio/design/assets/73320460/7704a196-6309-4c04-a054-e8c24634e90e)

**Comment by samanthax7** [comment]
Currently collecting feedback for these designs and asked around 5 users, so far people like having it as just the back of the development card. 

[https://www.figma.com/file/FKUOkPSzujeXpVfXWLChHo/Trade-System-(Samantha)?type=design&node-id=165-263252](url)

<img width="818" alt="Screen Shot 2023-05-17 at 10 20 15 PM" src="https://github.com/colonistio/design/assets/31858793/ee54edbf-afa3-48bd-a8f9-cbbddc75247e">

**Comment by demiculus** [comment]
https://github.com/colonistio/katan/issues/11108
