### ISSUE TITLE
Gaining Victory Points Is Clearer

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#331]
## Description

Its not clear when we gain Victory points

## Actions
- [ ] Make a list of all the Victory points gained
  - Building Settlement
  - Building City
  - Dev cards (Victory Points) 
  - Progress cards (Constitution, Printer) 
  - Longest Road
  - Largest Army
  - Defender of Colonist (defeating barbarians) 
  - Gaining Metropolis 
  - Settle on Foreign Land 
  - Place Merchant 
- [ ] Categorize these
- [ ] For each category do an animation showing the VPs gained
  - What I have in mind https://www.loom.com/share/fc9698bd1a0c466c9268e12a0f4b4e2d
- [ ] Consider other edge cases

## Reviewer

@demiculus

**Comment by samanthax7** [comment]
I
