### ISSUE TITLE
Web Room - Mode & Map Previews

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#337]
### Current

<img width="1354" alt="image" src="https://github.com/colonistio/design/assets/6215305/b2a50518-5806-4601-8ba1-f16b874a2157">

<img width="1368" alt="image" src="https://github.com/colonistio/design/assets/6215305/8124c925-4a00-4b0d-888f-f04e932d5d65">

### Problems

1. Player doesn't know what the mode & map is
2. Player doesn't know which ones are premium which ones are free
  - Weekly free map is rotating so thats an edge case
4. Its not clear which ones used to be premium but they purchased

We will be adding this to discord as well.

## Actions
- [ ] Read everything in resources
- [ ] Do research
- [ ] Break down the designs and create a submission with many smaller decision parts (like, size of image, how to navigate between images, how to select, how to show, etc..)
- [ ] Iterate

## Resources
- https://discord.com/channels/605233308577562643/1055023081845968926/1120774197447233626
- Mobile room design, check out from mobile figma master file
- https://discord.com/channels/605233308577562643/1115534750401167411/1115896669104517190

## Reviewer

@demiculus @rgsthethird @JuanRoman77

**Comment by Mau-MD** [comment]
we can do something similar to what we have currently on mobile.

the users can clearly see what each gamemode is and a small preview of it

![CleanShot 2023-06-20 at 21 53 48@2x](https://github.com/colonistio/design/assets/74751751/8acd630a-2bc7-4cb8-9067-3bac0158fbf9)

**Comment by oguzilerle** [comment]
> Player doesn't know what the mode & map is

do we want to let player learn about modes&maps that they own? 
do we want to let player learn about modes&maps even if they don't own?

I'd prefer second option, but both options seem like progress. 
Asking to be able to provide proper feedback on designs
