### ISSUE TITLE
Create a hint animation

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#338]
## Description

We want to suggest the players specific actions on the board without intruding.
We need a sparkle type of animation for it.
We don't want to download a 500kb gif
Ideally its 4 * 4kb images. That can be stitched together with code. Or a 16 kb gif is better, then we don't need to stitch them with code.

The case we'll be using is 

- When a new player wants to place a settlement but doesn't know where is a good spot (since they don't know numbers or anything else)

We might use it on other cases in the future

## Actions
- [ ] Research candy crush
- [ ] Research other games
- [ ] Create a nice gif
- [ ] Once approved create 2 development issues
  - [ ] Showing the image on specific locations according to dummy logic
  - [ ] Implementing the logic to make sure the hints we show are top notch to newbies

## Reviewer

@demiculus @oguzilerle @huaniebun

**Comment by huaniebun** [comment]
PIP info solves this problem
