### ISSUE TITLE
In Game - Create Sound Effects (SFX Improvement)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#34]
### Old Issue
- https://github.com/colonistio/katan/issues/139

## Description

- Getting new cards sound
- Placing Road sound
- Placing settlement sound
- Placing city sound
- Getting development card sound
- Using development card sound
- Losing sound
- Move knight sound
- Add a game start noise so the player can know the game is starting
- Add bg music
- Find a better turn timer
- Inactive button sounds (to let the player know that the button is inactive)
- Announcement popup sound

**For audios**
You can use free audio
You can use licensed audio ones whos license we can purchase
You can suggest any other audio and we can tell someone to create something similar.

## Resource

- https://colonist.featureupvote.com/suggestions/86329/sound-alert-when-trade-is-made
- https://colonist.featureupvote.com/suggestions/150465/sound-on-disconnect
- https://colonist.featureupvote.com/suggestions/106144/sound-effects-for-placed-roads-settlements-cities-etc-please
- https://colonist.featureupvote.com/suggestions/133635/sound-alert-when-your-special-build-phase-starts
- https://colonist.featureupvote.com/suggestions/92629/make-sound-toggle-different

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by demiculus** [comment]
@H5KY see if there is anything you can take from this issue.

**Comment by demiculus** [comment]
@JuanRoman77 see if we need to do anything about the feature upvote suggestions.

Also @H5KY check if there are other sound related feature upvote suggestions

**Comment by H5KY** [comment]
> @H5KY see if there is anything you can take from this issue.

Yeah almost everything is already in our main audio list! Thanks for tagging me.
