### ISSUE TITLE
Player doesn't know the starting elements

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#341]
When the game starts, player doesn't know what to place and how many of them.

In base game -> 2 settlements 2 roads
In C&K -> 1 settlement + road then a city + road

We will have more types of games where the player might start off with only a single settlement or double cities etc.. 

It should be clear what they're starting with.

**Comment by Esqarrouth** [comment]
And also the snake case building order

**Comment by demiculus** [comment]
https://github.com/colonistio/katan/issues/12279
