### ISSUE TITLE
Game UX - Dust Animation During Placements

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#345]
## Description

When placed a settlement we should show a dust animation

![image](https://github.com/colonistio/design/assets/6215305/7fedba8a-dfed-457c-8e66-02eb7a0484f8)

https://youtu.be/UloCB1f2BnQ?t=65

## Actions
- [ ] Find or create one. 
- [ ] Dust for my player should feel much stronger than for other players
- [ ] Think of the second order effects and other type of buildings & game modes

## Reviewer

@demiculus marc

**Comment by ayden1z** [comment]
I researched for assets but couldn't find any useful one. So i started to create dust/smoke effect on Figma. We can export the effect as Lottie JSON. I created this effect by 3 frames. We can change the dust/smoke effect by player's colors. Like red player will have red dust/smoke effect. Thank you in advance for your comments.

https://github.com/colonistio/design/assets/70596654/76b8291d-5065-4486-b29e-dafcb2cd69b2
![image](https://github.com/colonistio/design/assets/70596654/810dd995-7e2a-4c1a-b966-1b8ee16f06ad)

**Comment by ayden1z** [comment]
Created .GIF & .WEBM assets for this issue.
Link to download: https://www.dropbox.com/home/Smoke%20Effect?share_manage_access=false
Link to animation: https://app.lottiefiles.com/share/098d5cd6-3873-4732-a885-384626fa52b9
Link to design: https://www.figma.com/design/ULjVcGEGY6vHYy2xjie0hY/Aydeniz---Issue-Solving?node-id=100%3A36176&t=YdgUWNJyu3saIwRt-1

https://github.com/colonistio/design/assets/70596654/4ddce65f-eb0a-4b89-838c-c3cd37b3cb2c
