### ISSUE TITLE
Store & Checkout Future A/B Test Ideas

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#38]
## Description

This is a dump of ideas to test for when we start optimizing. While dumping an idea please use the format. We will not have the resources to test all ideas. We will select the most promising ones during testing phases.

Related
- https://github.com/colonistio/design/issues/5
- https://github.com/colonistio/design/issues/6
- https://github.com/colonistio/design/issues/16
- https://github.com/colonistio/design/issues/37

Moved ideas here:
https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=1245841763

**Comment by samgawaran** [comment]
Added the ideas from the previous [A/B test](https://github.com/colonistio/design/issues/16) issue here. Filtered out some of the ideas that we wouldn't be moving forward (ex. adding subscription length in the checkout page)

**Comment by goktugyil** [comment]
> I did not use any of the A/B test images in this submission, I figured that showing the membership icons is better rather than some generic icons that we used during testing.

First test had an extremely high conversion rate compared to the others: https://github.com/colonistio/katan/issues/6266
My theory is using banners that has those images might increase our conversion rate by 4x

**Comment by goktugyil** [comment]
Do this test: https://github.com/colonistio/katan/issues/6267

**Comment by demiculus** [comment]
Trial Subscription

If stripe has such a thing. We can test, They enter their credit card, play free for 7 days. If they don't cancel within the time they will start being charged.

**Comment by JuanRoman77** [comment]
> Trial Subscription
> 
> If stripe has such a thing. We can test, They enter their credit card, play free for 7 days. If they don't cancel within the time they will start being charged.

Looks like it has https://stripe.com/docs/billing/subscriptions/trials

**Comment by goktugyil** [comment]
## Next Test
* It is too hard to change prices on payment provider side
* This test will not change the actual price, it is just a visual indicator, just to capture interest
* We'll change the official prices after we reach a strong conclusion
* Instead of 130K Distinct values of User Id, this test should be assigned and we should know how many people got into the store
* In addition to how many people purchased which version, we need to know how many people `Subscribe` button
* Show these prices:
  * Control: 
    * Yearly: $6.99 | $14.99 | $19.99
    * Monthly: $8.99 | $18.99 | $24.99
  * A: 
    * Yearly: $5.99 | $13.99 | $18.99
    * Monthly: $7.99 | $17.99 | $23.99
  * B: 
    * Yearly: $4.99 | $12.99 | $17.99
    * Monthly: $6.99 | $16.99 | $22.99

**Comment by demiculus** [comment]
Aggregated the useful looking & nonimplemented ideas here: https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=304465379
