### ISSUE TITLE
Profile Page Submission #2 - Profile Overview Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#41]
## Summary
- Proposing some designs for our profile page. Started with presenting screenshots first before doing whole prototypes to explore faster

## Details
- https://www.loom.com/share/9a03e7b6809c4a2e943534d40b296899

## Previous Submissions
- https://github.com/colonistio/design/issues/40

## Resource:
- [Findings from Competitor Analysis and Feature Suggestions](https://user-images.githubusercontent.com/90673012/167742178-2239e4a6-7afa-4e5b-bd6f-068239cd10f0.png)
- [Competitive Analysis](https://user-images.githubusercontent.com/90673012/167742542-c5fd3551-e1df-4a06-9fa1-2c4ce248bcb0.png)
- [From Feature Suggestions](https://github.com/colonistio/design/issues/2)

## Related Links
- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [x] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [x] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
@demiculus @JuanRoman77 for review

Designs are based on research done in issue: https://github.com/colonistio/design/issues/40

**Comment by demiculus** [comment]
@alperozgunyesil

**Comment by demiculus** [comment]
Dont worry about english & politeness. We're a pragmatic team focused on getting shit done.

@alperozgunyesil as mentioned in https://github.com/colonistio/design/issues/41#issuecomment-1123358592 number2, we want to avoid double horizontal tabs https://i.imgur.com/73FTQgV.png. I feel like its a bad design, feel free to educate me on that.

Also check out all our other pages 
https://colonist.io/press-kit
https://colonist.io/faq
https://colonist.io/jobs
https://colonist.io/store
https://colonist.io/leaderboards

The navigation section is on the left side. We want to keep it consistent as much as possible.

**Comment by alperozgunyesil** [comment]
I wouldn't say it's bad, it's consistent in its own realm there is no one truth in this work. but you are craving consistency of the bigger picture, which is good. let me think about how we merge these two approaches. I'll get back to you guys ASAP
