### ISSUE TITLE
Profile Page Submission #3 - Overview Screen Studies Iteration 2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#42]
## Summary
Designed a new iterations for the overview tab based on feedback gathered from [Profile Overview Studies](https://github.com/colonistio/design/issues/41) 

## Details
https://www.loom.com/share/5b4765d15a194150b9d9e916a6a74829

## Previous Submissions

- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [x] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [x] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
@demiculus @JuanRoman77 @alperozgunyesil for review

**Comment by alperozgunyesil** [comment]
hey @samgawaran! I like the new searches. all of them come with lots of potential. Of course, the vertical one is going far more mature than the others.
Even though I don't have a problem with the secondary horizontal bar; to fulfill the left side menu item wish, last night I made something like this https://imgur.com/uEhqsXK

 BUT, I don't think it is necessary...
https://imgur.com/RU90lty you are using a similar thing in other designs from time to time.  and the presence of a search bar kinda makes it legit.  lastly thanks to your layout all of the elements in the right work together as a whole. so it makes them one big vertical shape if you squint your eyes...  Other compositions look a bit forced than the vertical ones, so my advice keeping the fricking horizontal bar guys :D

**Comment by demiculus** [comment]
Profile page design: which design type should we go with and why?
A. https://i.imgur.com/2Y82K0O.png
B. https://i.imgur.com/owxQ2Gv.png

Change B like this: https://www.loom.com/share/9383f1158b66437d9283c2820ad23a61 and lets try that. Then we can decide the placements. 

When it comes to this part, it feels very crowded https://i.imgur.com/7fMbny6.png how can it be better, more relaxed?

**Comment by JuanRoman77** [comment]
@demiculus The side navigation being **below** profile content is inconsistent with the rest of the site.

**Comment by samgawaran** [comment]
> The side navigation being below profile content is inconsistent with the rest of the site.

I agree with this too. Though I'll try doing that idea for iteration 3. We can probably allow the profile page to be unique? since its more on the social part of the game and profile pages are generally different compared to other screens.

I'll try coming up with something similar to B as well. ping you guys later

**Comment by alperozgunyesil** [comment]
Hey guys, have a great week.

Let's begin with the crowded content area. i have a little solution: https://imgur.com/qW7OeRH since all the dudes have this ranked etc. changing area, we can tuck all of them under this bigger thingy. I think it is more readable and pleasing and also more convenient because the older version was less clickable. 

but you may say the area is still crowded, and you would probably be right, so I tried this: https://imgur.com/I92lECq of course its typography is pretty bad rn but I am sure @samgawaran's magic touch can create wonders with it.

**Comment by alperozgunyesil** [comment]
I agree with @JuanRoman77 

but wanting to keep the profile constant is a reasonable wish so i can offer these guys https://imgur.com/9DtIITj
