### ISSUE TITLE
Profile Page Submission #5 - Items Screen Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#44]
## Summary
Design proposals for the Items Tab. I made sure that the designs could work on the studies for both [overview](https://github.com/colonistio/design/issues/42) and [match history](https://github.com/colonistio/design/issues/43) tab

## Details
https://www.loom.com/share/dc6805d179aa4251959209618c1849ee

## Previous Submissions

- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [x] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [x] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [x] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review: 
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

**Comment by JuanRoman77** [comment]
Same feedback as in here [
Profile Page Submission #4](https://github.com/colonistio/design/issues/43#issuecomment-1127213852), since I reviewed these designs before this issue was created.

**Comment by demiculus** [comment]
I like the collectables version. We can remove the Packs for people who don't have presale packs. The rest is nice 👍
