### ISSUE TITLE
Profile Page Submission #5 - Membership Screen Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#45]
## Summary
Design proposals for the membership tab. This tab is only accessible to players looking at their own profiles. for guest players, they will only see Overview, Match History & Items

## Details
https://www.loom.com/share/b4d7aa81e0524ee49203c682312df70e

## Previous Submissions

- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2- 

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

After this submission, I'll revisit the previous studies and see what I could finalize before doing the scenarios

**Comment by demiculus** [comment]
Put the membership tab at the front. It should show on all players so other players are incentivized to become member as well. It should be the default tab when the profile opens: 

![image](https://user-images.githubusercontent.com/6215305/168534788-0297ce8b-599c-452e-ad42-cb691cb4f4d3.png)

The rest is good

**Comment by JuanRoman77** [comment]
> Put the membership tab at the front. It should show on all players so other players are incentivized to become member as well. It should be the default tab when the profile opens:
> 
> ![image](https://user-images.githubusercontent.com/6215305/168534788-0297ce8b-599c-452e-ad42-cb691cb4f4d3.png)
> 
> The rest is good

This is not a good idea. Overview is the main tab in all games. The Membership tab shouldn't even be visible for other users. That's why we need the golden stroke, and the achievements section in the overview tab, to display best ranking in past seasons or something like that.
