### ISSUE TITLE
Profile Page Submission #7 - Membership Screen Research

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#46]
## Summary
Did some research to improve decision-making on what and what's not to include on the membership page. 

## Details
![image](https://user-images.githubusercontent.com/90673012/168615276-dd1df8b2-9160-4ba4-8181-3baa935a0923.png)

## Findings
- Not required to show both billing and payment history on one page
- Add a section on the FAQs page about Billing and Membership

> When it comes to the membership page, can you show examples of other products? I don't ever remember seeing all the previous payments in any app that I used. We should hide the cancel button even more. Think of where we can hide it.

@demiculus for both of these, I suggest we follow Youtube's design of hiding the cancel and billing history inside the card via a dropdown. That way we are not showing the cancel button and at the same time keep the layout simple.

## Previous Submissions

- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2- 

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
@demiculus @JuanRoman77 for review:

not tagging the contributors since this is research, or should I tag them as well?

**Comment by demiculus** [comment]
> should I tag them as well?

its fine

> I suggest we follow Youtube's design of hiding the cancel and billing history inside the card via a dropdown. That way we are not showing the cancel button and at the same time keep the layout simple.

ok looking forward to the designs
