### ISSUE TITLE
Profile Page Submission #9 - Profile Page Scenarios

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#48]
## Summary
Scenarios/Screen flows that are needed for the profile pages

# Profile Page Scenarios

### Owner
- When a player clicks on their own Profile
     - Header Tab
     - In-Game Screen
     - Leaderboards
     - Room Lobby
     - Search Bar
- When a player wants to share their own profile

### Guest/Other Signed Users
- When a player clicks on their another player's profile
     - In-Game Screen
     - Leaderboards
     - Room Lobby
     - Search Bar
- When a player wants to block/report the player
- When a player wants to share the profile of the player
- When a player wants to add the player
- When a player wants to send gifts to the player

## General Scenarios
- Make all tabs/selectors interactive with hover states
- Button hover states 
- interactable search bar
- Loading screens / No internet connection

## Overview Tab
- When a player clicks on each game mode filter:
      - Ranked
      - Unranked
      - All Time
- When a player clicks on the division/game mode icon 
- When a player doesn't have placement games and ranked stats yet

## Match History Tab
- When a player scrolls down/up
- When a player clicks on another player's name
- When a player clicks on a specific match history
     - expanded match history card view

## Items Tab
- When a player scrolls down/up
- When a player doesn't have any items purchased
- When a player has an item purchased
- When a player purchased all items in a category
- When a player wants to gift an item to another player

## Friends Tab
- When a player has no friends yet
- When a player has friends on their friend list
      - Enough friends to scroll down/up

### Player has a membership
- Player clicks on update billing info
- Player expands the billing info
      - Player clicks on cancel membership
      - Player updates payment method
       
## Edit Profile Tab
- Player edits their avatar
- Player edits their username
- Player edits their default color

=====================================================================================

## Previous Submissions
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
@demiculus @JuanRoman77 for review:

same with the [Profile Page Requirements](https://github.com/colonistio/design/issues/47) let me know if I miss something here. Otherwise, leave a like and I'll add the link to the master profile page issue

Edit: Added Share, Add Friend, Gifting, Block & Report features

**Comment by JuanRoman77** [comment]
Access points:
Owner

- Header Tab: Yes
- In-Game Screen: Yes
- Leaderboards: No, use dropdown. Clicking on your own row should focus your position in the leaderboards. 
- Room Lobby: No, if they are about to start a game don't drive them away from the room. 
- Search Bar: Yes
- Url: Yes

Guest
- In-Game Screen: Yes
- Leaderboards: Yes
- Room Lobby: No
- Search Bar: Yes

**Comment by demiculus** [comment]
> Leaderboards: No, use dropdown. Clicking on your own row should focus your position in the leaderboards.

Clicking on your own row when it isn't on the table list, should focus. When it is on the table list, should act like clicking on anyone else

> Owner Room Lobby: No, if they are about to start a game don't drive them away from the room.

Agree

> Guest Room Lobby: No

Disagree, we should be able to click & go to other peoples profiles

**Comment by JuanRoman77** [comment]
> Clicking on your own row when it isn't on the table list, should focus. When it is on the table list, should act like clicking on anyone else

1. It's too specific, too much optimization. 
2. Behavior shouldn't change; if clicking focuses, clicking when it's on the middle table list should focus again (sticky to the bottom).
3. Profile access point is in the dropdown list, there's no need to add more for each single page.

> Disagree, we should be able to click & go to other peoples profiles
1. I don't want people delaying the start of a game because they are checking other players' profiles. This should be solved with the room redesign (for example displaying win% and games played on hover). But sure, we can keep that in this list.
