### ISSUE TITLE
Subscription - P3: Design Research

### ISSUE THREAD

**Issue by goktugyil** [colonistio/design#5]
## Description

Before designing subscription page we should do some research. You're going to gather information like you did in the previous times. Things you should pay attention is specifically UX, categorizations, placements, subscriptions

## Store UI:

Gather screenshots and informations from these sites just as you do for other pages

- [ ] https://www.chess.com/membership
- [ ] https://littlebigsnake.com/ VIP Tab
- [ ] Find 3 other sites with subscription, add more sites if you still see something new. 
    - When to stop exploring. Each site you check out you're going to see something interesting and new. After a certain amount of sites, things are going to start repeating themselves. Once that happens for 3 sites you probably collected most of the information. As long as you see something new/interesting research more sites.

## Xsolla:

For the below websites go in and make a payment purchase a few separate things. While doing it take a loom video of it. You should request reimbursement from Mayla for the purchases. 

- [ ] [tetr.io](http://tetr.io/)  
- [ ] https://venge.io/ 
- [ ] Find a game that is more op and go in and make payments as well. https://xsolla.com/portfolio

**Comment by samgawaran** [comment]
**Store Page UI Analysis**
![image](https://user-images.githubusercontent.com/90673012/163316844-a419ca02-2843-47c3-adee-7c953b512012.png)

**Payment Page UI Analysis**
![image](https://user-images.githubusercontent.com/90673012/163316928-37cc727f-255e-479a-8b6e-659aef261d43.png)

**Recommendations / Next Steps for Store and Payment Design**
![image](https://user-images.githubusercontent.com/90673012/163317024-b9e28220-bfe8-4335-ac8c-4918ece59aa1.png)

**Comment by goktugyil** [comment]
I also checked but didn't include platforms like steam, gog, roblox because their offerings are not relevant to us.

**Comment by goktugyil** [comment]
- Owned items, could have a check mark? 
- Should we show renews on x date? I'm not sure if that provides benefits?

I agree with all the other recommendations and next steps

**Comment by demiculus** [comment]
One question is are we going to allow purchasing subscription with coins or $s or both? I think we concluded on both initially right @goktugyil ? We ideally wan't them to purchase directly with $ so that after X months we can auto charge until they cancel their subscription. 
So the design should make it easier to purchase with card rather than coins.

**Comment by goktugyil** [comment]
> I think we concluded on both initially right

Both until 2023

> So the design should make it easier to purchase with card rather than coins.

Yes. @samgawaran  keep this in mind, the card purchase method should be supeeer smooth. The way to purchase with coins could be even semi hidden or hard to navigate to. Design it as so it is easy to remove

**Comment by goktugyil** [comment]
https://user-images.githubusercontent.com/5816878/165802487-39b88f18-8145-434d-bd63-fbabc2cb1a2e.mov
