### ISSUE TITLE
Profile Page Submission #11 - Profile Tabs (Owner View)

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#50]
## Summary
Collated all comments from previous submissions and created an initial prototype for the Owner View of the profile page. Showed pages that are exclusive for owners only like Membership

## Details
https://www.loom.com/share/71193c95084c480ea739b7444b9a973f

## Previous Submissions
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [x] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [x] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

**Comment by JuanRoman77** [comment]
1. Don't add edits!! Let them use the dropdown for that. Don't add unnecessary buttons. Already gave this feedback twice 😅
2. Overview header should look the same for own view, and for visitors view. When I go into my profile I want to see the same stats I see when I visit another players'. For consistency and easier comparison. https://i.imgur.com/bk0PzLv.png
3. Don't show Membership price as default. Hide that under Manage Membership https://i.imgur.com/moxAwAU.png

**Comment by demiculus** [comment]
Friends should be a table list. Will inlude stuff like last online, message etc..
