### ISSUE TITLE
Profile Page Submission #12 - Profile Tabs (Guest View and Owner View) Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#51]
## Summary
- Adjusted designs based on comments and feedback from issues: https://github.com/colonistio/design/issues/49 & https://github.com/colonistio/design/issues/50

Note: only contain Profile Tabs and some vertical scrolling on pages that need it. No access points yet (ex. Lobby to Profile)

## Prototypes
Guest View:
https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=3245%3A57499&node-id=7194%3A345693&viewport=857%2C4514%2C0.25&scaling=scale-down&starting-point-node-id=7194%3A345693

Owner View:
https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=3245%3A57499&node-id=7201%3A350854&viewport=857%2C4514%2C0.25&scaling=scale-down&starting-point-node-id=7201%3A350854&show-proto-sidebar=1

## Previous Submissions
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [x] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [x] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

**Comment by samgawaran** [comment]
For Review: 
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

please click the links on the prototype section, thanks

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/169658851-65ffa7eb-e0cc-4a4a-8b3a-b573623d2347.png)

1. No need to have 2 buttons. Adding/removing friends can go inside the options menu ( **...** ). By the way, what else would go in there?? Report?
2. `Total Won Games` -> `Total Win/Lose`
3. `Winrate` -> `Win Rate`
4. `Total Games Played` -> `Total Played`
5. Smaller expansions icons
6. Too big. This number doesn't mean anything if looked at alone. It only does when looked at in the leaderboards when it's on a list and can be compared to other values and players' positions. Place it below Ranked/Unranked, and include highest rank (Singapore #78) 
7. Carousel menu for only 2 options doesn't make much sense. I think a dropdown works but it might not look great. Try something different? 
8. This design is still too Member oriented. And even if they are not members, but play Ranked limited free, there might be seasons where they don't play any games. 
- How would the profile look for a Member who has not played ranked?
- How would the profile look for a User who is not a member but has played limited free?
- How would the profile look for a User who is not a member and hasn't played limited free?
- Where can I see past seasons, best positions, achievements, divisions, etc.? 
This whole section takes too much space https://i.imgur.com/eximuRy.png

Also I think you missed this https://i.imgur.com/YkABfXQ.png

**Comment by samgawaran** [comment]
Hey, answering Juan's comments here before doing the new submissions:

1. Yep, it was originally just report and block since Add Friends is outside, though I agree that its neat to have it all inside the `...` button.

2. It should only show the games won by the player right? making it Total Win/Lost makes it inaccurate

3. 4. 5. 6. Agree on all of this 

7. it shows 3 options `Unranked` (default on loading) `Ranked` and `All-Time`, I'll try to check another way but having them as that carousel option seems the easiest for the UX

8. Yes, that's why the idea is to set `Unranked` as the default when the page is loaded.

> How would the profile look for a Member who has not played ranked? How would the profile look for a User who is not a member but has played limited free? How would the profile look for a User who is not a member and hasn't played limited free?

I'll present them via loom on future submissions

> Where can I see past seasons, best positions, achievements, divisions, etc.?

for past seasons, all will be included in the `All Time`, achievements can be shown in another tab but that's a huge task in itself, I would want to decrease the scope for now since that feature will probably be months away. for Divisions, I interchanged it with the game mode icons from my earlier iterations, we can also do that if its finalized already.

**Comment by JuanRoman77** [comment]
> 2. It should only show the games won by the player right? making it Total Win/Lost makes it inaccurate

Total Win/Lose
236/1343

> it shows 3 options Unranked (default on loading) Ranked and All-Time, I'll try to check another way but having them as that carousel option seems the easiest for the UX

Yeah try something different, not seeing the other options when the content is not clear is not great UX. Speed setting in room is clear because it has a title (Game Speed https://i.imgur.com/StYWEcb.png), and it's obvious what's inside the carousel. This could be clearer imo.

> I would want to decrease the scope for now since that feature will probably be months away

It's not increasing the scope. It's about designing now considering future elements. We need to know now where the achievements will go. We don't need to know now how the achievements page will look like.

> Yes, that's why the idea is to set Unranked as the default when the page is loaded.

I get that, but most players will not play unranked via MM. They play against bots, or against friends. This design focuses on people playing via Matchmaking, and takes a lot of space.
