### ISSUE TITLE
Checkout Page Submission #1 - Payment Method to Purchase Detail Spacing A/B Test

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#52]
## Summary
A/B Test scenarios screens on @goktugyil feedback here: https://discord.com/channels/605233308577562643/790772223358402571/978367468894576720

## Details
![image](https://user-images.githubusercontent.com/90673012/169939939-0db5bb7a-f1f4-4023-af25-f8b844b8791a.png)

## Related links

- https://github.com/colonistio/design/issues/6

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
@demiculus @JuanRoman77 @goktugyil for review:

adding Goku here since the A/B test is based on his feedback

**Comment by goktugyil** [comment]
Give your opinion too when you create these
I think 80px is the best

**Comment by samgawaran** [comment]
160px spacing = I tried to follow the grid format that we use. Though I agree the spacing is too wide because of it.

120px= Middle ground of the 80px and 160px, I like this better compared to 160px since it's just the right amount, and the spacing on the right margin is not too wide

80px= I prefer this too. I think going smaller than 80px makes the right margin too wide. Also having it on 80px makes it easier for players to click on `Buy Now` after they selected a payment method.

If we all agree, I'll adjust the spacing of the next iterations by 80px

**Comment by goktugyil** [comment]
Go ahead, are you creating an implementation issue?

**Comment by samgawaran** [comment]
> Go ahead, are you creating an implementation issue?

Yup, I created this: https://github.com/colonistio/design/issues/58
