### ISSUE TITLE
Checkout Page Submission #2 - Minor Fixes and Changes 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#53]
## Summary
Collated some feedback/comments from the Colonist Team on Discord and iterated on the checkout page.

## Details
![image](https://user-images.githubusercontent.com/90673012/169971419-ba64a6d9-bf27-4733-9298-18bc25f4b2b5.png)

1. Moved the `powered with stripe` badge in near the secure guarantee based on this: https://prnt.sc/iNvOF7NIcxx6
2. Talked to Goku and found out that Xsolla requires these words on the checkout page. removed the Paystation icon since the logo is more commonly used. https://prnt.sc/YuCiRwIpWW7n
3. Changed from `Review Your Order` to `Purchase Details`
4. Increased spacing by 4px per payment method
5. Removed Paystation icon

For the spacing A/B Test - refer to issue #52 

## Past Submissions
- https://github.com/colonistio/design/issues/52

## Related links

- https://github.com/colonistio/design/issues/6

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
@demiculus @JuanRoman77 @goktugyil for review

**Comment by goktugyil** [comment]
I think we can move guaranteed & stripe part to below too? It doesn't have to be at top. I'm fine with other changes.

I'd like to add, should we group google/apple together & paypal, bitpay, amazon pay together?

**Comment by JuanRoman77** [comment]
Agree, Xsolla and Stripe references should be together at the bottom.
Should we move "We do not store..." to the top, right below Select Payment Method? Seems logical

**Comment by samgawaran** [comment]
> Should we move "We do not store..." to the top, right below Select Payment Method? Seems logical

I think @goktugyil mentioned before that part shouldn't be too highlighted. I suggest we move it all down at the bottom. Sending a new iteration later

**Comment by samgawaran** [comment]
> google/apple together & paypal, bitpay, amazon pay together?

No, based on my research, games and gaming platforms like GOG and Steam shows them separately on their payment options
