### ISSUE TITLE
Profile Page Submission #14 - Overview Tab (Game Mode Stats) Ideas

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#55]
## Summary
Explored some ideas on how we could present the game mode stats. Got feedback from @JuanRoman77 that the Game Stats in Overview is reliant for players to play via Matchmaking

## Details
https://www.loom.com/share/26eae3a25a0d4531b4edea0cb45693ee

## Previous Submissions
- https://github.com/colonistio/design/issues/54
- https://github.com/colonistio/design/issues/51
- https://github.com/colonistio/design/issues/50
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review: 
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

**Comment by JuanRoman77** [comment]
Gave feedback in https://github.com/colonistio/design/issues/57
