### ISSUE TITLE
Checkout Page Submission #3 - Minor Fixes and Changes Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#56]
## Summary
Collated Feedback/Comments from Issue: #53  

## Details
![image](https://user-images.githubusercontent.com/90673012/170171307-a8754538-a29b-42a6-829f-23e09b4a7700.png)

1. Moved Guarantee... and Stripe Badge at the bottom as suggested
2. Moved "we do not store payment info" near the `Buy Now` button since retaining it at the bottom with the Xsolla and Stripe badge makes it feel clogged. Also placing it here is good UX since after the player picks a payment method and proceeds on buying the item, they will see that we don't collect any of their payment info.
3. For consistency, I reworded `Pay Now` to `Buy Now` while checking this: https://demi.katan.io/checkout?coinProduct=0
4. Created a generic card icon for Other Local Methods. I used the blue bgs we used for the popups for consistency

## Past Submissions
- https://github.com/colonistio/design/issues/53
- https://github.com/colonistio/design/issues/52

## Related links

- https://github.com/colonistio/design/issues/6

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
@goktugyil @demiculus @JuanRoman77 for review:

**Comment by goktugyil** [comment]
Stripe could be moved to a new line

Other parts approved
