### ISSUE TITLE
Profile Page Submission #16 - Overview Tab Exploration Iteration #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#59]
## Summary
Collated feedback/ideas from https://github.com/colonistio/design/issues/55 and explored more. 

had some discussions with @JuanRoman77 and I redid the profile sticky to just contain the `Avatar / Username / Friend Dropdown / Search` this makes the sticky cleaner and opens up more possibilities for design exploration. this also moves down the "Account Stats" on the overview content 

## Details
![image](https://user-images.githubusercontent.com/90673012/170498118-4c0875fd-5373-4570-bf5c-fdac326f0733.png)

**Tabs**
- We are using tabs on our leaderboards so this is already being implemented. I had to separate the rankings with the game modes since Unranked and All-Time don't use rankings

**Season Stats** (Recommended)
- No buttons are needed to adjust the game type since everything is presented in one card. Added info icons if players want more context, removed all-time as a game type since it's being shown in account stats but in a more general way so we present them with less info but it's more condensed.

**Carousel (Arrow)**
- current layout in the main flow, just centered the win% and prioritize the global rankings over the MMR

## Previous Submissions
- https://github.com/colonistio/design/issues/57
- https://github.com/colonistio/design/issues/55
- https://github.com/colonistio/design/issues/54
- https://github.com/colonistio/design/issues/51
- https://github.com/colonistio/design/issues/50
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil

**Comment by samgawaran** [comment]
> For Review: @demiculus @JuanRoman77 @huaniebun @alperozgunyesil

hey guys, reminding you with this, no hurries though. also @DyLightedCatan Demi told me to tag you on my submissions, this is the latest of the design submissions for the profile but you can see some of the previous submissions in the details too :)

**Comment by JuanRoman77** [comment]
> Juan already commented on this via Discord

For the record, I requested putting ranked information inside Ranked tab because the vast majority of the players will not have anything to display, since they play vs bots or friends. So showing all these numbers in the main overview tab doesn't make sense.
