### ISSUE TITLE
Jobs Page Submission #1 - Guild Vacancies Card Improvements

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#61]
## Summary
The current design is not that recognizable. Explore new ideas to make the cards more visible upon visiting the jobs page

## Details
https://www.loom.com/share/466450ce8b6f4dfdaafab43d270fbc01

## Suggestion
`I love Colonist, I'll do anything` can be framed better by renaming it as `Volunteer/Contribute` or `Help us out!` what do you guys think?

## Related links

- https://github.com/colonistio/katan/pull/7249

## Submission Checklist

- [x] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [x] I considered horizontal & vertical mobile devices
- [x] I considered small & large screen desktop devices
- [x] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [x] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [x] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @goktugyil @JeffdEon

the [hiring process design](https://prnt.sc/HrKlqpMyw-QZ) will be presented in a separate submission

**Comment by goktugyil** [comment]
<img width="646" alt="Screen Shot 2022-05-28 at 12 35 33" src="https://user-images.githubusercontent.com/5816878/170834441-e5764a56-8b91-4342-864c-a935dbb10e7a.png">

I liked this, no way to miss the button

**Comment by JuanRoman77** [comment]
View -> Apply ?

**Comment by samgawaran** [comment]
> View -> Apply ?

Might be redundant because there's also an `Apply` button inside each job detail

> I liked this, no way to miss the button

we good with this @demiculus ? if yes, I'll update the one in the master file

**Comment by goktugyil** [comment]
> View -> Apply ?

I've already changed the text

**Comment by samgawaran** [comment]
Approved Design
![image](https://user-images.githubusercontent.com/90673012/173981474-e9fd0743-a618-4e04-b3dd-099548010aa6.png)

**Comment by JuanRoman77** [comment]
Buttons go at the end @goktugyil

**Comment by goktugyil** [comment]
> Buttons go at the end @goktugyil

Is that a question or a task or comment? I didn't understand

**Comment by JuanRoman77** [comment]
A comment, since you approved the design and it is flawed. My comment is letting you know that the implementation issue for this task requires the buttons to go at the right, not at the left.

**Comment by JeffdEon** [comment]
Since when are random banners in the middle of walls of text buttons to click on? 

Table would be much nicer with button inside to click `apply`. At least with the buttons on the left I can see its a button.

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/58959537/174198433-31a392ae-7351-4d4d-b60f-7e8963730efe.png">

**Comment by demiculus** [comment]
Leave it as it is, move on to other stuff. Its fine enough
