### ISSUE TITLE
Jobs Page Submission #2 - Hiring Process Infographic

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#62]
## Summary
Current hiring process info looks like this:
![image](https://user-images.githubusercontent.com/90673012/170832263-192acea5-68a2-4577-8da6-b4e930df9ba0.png)

Potential applicants might like it if they see an image of the process better. 

## Details
dimensions are both 1080x1080px (IG Standard)

![image](https://user-images.githubusercontent.com/90673012/170833459-42554cc3-fc24-4fc9-a338-67565b244ab0.png)

## Previous Submissions
- https://github.com/colonistio/design/issues/61

## Related links

- https://github.com/colonistio/katan/pull/7249

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JuanRoman77

**Comment by goktugyil** [comment]
can we do coast + cards?
with paid text

**Comment by JuanRoman77** [comment]
The design should guide people through each of the steps without the need to read the order number. Even less to read all order numbers to find the following step. There needs to be some sort hierarchy for this to happen, right now it's 5 cards that all look the same, in apparent random positions, and with non descriptive icons.

**Comment by goktugyil** [comment]
arrows?

**Comment by JuanRoman77** [comment]
> arrows?

For example, yeah. A bit of research wouldn't hurt
