### ISSUE TITLE
Profile Page Submission #18 - Ranked Tab + Scenarios

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#63]
## Summary
Moved the game mode stats inside a new `Ranked` Me and @JuanRoman77 both agree that showing the ranked games in the overview tab while the majority of our players are still playing vs bots / with friends is not ideal

## Details
![image](https://user-images.githubusercontent.com/90673012/171035747-cd0cdbf5-9ecf-4fb4-8729-da7f3bdfad76.png)

- removed all-time as we don't count it in our current codebase https://prnt.sc/dd-JNeLWBs7q

## Previous Submissions
- https://github.com/colonistio/design/issues/60
- https://github.com/colonistio/design/issues/59
- https://github.com/colonistio/design/issues/57
- https://github.com/colonistio/design/issues/55
- https://github.com/colonistio/design/issues/54
- https://github.com/colonistio/design/issues/51
- https://github.com/colonistio/design/issues/50
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil @DyLightedCatan

**Comment by alperozgunyesil** [comment]
Like I said in the previous message, I find the new tabs (rank area, etc) really good. There is a tiny detail that I can point out: the "past season ranking" button looks a bit old and off style. Yes, there is a solution like this but since you manage to make everything cohesive as possible I think this kind of areas deserve your attention.
