### ISSUE TITLE
Profile Page Submission #20 - Mobile Portrait & Landscape Prototypes

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#65]
## Summary
Created workable prototypes for both mobile landscape/portrait so its faster to implement whats approved for the desktop versions

_note_: only the tabs are clickable at the moment

## Prototypes

Mobile Landscape
https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=3245%3A57499&node-id=7481%3A376024&viewport=2265%2C1526%2C0.13&scaling=min-zoom&starting-point-node-id=7481%3A376024

Mobile Portrait
https://www.figma.com/proto/qoJZHxfBsMHtGRXNu5msuM/Colonist-UI%2FUX-Master-File?page-id=3245%3A57499&node-id=7481%3A376003&viewport=2265%2C1526%2C0.13&scaling=min-zoom&starting-point-node-id=7481%3A376003

## Previous Submissions
- https://github.com/colonistio/design/issues/64
- https://github.com/colonistio/design/issues/63
- https://github.com/colonistio/design/issues/60
- https://github.com/colonistio/design/issues/59
- https://github.com/colonistio/design/issues/57
- https://github.com/colonistio/design/issues/55
- https://github.com/colonistio/design/issues/54
- https://github.com/colonistio/design/issues/51
- https://github.com/colonistio/design/issues/50
- https://github.com/colonistio/design/issues/49
- https://github.com/colonistio/design/issues/48
- https://github.com/colonistio/design/issues/47
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/44
- https://github.com/colonistio/design/issues/43
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/40

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil @DyLightedCatan

**Comment by alperozgunyesil** [comment]
IMO, the hamburger button is quite big right now. (for example, the arrow next to the profile picture is much smaller than that and still works.) At this moment hamburger works as if its a logo of the game or something like that. Maybe if we can make it shrink like 20% it will be better.

How's the readability on your phones? And how is your oldest audience target, some people can have problems with small types you know

**Comment by JuanRoman77** [comment]
Mobile users is around 15%. So several tens of thousands users. Current readability is fine, we haven't gotten any complains.
