### ISSUE TITLE
Store Page Fix # 2 - Perk List Presentation Ideas

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#67]
## Summary
Current implementation could be improve as Juan pointed out in here: https://discord.com/channels/605233308577562643/790772223358402571/980603685233115217. Did some couple research on how things are implemented in other platforms/games as my basis

## Details
![image](https://user-images.githubusercontent.com/90673012/171124514-805956f0-8123-42e7-b28c-99ccf3d81e3c.png)

for the checklist study, I followed this orientation: https://prnt.sc/XVqtz8w-J23Y
for the All Tiers + I followed Patreon and some perk listing at Kickstarter

I'd recommend showing all of it as a checklist, since it shows more buck for the money

## Previous Submissions

- https://github.com/colonistio/design/issues/66

## Related links

- https://github.com/colonistio/design/issues/6
- https://github.com/colonistio/design/issues/37

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @goktugyil @JeffdEon 

also, the proposal for monthly/annual selector is listed [here](https://github.com/colonistio/design/issues/66) if you want to check it out

**Comment by JeffdEon** [comment]
> I'd recommend showing all of it as a checklist, since it shows more buck for the money

Much better and easier to see
