### ISSUE TITLE
Mobile Portrait/Landscape Fixes #1 - Header Icon Sizes

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#68]
## Summary
@alperozgunyesil talked about the hamburger icon hin the mobile versions being too big [here](https://github.com/colonistio/design/issues/65#issuecomment-1141738515) I agree with that, I haven't changed the mobile headers in a long time and we can start with this small change.

## Details
![image](https://user-images.githubusercontent.com/90673012/171341496-0d40d250-71d1-45a0-8634-c5d63111ea9e.png)

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @alperozgunyesil

**Comment by demiculus** [comment]
Can you write the exact sizes? https://www.loom.com/share/56aec673e2db49ce82a689bd2f02bbea

Also the image looks different than the current one. Is it a different png?

**Comment by demiculus** [comment]
up
