### ISSUE TITLE
Store Page Fix #3 - Perk List Presentation Ideas #2 & Annual/Monthly Tab Selector #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#69]
## Summary
Combined both ideas for both https://github.com/colonistio/design/issues/66 and https://github.com/colonistio/design/issues/67 into this issue to make it easier to check what change in the UI

## Details
![image](https://user-images.githubusercontent.com/90673012/171352287-7eaab036-4dfc-4059-8b73-30f87c94604a.png)

1, removed the highlight when selecting each tab
2. Grayed-out the perks not included in each tier. I didn't follow the other ideas:
- Making it X icon if the feature is not included - No games/platforms I saw does this, and it adds unnecessary visuals in the design
- Removing the feature if it's not included - this is our current one and we need to improve on it, also showing all of it makes it easier to compare what and what's not included in each tier

3. Make the check icons slightly smaller, making the cards smaller in the process

## Previous Submissions

- https://github.com/colonistio/design/issues/67
- https://github.com/colonistio/design/issues/66

## Related links

- https://github.com/colonistio/design/issues/6
- https://github.com/colonistio/design/issues/37

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by goktugyil** [comment]
I am missing context, but why did we add checkmarks instead of little icons? I liked the icons more.

- Overall I like current more, especially with icons with the features. My only complaint would be the order should be the same, so starting from worst item to best item. We can easily do that development, doesn't need design
- About the tab vs radio boxes, I am not sure. Tabs look better. Radio is more clear.

**Comment by samgawaran** [comment]
> Checkmarks mean "includes", "approved", "yes", "applies". Is more descriptive than small weird colorful icons that don't add much context or value to the items in the list.

Got to agree with @JuanRoman77 here, most platforms that have tiered subscription services use checkmarks to indicate a feature is included instead of icons. https://prnt.sc/3vvToQh4AwHX 

It also helps in reducing visual strain we have a lot of icons inside the store tab, as well as other store categories and adding "smaller icons inside the perks makes it _too detailed_ which fights the CTA button for attention.

> Also the circles in the checklist for Monthly/Annual should be smaller.

![image](https://user-images.githubusercontent.com/90673012/171536653-cf8865cc-9555-4084-8cc4-b652fe41b35a.png)

I'll just paste this here since its too small of a change to warrant a new issue, how about this? I made the circles smaller by about 25%

**Comment by goktugyil** [comment]
Everyone uses checkmarks. Everyone's store is boring. 

I think the one with icons, is colorful, interesting, fun, sells the feature. But this can easily be a/b tested

@demiculus decide on starting design, the other can be added to a/b test list

**Comment by JuanRoman77** [comment]
For the record, I like the second iteration, with the checkmarks and faded perks.

**Comment by JeffdEon** [comment]
> Everyone uses checkmarks. Everyone's store is boring.
> I think the one with icons, is colorful, interesting, fun, sells the feature. But this can easily be a/b tested

I saw a quote somewhere. I'm going to butcher it but it was basically along the lines of "all your fancy animations in your store to try to sell stuff. Go to amazon and see how much animations and fancy stuff they have. Turns out amazon sells more than you."

**Comment by demiculus** [comment]
@samgawaran 

1. Use iteration 3
2. Add the Icon idea to AB test list
