### ISSUE TITLE
Subscription - P3: Design Ad Banners

### ISSUE THREAD

**Issue by goktugyil** [colonistio/design#7]
## Prerequisite 
- [x] https://github.com/colonistio/design/issues/6
- [x] https://github.com/colonistio/katan/issues/6265
- [x] https://github.com/colonistio/katan/issues/6266
- [x] https://github.com/colonistio/katan/issues/6267

Need to wait for decisions to be ready and implementation to be started

## Description
- We need ad banners to lure people to the new subscription plans

## Related Submissions

- https://github.com/colonistio/design/issues/107
- https://github.com/colonistio/design/issues/106
- https://github.com/colonistio/design/issues/105
- https://github.com/colonistio/design/issues/102
- https://github.com/colonistio/design/issues/101

## Resources

- https://drive.google.com/drive/u/0/folders/0AEJGVe_PBa-HUk9PVA

### Guidelines
![image](https://user-images.githubusercontent.com/90673012/175336899-0948a513-aaa0-45d6-8c43-34e26c2ba560.png)

## Submission Checklist
- [x] I did not leave out anything that has already been implemented
- [x] I considered mobile (table & phone) devices
- [x] I considered horizontal & vertical mobile devices
- [x] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by goktugyil** [comment]
We're going to have:

- Season 1 of Colonist
- It will last 2 months
- People who make into leaderboards will stay in leaderboard history forever
- People who make into leaderboards will have their ranking and MMR in their profile forever
- Left large banner ad

- [ ] Use some of the good old pricing A/B test images (First batch had best results, the images were probably good: https://github.com/colonistio/katan/issues/6266 https://drive.google.com/drive/u/1/folders/1q6XtEZzS-_oCppWRlGuP7MUIHq_7kgQI)
- [ ] Come up with many good texts, good images, to promote players this idea

This needs to ready in a day so we can iterate on it and decide a good banner

**Comment by samgawaran** [comment]
@demiculus @goktugyil, just a heads-up did you see my submission tags relating to this issue? it's in  #101 & #192

**Comment by samgawaran** [comment]
Added new iterations that reflects the icon change and tier names here #105 & #106

**Comment by samgawaran** [comment]
Added the Gdrive link in the `Resource` section in this issue

**Comment by samgawaran** [comment]
Added a guide chart for developers under the `Resource` section
