### ISSUE TITLE
Design Feedback

### ISSUE THREAD

**Issue by Esqarrouth** [colonistio/design#71]
## Description
- I attended a UX meetup to get feedback on our site and store

Here is the feedback I got: https://www.loom.com/share/6e05e11af7014530a1bdcf3733858b45
Go through it when you have time and create relevant tasks/implementation/design issues

**Comment by samgawaran** [comment]
created this issue for the ideas I got for this feedback: https://github.com/colonistio/design/issues/72

**Comment by demiculus** [comment]
@samgawaran I created this: https://github.com/colonistio/katan/issues/7393

Once you've done creating the designs for that
Singleton pages with icons and pages with texts as well as colonist lobby (it is also not aligned perfectly) let me know and I'll edit the issue.
