### ISSUE TITLE
Store Page Fix #3 - Perk List Presentation Ideas #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#72]
## Summary
Saw the design feedback @goktugyil posted here https://github.com/colonistio/design/issues/71, did a couple more of things we can try out for the memberships tab

## Details
![image](https://user-images.githubusercontent.com/90673012/171783259-6edf5dff-df18-4532-a72b-590136a274a7.png)

- Changed from `Annual (20%off)` to `Annually (-20%)`
- Replaced the check icons into the current icons we use for each perk
- Added some ideas we can use for the Promo Tags.
     - `Best Deal` is the one being used in our figma file
     - `Best for Hardcore players` are base on Miro, Chess.com and other tiered membership services

## Related Submissions
- https://github.com/colonistio/design/issues/67

## Related links

- https://github.com/colonistio/design/issues/6
- https://github.com/colonistio/design/issues/37

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@goktugyil @demiculus @JeffdEon @JuanRoman77

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/171786558-1776bdbc-bc71-47aa-8138-33650cb49681.png)
1. Too bulky. Try box surrounding the card as well perhaps?
2. Checkmarks better
3. These look like bottom tabs. As if clicking on them would change the content above. Try a toggle (as suggested in the video)

**Comment by demiculus** [comment]
The only thing better in this one could be "Best for hardcore players" but show us a version where it's included with radio buttons.
