### ISSUE TITLE
Profile Page Submission #23 - Overview Tab Iteration #4

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#74]
## Summary
Got a ton of feedback @JuanRoman77 for the overview tab. I decided to not make things complicated and just put the necessary things like total win rate, total win/lose, karma and membership

## Details
![image](https://user-images.githubusercontent.com/90673012/171971507-5f57be9e-a847-4b4f-86c3-16511a09ef17.png)

1. Added `My Profile` if you're looking at your own profile. For guests, it will show `Overview`
2. Retained the sections that both me and reviewers has no problems with, namely total win%, win/lose, karma and membership

Also made it scrollable like our store page UI. My reasoning for this is if we can't show a lot of things in the overview, its better to make it scrollable, its also easy to interchange the tabs so it wouldn't show the Ranked tab upon loading.

## Related Submissions

- https://github.com/colonistio/design/issues/41
- https://github.com/colonistio/design/issues/42
- https://github.com/colonistio/design/issues/55
- https://github.com/colonistio/design/issues/59
- https://github.com/colonistio/design/issues/64

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @huaniebun @alperozgunyesil @DyLightedCatan

**Comment by JuanRoman77** [comment]
1. `My Profile` -> `My Stats`

2. Most players will not have Membership. I would add Games Played back into the UI, and show the Membership box only to customers. The assumption that people with many games will feel bad about their miserable lives because they play too much Catan should be ab tested, if anything. Most people will not have that problem and it's a number people are usually interested in. Everyone I know brag about that number being high. And a lot of games show it as well. I say add it back.

**Comment by demiculus** [comment]
> My Profile -> My Stats
Is that My Stats in my page vs other peoples page?

**Comment by samgawaran** [comment]
> Is that My Stats in my page vs other peoples page?

it's originally `My Profile` for your own page, and `Overview` if you're looking at someone else.

My Stats is a bit general though, `Ranked` and `History` shows _stats_ too. I recommend we keep it as `Overview` for now.

**Comment by demiculus** [comment]
Better to make it `Overview` for everyone since the content doesn't change per person
