### ISSUE TITLE
Profile Page Submission #25 - History Tab Left vs Center Aligned

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#77]
## Summary
Mentioned at https://github.com/colonistio/design/issues/75 @JuanRoman77 showed the samples for both center and left aligned, this submission adds the expanded view based on the feedback given.

## Details
![image](https://user-images.githubusercontent.com/90673012/172100079-65c4fe7d-ecd0-49a3-a6b7-2700045e0b56.png)

## Related Submissions
- https://github.com/colonistio/design/issues/75

## Related Links

- https://github.com/colonistio/design/issues/32
- https://github.com/colonistio/design/issues/2

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by JuanRoman77** [comment]
What I was thinking was having these icons inside the arrow dropdown, not the icons up there. We might add achievement icons there, and there are other images and icons all around the profile page. So I don't think these will work.
@demiculus what exactly did you have in mind?
![image](https://user-images.githubusercontent.com/73320460/172115497-4470d735-14b2-4370-9c34-69b3b63ee7c5.png)

**Comment by demiculus** [comment]
1. What was the decision making process behind adding MMR tab? 
  1a. What percentage of the games will have that tab? 
  1b. What are other alternatives we can use instead of MMR tab?
2. Go with left aligned

**Comment by JuanRoman77** [comment]
1. I assume you meant MMR column, not Tab.
a. Every single game will have a value in this column. Possibilities are:
- Bots
- Unranked
- Placement
- MMR won/lost values

b. We can change the header to Type, and the MMR won/lost numbers to just `Ranked`. For consistency.

The idea behind numbers was to show Ranked players a history of their MMR gain/loss. See how many wins on a row, how long a bad streak lasted, which opponents gave the higher MMR win, etc. A nice perk to have; would definitely add value to the Ranked experience.

Easy path is just show Ranked.

**Comment by demiculus** [comment]
> Easy path is just show Ranked.

Lets go with this.
