### ISSUE TITLE
Profile Page Submission #27 - Membership Tab Scenarios

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#79]
## Summary
Added screens for players who don't have a membership and a screen when a player wants to deactivate their membership.

## Details
![Membership Tab Scenarios](https://user-images.githubusercontent.com/90673012/172129826-7c019864-0170-4b1c-86d7-da1f719f5feb.png)

## Related Submissions
- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/46

## Related Links:
- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by samgawaran** [comment]
https://github.com/colonistio/design/issues/75#issuecomment-1146618987

@demiculus for the scenario you wrote here with :
> viewing another profile & not purchased
> viewing another profile & purchased

@JuanRoman77 and I discussed previously via DM that `only the player could see their own membership tab` so I didn't add it here.

**Comment by JuanRoman77** [comment]
1. `Get a Membership!` in color-cta-main
![image](https://user-images.githubusercontent.com/73320460/172124249-48582194-c7e7-4b9e-9f48-e3cd2c649f78.png)

2. Leave only the arrow
![image](https://user-images.githubusercontent.com/73320460/172124336-266ff8db-ca57-442c-aca0-babc96c6e3b8.png)

3.
![image](https://user-images.githubusercontent.com/73320460/172124552-8aa3b86a-15aa-4d00-aba2-e3bb2c61eb2d.png)
(1) `Paid with` is clearer and sounds better
(2) Remove `Automatically renews for`
(3) `Update Payment Method`
(4) `Cancel`

I haven't seen your research so if other games don't use any of the suggested in 3. , let me know

**Comment by samgawaran** [comment]
> (1) Paid with is clearer and sounds better
(2) Remove Automatically renews for
(3) Update Payment Method
(4) Cancel

1, 3 & 4 could be done. for 4, more games use `Cancel` but I figured `Deactivate` like the one Youtube is doing makes the word button harder to click since the word is harsher lol

2, Based on the games/platforms I saw, I think it needs to say that it `automatically renews` or `billed every` it also provides more context with it as a subcopy

**Comment by demiculus** [comment]
I agree with the edits.

This doesn't show cancel popup: https://github.com/colonistio/design/issues/46 can you gather examples of it? 

<img width="353" alt="image" src="https://user-images.githubusercontent.com/6215305/172154394-e405e627-924f-419f-b4e0-06fa7cc936d0.png">
