### ISSUE TITLE
Design One Time Notifications To Players

### ISSUE THREAD

**Issue by Esqarrouth** [colonistio/design#8]
## Summary
* We need to be able to send a one time notification to certain players. User needs to mark it as read or do some action to mark it complete
* This can be designed and comboed with email and browser notifications in the future
* Example use cases:
  * We deleted someone's expansion pack, we show him a popup or a message or notification somewhere on their profile
  * User ranked up or did something, they should be able to check that out
  * We offer something new in the shop that this particular player might be interested in

What is the best way to do this? Popup? Notification drop down part somewhere? Notification chat somewhere? 

## Key Knowledge
- https://discord.com/channels/605233308577562643/1101315255168143454
- https://docs.google.com/document/d/1hfjhisxB_mt6fCja8ml-RjR1GBVWG8kwKcLpcCl_KPE/edit?usp=sharing

## Submission Checklist
- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by goktugyil** [comment]
Store stuff are higher priority. First research some notification systems, post them somewhere, let's go over them. Then work on our design

**Comment by goktugyil** [comment]
Decided not to do this for subscription. It will be a separate feature, sometime when we decide that it is a priority

**Comment by goktugyil** [comment]
Some ideas:
- Need DB with personal notifications
- Need DB with everyone generic notifications
- Notification for: youtubers, new subscriptions, packs, pack refunds, patch notes, friends passed in leaderboard, new tournament, new season, passed friend in leaderboard, community events, hiring, blog posts

**Comment by aalmadan** [comment]
Related: 

- https://discord.com/channels/605233308577562643/1101315255168143454
- https://docs.google.com/document/d/1hfjhisxB_mt6fCja8ml-RjR1GBVWG8kwKcLpcCl_KPE/edit?usp=sharing
