### ISSUE TITLE
Profile Page Submission #30 - Membership Tab Scenarios #2

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#83]
## Summary
Changed the copy for the membership based on Juan's feedback. Created a new design for cancel membership that shows a page instead of a popup since the majority of games that has a membership function shows it as a page. 

Gaming Platforms such as Humble Bundle, Apple Store/Music and Origin shows it as popup

## Details
https://www.loom.com/share/8b627a3ce34a49e58795d7f6c80a1575

New page design for Cancel membership:
![image](https://user-images.githubusercontent.com/90673012/172353680-8a371106-9578-4ed8-87c0-34283a5cd439.png)

## Related Submissions

- https://github.com/colonistio/design/issues/45
- https://github.com/colonistio/design/issues/46
- https://github.com/colonistio/design/issues/79

## Related links

- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by JuanRoman77** [comment]
I think it would be better to only have 1 place where to cancel Membership. Either in the store or in the profile, but not both. One should redirect to the other.
Also there should be a CTA to allow players to either upgrade their current pack, or get a different pack. Explore that as well. Keep the store designs in mind as well for this.

**Comment by samgawaran** [comment]
> I think it would be better to only have 1 place where to cancel Membership. Either in the store or in the profile, but not both. One should redirect to the other.

Only access point we could have for the cancellation should be inside the profile, having it on the store page makes it easier for them to cancel and we don't want that. 

Sending the prototype later.

**Comment by JuanRoman77** [comment]
Yeah but the store is where you purchase the stuff. So it makes sense to have both things at the same place, right?

**Comment by samgawaran** [comment]
No, none of the games I saw does that and we wouldn't want them to cancel there. 

What we could write for the store, instead of `Cancel` we could write it as `Manage` and clicking that would redirect them inside their profile/membership. that way, there would be more clicks to hinder them from canceling.

**Comment by JuanRoman77** [comment]
`Manage` for the pack they own
`Upgrade` for the higher tiers they don't own
`Subscribe` for the lower tiers

**Comment by demiculus** [comment]
Cancel membership shouldn't be a big bright button it should be this: https://i.imgur.com/M9IHahg.png
