### ISSUE TITLE
Profile Page Submission #31 - Scenarios: Profile Access Points

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#84]
## Summary
Scenarios on how players can get into their profile/profile of another player.

## Details
![Access Points](https://user-images.githubusercontent.com/90673012/172699674-f1568de9-65cd-4a6e-a33a-5d8e4f097c2f.png)

## Related Submission

- https://github.com/colonistio/design/issues/48

## Related links

- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by demiculus** [comment]
The last one is a new issue.. create a separte submission for it with the feedback. Make sure to include all cases
Host clicking vs other clicking
Clicking on host vs others vs bots

Also can you fix up the report icon with the new submission? Current report icon is the upside down information icon.
