### ISSUE TITLE
Profile Page Submission #32 - Scenarios: Overview and Search Bar

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#85]
## Summary
Scenarios involving the overview tab and the search bar

## Details

![Overview   Search Bar Scenarios](https://user-images.githubusercontent.com/90673012/172700459-9945a7aa-99b5-4da3-a4d4-3e6dc357bc57.png)

## Related Submission"
- https://github.com/colonistio/design/issues/48

## Related links

- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by JuanRoman77** [comment]
I don't like this UX 
![image](https://user-images.githubusercontent.com/73320460/172745812-13c16e5b-8732-45a3-a551-22ba53dda537.png)

If a username doesn't exist, it's better to show a tooltip, or a popup, or red line below the search box, or something like that. Not a new screen to tell them the user doesn't exist, and a small cta to go back.

**Comment by demiculus** [comment]
> If a username doesn't exist, it's better to show a tooltip, or a popup, or red line below the search box, or something like that. Not a new screen to tell them the user doesn't exist, and a small cta to go back.

What if someone goes to colonist.io/profile/awefawefawefawfweafe 

check these out

https://twitter.com/hthtrshsrthrsh
https://www.facebook.com/ahtsyjrhsrhsrt
https://www.instagram.com/ahutruigaiueaegrguiea/

We need a doesn't exist page
