### ISSUE TITLE
Profile Page Submission #33 - Scenarios: Ranked Tab

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#86]
## Summary
Scenarios involving the Ranked tab from new account screens and when a player checks the leaderboard from a player's profile

## Details

![Ranked Tab](https://user-images.githubusercontent.com/90673012/172700938-026734f0-2732-44f2-9844-d26a1c2b2fd1.png)

## Related Submission

- https://github.com/colonistio/design/issues/48

## Related links

- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/172746161-68133159-14bf-4344-9fa8-f867dfc02fe6.png)

If the player's ranking is higher, it should appear at the top of the leaderboards, not in the middle (and your own at the bottom). It's an infinite scroll, there is no middle. It changes depending on the screen size and such.
Same if the player's rank is lower, it should appear at the bottom (and your own at the top).

**Comment by demiculus** [comment]
> If the player's ranking is higher, it should appear at the top of the leaderboards, not in the middle (and your own at the bottom). It's an infinite scroll, there is no middle. It changes depending on the screen size and such.
Same if the player's rank is lower, it should appear at the bottom (and your own at the top).

Players will be sent to leaderboards starting from 1. so it won't load #200 player section. Coding that is a pain and there is not much value. 

Overall players will just be sent to the right tab of the leaderboard, we wont do scrolling for them

**Comment by JuanRoman77** [comment]
What's the point of having a leaderboards access point from a players profile if you can't compare with them or see them in the leaderboards? People would need to copy the username in the profile page, paste it in the leaderboards search box, and hit enter. That's a lot of extra steps. Bad UX.

**Comment by demiculus** [comment]
> What's the point of having a leaderboards access point from a players profile if you can't compare with them or see them in the leaderboards? People would need to copy the username in the profile page, paste it in the leaderboards search box, and hit enter. That's a lot of extra steps. Bad UX.

> Coding that is a pain

with respect to the value we get. Let 0.5% of the hardcore players do extra clicks 1% of the time.
