### ISSUE TITLE
Profile Page Submission #35 - Scenarios: Items Tab

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#88]
## Summary
Scenarios involving the Items Tab

## Details

![Items Tab](https://user-images.githubusercontent.com/90673012/172702159-be64add7-0360-469d-8d4f-ec840e5952f4.png)

## Related Submission

- https://github.com/colonistio/design/issues/48

## Related links

- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by demiculus** [comment]
Gifting should happen from clicking on another users item, not their own.

**Comment by JuanRoman77** [comment]
> Gifting should happen from clicking on another users not owned item, not their own. 

We also need a Store CTA for gifting stuff.
