### ISSUE TITLE
Profile Page Submission #36 - Scenarios: Membership Tab

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#89]
## Summary
Scenarios involving the Membership Tab from player who don't have a membership to players who want to cancel their membership

## Details

![Membership Tab](https://user-images.githubusercontent.com/90673012/172702726-c8502fd9-4f53-4994-ba73-ec0d02ca0ce6.png)

## Related Submission

- https://github.com/colonistio/design/issues/48

## Related Links

- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/172747091-31a57c75-a59f-48ba-8dcd-a06ffc01cc1e.png)

What does this mean exactly? Why is the font bigger than the pack name?

**Comment by JuanRoman77** [comment]
![image](https://user-images.githubusercontent.com/73320460/172747258-51eaecf1-b195-4c29-aeb5-cd6c527adf89.png)

1. You don't own a Membership.
2. Remove
3. Become a Member (not sure, thoughts?)

**Comment by JuanRoman77** [comment]
Feedback was given about this button
![image](https://user-images.githubusercontent.com/73320460/172747420-7f8fed76-c83d-4fea-bd9c-e670e2e1b1ef.png)
