### ISSUE TITLE
Make ports more obvious

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#9]
## Description

Here is a design:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/6215305/163312853-e715bece-633e-488a-ac56-d4f58c55bb81.png">

But it doesn't show 2:1 ratios. It also feels a bit strong. Come up with version on how it could be made better. Consider the checklist below.

## Resources
- Context from dylighted: https://discord.com/channels/605233308577562643/729055418868826192/963942283881873438

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by demiculus** [comment]
https://cdn.discordapp.com/attachments/729055418868826192/968352196511039528/unknown.png

**Comment by JuanRoman77** [comment]
Design #1: color resource icon inside port ship flag
https://i.imgur.com/udzjedr.png
https://i.imgur.com/dZzvj9C.jpg
https://i.imgur.com/udzjedr.png
https://i.imgur.com/oeqzpuR.jpg
