### ISSUE TITLE
Profile Page Submission #38 - Scenario Fixes 

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#91]
## Summary
Fixes for the comments I got from issues: Profile Page Submission 31 to 37. 

## Details
![image](https://user-images.githubusercontent.com/90673012/172963900-278e9e57-2d87-4930-b91e-ac4d692476e0.png)

### Player clicks on an item on their own item tab

Changed the copy for the header and CTA | [Before](https://prnt.sc/p7hYgLngb-e8)

### Players clicks on cancel

Changed cancel membership cta into a hyperlink | [Before](https://prnt.sc/xu3Fy4YqboMw)

### Player clicks on the info icon

Added Finished Games in the expanded view | [Before](https://prnt.sc/1aPAz_2HMktx)

### Player clicks on "Go To Leaderboards"

Realigned it based on Juan's feedback. We can disregard this if we would only bring the players to the top of the respective game mode they clicked.

### Searching an inactive username in the profile search bar

Change from creating a new screen into showing just a popup instead. I followed what we did when a player searches a wrong name in the leaderboards. | [Before](https://prnt.sc/od3zpvSibd7i)

I also applied the size of the popup we're using currently on the website to all popups used.

## Related Submissions

- https://github.com/colonistio/design/issues/84
- https://github.com/colonistio/design/issues/85
- https://github.com/colonistio/design/issues/86
- https://github.com/colonistio/design/issues/87
- https://github.com/colonistio/design/issues/88
- https://github.com/colonistio/design/issues/89
- https://github.com/colonistio/design/issues/90

## Related links

- https://github.com/colonistio/design/issues/2
- https://github.com/colonistio/design/issues/32

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For Review:
@demiculus @JuanRoman77 @huaniebun @DyLightedCatan

**Comment by samgawaran** [comment]
Also @demiculus @JuanRoman77 I got to see some of your comments late, I'll be replying here:

> Also can you fix up the report icon with the new submission? Current report icon is the upside down information icon.

> New Issue for Access Points at Create Room Lobby

- I'll apply the changes once I created the issue for this.

> Gifting should happen from clicking on another users not owned item, not their own. / Store Tab Improvements

- Agree, It would be reflected on the Friends Tab Scenarios

**Comment by demiculus** [comment]
https://www.loom.com/share/1d3e27abf15a4b7ba961b7ec2340ff42

**Comment by samgawaran** [comment]
@demiculus

> Italicize silent link version

@JuanRoman77 and I talked about this and maybe we could just create a new hyperlink style? instead of having 2 hyperlink styles (one with green and one with the italicize whitish-blue) which may confuse people 

> removing the info icon on history tab

- I agree with this. it would look the same with our other list like the lobby and leaderboards though the difference is that both on lobby and leaderboards leads to another page. if we would retain it maybe we could just add a dropdown arrow or something. I'll create something up for you guys to check

**Comment by JuanRoman77** [comment]
> https://www.loom.com/share/1d3e27abf15a4b7ba961b7ec2340ff42

Yes to everything

**Comment by samgawaran** [comment]
updated the images. now it should load for everyone from Kyrgyzstan, Philippines and wherever JUAN is.

also added the hyperlink style for Cancellation, and added a scenario when a player searches via the browser directly for a profile

**Comment by JuanRoman77** [comment]
Shouldn't these be the same? 
![image](https://user-images.githubusercontent.com/73320460/172997342-10696d1d-5803-499f-beab-f5c8944d6ebd.png)

**Comment by demiculus** [comment]
> @JuanRoman77 and I talked about this and maybe we could just create a new hyperlink style? instead of having 2 hyperlink styles (one with green and one with the italicize whitish-blue) which may confuse people

That might work, just gotta change it and see how it looks everywhere. Let me know the result: https://www.loom.com/share/274da7fdc4db44e696e514351151d695?from_recorder=1&focus_title=1

**Comment by JuanRoman77** [comment]
We've been discussing it via dm. We'll figure something out.

**Comment by demiculus** [comment]
> We've been discussing it via dm. We'll figure something out.

I liked your color scheme in `Go To Leaderboards` example

**Comment by demiculus** [comment]
> Shouldn't these be the same? I'd rather have popup for both. Easier to close. ![image](https://user-images.githubusercontent.com/73320460/172997342-10696d1d-5803-499f-beab-f5c8944d6ebd.png)

Lets remove the popup. It'll be easier to just have 1 system and its okay to show a no-user-page. if we do popup we'll need to build another api for search popup. I want to avoid it. A no-user-page is simpler and UX doesn't matter much.

**Comment by JuanRoman77** [comment]
> UX doesn't matter much

How you dare.
