### ISSUE TITLE
Store Page Fix #4 - Annual/Monthly Selector

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#92]
## Summary
I looked at how we could improve our membership selectors and saw some great examples here: https://uxplanet.org/how-to-design-better-checkbox-radio-and-toggle-buttons-197b85fa0820 we can also apply this in our other selectors as well.

## Details
![image](https://user-images.githubusercontent.com/90673012/173176118-de3d33b6-d2be-45bd-a92d-1de640f19b1a.png)

Based on research, **I recommend using toggles if we offer 2 options only**. Like so with Monthly/Annual or even for membership renewals like @JuanRoman77 suggested via our DMs

## Related Submissions

- https://github.com/colonistio/design/issues/66
- https://github.com/colonistio/design/issues/67
- https://github.com/colonistio/design/issues/69

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 @goktugyil 

suggesting the toggle number 2. Since its hard to put the -20% if we're putting the text inside the toggle

**Comment by JuanRoman77** [comment]
This says Monthly is disabled
![image](https://user-images.githubusercontent.com/73320460/173177339-28ec6718-448c-4aae-9830-680673406cc5.png)

I think both words should appear at the same time.

**Comment by goktugyil** [comment]
Don't feel strongly toward any

**Comment by demiculus** [comment]
@samgawaran I agree with Juan. This submission has on/off toggle button for a/b type of scenario.

Google more examples and suggest a toggle style that is a/b post the examples in the description as well
