### ISSUE TITLE
Membership Design Submission #1 - Color Research and Implementation

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#94]
## Summary
Demi notified me that we will go for the names: `Gold` `Platinum` `Diamond` I looked into some famous AAA games/platforms to see how they use their colors and applied them to our color scheme.

### Current
![image](https://user-images.githubusercontent.com/90673012/173250443-7c615587-5c9e-4e87-8d66-e6901d7b094d.png)

### Competitive Analysis
![image](https://user-images.githubusercontent.com/90673012/173250473-e1a463db-2c74-46b1-a866-9d8908973c96.png)
![image](https://user-images.githubusercontent.com/90673012/173250483-107ece6f-0c5b-4f99-9c5b-ab4a3b5ed5c7.png)
![image](https://user-images.githubusercontent.com/90673012/173250515-a47becae-c7dd-429b-a181-14404ba54749.png)

### All Variations and Recommendations
![image](https://user-images.githubusercontent.com/90673012/173250540-8d9e50bc-96b2-4dde-9d0f-5a37493110e1.png)

I recommend using the schemes of `Dota 2` for Gold `Dribble` for Platinum and `Apex Legends` for Diamond. since it's different enough from one another and light enough to complement the blue bg in our website

## Related links

- https://github.com/colonistio/design/issues/6
- https://github.com/colonistio/design/issues/37

## Submission Checklist

- [x] I did not leave out anything that has already been implemented
- [x] I considered mobile (table & phone) devices
- [x] I considered horizontal & vertical mobile devices
- [x] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [x] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
for review:
@demiculus @JuanRoman77 

colors are not componentized yet. let me know what colors are good for you and I'll add those in our color styles

**Comment by JuanRoman77** [comment]
Grey for tier 2 is a bad idea. Looks disabled. Less appealing than tier 1. Bad contrast.

If we are using color names for each pack, we should definitely choose different icons. We can't use game pieces we actually use in the game and that we sell in the store. It's confusing.

Names are also incoherent. Gold pack only offers ranked and no ads; the name (and color, for that matter) should be much less appealing.

**Comment by alperozgunyesil** [comment]
Maybe you can use some feudalism terms as membership names. Such as Farmer / Baron / Lord / King?

**Comment by demiculus** [comment]
1. Gold -> yellow
2. Platnium -> bluish, tealish (experiment on this to see which one fits with gold & purple)
3. Diamond -> purple

light at top, dark at bottom works

Agree w juan about icons. Remove them or change them to non item stuff or create new ones or just write text.

**Comment by goktugyil** [comment]
@samgawaran 

## Colors

League is the most played and most optimized out of these examples. Gold isn't too shiny, Plat doesn't lookdisabled, Diamond however doesn't look interesting

Gold: LoL
Plat: LoL
Diamond: Valorant

## Icons

Come up with new icon suggestions that are not game pieces. Ideally we find a new icon set before you go to vacation so first version has nonconfusing icons

**Comment by samgawaran** [comment]
> Maybe you can use some feudalism terms as membership names. Such as Farmer / Baron / Lord / King?

This was suggested before, but scrapped it since medieval names differs in each country and its too complicated.

> Come up with new icon suggestions that are not game pieces. Ideally we find a new icon set before you go to vacation so first version has nonconfusing icons

Agree, Juan and I talked about this, I'll try out flat colors too

**Comment by samgawaran** [comment]
> Come up with new icon suggestions that are not game pieces. Ideally we find a new icon set before you go to vacation so first version has nonconfusing icons

Agree, Juan and I talked about this as well. I'll try out flat colors too, some of my designer friends suggested that it might help in the contrast 

> Maybe you can use some feudalism terms as membership names. Such as Farmer / Baron / Lord / King?

This was suggested before but we decided to scrap it.  Not every country uses feudal systems and its too complicated compared to standard tier-based systems
