### ISSUE TITLE
Store Membership `Best Value` Tag Submission #1 - Research and Design Studies

### ISSUE THREAD

**Issue by samgawaran** [colonistio/design#97]
## Summary
Games and software platforms usually want to nudge players/users to a particular membership option. I did some research on whether it's really viable for us and did a couple of studies based on those as well.

### Research
![image](https://user-images.githubusercontent.com/90673012/173518925-2e66b9a3-ca5d-421b-8052-8831aec52f95.png)

`Full Width on Top` - Really noticeable in terms of UI, cons is that the card we're showcasing don't have the same size with other store cards, which is hard to show in mobile
`Stub Type` - Compatible for both Desktop and Mobile and other store items. Not too noticeable but changing the CTA color also helps. 
`Different Color`- Only works for Membership, implementing this in the other store cards wouldn't look good.

**Other Findings**
- About 60% of sites (Notion, Loom, Dropbox, Miro etc.) don't use Promo tags for their membership plans so I'm not sure if this works best for us. though in my opinion, It would certainly make the store layout much cleaner without the value tags.

### Implementation
![image](https://user-images.githubusercontent.com/90673012/173519743-bfae2871-34b6-47aa-a5cd-559ee758d2c5.png)

## Related Submissions

- https://github.com/colonistio/design/issues/72

## Related Links

- https://github.com/colonistio/design/issues/66
- https://github.com/colonistio/design/issues/67
- https://github.com/colonistio/design/issues/69

## Submission Checklist

- [ ] I did not leave out anything that has already been implemented
- [ ] I considered mobile (table & phone) devices
- [ ] I considered horizontal & vertical mobile devices
- [ ] I considered small & large screen desktop devices
- [ ] I considered all possible use-cases of the design, including disconnects, page refreshes, scrolling, changing tab, hovering etc.
- [ ] I considered all related screens this feature might effect. (Landing page, Lobby, Room, Game, Store, Community, Press-kit etc..)
- [ ] I checked out data on Google Analytics, Indicative and Metabase to make the right decision.
- [ ] I considered C&K, SF, large maps and other possible future modes and maps
- [ ] I considered 2nd order effects
- [ ] I looked at examples of other products
- [ ] All designs I submitted are final and for implementation purposes

**Comment by samgawaran** [comment]
For review:
@demiculus @JuanRoman77 

Let me know if I should tag the others in this.

**Comment by samgawaran** [comment]
@JuanRoman77 just list down all other variations here. Thanks

**Comment by demiculus** [comment]
We shouldn't use the diagonal banners, horizontal text is better.

**Comment by demiculus** [comment]
We shouldn't use the diagonal banners, horizontal text is better.
