### ISSUE TITLE
Hide Rooms

### ISSUE THREAD

**Issue by demiculus** [colonistio/design#99]
## Description

We want to hide this behind an extra button. https://i.imgur.com/3aiTdni.jpg 
We need to fill it out with something else.

Come up with ideas. Create basic designs. Lets see if we can come up with something nice.

Check ideas from featureupvote.

## Ideas from Feature Suggestion

- https://colonist.featureupvote.com/

**Comment by demiculus** [comment]
https://github.com/colonistio/katan/pull/7937
https://github.com/colonistio/katan/pull/7936

**Comment by demiculus** [comment]
Aggregated the useful looking & nonimplemented ideas here: https://docs.google.com/spreadsheets/d/1A2qZ-KG4E2ma8TdnP_9LayMfnEfLVhmoM5_SgazXYHw/edit#gid=304465379

**Comment by goktugyil** [comment]
@omarhurani fyi
